Repository projectacrn/acrn-hypervisor, pull requests merged in 2018-12, with the labels that each got.

#1950 Vq count vendor
  devicemodel/hw/pci/virtio/virtio_audio.c
Labels: CI: Tracked On Pass

#1959 hv: fix 'Space missing before or after binary operator'
  hypervisor/arch/x86/guest/guest.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/trusty.c
  hypervisor/arch/x86/vmx.c
  hypervisor/boot/sbl/abl_seed_parse.c
  hypervisor/common/vm_load.c
  hypervisor/include/lib/bits.h
  hypervisor/lib/sprintf.c
  hypervisor/lib/string.c
Labels: CI: Tracked On Pass

#1905 Update "Using Ubuntu as the Service OS" tutorial
  doc/tutorials/using_ubuntu_as_sos.rst
Labels: area: documentation

#1866 doc: add a document on considerations and current status of hypervisor modularization
  doc/developer-guides/images/modularity-architecture.png
  doc/developer-guides/index.rst
  doc/developer-guides/modularity.rst
Labels: area: documentation

#1840 doc: hv: add comments to timer APIs for documentation
  doc/acrn.doxyfile
  doc/developer-guides/hld/hv-timer.rst
  hypervisor/include/arch/x86/timer.h
Labels: CI: Tracked On Pass

#1967 HV: Remove some comments for crypto library
  hypervisor/lib/crypto/mbedtls/md.h
Labels: CI: Tracked On Pass

#1963 hv: fixes related to unused API and uninitialized variable
  hypervisor/arch/x86/guest/instr_emul.c
  hypervisor/include/arch/x86/irq.h
  hypervisor/include/arch/x86/vmexit.h
  hypervisor/include/debug/logmsg.h
  hypervisor/release/logmsg.c
Labels: CI: Tracked On Pass

#1977 security: remove cflag _FORTIFY_SOURCE in hypervisor
  hypervisor/Makefile
Labels: CI: Tracked On Pass

#1988 hv: fix one MISRA-C violation in mtrr.c
  hypervisor/arch/x86/mtrr.c
Labels: CI: Tracked On Pass

#1989 hv: fix "Array has no bounds specified" in vmsr.c
  hypervisor/arch/x86/guest/vmsr.c
Labels: CI: Tracked On Pass

#1994 hv: fix string assigned to non const object
  hypervisor/arch/x86/guest/vlapic.c
Labels: CI: Tracked On Pass

#2004 DM: updating launch_uos.sh
  devicemodel/samples/nuc/launch_uos.sh
Labels: CI: Tracked On Pass

#2019 DM: xHCI: unbind slot id and ndevices relationship.
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2023 ACRN: Add runC container sample config file
  devicemodel/samples/apl-mrb/runC.json
  devicemodel/samples/nuc/runC.json
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2027 dm: adjust the sequence of destroy client and wait for vm_loop exit
  devicemodel/core/main.c
Labels: Coding Guidelines: PASS

#2033 dm: virtio-input: ignore all MSC events from FE
  devicemodel/hw/pci/virtio/virtio_input.c
Labels: Coding Guidelines: PASS

#2025 hv[v2]: enable NX in hypervisor
  hypervisor/Makefile
  hypervisor/arch/x86/boot/trampoline.S
  hypervisor/arch/x86/mmu.c
  hypervisor/bsp/ld/link_ram.ld.in
  hypervisor/include/arch/x86/mmu.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2029 dm: bios: update vSBL to V1.1
  devicemodel/bios/MD5SUM
  devicemodel/bios/SHA512SUM
  devicemodel/bios/VSBL.bin
  devicemodel/bios/VSBL_debug.bin
  devicemodel/bios/changelog.txt
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2018 tools: acrnctl: Change STOP_TIMEOUT to 30s
  tools/acrn-manager/acrnctl.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2022 doc: additional DM parameter documentation
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/user-guides/acrn-dm-parameters.rst
  doc/user-guides/index.rst
Labels: area: device model, area: documentation

#2038 modulization: move virtual cpuid stuff into guest dir
  hypervisor/Makefile
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/include/arch/x86/cpuid.h
  hypervisor/include/arch/x86/guest/vcpuid.h
  hypervisor/include/arch/x86/hv_arch.h
Labels: Coding Guidelines: PASS

#2047 profiling: split profiling_vmexit_handler into two functions
  hypervisor/common/hv_main.c
  hypervisor/debug/profiling.c
  hypervisor/include/debug/profiling.h
  hypervisor/release/profiling.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2049 Init modulization upstream
  hypervisor/Makefile
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/init.c
  hypervisor/debug/dump.c
  hypervisor/include/arch/x86/cpu.h
  hypervisor/include/arch/x86/init.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2053 dm: Fix issues for tpm_emulator
  devicemodel/hw/platform/tpm/tpm_emulator.c
Labels: Coding Guidelines: PASS

#2062 hv: emulate IA32_TSC_ADJUST MSR
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/arch/x86/trusty.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Coding Guidelines: PASS

#2061 hv: fix possible buffer overflow issues
  hypervisor/arch/x86/assign.c
  hypervisor/arch/x86/cpu.c
  hypervisor/common/hypercall.c
  hypervisor/common/ptdev.c
  hypervisor/include/public/acrn_common.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2071 Doc: Update GSG for v0.4 version and launch and acrn.conf sample script
  devicemodel/samples/nuc/launch_uos.sh
  doc/getting-started/apl-nuc.rst
  hypervisor/bsp/uefi/clearlinux/acrn.conf
Labels: area: documentation

#2063 doc: add partition mode hld
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hv-console.rst
  doc/developer-guides/hld/hv-partitionmode.rst
  doc/developer-guides/hld/hv-startup.rst
  doc/developer-guides/hld/images/partition-image1.png
  doc/developer-guides/hld/images/partition-image13.png
  doc/developer-guides/hld/images/partition-image14.png
  doc/developer-guides/hld/images/partition-image16.png
  doc/developer-guides/hld/images/partition-image18.png
  doc/developer-guides/hld/images/partition-image20.png
  doc/developer-guides/hld/images/partition-image3.png
  doc/developer-guides/hld/images/partition-image7.png
Labels: area: documentation

#2073 hv: vmsr: fix MISRA_C violations
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/arch/x86/vmx.c
  hypervisor/include/arch/x86/guest/guest.h
Labels: Coding Guidelines: PASS

#2078 Fix a bug for USB S3
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2065 modulization:move out efi dir from hypervisor
  Makefile
  doc/getting-started/apl-nuc.rst
  efi-stub/Makefile
  efi-stub/boot.c
  efi-stub/boot.h
  efi-stub/clearlinux/acrn.conf
  efi-stub/efilinux.h
  efi-stub/malloc.c
  efi-stub/multiboot.h
  efi-stub/pe.c
  efi-stub/stdlib.h
  hypervisor/Makefile
Labels: CI: Tracked On Pass, Coding Guidelines: PASS, status: on hold

#2091 hv: MISRA-C fix "identifier reuse" in vpci code
  hypervisor/dm/vpci/msix.c
  hypervisor/dm/vpci/partition_mode.c
  hypervisor/dm/vpci/sharing_mode.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/dm/vpci.h
Labels: Coding Guidelines: PASS

#2087 hv: enable/disable snoop control bit per vm
  hypervisor/arch/x86/ept.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/vtd.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2092 hv:refine alloc_vm_id api
  hypervisor/arch/x86/guest/vm.c
Labels: Coding Guidelines: PASS

#2093 hv:fix possible buffer overflow in 'ptirq_get_intr_data()'
  hypervisor/common/ptdev.c
Labels: Coding Guidelines: PASS

#2099 hv:refine prepare_vm0 api
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Coding Guidelines: PASS

#2101 hv: refine a few functions to only one exit point
  hypervisor/arch/x86/guest/vmtrr.c
  hypervisor/dm/vioapic.c
  hypervisor/dm/vpic.c
Labels: Coding Guidelines: PASS

#2102 hv: vpci: fix MISRA-C violations related to variable declarations
  hypervisor/dm/vpci/hostbridge.c
  hypervisor/dm/vpci/msi.c
  hypervisor/dm/vpci/msix.c
  hypervisor/dm/vpci/partition_mode.c
  hypervisor/dm/vpci/pci_priv.h
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/sharing_mode.c
  hypervisor/include/dm/vpci.h
Labels: Coding Guidelines: PASS

#2096 hv: refine coding style for ucode.c
  hypervisor/arch/x86/guest/ucode.c
Labels: Coding Guidelines: PASS

#2100 HV: modularization to refine pm related code.
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/pm.c
  hypervisor/arch/x86/wakeup.S
  hypervisor/boot/acpi.c
  hypervisor/include/arch/x86/host_pm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2103 hv: fix MISRA-C violations "Pointer param should be declared pointer to const."
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/dm/vpci/core.c
  hypervisor/dm/vpci/hostbridge.c
  hypervisor/dm/vpci/msi.c
  hypervisor/dm/vpci/msix.c
  hypervisor/dm/vpci/pci_priv.h
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/sharing_mode.c
  hypervisor/include/arch/x86/guest/guest.h
  hypervisor/include/dm/vpci.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2105 security: remove gcc flags Wformat Wformat-security in HV
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2109 hv: coding style: refine mmu.c
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/mmu.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2111 dm: passthru: simplify msi/msix handling
  devicemodel/hw/pci/passthrough.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2112 hv: ptdev: fix MISRAC violations
  hypervisor/common/ptdev.c
  hypervisor/include/common/ptdev.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2115 hv:clean io_request.c misra violations
  hypervisor/common/io_request.c
Labels: Coding Guidelines: PASS

#2126 hv: fix the MISRA-C violations related to string
  hypervisor/debug/string.c
  hypervisor/include/lib/rtl.h
  hypervisor/lib/string.c
Labels: Coding Guidelines: PASS

#2123 hv: assign: fix MISRA-C violations
  hypervisor/arch/x86/assign.c
  hypervisor/include/arch/x86/assign.h
  hypervisor/include/common/ptdev.h
Labels: Coding Guidelines: PASS

#2125 hv: config.h fix "Nested comment found."
  scripts/kconfig/generate_header.py
Labels: Coding Guidelines: PASS

#2118 hv: coding style: refine page related
  hypervisor/arch/x86/pagetable.c
  hypervisor/include/arch/x86/e820.h
  hypervisor/include/arch/x86/page.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2122 hv: fix enable_msr_interception() function
  hypervisor/arch/x86/guest/vmsr.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2124 hv:fix MISRA-C violations in create_vm
  hypervisor/arch/x86/guest/guest.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/guest/guest.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2119 Debug: Add one hypercall to quary hardware info
  hypervisor/debug/hypercall.c
  hypervisor/include/public/acrn_hv_defs.h
Labels: CI: Tracked On Pass

#2128 hv: coding style: remove no real declaration for external variable
  hypervisor/include/arch/x86/gdt.h
Labels: CI: Tracked On Pass

#2134 DM USB: xHCI: change log level of some logs for S3 online debugging
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass

#2083 dm: pass mac seed not to use vm name on UP2
  devicemodel/samples/up2/launch_uos.sh
Labels: CI: Tracked On Pass, CI: pending approve, Coding Guidelines: PASS

#2129 HV: fix pm code for multi-exits & unsigned const
  hypervisor/arch/x86/guest/pm.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2127 Cpuid: refine coding style
  hypervisor/arch/x86/guest/vcpuid.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2113 DOC: change PCI uart description from mmio to bdf
  doc/getting-started/apl-nuc.rst
  doc/getting-started/up2.rst
  doc/tutorials/images/menuconfig-partition-mode.png
  doc/tutorials/using_partition_mode_on_up2.rst
Labels: CI: Tracked On Pass, area: documentation

#2140 Patch for modularising ioapic.[c/h] and related files.
  hypervisor/arch/x86/assign.c
  hypervisor/arch/x86/ioapic.c
  hypervisor/arch/x86/irq.c
  hypervisor/arch/x86/pm.c
  hypervisor/debug/shell.c
  hypervisor/debug/vuart.c
  hypervisor/include/arch/x86/hv_arch.h
  hypervisor/include/arch/x86/ioapic.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2141 hv: fix e820.c violations
  hypervisor/arch/x86/e820.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2136 hv: coding style: refine cpu related function to one exit
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/security.c
  hypervisor/include/arch/x86/cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2148 hv: cpu_state_tbl: fix multiple exits
  hypervisor/arch/x86/cpu_state_tbl.c
Labels: Coding Guidelines: PASS

#2151 dm: virtio: fix compile issue on ubuntu
  devicemodel/include/virtio.h
Labels: Coding Guidelines: PASS

#2152 hv: vcpuid: leaf 02h has no subleaf
  hypervisor/arch/x86/guest/vcpuid.c
Labels: Coding Guidelines: PASS

#2153 Documentation: fix formatting in partition mode tutorial
  doc/tutorials/using_partition_mode_on_up2.rst
Labels: area: documentation

#2045 doc: fix vhm_request doxygen comment
  hypervisor/include/public/acrn_common.h
Labels: area: documentation

#2160 hv: vmcall: fix "goto detected" violations
  hypervisor/arch/x86/guest/vmcall.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2164 hv: remove duplicated `is_vmx_disabled`
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/vmcs.c
Labels: Coding Guidelines: PASS

#2166 hv: Write Buffer Flush - VT-d
  hypervisor/arch/x86/vtd.c
  hypervisor/include/arch/x86/vtd.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2135 DM USB: xHCI: change log level of some logs for S3 online debugging
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS, status: on hold

#2171 hv: virq: refine acrn_handle_pending_request()
  hypervisor/arch/x86/virq.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2174 hv: vcpuid: leaf 0dh is percpu related
  hypervisor/arch/x86/guest/vcpuid.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2175 hv: io: fix MISRA-C violations related to break
  hypervisor/arch/x86/io.c
Labels: Coding Guidelines: PASS

#2177 hv: hypercall: fix "Procedure has more than one exit point"
  hypervisor/common/hypercall.c
Labels: Coding Guidelines: PASS

#2180 HV: [v2] bugfix in 'hv_access_memory_region_update()'
  hypervisor/arch/x86/mmu.c
  hypervisor/include/arch/x86/mmu.h
Labels: CI: no coding guideline

#2184 hv:vtd: fix additional violations in vtd.c
  hypervisor/arch/x86/vtd.c
Labels: Coding Guidelines: PASS

#2183 HV: x86: Fix "Variable should be declared static"
  hypervisor/arch/x86/ioapic.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2188 hv: remove the usage of 'atoi()'
  hypervisor/debug/shell.c
  hypervisor/debug/string.c
  hypervisor/include/lib/rtl.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2189 hv: fix coding style violations in mmu.c
  hypervisor/arch/x86/mmu.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2193 hv: hypercall clean "Procedure has more than one exit point"
  hypervisor/common/hypercall.c
Labels: Automerge: Pass, CI: Tracked On error, Coding Guidelines: PASS

#2196 hv: tursty_hypercall: fix "Procedure has more than one exit point"
  hypervisor/common/trusty_hypercall.c
Labels: Automerge: Pass, Coding Guidelines: PASS

#2199 hv: vcpuid: cpuid leaf 07h has subleaf
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/include/arch/x86/cpuid.h
Labels: Automerge: Pass, Coding Guidelines: PASS

#2194 hv: schedule: fix "Procedure has more than one exit point"
  hypervisor/common/schedule.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2060 doc: initial draft of ACRN coding guidelines
  doc/developer-guides/coding_guidelines.rst
  doc/developer-guides/index.rst
Labels: area: documentation

#2206 script: fix launch_uos script issue due to unseen character
  devicemodel/samples/up2/launch_uos.sh
Labels: CI: Tracked On Pass, Coding Guidelines: PASS, status: on hold

#2203 dm: acpi: add PSDS table in ACPI table
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/include/acpi.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2210 hv: fix mis-usage of "PAGE_SHIFT"
  hypervisor/arch/x86/assign.c
  hypervisor/include/arch/x86/irq.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2211 hv: fix sos kernel hang when migrate irq to different cpu
  hypervisor/dm/vioapic.c
Labels: CI: Tracked On Pass, CI: apl_sdc_stable, CI: pending approve

#2215 hv: assign: fix remaining MISRA-C violations
  hypervisor/arch/x86/assign.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS
