Repository projectacrn/acrn-hypervisor, pull requests merged in 2018-10, with the labels that each got.

#1334 Documentation: updates to Getting Started Guide
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#1513 doc: update HLD overview chapter
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/images/over-image11.png
  doc/developer-guides/hld/images/over-image110.png
  doc/developer-guides/hld/images/over-image13.png
  doc/developer-guides/hld/images/over-image15.png
  doc/developer-guides/hld/images/over-image21.png
  doc/developer-guides/hld/images/over-image29.png
  doc/developer-guides/hld/images/over-image34.png
  doc/developer-guides/hld/images/over-image4.png
  doc/developer-guides/hld/images/over-image85.png
Labels: area: documentation, type: enhancement

#1556 tools: acrnctl: fix: resume default wakeup reason is CBC_WK_RSN_BTN
  tools/acrn-manager/acrnctl.c
Labels: project: gp, project:op

#1554 HV:fix MACRO value mismatch
  hypervisor/include/debug/npk_log.h
Labels: project:op

#1548 dm: rpmb: Support RPMB mode config from launch.sh
  devicemodel/hw/pci/virtio/virtio_rpmb.c
  devicemodel/hw/platform/rpmb/rpmb_backend.c
Labels: project: gp, project:op

#1558 HV: checkpatch: add configurations to customize checkpatch.pl
  .checkpatch.conf
  doc/developer-guides/contribute_guidelines.rst
Labels: project:op

#1559 Fix potential NULL pointer issue and array out of range issue
  devicemodel/hw/pci/xhci.c
Labels: project: gp

#1437 tools: acrn-crashlog: update the documents
  tools/acrn-crashlog/README.rst
  tools/acrn-crashlog/usercrash/README.rst
Labels: area: documentation

#1591 doc: update Memory management HLD
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/hld/images/mem-image18.png
  doc/developer-guides/hld/images/mem-image4.png
  doc/developer-guides/hld/images/mem-image45.png
  doc/developer-guides/hld/images/mem-image69.png
  doc/developer-guides/hld/images/mem-image8.png
  doc/developer-guides/hld/images/mem-image84.png
  doc/developer-guides/hld/memmgt-hld.rst
Labels: area: documentation

#1515 doc: filter error exit status incorrect
  doc/scripts/filter-doc-log.sh
Labels: area: documentation

#1609 doc: update I/O emulation section
  doc/.known-issues/doc/dupdecl.conf
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/hld-io-emulation.rst
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/hld/hv-startup.rst
  doc/developer-guides/hld/images/ioem-image100.png
  doc/developer-guides/hld/images/ioem-image101.png
  doc/developer-guides/hld/images/ioem-image106.png
  doc/developer-guides/hld/images/ioem-image92.png
  doc/developer-guides/hld/index.rst
Labels: area: documentation

#1555 HV: debug: Check if vUART is configured in partition mode
  hypervisor/debug/shell.c
Labels: CI: no ext-id

#1545 Fix AcrnGT broken API doc due to kernel upgrade
  doc/api/GVT-g_api.rst
Labels: area: documentation, type: bug

#1647 doc: update HLD Device passthrough
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/images/passthru-image102.png
  doc/developer-guides/hld/images/passthru-image22.png
  doc/developer-guides/hld/images/passthru-image30.png
  doc/developer-guides/hld/images/passthru-image42.png
  doc/developer-guides/hld/images/passthru-image72.png
  doc/developer-guides/hld/images/passthru-image77.png
  doc/developer-guides/hld/images/passthru-image86.png
  doc/developer-guides/hld/images/passthru-image91.png
  doc/developer-guides/hld/images/passthru-image98.png
Labels: area: documentation

#1667 doc: update rest of hypervisor HLD sections
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hv-config.rst
  doc/developer-guides/hld/hv-console.rst
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/hv-hypercall.rst
  doc/developer-guides/hld/hv-io-emulation.rst
  doc/developer-guides/hld/hv-pm.rst
  doc/developer-guides/hld/hv-timer.rst
  doc/developer-guides/hld/hv-vt-d.rst
  doc/developer-guides/hld/images/config-image103.png
  doc/developer-guides/hld/images/console-image41.png
  doc/developer-guides/hld/images/console-image93.png
  doc/developer-guides/hld/images/pm-image24-105.png
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#1685 doc: update HLD Device Model
  doc/developer-guides/hld/acpi-virt.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/images/dm-image108.png
  doc/developer-guides/hld/images/dm-image26.png
  doc/developer-guides/hld/images/dm-image33.png
  doc/developer-guides/hld/images/dm-image36.png
  doc/developer-guides/hld/images/dm-image43.png
  doc/developer-guides/hld/images/dm-image52.png
  doc/developer-guides/hld/images/dm-image74.png
  doc/developer-guides/hld/images/dm-image75.png
  doc/developer-guides/hld/images/dm-image80.png
  doc/developer-guides/hld/images/dm-image83.png
  doc/developer-guides/hld/images/dm-image94.png
  doc/developer-guides/hld/images/dm-image96.png
  doc/developer-guides/hld/images/dm-image97.png
  doc/developer-guides/hld/images/dm-image99.png
Labels: area: documentation
