Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-05, with the labels that each got.

#3048 dm: uart_core: fix uart dm cause interrupt storm issue
  devicemodel/hw/uart_core.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3049 doc: update "Using PREEMPT_RT-Linux for real-time UOS" to use RTVM term
  doc/tutorials/images/RT-NUC-setup.png
Labels: area: documentation

#3036 Updated GSG of using RT Linux as RTVM in accordance with acrn-kernel v4.19.28
  doc/tutorials/rt_linux.patch
  doc/tutorials/rt_linux.rst
Labels: area: documentation

#3020 doc: Add instruction for gsg_quick_setup.sh script.
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/apl-nuc.rst
  doc/getting-started/images/gsg-successful-boot.png
Labels: area: documentation

#3055 doc: update APL GSG details
  doc/getting-started/apl-nuc.rst
  doc/getting-started/images/gsg-successful-boot.png
Labels: area: documentation

#3047 hv:remove accessing shared log buffer cases between stac/clac
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/seed/seed_sbl.c
  hypervisor/common/hypercall.c
  hypervisor/debug/profiling.c
  hypervisor/include/arch/x86/cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, CI: no coding guideline

#3057 HV: rename structure acrn_vm_type
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/boot/sbl/multiboot.c
  hypervisor/dm/io_req.c
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/arch/x86/vm_config.h
  hypervisor/scenarios/logical_partition/vm_configurations.c
  hypervisor/scenarios/sdc/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3058 hv: add one more guest VM to the industry scenario
  hypervisor/arch/x86/Kconfig
  hypervisor/scenarios/industry/vm_configurations.c
  hypervisor/scenarios/industry/vm_configurations.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3064 hv: rename 'interrupt_init' to 'init_interrupt'
  doc/developer-guides/hld/hv-interrupt.rst
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/irq.c
  hypervisor/include/arch/x86/irq.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3062 HV: rename 'type' in struct io_request
  hypervisor/arch/x86/guest/vmx_io.c
  hypervisor/dm/io_req.c
  hypervisor/include/arch/x86/guest/vmx_io.h
  hypervisor/include/dm/io_req.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3063 hv: release IOMMU irte when releasing ptirq remapping entries
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/ptdev.c
  hypervisor/include/common/ptdev.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3046 doc: update the diagram of KBL NUC serial port rework in GSG
  doc/getting-started/apl-nuc.rst
  doc/getting-started/images/KBL-serial-port-header.png
Labels: area: documentation, no Signed-off-by

#3068 doc: Fix references to be Wi-Fi
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hv-ioc-virt.rst
  doc/introduction/index.rst
Labels: area: documentation

#3060 doc: initial draft of Assembly coding guidelines
  doc/developer-guides/asm_coding_guidelines.rst
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#3067 HV: vuart: cleanup MISRA-C issues
  hypervisor/dm/vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3070 DM: Add one sample script to launch VxWorks as guest
  devicemodel/samples/nuc/launch_vxworks.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3033 doc: Add v1.0 release note
  doc/release_notes_1.0.rst
  doc/tutorials/using_sbl_on_up2.rst
Labels: area: documentation

#3072 HV: hotfix for acpi.c compile error
  hypervisor/boot/acpi.c
Labels: CI: Tracked On Pass

#3076 doc: update APL NUC GSG
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#3077 doc: Update 1.0 release notes
  doc/release_notes_1.0.rst
Labels: area: documentation

#3089 HV: remove some redundant includes
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/arch/x86/pm.c
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/scenarios/industry/vm_configurations.c
  hypervisor/scenarios/logical_partition/vm_configurations.c
  hypervisor/scenarios/sdc/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3087 tools: Fix the non-effective option -f --frequency
  tools/acrntrace/scripts/acrnalyze.py
  tools/acrntrace/scripts/config.py
  tools/acrntrace/scripts/irq_analyze.py
  tools/acrntrace/scripts/vmexit_analyze.py
Labels: Automerge: Pass, CI: Tracked On Pass

#3083 vm_state: Update vm state VM_STATE_INVALID to VM_POWERED_OFF
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hypercall.c
  hypervisor/debug/console.c
  hypervisor/debug/profiling.c
  hypervisor/debug/shell.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3080 doc: acrnlog: update loglevel usage
  tools/acrnlog/README.rst
Labels: area: documentation

#3090 doc: add v1.0 doc menu to master
  doc/conf.py
Labels: area: documentation

#3091 doc: Update intro to 1.0 release notes
  doc/release_notes_1.0.rst
Labels: area: documentation

#3088 doc: add rules in C coding guidelines
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation

#3092 doc: release note v1.0, correct some words.
  doc/release_notes_1.0.rst
Labels: area: documentation

#3093 dm: not register/unregister gvt bar memory
  devicemodel/hw/pci/core.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3086 Doc: virtio-blk: add description of boot device option
  doc/developer-guides/hld/virtio-blk.rst
Labels: area: documentation

#3098 hv: refine 'init_percpu_lapic_id'
  hypervisor/arch/x86/cpu.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3013 Dockerfile: update Ubuntu 16.04 Dockerfile to include all deps
  .travis-dockerfiles/Dockerfile.ubuntu16.04
Labels: Automerge: Pass, CI: Tracked On Pass

#3100 build fix: fix build issue with latest gcc for blkrescan
  tools/acrn-manager/acrn_vm_ops.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3101 hv: instr_emul: fix movzx return memory opsize wrong
  hypervisor/arch/x86/guest/instr_emul.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3102 dm: add sample script to launch Windows as guest
  devicemodel/samples/nuc/launch_win.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3084 dm:add grep -w option for uos launch sh
  devicemodel/samples/apl-mrb/launch_uos.sh
  devicemodel/samples/apl-up2/launch_uos.sh
  devicemodel/samples/nuc/launch_uos.sh
  devicemodel/samples/nuc/launch_vxworks.sh
  devicemodel/samples/nuc/launch_zephyr.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3104 hv:merge static_checks.c
  hypervisor/Makefile
  hypervisor/common/static_checks.c
  hypervisor/pre_build/static_checks.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3117 DM: Get max vcpu per vm from HV instead of hardcode
  devicemodel/core/main.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3115 HV: hot fix on usage of CONFIG_ACPI_PARSE_ENABLED
  hypervisor/boot/guest/vboot_wrapper.c
  hypervisor/boot/include/acpi.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3112 HV: fix MISRA violation of host_pm.h
  hypervisor/include/arch/x86/host_pm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3119 DM: virtio-gpio: fixed static variable keeps increasing issue
  devicemodel/hw/pci/virtio/virtio_gpio.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3122 build: fix build issue with latest gcc
  devicemodel/Makefile
  devicemodel/core/hugetlb.c
  devicemodel/core/monitor.c
  devicemodel/hw/pci/virtio/virtio_audio.c
  devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c
  devicemodel/hw/pci/virtio/virtio_ipu.c
  devicemodel/hw/pci/virtio/virtio_rnd.c
  hypervisor/arch/x86/guest/instr_emul.c
  tools/acrn-crashlog/acrnprobe/main.c
  tools/acrn-manager/acrn_mngr.c
  tools/acrn-manager/acrn_vm_ops.c
  tools/acrn-manager/acrnctl.c
  tools/acrn-manager/acrnd.c
Labels: CI: Tracked On Pass, CI: apl_sdc_stable

#3105 signal SIGINT: map SIGINT to watchdog reset
  devicemodel/core/main.c
  devicemodel/hw/pci/wdt_i6300esb.c
  devicemodel/include/vmmapi.h
Labels: CI: Tracked On Pass, CI: apl_sdc_stable

#3125 hv:remove some unnecessary includes
  hypervisor/acpi_parser/acpi_ext.c
  hypervisor/acpi_parser/dmar_parse.c
  hypervisor/boot/acpi_base.c
  hypervisor/boot/guest/direct_boot_info.c
  hypervisor/include/arch/x86/per_cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3135 dm: refine the passthrough devices with dictionary
  devicemodel/samples/apl-mrb/launch_uos.sh
  devicemodel/samples/apl-up2/launch_uos.sh
  devicemodel/samples/nuc/launch_hard_rt_vm.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3129 HV: Remove undefined CONFIG_REMAIN_1G_PAGES
  hypervisor/common/vm_load.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3141 reshuffle init_vm_boot_info
  hypervisor/Makefile
  hypervisor/arch/x86/guest/vm.c
  hypervisor/boot/guest/deprivilege_boot.c
  hypervisor/boot/guest/deprivilege_boot_info.c
  hypervisor/boot/guest/direct_boot.c
  hypervisor/boot/guest/vboot_info.c
  hypervisor/boot/guest/vboot_wrapper.c
  hypervisor/boot/include/guest/deprivilege_boot.h
  hypervisor/boot/include/guest/direct_boot.h
  hypervisor/boot/include/guest/vboot.h
  hypervisor/boot/include/guest/vboot_info.h
  hypervisor/common/vm_load.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3140 fix cpu family calculation
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/lib/sprintf.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3149 HV: predefine pci vbar's base address for pre-launched VMs in vm_config
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/arch/x86/vm_config.h
  hypervisor/include/dm/vpci.h
  hypervisor/scenarios/logical_partition/pt_dev.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3147 HV: remove unused UNDEFINED_VM
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/include/arch/x86/vm_config.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3124 doc: Update clearlinux os installation guide link.
  doc/getting-started/apl-nuc.rst
  doc/tutorials/agl-vms.rst
  doc/tutorials/using_partition_mode_on_up2.rst
Labels: area: documentation

#3120 doc: add <vm_id> parameter to the "vm_console" command description
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#3109 doc: add note to indicate that vSBL is only supported on APL platforms
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#3074 doc: remove hard-coded interfaces in .rst files
  doc/developer-guides/hld/hv-interrupt.rst
  doc/developer-guides/hld/hv-memmgt.rst
  doc/developer-guides/hld/hv-virt-interrupt.rst
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/arch/x86/ioapic.h
  hypervisor/include/arch/x86/irq.h
  hypervisor/include/arch/x86/lapic.h
  hypervisor/include/arch/x86/pgtable.h
Labels: CI: Tracked On Pass, CI: pending approve, area: documentation

#3155 doc: prepare for sphinx 2.0 upgrade
  doc/.known-issues/doc/dupdecl.conf
  doc/extensions/kerneldoc.py
Labels: area: documentation

#3154 hv: distinguish between LAPIC_PASSTHROUGH configured vs enabled
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/common/hv_main.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/guest/vlapic.h
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3153 DM: add virtual hostbridge in launch script for RTVM
  devicemodel/samples/nuc/launch_hard_rt_vm.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3157 hv: initial host reset implementation
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/public/acrn_common.h
  hypervisor/scenarios/industry/vm_configurations.c
  hypervisor/scenarios/sdc/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3162 tools:acrn-crashlog: fix potential memory corruption
  tools/acrn-crashlog/acrnprobe/event_handler.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3159 hv:not allow SOS to access pre_launched vm memory
  hypervisor/arch/x86/guest/vm.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3111 doc: update coding guidelines
  doc/developer-guides/asm_coding_guidelines.rst
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation

#3168 DM: Fix minor issue of USB vendor ID
  devicemodel/hw/pci/xhci.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3172 hv: move msr_bitmap from acrn_vm to acrn_vcpu_arch
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/arch/x86/msr.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3173 hv: vm: enable iommu after vpci init
  hypervisor/arch/x86/guest/vm.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3175 debug/release: Enable enable -g option for debug build
  devicemodel/Makefile
Labels: CI: Tracked On Pass, CI: apl_sdc_stable

#3071 Doc: Add tutorial about using VxWorks as uos
  doc/tutorials/using_vxworks_as_uos.rst
Labels: area: documentation

#3178 HV: remove mptable in vm_config
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/dm/vmptable.c
  hypervisor/include/arch/x86/vm_config.h
  hypervisor/scenarios/logical_partition/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3161 hv: vtd: fix a logic error when set iommu page walk coherent
  hypervisor/arch/x86/vtd.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3176 doc: update function naming convention
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation

#3186 dm: update uos path in launch_hard_rt_vm.sh
  devicemodel/samples/nuc/launch_hard_rt_vm.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3183 vm state: reset vm state to VM_CREATED when reset_vm is called
  hypervisor/arch/x86/guest/vm.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3171 hv: Precondition checks for vcpu_from_vid
  hypervisor/arch/x86/guest/vlapic.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3195 hv: vmcs: refine CR4 guest/host mask setting
  hypervisor/arch/x86/guest/virtual_cr.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3197 dm: pci: update MMIO EPT mapping when update BAR address
  devicemodel/hw/pci/core.c
  devicemodel/hw/pci/passthrough.c
  devicemodel/include/pci_core.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3199 hv: use 64bit FACS table address only beyond ACPI2.0
  hypervisor/acpi_parser/acpi_ext.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3206 hv: Remove unused variable in ptirq_msi_info
  hypervisor/dm/vpci/vmsi.c
  hypervisor/dm/vpci/vmsix.c
  hypervisor/include/common/ptdev.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3204 dm: virtio: bugfix for polling mode
  devicemodel/hw/pci/virtio/virtio.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3201 tools:acrn-crashlog: fix error logs writing to server
  tools/acrn-crashlog/usercrash/client.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3187 doc: Update Using PREEMPT_RT-Linux for real-time UOS
  doc/tutorials/rt_linux.rst
Labels: area: documentation
