Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-10, with the labels that each got.

#3786 Makefile refine
  Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3791 acrn-config: fix pci sub class name contain "-" and ' '
  misc/acrn-config/board_config/pci_devices_h.py
Labels: Automerge: Pass, CI: Tracked On Pass

#3688 dm: Add Oracle subsystem vendor ID
  devicemodel/core/main.c
  devicemodel/hw/pci/virtio/virtio_block.c
  devicemodel/hw/pci/virtio/virtio_input.c
  devicemodel/hw/pci/virtio/virtio_net.c
  devicemodel/include/dm.h
  devicemodel/include/virtio.h
  devicemodel/samples/nuc/launch_win.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3794 hv: vpci: remove PC-Card type support
  hypervisor/hw/pci.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3707 dm: switch to launch RT_LaaG with OVMF by default
  devicemodel/samples/nuc/launch_hard_rt_vm.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3800 makefile: fix efi stub install issue
  Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3803 hv: fix error debug message in hcall_set_callback_vector
  hypervisor/common/hypercall.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3797 hv: vpci: remove pci_msi_cap in pci_pdev
  hypervisor/dm/vpci/vmsi.c
  hypervisor/hw/pci.c
  hypervisor/include/hw/pci.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3665 doc: update doc generation tooling to only work within the $BUILDDIR
  .gitignore
  doc/Makefile
  doc/scripts/filter-doc-log.sh
Labels: CI: Tracked On Pass, area: documentation

#3774 doc: move the "Building ACRN in Docker" user guide
  doc/develop.rst
  doc/getting-started/Dockerfile
  doc/getting-started/building-from-source.rst
  doc/getting-started/building_acrn_in_docker.rst
  doc/try.rst
Labels: area: documentation

#3781 doc: ioc: remove two unused parts
  doc/developer-guides/hld/hv-ioc-virt.rst
Labels: area: documentation

#3815 Corrected number issue in GSG for ACRN Ind Scenario file
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#3810 acrn-config: fix the issue some select boxes disappear after edited
  misc/acrn-config/config_app/static/main.js
Labels: Automerge: Pass, CI: Tracked On Pass

#3790 dm: refine the check of return value of snprintf
  devicemodel/hw/pci/ahci.c
  devicemodel/hw/pci/npk.c
  devicemodel/hw/pci/virtio/virtio_block.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3780 dm: reduce potential crash caused by LIST_FOREACH
  devicemodel/hw/pci/gsi_sharing.c
  devicemodel/hw/pci/virtio/virtio_mei.c
Labels: CI: Tracked On Pass

#3805 hv:remove some unnecessary includes
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/init.c
  hypervisor/boot/guest/vboot_info.c
  hypervisor/common/hv_main.c
  hypervisor/common/vm_load.c
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vhostbridge.c
  hypervisor/dm/vpci/vmsi.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/arch/x86/vm_config.h
  hypervisor/include/common/hypercall.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3740 hv: vmsr: disable prmrr related msrs in vm
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/msr.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#3816 doc: fix missing words issue in acrn configuration tool doc
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#3772 doc: optimize Clear Linux "ACRN builder" container image
  doc/getting-started/Dockerfile
  doc/getting-started/building_acrn_in_docker.rst
Labels: area: documentation

#3818 acrn-config: supply optional passthrough device for vm
  misc/acrn-config/launch_config/com.py
  misc/acrn-config/launch_config/pt.py
  misc/acrn-config/library/launch_cfg_lib.py
Labels: Automerge: Pass, CI: Tracked On Pass

#3824 dm: modify DIR handler reference postion
  devicemodel/hw/pci/npk.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3826 dm: validation for input to public functions
  devicemodel/hw/pci/core.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3792 tools: acrn-crashlog: refine crash complete code
  misc/tools/acrn-crashlog/usercrash/server.c
Labels: CI: Tracked On Pass

#3796 hv: fix a bug that tpr threshold is not updated
  hypervisor/arch/x86/guest/vlapic.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3829 dm: NVME bdf info update on KBLNUC7i7DNH
  misc/acrn-config/xmls/config-xmls/apl-mrb/hybrid.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/hybrid.xml
  misc/acrn-config/xmls/config-xmls/generic/hybrid.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/hybrid.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/hybrid.xml
Labels: Automerge: Pass, CI: Tracked On Pass

#3782 doc: add socket console backend for virtio-console
  doc/developer-guides/hld/virtio-console.rst
Labels: area: documentation

#3819 dm: close filepointer before return from acrn_load_elf()
  devicemodel/core/sw_load_elf.c
Labels: CI: Tracked On Pass

#3846 doc: add 'rsync' to the ACRN builder container
  doc/getting-started/Dockerfile
Labels: area: documentation

#3806 doc: detail change for hld-devicemodel
  doc/developer-guides/hld/hld-devicemodel.rst
Labels: area: documentation

#3784 doc: merge random device doc to virtio-rnd doc
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/images/rand-virt.png
  doc/developer-guides/hld/images/virtio-hld-image61.png
  doc/developer-guides/hld/random-virt-hld.rst
  doc/developer-guides/hld/virtio-rnd.rst
Labels: area: documentation

#3860 minor content edits to virtio-rnd doc
  doc/developer-guides/hld/virtio-rnd.rst
Labels: area: documentation

#3851 dm: fix mutex lock issue in tpm_rbc.c
  devicemodel/hw/platform/tpm/tpm_crb.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3867 doc: Align CL version for RT GSG and NUC GSG on 1.3
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#3866 doc: Align CL version for RT GSG and NUC GSG
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#3855 hv:Wrap some APIs related with guest pm
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/guest/guest_pm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3804 Doc: Update hld-trace-log.rst
  doc/developer-guides/hld/hld-trace-log.rst
  doc/developer-guides/hld/images/log-image59.png
Labels: area: documentation

#3833 doc: hld-security introduction update
  doc/developer-guides/hld/hld-security.rst
Labels: area: documentation

#3865 doc: hld-security hypervisor enhancement section update
  doc/developer-guides/hld/hld-security.rst
Labels: area: documentation

#3861 vm-manager: fix improper return value check for "strtol()"
  misc/acrn-manager/acrn_vm_ops.c
  misc/acrn-manager/acrnd.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3823 acrn-config: modify board info of block device info
  misc/acrn-config/target/parser_lib.py
  misc/acrn-config/xmls/board-xmls/apl-mrb.xml
  misc/acrn-config/xmls/board-xmls/apl-up2-n3350.xml
  misc/acrn-config/xmls/board-xmls/apl-up2.xml
  misc/acrn-config/xmls/board-xmls/nuc6cayh.xml
  misc/acrn-config/xmls/board-xmls/nuc7i7dnb.xml
Labels: CI: Tracked On Pass

#3871 doc: acrn_configuration_tool add one more scenario element description
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#3878 hv:Change the function parameter for init_ept_mem_ops
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/page.c
  hypervisor/include/arch/x86/page.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3837 doc: update Hv CPU virt HLD
  doc/developer-guides/hld/hv-cpu-virt.rst
Labels: area: documentation

#3847 doc: update hld-security verified boot section
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/images/security-image-bootflow-sbl.png
  doc/developer-guides/hld/images/security-image-bootflow-uefi.png
  doc/developer-guides/hld/images/security-image2.png
Labels: area: documentation

#3857 Doc: Add ART virtualization hld
  doc/developer-guides/hld/hv-cpu-virt.rst
Labels: area: documentation

#3845 doc:Update hypercall and upcall
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/hv-hypercall.rst
  doc/developer-guides/hld/hv-interrupt.rst
  doc/developer-guides/trusty.rst
Labels: area: documentation

#3888 acrn-config: add '--windows' option for WaaG vm
  misc/acrn-config/launch_config/com.py
Labels: Automerge: Pass, CI: Tracked On Pass

#3889 acrn-config: refine the vbootloader of vm
  misc/acrn-config/launch_config/com.py
Labels: Automerge: Pass, CI: Tracked On Pass

#3907 hv:fix reference to uninitialized variable in vmsi_remap()
  hypervisor/dm/vpci/vmsi.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3897 Misc: lifemngr-daemon-on-UOS for windows
  misc/Makefile
  misc/life_mngr/COPYING.MinGW-w64-runtime.txt
  misc/life_mngr/Makefile
  misc/life_mngr/life_mngr_win.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3908 hv[v2]: remove registration of default port IO and MMIO handlers
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/io_req.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/dm/io_req.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3921 makefile: add dash support to build efi
  Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3901 acrn-config: refine ttyS info of board file
  misc/acrn-config/library/scenario_cfg_lib.py
  misc/acrn-config/target/misc.py
  misc/acrn-config/xmls/board-xmls/apl-mrb.xml
  misc/acrn-config/xmls/board-xmls/apl-up2-n3350.xml
  misc/acrn-config/xmls/board-xmls/apl-up2.xml
  misc/acrn-config/xmls/board-xmls/nuc6cayh.xml
  misc/acrn-config/xmls/board-xmls/nuc7i7dnb.xml
Labels: CI: Tracked On Pass

#3928 OVMF release v1.4
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#3935 dm: update ACPI with latest ASL standard
  devicemodel/hw/platform/acpi/acpi.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3936 acrn-config: remove vm3 for industry scenario
  misc/acrn-config/xmls/config-xmls/apl-mrb/industry.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/industry.xml
  misc/acrn-config/xmls/config-xmls/generic/industry.xml
  misc/acrn-config/xmls/config-xmls/generic/industry_launch_3uos.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_3uos.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_3uos.xml
Labels: Automerge: Pass, CI: Tracked On Pass

#3926 hv: Update industry scenarios configuration
  hypervisor/scenarios/industry/vm_configurations.c
  hypervisor/scenarios/industry/vm_configurations.h
Labels: CI: Tracked On Pass

#3909 document: update HLD for vm management
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hld-vm-management.rst
  doc/developer-guides/hld/hv-vm-management.rst
  doc/developer-guides/hld/images/hld-image108.png
Labels: area: documentation

#3887 doc: add ahci virtualization introduction
  doc/developer-guides/hld/ahci-hld.rst
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/images/ahci-image1.png
Labels: area: documentation

#3892 doc: refine the vUART doc
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/images/uart-virt-hld-1.png
  doc/developer-guides/hld/images/uart-virt-hld-2.png
  doc/developer-guides/hld/images/uart-virt-hld-3.png
  doc/developer-guides/hld/vuart-virt-hld.rst
Labels: area: documentation

#3890 doc: modify virtio-i2c doc path
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/developer-guides/hld/images/virtio-i2c-1.png
  doc/developer-guides/hld/images/virtio-i2c-1a.png
  doc/developer-guides/hld/virtio-i2c.rst
Labels: area: documentation

#3893 doc: add entry for passthru realization
  doc/developer-guides/hld/hld-devicemodel.rst
Labels: area: documentation

#3941 doc: Align the updates of rt gsg with 1.3
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#3943 Doc: remove tutorials/rt_linux.rst file
  doc/develop.rst
  doc/tutorials/rt_linux.rst
Labels: area: documentation

#3894 doc: add virtio-gpio doc
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/developer-guides/hld/images/virtio-gpio-1.png
  doc/developer-guides/hld/images/virtio-gpio-2.png
  doc/developer-guides/hld/virtio-gpio.rst
Labels: area: documentation

#3891 doc: add RTC virtualization doc
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/rtc-virt-hld.rst
Labels: area: documentation

#3905 doc: add hostbridge emulation doc
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/hostbridge-virt-hld.rst
Labels: area: documentation

#3902 doc: add system timer virtualization
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/images/hld-dm-timer-image1.png
  doc/developer-guides/hld/system-timer-hld.rst
Labels: area: documentation

#3870 doc: Update waag tutorial
  doc/tutorials/images/windows_install_6_1.png
  doc/tutorials/images/windows_install_6_2.png
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#3884 document: update HLD for hypervisor startup
  doc/developer-guides/hld/hv-startup.rst
  doc/developer-guides/hld/images/hld-image104.png
  doc/developer-guides/hld/images/hld-image107.png
Labels: area: documentation

#3885 doc: add HLD for CAT
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hv-rdt.rst
Labels: area: documentation

#3906 doc: add atkbdc emulation doc
  doc/developer-guides/hld/atkbdc-virt-hld.rst
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/images/atkbdc-virt-hld.png
Labels: area: documentation

#3922 doc: some updates in gsg preempt rt setup guide.
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#3940 doc: Add industry argument for auto setup script
  doc/getting-started/acrn_quick_setup.sh
Labels: area: documentation

#3964 doc: fix vuart-virt-hld errors
  doc/developer-guides/hld/vuart-virt-hld.rst
Labels: area: documentation

#3962 doc: fix broken include paths
  doc/getting-started/apl-nuc.rst
  doc/tutorials/static-ip.rst
Labels: area: documentation

#3959 doc: doc build errors not being reported
  doc/conf.py
  doc/scripts/filter-doc-log.sh
Labels: area: CI, area: documentation

#3952 dm: file lock should be held till all mmap is done
  devicemodel/core/hugetlb.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3951 acrn-config: Hotfix for launch config
  misc/acrn-config/launch_config/com.py
  misc/acrn-config/launch_config/pt.py
Labels: Automerge: Pass, CI: Tracked On Pass

#3954 Modify KBL-NUC/SDC for default build
  Makefile
  misc/efi-stub/Makefile
Labels: CI: Tracked On Pass, CI: pending approve

#3970 hv: fixed by replace ull to ul.
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/arch/x86/seed/seed.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3976 HV: Fix poweroff issue of hard RTVM
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vmcs.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#3929 document: update HLD for cpu virtualization
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/hld/images/hld-image17.png
  doc/developer-guides/hld/images/hld-image35.png
  doc/developer-guides/hld/images/hld-image47.png
  doc/developer-guides/hld/images/hld-image68.png
  doc/developer-guides/hld/images/hld-image7.png
  doc/developer-guides/hld/images/static-core-image1.png
Labels: area: documentation

#3934 document: update HLD for hypervisor overview
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/images/over-image34.png
  doc/developer-guides/hld/images/over-image35.png
Labels: area: documentation

#3874 doc: Update hv power management doc
  doc/developer-guides/hld/hv-pm.rst
  doc/developer-guides/hld/images/pm-image24-105.png
Labels: area: documentation

#3836 Doc: Update system power management doc
  doc/developer-guides/hld/hld-power-management.rst
  doc/developer-guides/hld/images/hld-pm-image62.png
  doc/developer-guides/hld/images/hld-pm-image63.png
Labels: area: documentation
