Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-09, with the labels that each got.

#3596 Makefile: Refine Makefile to generate both industry and sdc images
  Makefile
  hypervisor/Makefile
  misc/efi-stub/Makefile
Labels: CI: Tracked On Pass

#3633 dm: support VM running with more than 4 vcpus
  devicemodel/core/main.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3635 DM USB: fix enumeration related issues
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3637 hv:tiny cleanup
  hypervisor/acpi_parser/acpi_ext.c
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/init.c
  hypervisor/include/arch/x86/multiboot.h
  hypervisor/include/arch/x86/security.h
  hypervisor/include/dm/vacpi.h
  hypervisor/lib/stack_protector.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3631 hv: cat: isolate hypervisor from rtvm
  hypervisor/arch/x86/cat.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/cat.h
  hypervisor/include/arch/x86/cpu.h
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3646 efi-stub: fix stack memory free issue
  misc/efi-stub/boot.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3645 hv:change function parameter for invept
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/mmu.c
  hypervisor/include/arch/x86/mmu.h
  hypervisor/include/arch/x86/pgtable.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3647 vm reset: refine platform reset
  hypervisor/arch/x86/pm.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3658 Add supported USB devices for WaaG and LaaG OSs
  doc/developer-guides/hld/usb-virt-hld.rst
Labels: area: documentation

#3559 doc: Add ACRN configuration tool tutorial
  doc/develop.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/images/GUI_of_menuconfig.png
  doc/tutorials/images/offline_tools_workflow.png
  doc/tutorials/images/sample_of_defconfig.png
Labels: area: documentation

#3653 Remove "or newer" reference to ensure that users know ACRN 1.2 requir…
  doc/release_notes/release_notes_1.2.rst
Labels: area: documentation

#3649 doc: add 'zlib1g-dev' to list of dependencies in Debian
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#3640 doc: Add three new glossaries
  doc/glossary.rst
Labels: area: documentation

#3567 doc: update Build ACRN from Source
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#3613 doc: add "-f/--force' optional arg to 'acrnctl' documentation
  misc/acrn-manager/README.rst
Labels: area: documentation

#3632 doc: update Language Extensions in coding guidelines
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation

#3650 hv: remove pr_dbg between stac/clac
  hypervisor/dm/io_req.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3643 dm: reserve 16M hole for gvt in e820 table
  devicemodel/core/sw_load_common.c
  devicemodel/include/sw_load.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3641 doc: update CODEOWNERS for doc, misc reviews
  CODEOWNERS
Labels: CI: Tracked On Pass

#3651 hv:add volatile keyword for some variables
  hypervisor/arch/x86/cpu.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3661 Vpci: adjust EPT APIs to support guest re-program PCI BAR
  hypervisor/arch/x86/pagetable.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3656 dm: remove '-p' option from the embedded help
  devicemodel/core/main.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3639 doc: update .gitignore to reflect the new location of the tools
  .gitignore
Labels: CI: Tracked On error

#3657 doc: add 'logger_setting' parameter information to acrn-dm documentation
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#3659 doc: review edits for config tool doc
  doc/develop.rst
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#3664 acrn-config: web UI app for acrn-config tool
  misc/acrn-config/config_app/app.py
  misc/acrn-config/config_app/configs.py
  misc/acrn-config/config_app/controller.py
  misc/acrn-config/config_app/requirements
  misc/acrn-config/config_app/static/main.js
  misc/acrn-config/config_app/static/styles.css
  misc/acrn-config/config_app/templates/base.html
  misc/acrn-config/config_app/templates/launch.html
  misc/acrn-config/config_app/templates/scenario.html
  misc/acrn-config/config_app/views.py
Labels: Automerge: Pass, CI: Tracked On Pass

#3667 HV: add acpi info header for nuc7i7dnb
  hypervisor/arch/x86/configs/nuc7i7dnb/platform_acpi_info.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3671 doc: update CODEOWNER for rst
  CODEOWNERS
Labels: CI: Tracked On Pass, CI: pending approve

#3668 doc: Remove "or newer/higher" descriptions for other release notes an…
  doc/release_notes/release_notes_0.6.rst
  doc/release_notes/release_notes_0.7.rst
  doc/release_notes/release_notes_0.8.rst
  doc/release_notes/release_notes_1.0.rst
  doc/release_notes/release_notes_1.1.rst
  doc/tutorials/open_vswitch.rst
  doc/tutorials/rt_linux.rst
  doc/tutorials/using_celadon_as_uos.rst
Labels: area: documentation

#3674 Misc: lifemngr-daemon-on-UOS
  misc/life_mngr/life_mngr.c
  misc/life_mngr/life_mngr.service
Labels: Automerge: Pass, CI: Tracked On Pass

#3652 hv:enable the O2 option for HV
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3677 DM: make LaaG launch script use the OVMF.fd from the Service VM
  devicemodel/samples/nuc/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3685 support vuart reliable communication
  hypervisor/dm/vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: no coding guideline

#3687 DM: update launch scripts to use OVMF.fd directly from the rootfs
  devicemodel/samples/nuc/launch_vxworks.sh
  devicemodel/samples/nuc/launch_win.sh
  devicemodel/samples/nuc/launch_zephyr.sh
  doc/tutorials/OVMF.fd
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_windows_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
Labels: Automerge: Pass, CI: Tracked On Pass

#3690 Makefile: override .config with specified scenario
  Makefile
  hypervisor/Makefile
  misc/efi-stub/Makefile
Labels: CI: Tracked On Pass

#3694 Modify the maintainer of each sub directory
  CODEOWNERS
Labels: Automerge: Pass, CI: Tracked On Pass

#3696 hv: save/restore TSC in host's suspend/resume path
  hypervisor/arch/x86/pm.c
  hypervisor/include/arch/x86/per_cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3709 hv: vm: properly reset pCPUs with LAPIC PT enabled during VM shutdown/reset
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass, CI: no coding guideline

#3703 OVMF release v1.3
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: Automerge: Pass, CI: Tracked On Pass

#3712 dm: switch to launch RT_LaaG with OVMF by default
  devicemodel/samples/nuc/launch_hard_rt_vm.sh
Labels: CI: Tracked On Pass

#3689 hv: vpci: refine vPCI BAR initialization
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/hw/pci.c
  hypervisor/include/hw/pci.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3724 fix foldernames in CODEOWNERS
  CODEOWNERS
Labels: Automerge: Pass, CI: Tracked On Pass

#3695 hv: save/restore TSC in host's suspend/resume path
  hypervisor/arch/x86/pm.c
  hypervisor/include/arch/x86/per_cpu.h
Labels: CI: Tracked On Pass, CI: apl_sdc_stable

#3728 Makefile: build default acrn.efi with nuc6cayh
  misc/efi-stub/Makefile
Labels: CI: Tracked On Pass, CI: no coding guideline

#3699 doc: update gsg and acrn_quick_setup.sh
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#3705 update using_sbl_on_up2 doc and create-up2-images.sh
  doc/tutorials/create-up2-images.sh
  doc/tutorials/using_sbl_on_up2.rst
Labels: area: documentation

#3717 doc: Add document of RT performance tuning.
  doc/develop.rst
  doc/tutorials/images/vm_exits_log.png
  doc/tutorials/realtime_performance_tuning.rst
Labels: area: documentation

#3736 doc: content updates to GSG for the Intel NUC
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#3737 doc: minor edits to using celadon as user os file
  doc/tutorials/using_celadon_as_uos.rst
Labels: area: documentation

#3735 doc: Use out-of-the-box image to boot ACRN RTVM
  doc/getting-started/acrn_ootb.rst
  doc/try.rst
Labels: area: documentation

#3701 OVMF release v1.3
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#3741 hv:fixed compilation error in Ubuntu
  hypervisor/Makefile
  hypervisor/arch/x86/cpu_caps.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3755 doc: update clearlinux version and acrn.efi name in GSG
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#3753 doc: update acrn_ootb.rst
  doc/getting-started/acrn_ootb.rst
Labels: area: documentation

#3742 doc: update ACRN configuration tool document
  doc/getting-started/building-from-source.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/images/choose_scenario.png
  doc/tutorials/images/click_import_board_info_button.png
  doc/tutorials/images/config_app_main_menu.png
  doc/tutorials/images/configure_scenario.png
  doc/tutorials/images/err_acrn_configuration.png
  doc/tutorials/images/generate_launch_script.png
  doc/tutorials/images/select_board_info.png
Labels: area: documentation

#3752 acrn-config: remove ethernet device from pass through config
  misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_aaag.xml
  misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_aliaag.xml
  misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_laag.xml
  misc/acrn-config/xmls/config-xmls/apl-up2-n3350/sdc_launch_1uos_laag.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/sdc_launch_1uos_aaag.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/sdc_launch_1uos_laag.xml
  misc/acrn-config/xmls/config-xmls/generic/hybrid_launch_1uos.xml
  misc/acrn-config/xmls/config-xmls/generic/industry_launch_1uos.xml
  misc/acrn-config/xmls/config-xmls/generic/industry_launch_2uos.xml
  misc/acrn-config/xmls/config-xmls/generic/industry_launch_3uos.xml
  misc/acrn-config/xmls/config-xmls/generic/sdc_launch_1uos.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_hardrt.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_vxworks.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_waag.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_2uos.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_3uos.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc_launch_1uos_laag.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc_launch_1uos_zephyr.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_hardrt.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_vxworks.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_waag.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_2uos.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_3uos.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc_launch_1uos_laag.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc_launch_1uos_zephyr.xml
Labels: Automerge: Pass, CI: Tracked On Pass

#3756 dm: hugetlb: add file lock to make sure huge page reserve atomic
  devicemodel/core/hugetlb.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3765 Doc: content updates to ACRN Config Tool and Build frm Source
  doc/getting-started/building-from-source.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/images/choose_scenario.png
  doc/tutorials/images/click_import_board_info_button.png
  doc/tutorials/images/config_app_main_menu.png
  doc/tutorials/images/configure_scenario.png
  doc/tutorials/images/err_acrn_configuration.png
  doc/tutorials/images/generate_launch_script.png
  doc/tutorials/images/select_board_info.png
Labels: area: documentation

#3745 doc: Release notes v1.3
  doc/release_notes/release_notes_1.3.rst
Labels: area: documentation

#3578 doc: Add introduction for using Preempt_RT VM with Industry scenario
  doc/getting-started/acrn_ootb.rst
  doc/getting-started/rt_industry.rst
  doc/try.rst
  doc/tutorials/using_cat_on_up2.rst
Labels: area: documentation

#3766 Doc: content edits for GSG for ACRN Ind Scenario
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#3748 doc: add 1.3 to version menu
  doc/conf.py
Labels: area: documentation

#3767 doc: update build from source
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#3768 doc: Add missing link in release notes 1.3
  doc/release_notes/release_notes_1.3.rst
Labels: area: documentation

#3726 Makefile: build default acrn.efi with nuc6cayh
  misc/efi-stub/Makefile
Labels: CI: Tracked On Pass

#3710 hv: vm: properly reset pCPUs with LAPIC PT enabled during VM shutdown/reset
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS
