Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-01, with the labels that each got.

#2218 dm: virtio: fix compile issue on ubuntu
  devicemodel/include/virtio.h
Labels: CI: Tracked On Pass, CI: apl_sdc_stable

#2225 hv: virq: refine hypervisor/arch/x86/virq.c
  hypervisor/arch/x86/virq.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2228 config: fix no serial output with SBL on UP2
  hypervisor/arch/x86/configs/up2.config
Labels: CI: Tracked On Pass

#2233 DM: xHCI: array bound checking before it is used
  devicemodel/hw/pci/xhci.c
Labels: Automerge: Pass

#2235 hv: virq: fix wrong coding style
  hypervisor/arch/x86/virq.c
Labels: Automerge: Pass, Coding Guidelines: PASS

#2248 DM: Try to load audio mediator BE driver before starting UOS
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: CI: apl_sdc_stable

#2250 hv:Rename several APIs for vpic and vioapic
  doc/developer-guides/hld/hv-virt-interrupt.rst
  hypervisor/arch/x86/assign.c
  hypervisor/common/hypercall.c
  hypervisor/debug/vuart.c
  hypervisor/dm/vioapic.c
  hypervisor/dm/vpic.c
  hypervisor/include/arch/x86/guest/vioapic.h
  hypervisor/include/arch/x86/guest/vpic.h
Labels: Automerge: Pass, Coding Guidelines: PASS

#2253 hv: clean the "Procedure has more than one exit point".
  hypervisor/arch/x86/guest/instr_emul.c
  hypervisor/common/io_request.c
  hypervisor/common/schedule.c
Labels: Automerge: Pass

#2254 hv: coding style: remove basic type declaration use
  hypervisor/include/arch/x86/cpu_caps.h
  hypervisor/lib/sprintf.c
Labels: Automerge: Pass

#2256 hv: coding style: refine functions under dm/ to one exit point
  hypervisor/dm/vioapic.c
  hypervisor/dm/vpci/msix.c
Labels: Automerge: Pass, Coding Guidelines: PASS

#2266 DM: Try to load audio mediator BE driver before starting UOS
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass

#2259 hv: disable more features from guest CPUID
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/arch/x86/vmcs.c
  hypervisor/include/arch/x86/cpuid.h
  hypervisor/include/arch/x86/msr.h
Labels: Automerge: Pass

#2255 fix "goto detected:exception_inject"
  hypervisor/arch/x86/guest/instr_emul.c
Labels: Automerge: Pass, Coding Guidelines: PASS

#2258 doc: add skylake NUC w/GPU passthrough doc
  doc/static/downloads/skl-patches-for-acrn.tar
  doc/tutorials/skl-nuc.rst
Labels: area: documentation

#2229 Update and complete `acrn-dm` parameters description
  devicemodel/core/main.c
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: CI: Tracked On Pass, area: documentation

#2265 hv: inst_emul: clean the "Procedure has more than one exit point"
  hypervisor/arch/x86/guest/instr_emul.c
Labels: Automerge: Pass, Coding Guidelines: PASS

#2269 script: remove DP-x:d parameters for UP2 board
  devicemodel/samples/up2/sos_bootargs_debug.txt
  devicemodel/samples/up2/sos_bootargs_release.txt
Labels: Automerge: Pass

#2281 Makefile: specify BOARD&FIRMWARE in sb-hypervisor-install
  Makefile
Labels: Automerge: Pass, CI: apl_sdc_stable

#2261 tools: acrn-crashlog: Reboot system to cold after collecting reserve log
  tools/acrn-crashlog/acrnprobe/channels.c
  tools/acrn-crashlog/acrnprobe/event_handler.c
Labels: Automerge: Pass

#2264 Fix crash by SMAP and align data types
  hypervisor/debug/profiling.c
  hypervisor/include/debug/profiling_internal.h
Labels: Automerge: Pass, CI: apl_sdc_stable

#2285 IOC mediator: fix the issue of abnormally missing tx package
  devicemodel/hw/platform/ioc.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2290 hv: vlapic: code clean-up
  doc/developer-guides/hld/hv-virt-interrupt.rst
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/irq.c
  hypervisor/boot/uefi/uefi_boot.c
  hypervisor/common/io_request.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2263 profiling: code cleanup
  hypervisor/debug/profiling.c
  hypervisor/include/debug/profiling_internal.h
Labels: Coding Guidelines: PASS

#2293 doc: add more rules in coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2286 IOC mediator: fix the issue of abnormally missing tx package
  devicemodel/hw/platform/ioc.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2294 doc: Four kinds of KBL NUC added in "Supported Hardware"
  doc/hardware.rst
Labels: area: documentation

#2287 Doc: Add release note for v0.5 release.
  doc/release_notes_0.5.rst
Labels: area: documentation

#2308 hv:fix violations
  hypervisor/arch/x86/timer.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2289 hv: fix MISRAC violations for crypto lib
  hypervisor/lib/crypto/mbedtls/md.c
  hypervisor/lib/crypto/mbedtls/md.h
  hypervisor/lib/crypto/mbedtls/md_internal.h
  hypervisor/lib/crypto/mbedtls/md_wrap.c
  hypervisor/lib/crypto/mbedtls/sha256.c
  hypervisor/lib/crypto/mbedtls/sha256.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2313 hv: init: minor fix related to header file
  hypervisor/include/arch/x86/init.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2314 hv: instr emul: remove some MISRA-C violations in instr_emul.c
  hypervisor/arch/x86/guest/instr_emul.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2304 hv: fix MISRA-C violations in vpic.c and vioapic.c
  hypervisor/dm/vioapic.c
  hypervisor/dm/vpic.c
  hypervisor/include/arch/x86/guest/vioapic.h
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/arch/x86/guest/vpic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2318 hv: fix 2 minor MISRA-C violations in inst_emul.c
  hypervisor/arch/x86/guest/instr_emul.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2312 hv:fix MISRA-C violation in multiboot.c
  hypervisor/boot/sbl/multiboot.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2305 hv: virq: fix attempt to change parameter passed by value
  hypervisor/arch/x86/virq.c
  hypervisor/include/arch/x86/irq.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2335 hv: string: rename `s1` and `s2`
  hypervisor/lib/string.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2310 DM: sos_bootargs: Add panic_print parameter to help debugging
  devicemodel/samples/apl-mrb/sos_bootargs_debug.txt
  devicemodel/samples/apl-mrb/sos_bootargs_release.txt
Labels: Automerge: Pass, CI: Tracked On Pass

#2337 dm: add dm log to kmsg for profiling
  devicemodel/Makefile
  devicemodel/core/main.c
  devicemodel/include/dm.h
  devicemodel/include/dm_kmsg.h
  devicemodel/lib/dm_kmsg.c
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2324 hv: fix coding style violations in acpi.c
  hypervisor/boot/acpi.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2339 Doc: Add one new known issue into v0.5 release note
  doc/release_notes_0.5.rst
Labels: area: documentation

#2317 hv: fix MISRA-C violations in vmsr.c
  hypervisor/arch/x86/guest/vmsr.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2353 dm: passthru: increase the delay after wifi reset
  devicemodel/hw/pci/passthrough.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2321 hv: Make reserved regions in E820 table to Supervisor pages
  hypervisor/arch/x86/mmu.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2359 hv:fix MISRA-C violation in virq.c
  hypervisor/arch/x86/virq.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2362 hv: add more MSR definitions
  hypervisor/include/arch/x86/msr.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2366 dm: script: echo 'high' instead of "out" to direction for gpio460
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2368 launch_uos.sh remove sd card passthru option
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2364 HV: modularization to separate CR related code
  doc/acrn.doxyfile
  hypervisor/Makefile
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/virtual_cr.c
  hypervisor/arch/x86/vmcs.c
  hypervisor/arch/x86/vmexit.c
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/arch/x86/virtual_cr.h
  hypervisor/include/arch/x86/vmcs.h
  hypervisor/include/arch/x86/vmexit.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2369 Makefile: support SBL binary for E2E build
  Makefile
  devicemodel/Makefile
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#2375 HV: check to avoid interrupt delay timer add twice
  hypervisor/common/ptdev.c
  hypervisor/include/arch/x86/timer.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2381 dm: script: use -d to check existence of gpio460
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2382 HV: modularization cleanup instr_emul header file
  hypervisor/arch/x86/ept.c
  hypervisor/arch/x86/guest/instr_emul.c
  hypervisor/arch/x86/guest/instr_emul.h
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/io_emul.c
  hypervisor/include/arch/x86/guest/instr_emul.h
  hypervisor/include/arch/x86/per_cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2386 Makefile: add rules for installing debug information
  Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#2400 tools: acrn-manager: fix mngr_send_msg() return 0 when read ack fail
  tools/acrn-manager/acrn_mngr.c
Labels: CI: apl_sdc_stable

#2396 dm: storage: change DISCARD to synchronous mode
  devicemodel/hw/block_if.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2388 kconfig: update .config on missed or conflicting symbol values
  scripts/kconfig/silentoldconfig.py
Labels: Automerge: Pass, CI: Tracked On Pass

#2399 hv: vlapic: remove `calcvdest`
  hypervisor/arch/x86/assign.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/dm/vioapic.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2377 doc: add more rules in coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2360 Use $(MAKE) when recursing
  Makefile
  devicemodel/Makefile
  tools/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#2357 tools: respect CFLAGS and LDFLAGS from environment
  tools/acrn-manager/Makefile
  tools/acrnlog/Makefile
  tools/acrntrace/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2384 security: bounds checking to avoid buffer overflow error
  hypervisor/include/debug/profiling_internal.h
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2404 Makefile: add missing dependency
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2420 dm: add log for debuging pci while vm reset
  devicemodel/arch/x86/pm.c
  devicemodel/core/vmmapi.c
  devicemodel/hw/pci/core.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable, Coding Guidelines: PASS

#2425 hv:Move severl variable declaration for boot code
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/mmu.c
  hypervisor/arch/x86/trampoline.c
  hypervisor/boot/include/reloc.h
  hypervisor/boot/reloc.c
  hypervisor/include/arch/x86/boot/ld_sym.h
  hypervisor/include/arch/x86/cpu.h
  hypervisor/include/arch/x86/mmu.h
  hypervisor/include/arch/x86/trampoline.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2421 tools: acrnd: fix wait_for_stop() return wrong vm state
  tools/acrn-manager/acrnd.c
Labels: CI: apl_sdc_stable

#2434 hv: remove redundant code for virtual interrupt injection
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/virq.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2430 Documentation build tools: update min version for kconfiglib
  doc/scripts/requirements.txt
Labels: area: documentation

#2437 hv: fix misra-c violations in reused partition mode functions
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/vmcs.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2423 profiling: fix the system freeze issue when running profiling
  hypervisor/debug/profiling.c
  hypervisor/include/debug/profiling_internal.h
Labels: CI: Tracked On Pass, CI: apl_sdc_stable

#2444 HV: modularization improve UEFI macro control code
  efi-stub/Makefile
  efi-stub/boot.c
  hypervisor/Makefile
  hypervisor/arch/x86/guest/guest.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/irq.c
  hypervisor/arch/x86/trampoline.c
  hypervisor/arch/x86/vmx.c
  hypervisor/boot/acpi.c
  hypervisor/boot/uefi/uefi_boot.c
  hypervisor/bsp/include/bsp_extern.h
  hypervisor/bsp/include/uefi/uefi.h
  hypervisor/bsp/sbl/sbl.c
  hypervisor/bsp/uefi/uefi.c
  hypervisor/include/arch/x86/ioapic.h
  hypervisor/include/arch/x86/per_cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2424 HV: MISRA clean in reloc.c
  hypervisor/boot/reloc.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2447 doc: update documents for "--lapic_pt" feature
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hv-virt-interrupt.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#2428 doc: update coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2458 doc: add rt-linux tutorial
  doc/getting-started/apl-nuc.rst
  doc/tutorials/images/RT-NUC-setup.png
  doc/tutorials/rt_linux.rst
Labels: area: documentation

#2459 doc: add Trusty ACRN doc
  doc/tutorials/images/trustyacrn-image1.png
  doc/tutorials/images/trustyacrn-image2.png
  doc/tutorials/images/trustyacrn-image3.png
  doc/tutorials/images/trustyacrn-image4.png
  doc/tutorials/images/trustyacrn-image5.png
  doc/tutorials/images/trustyacrn-image6.png
  doc/tutorials/images/trustyacrn-image7.png
  doc/tutorials/trustyACRN.rst
Labels: area: documentation

#2438 doc: change term of vm0 to sos_vm
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hv-memmgt.rst
  doc/developer-guides/hld/hv-startup.rst
  doc/developer-guides/hld/hv-vt-d.rst
  doc/developer-guides/primer.rst
  doc/faq.rst
  doc/introduction/index.rst
Labels: area: documentation

#2470 hv: fix dest of IPI for CPU with lapic_pt
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vmcs.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2473 Documentation: add caption to the "PREEMPT_RT VM on ACRN" figure
  doc/tutorials/rt_linux.rst
Labels: area: documentation
