Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-06, with the labels that each got.

#3208 dm: pci: fix the MMIO regions overlap when getting bar size
  devicemodel/hw/pci/core.c
  devicemodel/include/pci_core.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3209 dm: passthrough: allow not page-aligned sized bar to be mapped
  devicemodel/hw/pci/passthrough.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3191 doc: update prefix format in coding guidelines
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation

#3113 doc: setup logical parition scenario on kbl nuc i7
  doc/tutorials/images/logical_partition_scenario_on_nuc.png
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#3229 OVMF release v1.1
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: Automerge: Pass, CI: Tracked On Pass

#3233 dm: support VMs communication with virtio-console
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3225 doc: remove 'reboot' command from ACRN shell user guide
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#3238 Added recommended BIOS settings for better real-time performance.
  doc/tutorials/rt_linux.rst
Labels: area: documentation

#3220 ACRN/HV: Add one new board configuration for ACRN-hypervisor
  hypervisor/arch/x86/configs/icl-rvp.config
  hypervisor/arch/x86/configs/icl-rvp/board.c
  hypervisor/arch/x86/configs/icl-rvp/ve820.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3236 doc: add multiboot module string parameter
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_up2.rst
Labels: area: documentation

#3240 dm: Solve the problem of repeat mount hugetblfs
  devicemodel/core/hugetlb.c
  devicemodel/core/main.c
  devicemodel/include/vmmapi.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3223 hv: fix possible null pointer dereference
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/vtd.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3230 Fix a small typo
  doc/getting-started/building-from-source.rst
Labels: area: documentation, no Signed-off-by

#3248 xsave: inject GP when guest tries to write 1 to XCR0 reserved bit
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/include/arch/x86/cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3246 doc: add an introduction for building hypervisor
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#3243 DM: Adjust the priority related with ioreq emulation for Android Guest
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: CI: Tracked On Pass, CI: apl_sdc_stable

#3244 HV: introduce relative vm id for hcall api
  hypervisor/arch/x86/guest/vmcall.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3169 HV:Modularize vpic code to remove usage of acrn_vm
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/guest/virq.c
  hypervisor/common/hypercall.c
  hypervisor/dm/vpic.c
  hypervisor/dm/vuart.c
  hypervisor/include/dm/vpic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3250 ACRN/HV: emulated pcicfg uses the aligned offset to fix the unaligned…
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/hw/pci.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3256 doc: remove (outdated) primer documents
  doc/developer-guides/contribute_guidelines.rst
  doc/developer-guides/hld/hld-APL_GVT-g.rst
  doc/developer-guides/images/primer-dma-address-mapping.png
  doc/developer-guides/images/primer-host-gdt.png
  doc/developer-guides/images/primer-hypervisor-interrupt.png
  doc/developer-guides/images/primer-mem-layout.png
  doc/developer-guides/images/primer-pirq-routing.png
  doc/developer-guides/images/primer-pv-mapping.png
  doc/developer-guides/images/primer-sos-ept-mapping.png
  doc/developer-guides/images/primer-symmetric-io.png
  doc/developer-guides/images/primer-uos-ept-mapping.png
  doc/developer-guides/images/primer-virtio-net.png
  doc/developer-guides/index.rst
  doc/developer-guides/primer.rst
Labels: area: documentation

#3259 dm: enable audio passthrough device.
  devicemodel/samples/nuc/launch_win.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3258 DM: vrpmb: replace assert() with return false
  devicemodel/core/vrpmb.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3251 Introduce vLAPIC state for VMs
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hv_main.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/arch/x86/guest/vlapic.h
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3262 hv: ept: unify EPT API name to verb-object style
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/hld/hv-memmgt.rst
  doc/release_notes_0.2.rst
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/guest/trusty.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vmtrr.c
  hypervisor/common/hypercall.c
  hypervisor/dm/io_req.c
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/include/arch/x86/guest/ept.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3260 DM: Samples: Enable VxWorks as hard-rt VM
  devicemodel/samples/nuc/launch_vxworks.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3266 hv: Rename tables member of vPCI msix struct pci_msix
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vmsix.c
  hypervisor/include/dm/vpci.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3271 ACRN: DM: Add new options for NUC launch_uos script.
  devicemodel/samples/nuc/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3264 doc: add systemd-networkd-autostart bundle in APL GSG
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#3269 dm: add virtio-rnd device to command line
  devicemodel/samples/nuc/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3270 dm: passthru: remove the use of assert()
  devicemodel/hw/pci/passthrough.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3284 dm: virtio-net: clean up assert
  devicemodel/hw/pci/virtio/virtio_net.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3285 HV: Fix OVMF hang issue when boot with lapic_pt
  hypervisor/common/hypercall.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3137 doc: Instruction of enabling ACRN-DM QoS.
  doc/tutorials/acrn-dm_QoS.rst
  doc/tutorials/images/acrn-dm_qos_architecture.png
  doc/tutorials/images/cpu_utilization_image.png
Labels: area: documentation

#3275 hv: vlapic: clear which access type we support for APIC-Access VM Exit
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/include/arch/x86/guest/vmcs.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3297 HV: Allow pause RTVM when its state is VM_CREATED
  hypervisor/arch/x86/guest/vm.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3296 HV: fix expression is not boolean
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/boot/cmdline.c
  hypervisor/debug/console.c
  hypervisor/dm/vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3308 dm: samples: use stdio as vxWorks console by default
  devicemodel/samples/nuc/launch_vxworks.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3304 dm: clean up assert in virtio_input.c
  devicemodel/hw/pci/virtio/virtio_input.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3305 dm: clean up assert in virtio_audio.c
  devicemodel/hw/pci/virtio/virtio_audio.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3306 dm: clean up assert in virtio.c
  devicemodel/hw/pci/virtio/virtio.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3307 hv:Fix MISRA-C violations for static inline
  hypervisor/arch/x86/guest/vcpu.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3300 hv: Avoid run-time buffer overflows with IOAPIC data structures
  hypervisor/arch/x86/Kconfig
  hypervisor/arch/x86/ioapic.c
  hypervisor/include/arch/x86/ioapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3314 dm: refine assert usage
  devicemodel/core/mevent.c
  devicemodel/hw/pci/uart.c
  devicemodel/hw/pci/virtio/virtio_console.c
  devicemodel/hw/uart_core.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3312 Doc: Update acrn-shell.rst for new 'version' cmd
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#3309 doc: update acrnd/acrnctl option docs
  tools/acrn-manager/README.rst
Labels: area: documentation

#3316 DM: virtio_rpmb: clean up assert
  devicemodel/hw/pci/virtio/virtio_rpmb.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3311 HV: Debug: Add version command
  hypervisor/debug/shell.c
  hypervisor/debug/shell_priv.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3322 HV:fix simple violations
  hypervisor/arch/x86/configs/vmptable.c
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/vtd.c
  hypervisor/boot/acpi_base.c
  hypervisor/boot/guest/vboot_info.c
  hypervisor/dm/vrtc.c
  hypervisor/dm/vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3287 TravisCI: remove all config and support files related to TravisCI
  .travis-dockerfiles/Dockerfile.centos7
  .travis-dockerfiles/Dockerfile.clearlinux
  .travis-dockerfiles/Dockerfile.debian8
  .travis-dockerfiles/Dockerfile.fedora26
  .travis-dockerfiles/Dockerfile.fedora27
  .travis-dockerfiles/Dockerfile.fedora28
  .travis-dockerfiles/Dockerfile.ubuntu14.04
  .travis-dockerfiles/Dockerfile.ubuntu16.04
  .travis-dockerfiles/Dockerfile.ubuntu18.04
  .travis-dockerfiles/README.md
  .travis.yml
Labels: Automerge: Pass, CI: Tracked On Pass

#3327 ACRN: dm: Modify the runC.json for NUC.
  devicemodel/samples/nuc/runC.json
Labels: Automerge: Pass, CI: Tracked On Pass

#3320 hv:fix a bug for building debug/release lib
  hypervisor/Makefile
  hypervisor/debug/Makefile
  hypervisor/release/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3326 DM USB: clean up the assert usage
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_mouse.c
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3313 hv: vlapic: remove ISR vector stack
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3321 dm: sample: remove deprecated sos_bootargs files
  devicemodel/samples/apl-mrb/sos_bootargs_debug.txt
  devicemodel/samples/apl-mrb/sos_bootargs_release.txt
  devicemodel/samples/apl-up2/sos_bootargs_debug.txt
  devicemodel/samples/apl-up2/sos_bootargs_release.txt
Labels: Automerge: Pass, CI: Tracked On Pass

#3336 hv: bugfix for sbuf reset
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/debug/sbuf.c
  hypervisor/include/debug/sbuf.h
  hypervisor/release/sbuf.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3338 DM: virtio-console: bug fix for parsing options
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3318 tools: enhance online and built-in help messages
  tools/acrn-manager/README.rst
  tools/acrn-manager/acrnd.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3323 doc: Add v1.1 release note
  doc/release_notes_1.1.rst
Labels: area: documentation

#3328 doc: Update acrn-manager README and QoS introduction
  doc/tutorials/acrn-dm_QoS.rst
  tools/acrn-manager/README.rst
Labels: area: documentation

#3345 dm: add "noapic" to rt-linux kernel parameters
  devicemodel/samples/nuc/launch_hard_rt_vm.sh
Labels: Automerge: Pass, CI: Tracked On Pass
