Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-04, with the labels that each got.

#2861 hv: add default handlers for PIO/MMIO access
  hypervisor/arch/x86/guest/io_emul.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/guest/io_emul.h
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2867 Acrn 2358 tools acrnctl
  tools/acrn-manager/acrnctl.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2869 OVMF release v0.8
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/MD5SUM_vsbl
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/SHA512SUM_vsbl
  devicemodel/bios/changelog_ovmf.txt
  devicemodel/bios/changelog_vsbl.txt
  doc/user-guides/acrn-dm-parameters.rst
Labels: Automerge: Pass, CI: Tracked On Pass

#2842 doc: add kernel parameters documentation
  doc/developer-guides/GVT-g-kernel-options.rst
  doc/developer-guides/index.rst
  doc/developer-guides/kernel-parameters.rst
Labels: area: documentation

#2841 doc: minor changes according to one binary for SBL and UEFI
  doc/tutorials/using_partition_mode_on_up2.rst
  doc/tutorials/using_ubuntu_as_sos.rst
Labels: area: documentation

#2873 vm_id and acrn_vm pointer cleanup
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hypercall.c
  hypervisor/common/io_req.c
  hypervisor/debug/profiling.c
  hypervisor/debug/shell.c
  hypervisor/debug/vuart.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2875 hv: remove the unnecessary equality operation
  hypervisor/dm/vpic.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2876 hv: trusty: minor change of coding style
  hypervisor/arch/x86/guest/trusty.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2878 HV: removed unused pt_dev.c in board folder
  hypervisor/arch/x86/configs/apl-mrb/pt_dev.c
  hypervisor/arch/x86/configs/dnv-cb2/pt_dev.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2877 hv: fix "Else alternative missing in if."
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/guest/instr_emul.c
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/security.c
  hypervisor/debug/dbg_cmd.c
  hypervisor/debug/npk_log.c
  hypervisor/debug/shell.c
  hypervisor/dm/vpci/vmsix.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2882 hv: check vector count when set/reset msix info
  hypervisor/common/hypercall.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2885 doc: update documents for "--rtvm" parameter
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#2888 dm: storage: add read-only feature for virtio-blk
  devicemodel/hw/pci/virtio/virtio_block.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2889 DM: Keep consistency between HV and DM about PM1A_CNT_ADDR
  devicemodel/arch/x86/pm.c
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/include/acpi.h
  hypervisor/include/public/acrn_common.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2893 DM USB: fix memory leak during reboot
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
  devicemodel/include/usb_pmapper.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2855 doc: add some rules related to function documentation
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2894 doc: re-organize and consolidate ACRN kernel parameters documentation
  doc/developer-guides/GVT-g-kernel-options.rst
  doc/developer-guides/index.rst
  doc/developer-guides/kernel-parameters.rst
  doc/user-guides/images/i915-image1.png
  doc/user-guides/images/i915-image2.png
  doc/user-guides/images/i915-image3.png
  doc/user-guides/images/i915-image4.png
  doc/user-guides/images/i915-image5.png
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#2900 doc: tweaks to the "User Guides" section (esp. "ACRN DM parameters")
  doc/user-guides/acrn-dm-parameters.rst
  doc/user-guides/index.rst
Labels: area: documentation

#2905 DM: virtio-gpio: implement GPIO operations by PIO
  devicemodel/hw/pci/virtio/virtio_gpio.c
  devicemodel/include/gpio_dm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2856 doc: fix '@return' and '@retval' statements for vCPU ops
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2904 hv: Remove CONFIG_PARTITION_MODE used to compile out irq enable/disable
  hypervisor/include/arch/x86/cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2906 doc: update rules category in coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2909 dm: remove "acrn_" prefix from tap name
  devicemodel/hw/pci/virtio/virtio_net.c
  devicemodel/samples/apl-mrb/launch_uos.sh
  devicemodel/samples/apl-up2/launch_uos.sh
  devicemodel/vmcfg/apl-mrb/mrb-env-setup.sh
  tools/acrnbridge/Makefile
  tools/acrnbridge/acrn.network
  tools/acrnbridge/tap0.netdev
Labels: Automerge: Pass, CI: Tracked On Pass

#2846 doc: add the ACRN debug tutorial document
  doc/tutorials/debug.rst
  doc/tutorials/images/debug_image1.png
  doc/tutorials/images/debug_image19.png
  doc/tutorials/images/debug_image2.png
  doc/tutorials/images/debug_image20.png
  doc/tutorials/images/debug_image21.png
  doc/tutorials/images/debug_image22.png
  doc/tutorials/images/debug_image23.png
  doc/tutorials/images/debug_image24.png
  doc/tutorials/images/debug_image25.png
  doc/tutorials/images/debug_image26.png
  doc/tutorials/images/debug_image27.png
  doc/tutorials/images/debug_image28.png
  doc/tutorials/images/debug_image3.png
  doc/tutorials/images/debug_image4.png
  doc/tutorials/images/debug_image5.png
  doc/user-guides/acrn-shell.rst
  doc/user-guides/images/shell_image10.png
  doc/user-guides/images/shell_image11.png
  doc/user-guides/images/shell_image12.png
  doc/user-guides/images/shell_image13.png
  doc/user-guides/images/shell_image14.png
  doc/user-guides/images/shell_image15.png
  doc/user-guides/images/shell_image16.png
  doc/user-guides/images/shell_image17.png
  doc/user-guides/images/shell_image18.png
  doc/user-guides/images/shell_image6.png
  doc/user-guides/images/shell_image7.png
  doc/user-guides/images/shell_image8.png
  doc/user-guides/images/shell_image9.png
Labels: area: documentation

#2914 doc: update the "ACRN Debugging Tools" tutorial
  doc/tutorials/debug.rst
Labels: area: documentation

#2911 doc: update documentation to the latest TAP name (no acrn_ prefix)
  doc/developer-guides/hld/virtio-net.rst
  doc/getting-started/apl-nuc.rst
  doc/tutorials/agl-vms.rst
  doc/tutorials/launch_uos.sh
  doc/tutorials/static-ip.rst
  doc/tutorials/using_ubuntu_as_sos.rst
Labels: area: documentation

#2910 doc: add rules in coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2916 doc: add 0.8 version to master branch
  doc/conf.py
Labels: area: documentation

#2913 doc: add v0.8 release note
  doc/release_notes_0.8.rst
Labels: area: documentation

#2929 DM USB: xHCI: WA for an isochronous crash issue
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
  devicemodel/include/usb_core.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2930 DM USB: xHCI: fix an issue during BULK transfer
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2932 dm: passthru: support SD hotplug
  devicemodel/hw/pci/passthrough.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2928 Domain id and name added to launch_uos.sh
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#2935 hv: Use virtual APIC IDs for Pre-launched VMs
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/dm/vmptable.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2936 DM USB: xHCI: refine the failure process logic of control transfer
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2948 hv: rename 'assign_iommu_device' and 'unassign_iommu_device'
  doc/developer-guides/hld/hv-vt-d.rst
  hypervisor/arch/x86/vtd.c
  hypervisor/common/hypercall.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/arch/x86/vtd.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2942 hv: Build mptable for guest if VM type is Pre-Launched
  hypervisor/Makefile
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/vmptable.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/arch/x86/vm_config.h
  hypervisor/include/dm/mptable.h
  hypervisor/scenarios/logical_partition/vm_configurations.c
  hypervisor/scenarios/logical_partition/vm_configurations.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2950 tools: acrn-manager: fix the possibility of creating directory at wil…
  devicemodel/core/monitor.c
  tools/acrn-manager/acrn_mngr.c
  tools/acrn-manager/acrn_mngr.h
  tools/acrn-manager/acrn_vm_ops.c
  tools/acrn-manager/acrnctl.c
  tools/acrn-manager/acrnctl.h
  tools/acrn-manager/acrnd.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2953 dm: fix possible memory leak in 'load_elf32()'
  devicemodel/core/sw_load_elf.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2951 tools: acrn-manager: fix mngr_send_msg() return 0 when read ack fail
  tools/acrn-manager/acrn_mngr.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2952 tools: acrnd: fix wait_for_stop() return wrong vm state
  tools/acrn-manager/acrnd.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2949 tools: acrn-mngr: add delay to allow user to prevent VM autostart for debug
  tools/acrn-manager/acrnd.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2539 hv: add new hypercall to fetch platform configurations
  hypervisor/arch/x86/guest/vmcall.c
  hypervisor/common/hypercall.c
  hypervisor/include/common/hypercall.h
  hypervisor/include/public/acrn_hv_defs.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2954 tools: acrn-crashlog: fix some possible memory leak
  tools/acrn-crashlog/acrnprobe/load_conf.c
  tools/acrn-crashlog/common/fsutils.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2964 DM: enable debug macro and remap watchdog reset
  Makefile
  devicemodel/Makefile
  devicemodel/core/main.c
  devicemodel/hw/pci/wdt_i6300esb.c
  devicemodel/include/vmmapi.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2966 hv: Remove need for init_fallback_iommu_domain and fallback_iommu_domain
  doc/developer-guides/hld/hv-vt-d.rst
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/vtd.c
  hypervisor/common/hypercall.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpci/vpci_priv.h
  hypervisor/include/arch/x86/vtd.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2960 HV: enable lapic passthru for logical partition VM1
  hypervisor/scenarios/logical_partition/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2968 hv: enable vMCE from guest CPUID
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2970 hv: Add host CR2 to exception dump
  hypervisor/debug/dump.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2972 dm: add IOCTL command to get platform information
  devicemodel/include/public/vhm_ioctl_defs.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2958 doc: Setting up KBL serial console on the GSG
  doc/getting-started/apl-nuc.rst
  doc/getting-started/images/RS232-to-USB-to-Host-cable.png
Labels: area: documentation

#2943 doc: update coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2946 doc: add security advisory section in ACRN introduction website
  README.rst
Labels: area: documentation

#2973 hv:hotfix for register_mmio_emulation_handler
  hypervisor/dm/io_req.c
  hypervisor/dm/vioapic.c
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/include/dm/io_req.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2967 hv: vlapic: add TPR below threshold implement
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2940 acrn-dm: enable debug option for acrn-dm
  Makefile
  devicemodel/Makefile
  devicemodel/core/main.c
  devicemodel/hw/pci/wdt_i6300esb.c
  devicemodel/include/vmmapi.h
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2975 hv: reset per cpu sbuf pointers during vcpu reset
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/debug/sbuf.c
  hypervisor/include/debug/sbuf.h
  hypervisor/release/sbuf.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: no coding guideline

#2990 hv: ept: correct EPT mapping gpa check
  hypervisor/common/hypercall.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2980 hv: seed: fix potential NULL pointer dereferencing
  hypervisor/arch/x86/seed/seed_sbl.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2985 hv: check vm state before creating a VM
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hypercall.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2983 hv: free ptdev device IRQs when shutting down VM
  hypervisor/common/ptdev.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2986 HV: validate target vm in hypercall
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2989 hv: allocate vpid based on vm_id and vcpu_id mapping
  doc/developer-guides/hld/hv-memmgt.rst
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/mmu.c
  hypervisor/arch/x86/static_checks.c
  hypervisor/include/arch/x86/mmu.h
  hypervisor/include/arch/x86/vmx.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2996 hv: fix possible buffer overflow in vlapic.c
  hypervisor/arch/x86/guest/vlapic.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2997 dm: fix possible null pointer dereference in pci_gvt_deinit
  devicemodel/hw/pci/gvt.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3000 dm: uart: use mevent_add only when it is a tty
  devicemodel/hw/uart_core.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2999 HV: fix the issue of ACRN_REQUEST_EXCP flag is not cleared.
  hypervisor/arch/x86/guest/virq.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3005 HV: Add prefix 'p' before 'cpu' to physical cpu related functions
  hypervisor/arch/x86/boot/cpu_primary.S
  hypervisor/arch/x86/boot/trampoline.S
  hypervisor/arch/x86/cat.c
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/cpu_state_tbl.c
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/arch/x86/init.c
  hypervisor/arch/x86/irq.c
  hypervisor/arch/x86/lapic.c
  hypervisor/arch/x86/mmu.c
  hypervisor/arch/x86/notify.c
  hypervisor/arch/x86/pm.c
  hypervisor/arch/x86/security.c
  hypervisor/arch/x86/timer.c
  hypervisor/bsp/firmware_uefi.c
  hypervisor/common/hv_main.c
  hypervisor/common/ptdev.c
  hypervisor/common/schedule.c
  hypervisor/common/softirq.c
  hypervisor/debug/dump.c
  hypervisor/debug/logmsg.c
  hypervisor/debug/npk_log.c
  hypervisor/debug/profiling.c
  hypervisor/debug/shell.c
  hypervisor/debug/trace.c
  hypervisor/include/arch/x86/cpu.h
  hypervisor/include/arch/x86/cpu_caps.h
  hypervisor/include/arch/x86/init.h
  hypervisor/include/arch/x86/mmu.h
  hypervisor/include/arch/x86/per_cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3006 HV: Remove unnecssary indent in pm.c
  hypervisor/arch/x86/pm.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3007 HV: move AP_MASK to cpu.h
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/pm.c
  hypervisor/include/arch/x86/cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3004 vlapic: refine IPI broadcast to support x2APIC mode
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3008 HV: correct usage of GUEST_FLAG_IO_COMPLETION_POLLING
  hypervisor/arch/x86/guest/vm.c
  hypervisor/scenarios/logical_partition/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3017 tools:acrn-crashlog: fix the compiling error
  tools/acrn-crashlog/acrnprobe/main.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3015 acrn/dm: gvt returns negative errno to terminate the initialization
  devicemodel/hw/pci/gvt.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3016 DM: virtio-gpio: fix falling or rising irq can't work
  devicemodel/hw/pci/virtio/virtio_gpio.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3021 Makefile: add gcc option to workaround build issue with latest gcc
  devicemodel/Makefile
  tools/acrn-manager/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#2977 doc: re-organize coding guidelines
  doc/developer-guides/c_coding_guidelines.rst
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#3025 hv: separate host e820 and SOS ve820
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/vm_load.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2995 HV: check vm id param when dispatching hypercall
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vmcall.c
  hypervisor/debug/vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3031 HV: minor changes on pci devices config
  hypervisor/arch/x86/configs/apl-mrb/pci_devices.h
  hypervisor/arch/x86/configs/dnv-cb2/pci_devices.h
  hypervisor/arch/x86/configs/nuc7i7bnh/pci_devices.h
  hypervisor/scenarios/logical_partition/pt_dev.c
  hypervisor/scenarios/logical_partition/vm_configurations.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3023 hv: instr_emul: fix operand size decode
  hypervisor/arch/x86/guest/instr_emul.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3035 hv: Rename NORMAL_VM to POST_LAUNCHED_VM
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/introduction/index.rst
  hypervisor/arch/x86/Kconfig
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hypercall.c
  hypervisor/dm/io_req.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/arch/x86/vm_config.h
  hypervisor/scenarios/sdc/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3029 DM: virtio-gpio: close gpio line fd
  devicemodel/hw/pci/virtio/virtio_gpio.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3041 hv: add scenario for the industry use case
  hypervisor/Makefile
  hypervisor/arch/x86/Kconfig
  hypervisor/scenarios/industry/vm_configurations.c
  hypervisor/scenarios/industry/vm_configurations.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3026 doc: rename rules ID in C coding guidelines
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation

#3018 DOC: change hv shell cmd sos_console to vm_console
  doc/developer-guides/hld/hv-partitionmode.rst
  doc/tutorials/debug.rst
  doc/tutorials/using_partition_mode_on_up2.rst
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#3014 doc: update instructions for building ACRN on Ubuntu 16.04
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#3044 HV: correct GUEST_FLAG_IO_COMPLETION_POLLING in SOS
  hypervisor/scenarios/industry/vm_configurations.c
  hypervisor/scenarios/sdc/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3045 doc: add rules in C coding guidelines
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation

#3040 doc: How to build ACRN on Fedora 29
  doc/faq.rst
Labels: area: documentation
