Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-11, with the labels that each got.

#3969 Modify KBL-NUC/SDC for default build on master
  Makefile
  misc/efi-stub/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3985 Makefile: add default defconfig for new board
  Makefile
  hypervisor/Makefile
Labels: CI: Tracked On Pass

#3986 acrn-config: add serial config in new $(board).config
  misc/acrn-config/board_config/board_cfg_gen.py
  misc/acrn-config/board_config/new_board_kconfig.py
  misc/acrn-config/library/board_cfg_lib.py
Labels: CI: Tracked On Pass

#3988 acrn-config: add 'xhci' usb mediator for laag and waag
  misc/acrn-config/launch_config/com.py
Labels: CI: Tracked On Pass

#3981 HV: Fix poweroff issue of hard RTVM
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vmcs.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3995 Revert "Makefile: add default defconfig for new board"
  Makefile
  hypervisor/Makefile
Labels: CI: Tracked On Pass

#3961 doc: OVMF high level description
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/images/over-image134.png
Labels: area: documentation

#3990 doc: remove the guest cpu number option '-c' from the document
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#3973 doc: remove redundant copy of ovmf.fd firmware
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/using_celadon_as_uos.rst
Labels: area: documentation

#4000 dm: remove cfc/cf8 pio handler
  devicemodel/hw/pci/core.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3944 doc: Remove apl gsg and merge contents into rt gsg
  doc/develop.rst
  doc/faq.rst
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/changelog_QuickSetupScript.txt
  doc/getting-started/rt_industry.rst
  doc/getting-started/up2.rst
  doc/reference/hardware.rst
  doc/release_notes/release_notes_0.6.rst
  doc/release_notes/release_notes_0.7.rst
  doc/release_notes/release_notes_0.8.rst
  doc/release_notes/release_notes_1.0.rst
  doc/release_notes/release_notes_1.1.rst
  doc/release_notes/release_notes_1.2.rst
  doc/release_notes/release_notes_1.3.rst
  doc/try.rst
  doc/tutorials/acrn-dm_QoS.rst
  doc/tutorials/debug.rst
  doc/tutorials/docbuild.rst
  doc/tutorials/images/gsg-successful-boot.png
  doc/tutorials/kbl-nuc-sdc.rst
  doc/tutorials/skl-nuc.rst
  doc/tutorials/using_agl_as_uos.rst
  doc/tutorials/using_celadon_as_uos.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_sdc2_mode_on_nuc.rst
  doc/tutorials/using_ubuntu_as_sos.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_windows_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
Labels: area: documentation

#4002 dm: validate the input in 'pci_emul_mem_handler()'
  devicemodel/hw/pci/core.c
Labels: CI: Tracked On Pass, CI: apl_sdc_stable, CI: pending approve

#4004 dm: validate the input in 'pci_emul_mem_handler()'
  devicemodel/hw/pci/core.c
Labels: CI: Tracked On Pass, CI: pending approve

#4006 doc: schedule_vcpu was removed
  doc/developer-guides/hld/hv-cpu-virt.rst
Labels: area: documentation

#4013 HV: correct the formatting flag of hypcall_id
  hypervisor/arch/x86/guest/vmcall.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4009 acrn-config: modify board config for whl-ipc-i5/whl-ipc-i7
  misc/acrn-config/library/board_cfg_lib.py
Labels: CI: Tracked On Pass

#4015 Clean up language in the acrn_quick_setup script.
  doc/getting-started/acrn_quick_setup.sh
Labels: area: documentation

#3883 doc: add waag secure boot enabling
  doc/tutorials/images/waag_secure_boot_image1.png
  doc/tutorials/images/waag_secure_boot_image10.png
  doc/tutorials/images/waag_secure_boot_image2.png
  doc/tutorials/images/waag_secure_boot_image3.png
  doc/tutorials/images/waag_secure_boot_image5.png
  doc/tutorials/images/waag_secure_boot_image6.png
  doc/tutorials/images/waag_secure_boot_image7.png
  doc/tutorials/images/waag_secure_boot_image8.png
  doc/tutorials/images/waag_secure_boot_image9.png
  doc/tutorials/using_windows_as_uos.rst
  doc/tutorials/waag-secure-boot.rst
Labels: area: documentation

#4001 doc:update acrn_configuration_tool
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#3920 doc: add hld-security guest secure boot description
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/images/security-image-HC-interface-restriction.png
  doc/developer-guides/hld/images/security-image-HV-overview.png
  doc/developer-guides/hld/images/security-image-bootflow-sbl.png
  doc/developer-guides/hld/images/security-image-bootflow-uefi.png
  doc/developer-guides/hld/images/security-image-platform-seed-derivation.png
  doc/developer-guides/hld/images/security-image-secure-boot-uefi.png
  doc/developer-guides/hld/images/security-image-secure-storage-virt.png
  doc/developer-guides/hld/images/security-image-secure-world.png
  doc/developer-guides/hld/images/security-image-world-switching-HC.png
  doc/developer-guides/hld/images/security-image1.png
  doc/developer-guides/hld/images/security-image10.png
  doc/developer-guides/hld/images/security-image11.png
  doc/developer-guides/hld/images/security-image12.png
  doc/developer-guides/hld/images/security-image6.png
  doc/developer-guides/hld/images/security-image7.png
Labels: area: documentation

#3938 doc: instruction of enabling the laag secure boot
  doc/develop.rst
  doc/tutorials/enable_laag_secure_boot.rst
  doc/tutorials/images/enable_custom_boot.png
  doc/tutorials/images/enroll_pk_key_1.png
  doc/tutorials/images/enroll_pk_key_2.png
  doc/tutorials/images/enroll_pk_key_3.png
  doc/tutorials/images/enroll_pk_key_4.png
  doc/tutorials/images/enroll_pk_key_5.png
  doc/tutorials/images/enroll_pk_key_6.png
  doc/tutorials/images/exit_uefi_shell.png
  doc/tutorials/images/reset_in_bios.png
  doc/tutorials/images/reset_in_uefi_shell.png
  doc/tutorials/images/secure_boot_config_1.png
  doc/tutorials/images/secure_boot_config_2.png
  doc/tutorials/images/secure_boot_config_3.png
  doc/tutorials/images/secure_boot_enabled.png
  doc/tutorials/images/select_custom_mode.png
  doc/tutorials/images/uefi_shell_boot_default.png
  doc/tutorials/sign_clear_linux_image.rst
Labels: area: documentation

#4018 hv: rename vuart operations
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/vuart.c
  hypervisor/include/dm/vuart.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4051 doc: Stop using kconfig to make a customized efi.
  doc/faq.rst
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#4052 doc:modfiy ubuntu build on 18.04
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#4036 doc: Update Using Windows as Guest VM on ACRN
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4022 doc: clean up the docs in try using acrn table.
  doc/develop.rst
  doc/try.rst
  doc/tutorials/acrn_ootb.rst
  doc/tutorials/building_acrn_in_docker.rst
  doc/tutorials/images/USB-to-TTL-serial-cable.png
  doc/tutorials/images/the-bottom-side-of-UP2-board.png
  doc/tutorials/images/the-connection-of-serial-port.png
  doc/tutorials/up2.rst
Labels: area: documentation

#4053 doc: fix error in building_from_source doc
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#3998 doc: correct some mistakes add add cores and threads for CPU of supported hardware
  doc/reference/hardware.rst
Labels: area: documentation

#4056 Doc: Final edits to Memory Mangt HLD doc.
  doc/developer-guides/hld/hv-memmgt.rst
Labels: area: documentation

#4060 Doc: Final edits to the HV Hypercall doc.
  doc/developer-guides/hld/hv-hypercall.rst
Labels: area: documentation

#4062 doc: add copyright/license header to doc scripts
  doc/scripts/filter-doc-log.sh
  doc/scripts/pullsource.sh
Labels: area: documentation

#4063 Doc: Final edits for the HLD-Security doc.
  doc/developer-guides/hld/hld-security.rst
Labels: area: documentation

#4030 hv:remove unnecessary wrapper for emulate_instruction
  hypervisor/arch/x86/guest/instr_emul.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#3957 acrn-config: keep_gsi set for android only
  misc/acrn-config/launch_config/com.py
  misc/acrn-config/launch_config/pt.py
Labels: CI: Tracked On Pass

#4068 acrn-config: include msr.h in board.c
  misc/acrn-config/board_config/board_c.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4065 hv: instr_emul: use cs segment when fetching instructions
  hypervisor/arch/x86/guest/instr_emul.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4070 dm: Add licenses to the scripts.
  devicemodel/samples/apl-mrb/launch_uos.sh
  devicemodel/samples/apl-up2/launch_uos.sh
  devicemodel/samples/nuc/launch_hard_rt_vm.sh
  devicemodel/samples/nuc/launch_uos.sh
  devicemodel/samples/nuc/launch_vxworks.sh
  devicemodel/samples/nuc/launch_win.sh
  devicemodel/samples/nuc/launch_zephyr.sh
  hypervisor/scripts/genld.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3997 doc: enable s5 guide
  doc/develop.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/images/Microsoft-Visual-C-install-option-1.png
  doc/tutorials/images/Microsoft-Visual-C-install-option-2.png
  doc/tutorials/images/launch-startup.png
  doc/tutorials/images/open-com-success.png
  doc/tutorials/images/run-shell-startup.png
  doc/tutorials/images/s5-scenario-1.dot
  doc/tutorials/images/s5-scenario-2.dot
  doc/tutorials/images/s5_overall_architecture.png
Labels: area: documentation

#4076 Doc: Grammatical edits to the Enable S5 Guide.
  doc/tutorials/enable_s5.rst
Labels: area: documentation

#4011 doc: Add Advisory notes
  doc/asa.rst
  doc/index.rst
Labels: area: documentation

#4050 doc: Release notes v1.4
  doc/release_notes/release_notes_1.4.rst
Labels: area: documentation

#4079 Doc: Grammatical edits to the 1.4 Release Notes.
  doc/release_notes/release_notes_1.4.rst
Labels: area: documentation

#3924 Makefile: refine include path for efi_stub
  misc/efi-stub/Makefile
Labels: CI: Tracked On Pass

#4078 Makefile: pass BOARD/SCENARIO FILE to make hv
  Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#4095 DM: samples: Correct parameter of intel_pstate
  devicemodel/samples/nuc/launch_hard_rt_vm.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#4100 hv: ept: disable execute right on large pages
  hypervisor/arch/x86/guest/vmx_io.c
  hypervisor/arch/x86/page.c
  hypervisor/arch/x86/pagetable.c
  hypervisor/include/arch/x86/page.h
Labels: CI: Tracked On Pass, CI: no coding guideline

#4081 CODEOWNERS: add acrn-hypervisor Makefile owner
  CODEOWNERS
Labels: Automerge: Pass, CI: Tracked On Pass

#4096 Makefile: acpi header cleanup and *.mk files movement
  Makefile
  hypervisor/Makefile
  hypervisor/scripts/makefile/cfg_update.mk
  hypervisor/scripts/makefile/deps.mk
  hypervisor/scripts/makefile/kconfig.mk
Labels: Automerge: Pass, CI: Tracked On Pass

#4103 hv: Fix the definition of struct representing interrupt hw frame
  hypervisor/debug/dump.c
  hypervisor/include/arch/x86/irq.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4124 doc: add mitigation description for latest fix in advisory
  doc/asa.rst
Labels: area: documentation

#4071 doc: edit agl-vms.rst adjust to v1.3
  doc/tutorials/agl-vms.rst
Labels: area: documentation, no Signed-off-by

#4075 hv: add printf "not support the value of vuart index parameter" in fu…
  hypervisor/dm/vuart.c
Labels: CI: Tracked On Pass

#4131 Makefile: do not rm board acpi info header
  Makefile
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#4136 Release notes for release_1.0.2
  doc/release_notes/release_notes_1.0.2.rst
Labels: area: documentation

#4140 Doc: Corrected title formatting in RN 1.0.2 doc.
  doc/release_notes/release_notes_1.0.2.rst
Labels: area: documentation

#4097 doc: Update 1.4 versions and some words
  doc/asa.rst
  doc/faq.rst
  doc/getting-started/rt_industry.rst
  doc/release_notes/release_notes_1.4.rst
Labels: area: documentation

#4080 doc: update acrn ootb doc
  doc/tutorials/acrn_ootb.rst
Labels: area: documentation

#4141 doc: remove rt gsg kernel info
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#4142 doc: update release_notes_1.0.x directory
  doc/release_notes_1.0.1.rst
  doc/release_notes_1.0.2.rst
Labels: area: documentation

#4153 hv:panic if there is no memory map in multiboot info
  hypervisor/arch/x86/e820.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4147 doc: edit using_ubuntu_as_sos.rst adjust to v1.4
  doc/tutorials/using_ubuntu_as_sos.rst
Labels: area: documentation

#4155 dm: fix memory free issue for xhci
  devicemodel/hw/pci/xhci.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4019 hv: add Kconfig parameter to define the Service VM EFI bootloader
  hypervisor/arch/x86/Kconfig
  misc/efi-stub/boot.c
  misc/efi-stub/stdlib.h
Labels: CI: Tracked On Pass

#4174 acrn-config: remove extra function in launch config library
  misc/acrn-config/library/launch_cfg_lib.py
Labels: Automerge: Pass, CI: Tracked On Pass
