Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-02, with the labels that each got.

#2465 efi-stub: reset all APs after entering guest mode
  efi-stub/MpService.h
  efi-stub/boot.c
Labels: Coding Guidelines: PASS

#2472 watchdog: map the watchdog reset to warm reset
  devicemodel/core/main.c
  devicemodel/hw/pci/wdt_i6300esb.c
  devicemodel/include/vmmapi.h
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2475 profiling: enable to capture dropped samples while buffering
  hypervisor/debug/hypercall.c
  hypervisor/debug/profiling.c
  hypervisor/include/debug/profiling_internal.h
  hypervisor/include/public/acrn_hv_defs.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2460 profiling: fix the system freeze issue when running profiling tool
  hypervisor/debug/profiling.c
  hypervisor/include/debug/profiling_internal.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2480 DM: ACPI: Avoiding hard code the ASL_COMPILER macro
  Makefile
  devicemodel/Makefile
  devicemodel/hw/platform/acpi/acpi.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2482 IOC mediator: dynamically enable dummy channels
  devicemodel/hw/platform/ioc.c
  devicemodel/include/ioc.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2485 hv: refine `guest.c`
  hypervisor/Makefile
  hypervisor/arch/x86/guest/guest_memory.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/guest/guest.h
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2487 hv: rename MACROs 'VMX_CRx_MASK"
  hypervisor/arch/x86/guest/virtual_cr.c
  hypervisor/include/arch/x86/vmx.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2489 hv: vlapic: make vlapic deliver interrupt related functions more read…
  doc/developer-guides/hld/hv-virt-interrupt.rst
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/common/hypercall.c
  hypervisor/dm/vioapic.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2498 hv:remove several redundancy variables related memory
  hypervisor/arch/x86/e820.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/bsp/include/bsp_extern.h
  hypervisor/include/arch/x86/e820.h
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2499 HV: repace vpci_vdev_array with pci_ptdev config
  hypervisor/arch/x86/configs/apl-mrb/partition_config.h
  hypervisor/arch/x86/configs/apl-mrb/pt_dev.c
  hypervisor/arch/x86/configs/dnv-cb2/partition_config.h
  hypervisor/arch/x86/configs/dnv-cb2/pt_dev.c
  hypervisor/arch/x86/configs/partition_config.c
  hypervisor/dm/vpci/partition_mode.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2501 hv: refine `guest.h`
  doc/acrn.doxyfile
  hypervisor/arch/x86/guest/vmx_asm.S
  hypervisor/include/arch/x86/e820.h
  hypervisor/include/arch/x86/guest/guest_memory.h
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/arch/x86/guest/vmexit.h
  hypervisor/include/arch/x86/hv_arch.h
  hypervisor/include/arch/x86/irq.h
  hypervisor/include/arch/x86/msr.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2492 Porting the patch from master branch
  hypervisor/debug/profiling.c
  hypervisor/include/debug/profiling_internal.h
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2506 dm: vhpet: fix vHPET memory leak on device reset
  devicemodel/hw/platform/hpet.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2493 HV: Modularize vtd.c to remove acrn_vm usage
  doc/developer-guides/hld/hv-vt-d.rst
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/guest/virtual_cr.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/arch/x86/init.c
  hypervisor/arch/x86/pm.c
  hypervisor/arch/x86/vtd.c
  hypervisor/bsp/sbl/const_dmar.c
  hypervisor/common/hypercall.c
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/include/arch/x86/hv_arch.h
  hypervisor/include/arch/x86/vtd.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2511 doc:add build option on the using_sbl_on_up2.rst
  doc/tutorials/using_sbl_on_up2.rst
Labels: area: documentation

#2508 doc: initial draft of 0.6 release notes
  doc/release_notes_0.6.rst
Labels: area: documentation

#2479 doc: modify create up2 image for changing uos default bootargs
  doc/tutorials/create-up2-images.sh
Labels: area: documentation

#2517 script: remove enable_initial_modeset for UP2 platform
  devicemodel/samples/up2/sos_bootargs_debug.txt
  devicemodel/samples/up2/sos_bootargs_release.txt
Labels: Automerge: Pass, CI: Tracked On Pass

#2510 HV: Remove snoopy_mem from iommu
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/vtd.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2521 dm: Add socket backend support for virtio-console
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2531 doc: use weston instead of ias by bundle add x11-server
  doc/tutorials/create-up2-images.sh
  doc/tutorials/using_sbl_on_up2.rst
Labels: area: documentation

#2533 Documentation: tweak GSG (and acrn.conf)
  doc/getting-started/apl-nuc.rst
  efi-stub/clearlinux/acrn.conf
Labels: area: documentation

#2491 profiling: enable to capture dropped samples while buffering
  hypervisor/debug/hypercall.c
  hypervisor/debug/profiling.c
  hypervisor/include/debug/profiling_internal.h
  hypervisor/include/public/acrn_hv_defs.h
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2505 doc: add more rules in coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2532 doc: add Fixed issues and known issues in release_notes_0.6
  doc/release_notes_0.6.rst
Labels: area: documentation

#2535 hv: extend the AC bit of rflags operations for smap
  hypervisor/debug/sbuf.c
  hypervisor/include/arch/x86/cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2500 doc: update partition mode config on up2
  doc/tutorials/using_partition_mode_on_up2.rst
Labels: area: documentation

#2540 doc: add review comments to up2 doc
  doc/tutorials/using_partition_mode_on_up2.rst
Labels: area: documentation

#2544 vmcall handling fix
  hypervisor/arch/x86/guest/vmcall.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2546 add features list on release_note_0.6
  doc/release_notes_0.6.rst
Labels: area: documentation

#2550 Add one more known issue
  doc/release_notes_0.6.rst
Labels: area: documentation

#2545 hv: vlapic: properly initialize DCR
  hypervisor/arch/x86/guest/vlapic.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2556 dm: add specify log for starting uos
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2554 dm: vtpm: disable Virtual TPM feature
  devicemodel/Makefile
  devicemodel/core/main.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2555 DM USB: xHCI: do not reset DRD role during S3 process
  devicemodel/hw/pci/xhci.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2559 hv: isrvec_stk_top could be zero once we enable APICv
  hypervisor/arch/x86/guest/vlapic.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2519 acrn.conf: clean-up SOS kernel options (EFI platforms)
  doc/tutorials/agl-vms.rst
  doc/tutorials/skl-nuc.rst
  doc/tutorials/using_ubuntu_as_sos.rst
  efi-stub/clearlinux/acrn.conf
Labels: Automerge: Pass, CI: Tracked On Pass

#2563 hv: exception: fault type exception should set resume flag in rflags
  hypervisor/arch/x86/guest/virq.c
  hypervisor/include/arch/x86/irq.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2564 DM: modify acpi for IASL to support ACPI6.3
  devicemodel/hw/platform/acpi/acpi.c
Labels: CI: apl_sdc_stable

#2566 DM: modify acpi for IASL to support ACPI6.3
  devicemodel/hw/platform/acpi/acpi.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2567 dm: implement power button for power managerment
  devicemodel/arch/x86/pm.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2573 config: enable parsing dmar table dynamically on UP2
  hypervisor/arch/x86/configs/up2.config
Labels: Automerge: Pass, CI: Tracked On Pass

#2570 doc: update partition mode config on up2
  doc/tutorials/using_partition_mode_on_up2.rst
Labels: area: documentation

#2591 tools: do not include unnecessary files in release build
  tools/Makefile
  tools/acrn-manager/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2585 doc: add 0.6 to doc version menu
  doc/conf.py
Labels: area: documentation

#2586 doc: fix formatting of up2 doc
  doc/tutorials/using_partition_mode_on_up2.rst
Labels: area: documentation

#2594 DM USB: xHCI: fix an error logic in DRD logic
  devicemodel/hw/pci/xhci.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2583 DM USB: xHCI: fix an issue during BULK transfer
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2596 Update vsbl to version 1.2
  devicemodel/bios/MD5SUM
  devicemodel/bios/SHA512SUM
  devicemodel/bios/VSBL.bin
  devicemodel/bios/VSBL_debug.bin
  devicemodel/bios/changelog.txt
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2592 hv: debug: mark the mmio address for npk log as hv owned
  hypervisor/debug/npk_log.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2590 hv: debug: mark the mmio address for npk log as hv owned
  hypervisor/debug/npk_log.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2593 tools: do not include unnecessary files in release build
  tools/Makefile
  tools/acrn-manager/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#2600 DM: virtio-gpio: return a valid length for GPIO request
  devicemodel/hw/pci/virtio/virtio_gpio.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2607 ABL seed parse new argument
  hypervisor/boot/sbl/abl_seed_parse.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2612 DM: Attestation Keybox support in SOS DM
  devicemodel/Makefile
  devicemodel/hw/pci/virtio/virtio_rpmb.c
  devicemodel/hw/platform/rpmb/att_keybox.c
  devicemodel/include/att_keybox.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2614 DM: rm console in release args for security reuest
  devicemodel/samples/apl-mrb/sos_bootargs_release.txt
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2609 HV: return an error code when REQ state mismatch in acrn_insert_request
  hypervisor/common/io_req.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#2619 hv: fix possibility of using uninitialized params
  hypervisor/boot/sbl/abl_seed_parse.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2617 hv: code style fix for partition mode specific code
  hypervisor/arch/x86/configs/apl-mrb/partition_config.h
  hypervisor/arch/x86/configs/apl-mrb/pt_dev.c
  hypervisor/arch/x86/configs/apl-mrb/ve820.c
  hypervisor/arch/x86/configs/dnv-cb2/partition_config.h
  hypervisor/arch/x86/configs/dnv-cb2/pt_dev.c
  hypervisor/arch/x86/configs/dnv-cb2/ve820.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/debug/vuart.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/debug/vuart.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2608 hv: search additional argument when parsing seed from ABL
  hypervisor/boot/sbl/abl_seed_parse.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2622 hv: improve multiboot guest image load addresses assignment
  hypervisor/boot/sbl/multiboot.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2623 dm: virtio: add memory barrier before notify FE
  devicemodel/hw/pci/virtio/virtio.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2626 DM: Attestation Keybox support in SOS DM
  devicemodel/Makefile
  devicemodel/hw/pci/virtio/virtio_rpmb.c
  devicemodel/hw/platform/rpmb/att_keybox.c
  devicemodel/include/att_keybox.h
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2634 Revert "dm: script: enable discard feature for virtio-blk"
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2631 hv: vmcs: simplify update EOI-exit bitmap
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/dm/vioapic.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2551 Documentation: tweak GSG
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#2639 sos-bootargs: change i915 initial mode setting to 0
  devicemodel/samples/apl-mrb/sos_bootargs_debug.txt
  devicemodel/samples/apl-mrb/sos_bootargs_release.txt
Labels: CI: apl_sdc_stable

#2642 doc: fix misspellings
  doc/developer-guides/GVT-g-kernel-options.rst
  doc/release_notes_0.5.rst
  doc/tutorials/rt_linux.rst
  doc/tutorials/trustyACRN.rst
Labels: area: documentation

#2644 Makefile: undefine _FORTIFY_SOURCE prior using it
  devicemodel/Makefile
  tools/acrn-crashlog/Makefile
  tools/acrn-manager/Makefile
  tools/acrnlog/Makefile
  tools/acrntrace/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2646 hv:cleanup header files for release folder
  hypervisor/release/console.c
  hypervisor/release/dump.c
  hypervisor/release/hypercall.c
  hypervisor/release/logmsg.c
  hypervisor/release/npk_log.c
  hypervisor/release/profiling.c
  hypervisor/release/trace.c
  hypervisor/release/vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2649 DM: virtio-gpio: use virtio_base as the first member of virtio_gpio
  devicemodel/hw/pci/virtio/virtio_gpio.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2653 fix AaaG boot panic issue
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2630 doc: add IOC virtualization HLD
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hv-ioc-virt.rst
  doc/developer-guides/hld/images/ioc-image1.png
  doc/developer-guides/hld/images/ioc-image10.png
  doc/developer-guides/hld/images/ioc-image12.png
  doc/developer-guides/hld/images/ioc-image13.png
  doc/developer-guides/hld/images/ioc-image14.png
  doc/developer-guides/hld/images/ioc-image15.png
  doc/developer-guides/hld/images/ioc-image16.png
  doc/developer-guides/hld/images/ioc-image17.png
  doc/developer-guides/hld/images/ioc-image18.png
  doc/developer-guides/hld/images/ioc-image19.png
  doc/developer-guides/hld/images/ioc-image2.png
  doc/developer-guides/hld/images/ioc-image20.png
  doc/developer-guides/hld/images/ioc-image21.png
  doc/developer-guides/hld/images/ioc-image22.png
  doc/developer-guides/hld/images/ioc-image24.png
  doc/developer-guides/hld/images/ioc-image3.png
  doc/developer-guides/hld/images/ioc-image4.png
  doc/developer-guides/hld/images/ioc-image5.png
  doc/developer-guides/hld/images/ioc-image6.png
  doc/developer-guides/hld/images/ioc-image7.png
  doc/developer-guides/hld/images/ioc-image8.png
  doc/developer-guides/hld/images/ioc-image9.png
Labels: area: documentation
