Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-12, with the labels that each got.

#4168 support xsave in context switch
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/guest/trusty.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/cpu.h
  hypervisor/include/arch/x86/cpu_caps.h
  hypervisor/include/arch/x86/cpufeatures.h
  hypervisor/include/arch/x86/cpuid.h
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/lib/types.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4158 HV: parse default pci mmcfg base
  hypervisor/acpi_parser/acpi_ext.c
  hypervisor/arch/x86/configs/nuc7i7dnb/platform_acpi_info.h
  hypervisor/arch/x86/configs/platform_acpi_info.h
  hypervisor/arch/x86/cpu.c
  hypervisor/boot/guest/vboot_wrapper.c
  hypervisor/boot/include/acpi.h
  hypervisor/hw/pci.c
  hypervisor/include/hw/pci.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS, config_tool_modified

#4179 hv: make init_vmcs as a event of VCPU
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/common/hv_main.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4184 hv: trap RDPMC instruction execution from any guest
  hypervisor/arch/x86/guest/vmcs.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4183 acrn-config: Extend ve820 generation script for sizes gt 512 MB
  misc/acrn-config/board_config/ve820_c.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4203 acrn-config: add xml to support TGL RVP board
  misc/acrn-config/xmls/board-xmls/tgl-rvp.xml
  misc/acrn-config/xmls/config-xmls/tgl-rvp/industry.xml
  misc/acrn-config/xmls/config-xmls/tgl-rvp/industry_launch_1uos.xml
Labels: Automerge: Pass, CI: Tracked On Pass

#4205 Makefile: fix make failure for logical_partition or hybrid scenario
  Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#4206 hypervisor: handle reboot from non-privileged pre-launched guests
  hypervisor/arch/x86/guest/vm_reset.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4207 acrn-config: Fix target xml generation issue with no Cx/Px driver
  misc/acrn-config/target/acpi.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4209 HV: Kconfig changes to support server platform.
  hypervisor/arch/x86/Kconfig
Labels: Automerge: Pass, CI: Tracked On Pass

#4202 hv: vlapic: kick targeted vCPU off if interrupt trigger mode has changed
  hypervisor/arch/x86/guest/vlapic.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4201 Makefile: add gcc flags to prevent some optimization
  devicemodel/Makefile
  misc/acrn-manager/Makefile
  misc/efi-stub/Makefile
  misc/life_mngr/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#4214 acrn-config: UI supports to edit mulitple virtio input devices
  misc/acrn-config/config_app/static/main.js
  misc/acrn-config/config_app/templates/launch.html
Labels: Automerge: Pass, CI: Tracked On Pass

#4192 acrnboot: correct the calculation of the end boundry of _DYNAMIC region
  hypervisor/boot/reloc.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4210 Makefile: highlight board acpi file warning msg
  Makefile
Labels: CI: Tracked On Pass

#4215 Doc: Add libnuma dependency for acrntrace
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#4156 doc:update acrn-shell.rst
  doc/user-guides/acrn-shell.rst
  doc/user-guides/images/shell_image19.png
  doc/user-guides/images/shell_image20.png
Labels: area: documentation

#4235 dm:gvt:update bus0 memlimit32 value
  devicemodel/hw/pci/core.c
Labels: CI: Tracked On Pass, CI: no coding guideline

#4224 acrn-config: Fix ve820 table generation when guest memory size is >512MB
  misc/acrn-config/board_config/ve820_c.py
Labels: CI: Tracked On Pass

#4231 hv: vtd: fix improper use of DMAR_GCMD_REG
  hypervisor/arch/x86/vtd.c
Labels: CI: Tracked On Pass

#4223 Makefile: Build Release version by default
  Makefile
Labels: CI: Tracked On Pass

#4221 hv:remove 2 unused variables in vm_arch structure
  hypervisor/include/arch/x86/guest/vm.h
Labels: CI: Tracked On Pass, CI: no coding guideline

#4234 HV: expose port 0x64 read for SOS VM
  hypervisor/arch/x86/guest/vm_reset.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4238 hv:remove need_cleanup flag in create_vm
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass

#4243 acrn-config: Add non-contiguous HPA to currently supported hardware.
  misc/acrn-config/board_config/ve820_c.py
  misc/acrn-config/xmls/config-xmls/apl-mrb/hybrid.xml
  misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/hybrid.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/hybrid.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/hybrid.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/hybrid.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/hybrid.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4241 hv:bugfix in write protect page hypercall
  hypervisor/common/hypercall.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4246 hv:fix crash issue when handling HC_NOTIFY_REQUEST_FINISH
  hypervisor/common/hypercall.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4252 hv: msr: remove redundant check in write_pat_msr
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/msr.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4254 hv: add lock for ept add/modify/del
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: CI: Tracked On Pass

#4236 doc: add new dependency to Clear Linux ACRN builder container
  doc/getting-started/Dockerfile
Labels: area: documentation

#4226 doc:debug feature is disabled by default
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#3775 doc: add a little info on how to configure the boot options
  doc/introduction/index.rst
Labels: area: documentation

#3820 doc: Update WaaG GSG to use ACRNGT GOP to install Windows
  doc/tutorials/images/windows_install_1.png
  doc/tutorials/images/windows_install_10.png
  doc/tutorials/images/windows_install_11.png
  doc/tutorials/images/windows_install_12.png
  doc/tutorials/images/windows_install_2.png
  doc/tutorials/images/windows_install_3.png
  doc/tutorials/images/windows_install_4.png
  doc/tutorials/images/windows_install_5.png
  doc/tutorials/images/windows_install_6.png
  doc/tutorials/images/windows_install_7.png
  doc/tutorials/images/windows_install_8.png
  doc/tutorials/images/windows_install_9.png
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4171 doc: add windows 10 activation
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4265 Doc: Content edits to Using WaaG VM on ACRN
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4251 acrnboot: fix the parsing hv_cmdline to correctly handle the case of …
  hypervisor/boot/cmdline.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4274 OVMF release v1.5
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass, CI: pending approve

#4276 hv: hotfix for xsave
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/cpu.h
Labels: CI: Tracked On Pass, CI: pending approve

#4275 OVMF release v1.5 (master branch)
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#4269 doc: add document for cpu sharing
  doc/develop.rst
  doc/tutorials/cpu_sharing.rst
  doc/tutorials/images/cpu_sharing_affinity.png
  doc/tutorials/images/cpu_sharing_api.png
  doc/tutorials/images/cpu_sharing_framework.png
  doc/tutorials/images/cpu_sharing_state.png
Labels: area: documentation

#4262 doc: modify Configuration Tools
  doc/getting-started/rt_industry.rst
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#4169 doc: Add tutorial about how to launch kata vm.
  doc/develop.rst
  doc/tutorials/run_kata_containers.rst
Labels: area: documentation

#4291 Doc: Add v1.5 release menu choice.
  doc/conf.py
Labels: area: documentation

#4287 acrn-config: remove pcpu3 from vm1 in SDC scenario
  misc/acrn-config/xmls/config-xmls/apl-mrb/sdc.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/sdc.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc.xml
Labels: Automerge: Pass, CI: Tracked On Pass

#4293 Doc: Content edits to Running Kata containers on a Service VM doc
  doc/tutorials/run_kata_containers.rst
Labels: area: documentation

#4294 acrn-config: modify hpa start size value for logical_partition scenario
  misc/acrn-config/library/common.py
  misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml
Labels: CI: Tracked On Pass

#4289 acrn-config: fix a few formatting issues
  misc/acrn-config/library/scenario_cfg_lib.py
  misc/acrn-config/scenario_config/pci_dev_c.py
  misc/acrn-config/scenario_config/vm_configurations_c.py
  misc/acrn-config/scenario_config/vm_configurations_h.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4295 DOC: Content edits to CPU Sharing doc
  doc/tutorials/cpu_sharing.rst
Labels: area: documentation

#4300 acrn-config: some cleanup for logical partition mode Linux bootargs
  doc/tutorials/using_partition_mode_on_up2.rst
  hypervisor/scenarios/logical_partition/vm_configurations.c
  misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/generic/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml
Labels: Automerge: Pass, CI: Tracked On Pass, config_tool_modified

#4302 HV: search rsdp from e820 acpi reclaim region
  hypervisor/boot/acpi_base.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4284 devicemodel: refactor CMD_OPT_LAPIC_PT case branch
  devicemodel/core/main.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4305 doc: remove no support OS parts
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#4309 Doc: Added Whiskey Lake specs to hardware ref page
  doc/reference/hardware.rst
Labels: area: documentation

#4306 hv: add sanity check for vuart configuration
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/dm/vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS, config_tool_modified

#4308 hv: instr_emul: add emulation for 0xf6 test instruction
  hypervisor/arch/x86/guest/instr_emul.c
Labels: CI: Tracked On Pass, CI: pending approve

#4321 doc: add more details to the Kata Containers with ACRN tutorial
  doc/tutorials/run_kata_containers.rst
Labels: area: documentation

#4323 doc: Update some of the wrong path in acrn configuration tool doc.
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#4324 Doc: Added missing period in run_kata_containers file.
  doc/tutorials/run_kata_containers.rst
Labels: area: documentation

#4299 acrn-config: dump CPU info from /sys/devices/system/cpu/possible
  misc/acrn-config/target/misc.py
Labels: Automerge: Pass, CI: Tracked On Pass
