Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-08, with the labels that each got.

#3507 OVMF release v1.2
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: Automerge: Pass, CI: Tracked On Pass

#3513 HV: fix highest severity flag in hybrid mode
  hypervisor/scenarios/hybrid/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3514 softirq: disable interrupt when modify timer_list
  hypervisor/arch/x86/timer.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3499 HV: inject exception for invalid vmcall
  hypervisor/arch/x86/guest/vmcall.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3521 doc: additional doc navigation restructuring
  doc/conf.py
  doc/contribute.rst
  doc/develop.rst
  doc/reference/index.rst
  doc/static/acrn-custom.css
  doc/try.rst
  doc/tutorials/skl-nuc.rst
  doc/user-guides/tools.rst
Labels: area: documentation

#3522 doc: fix broken links after content reorg
  doc/develop.rst
  doc/index.rst
  doc/try.rst
Labels: area: documentation

#3515 doc: release notes v1.0.1
  doc/release_notes/release_notes_1.0.1.rst
Labels: area: documentation

#3463 doc: adding guide to launch 2 Linux UOSes using SDC2 scenario
  doc/tutorials/images/sdc2-defconfig.png
  doc/tutorials/images/sdc2-launch-2-laag.png
  doc/tutorials/images/sdc2-save-mini-config.png
  doc/tutorials/images/sdc2-selected.png
  doc/tutorials/using_sdc2_mode_on_nuc.rst
Labels: area: documentation

#3527 doc: incorporate scenario-based doc update
  doc/getting-started/building-from-source.rst
  doc/introduction/images/boot-flow-2.dot
  doc/introduction/index.rst
  doc/try.rst
Labels: area: documentation

#3528 doc: add the SDC2 scenario doc into the navigation
  doc/develop.rst
  doc/tutorials/using_sdc2_mode_on_nuc.rst
Labels: area: documentation

#3535 memmap:reserve phys-addr for hvlog
  misc/efi-stub/clearlinux/acrn.conf
Labels: Automerge: Pass, CI: Tracked On Pass

#3544 dm: virtio-i2c: fix native_adapter memory leak
  devicemodel/hw/pci/virtio/virtio_i2c.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3550 HV: shell: fix temp_str out of bounds buffer access
  hypervisor/debug/shell.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3548 dm:gvt:keep LaaG aperture size consistent with the host
  devicemodel/hw/pci/gvt.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3554 hv:fix need to make twice in hypervisor folder
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3536 doc: hybrid mode scenario introduction
  doc/develop.rst
  doc/getting-started/apl-nuc.rst
  doc/tutorials/images/hybrid_scenario_on_nuc.png
  doc/tutorials/using_hybrid_mode_on_nuc.rst
Labels: area: documentation

#3557 Formatting for new Hardware Support page
  doc/tutorials/hw_support.rst
Labels: area: documentation

#3540 make: white-list SBL firmware boards
  Makefile
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3563 doc: add limitation for UEFI services
  doc/introduction/index.rst
Labels: area: documentation

#3561 doc: update Using SBL on UP2 Board
  doc/tutorials/images/sos_console_login.png
  doc/tutorials/images/vm_console_login.png
  doc/tutorials/using_sbl_on_up2.rst
Labels: area: documentation

#3555 doc:update Getting started guide for Intel NUC software setup
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#3566 hv: fix failed to build release version build with Kconfig setting
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3568 hv: move vmx_rdmsr_pat/vmx_wrmsr_pat from vmcs.c to vmsr.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/guest/vmcs.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3577 dm: expand default WaaG memory to 4G
  devicemodel/samples/nuc/launch_win.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3580 hv: fix Violations touched ACRN Coding Guidelines
  devicemodel/include/sw_load.h
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/arch/x86/configs/vmptable.c
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/guest/instr_emul.c
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/irq.c
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/arch/x86/guest/vlapic.h
  hypervisor/include/arch/x86/per_cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3581 doc: add hybrid scenario document review edits
  doc/tutorials/using_hybrid_mode_on_nuc.rst
Labels: area: documentation

#3582 doc: add new scenario-based intro
  doc/introduction/images/ACRN-V2-Industrial-Usage-Architecture-Overview.png
  doc/introduction/images/ACRN-V2-SDC-Usage-Architecture-Overview.png
  doc/introduction/images/ACRN-V2-SDC-scenario.png
  doc/introduction/images/ACRN-V2-high-level-arch.png
  doc/introduction/images/ACRN-V2-industrial-scenario.png
  doc/introduction/images/Industry-w-safetyVM.png
  doc/introduction/images/Industry-wo-safetyVM.png
  doc/introduction/images/Logical-partition.png
  doc/introduction/images/SDC-2VM.png
  doc/introduction/images/SDC-4VM.png
  doc/introduction/index.rst
Labels: area: documentation

#3579 doc: Release Notes v1.2
  doc/release_notes/release_notes_1.2.rst
Labels: area: documentation

#3586 doc: remove references to 2.0 in intro
  doc/introduction/index.rst
Labels: area: documentation

#3587 doc: add v1.2 to the release navigation picker
  doc/conf.py
Labels: area: documentation

#3574 hv: vcr: check guest cr3 before loading pdptrs
  hypervisor/arch/x86/guest/virtual_cr.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3558 hv: refine the function pointer type of port I/O request handlers
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/dm/io_req.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpic.c
  hypervisor/dm/vrtc.c
  hypervisor/dm/vuart.c
  hypervisor/include/dm/io_req.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3585 doc: remove modernizr.min.js
  doc/static/js/modernizr.min.js
Labels: area: documentation

#3575 HV: switch launch LaaG with OVMF by default
  devicemodel/samples/nuc/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3591 hv: enable console vuart in industry scenario
  hypervisor/scenarios/industry/vm_configurations.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3592 hv: remove 'flags' field in struct vm_io_range
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpic.c
  hypervisor/dm/vrtc.c
  hypervisor/dm/vuart.c
  hypervisor/include/dm/io_req.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3534 vm_load: update init gdt preparation
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/common/vm_load.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3595 dm: pm: support control method power button
  devicemodel/arch/x86/pm.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3589 dm: vsbl: update to v1.4
  devicemodel/bios/MD5SUM
  devicemodel/bios/SHA512SUM
  devicemodel/bios/VSBL.bin
  devicemodel/bios/VSBL_debug.bin
  devicemodel/bios/changelog.txt
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#3605 hv:move some APIs related host reset to pm.c
  hypervisor/acpi_parser/acpi_ext.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/arch/x86/pm.c
  hypervisor/include/arch/x86/guest/vm_reset.h
  hypervisor/include/arch/x86/host_pm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3603 hv: cleanup vmcs.h
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/guest/guest_memory.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/cpu.h
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/arch/x86/guest/vmcs.h
  hypervisor/include/arch/x86/msr.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3616 DM USB: fix potential crash risk due to null pointer
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3620 dm: bzimage loader: get linux bzimage setup_sects from header
  devicemodel/core/sw_load_bzimage.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3617 dm: virtio-console: add subclass
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3627 hv: vtd: fix MACRO typos
  hypervisor/arch/x86/vtd.c
Labels: Automerge: Pass, CI: Tracked On Pass
