Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-03, with the labels that each got.

#2650 power button emulation by acrnctl command
  devicemodel/arch/x86/pm.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2645 doc: add some rules related to coding style
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2640 doc: add VBSK overhead analysis doc
  doc/developer-guides/VBSK-analysis.rst
  doc/developer-guides/images/vbsk-image1.png
  doc/developer-guides/images/vbsk-image2.png
  doc/developer-guides/images/vbsk-image3.png
  doc/developer-guides/index.rst
Labels: area: documentation

#2663 OVMF release v0.7
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
Labels: Automerge: Pass, CI: Tracked On Pass

#2660 ACRN: dm: Fix luanch UOS script "-d" parameter fail issue
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#2656 doc: fix the typo related to tab
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2655 hv:move forward the initialization for iommu & ptdev
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/init.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2658 hv: Remove redundant get_dmar_info API calls
  hypervisor/arch/x86/vtd.c
  hypervisor/boot/dmar_parse.c
  hypervisor/bsp/sbl/const_dmar.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2669 hv: fix a redundant check in general_sw_loader
  hypervisor/common/vm_load.c
Labels: CI: Tracked On Pass, CI: pending approve, Coding Guidelines: PASS

#2670 [hv] set ECX.bit31 to indicate the presence of a hypervisor
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/include/arch/x86/cpuid.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2671 hv: vlapic: correct wrong use of vector
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2672 hv: simplify `get_primary_vcpu` and `vcpu_from_vid`
  hypervisor/arch/x86/guest/virq.c
  hypervisor/boot/uefi/uefi_boot.c
  hypervisor/common/vm_load.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2641 hv: do EPT mapping only for physical memory backed GPA on pre-launche…
  hypervisor/arch/x86/configs/apl-mrb/ve820.c
  hypervisor/arch/x86/configs/dnv-cb2/ve820.c
  hypervisor/arch/x86/guest/vm.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2676 Vlapic: refine vlapic Error Handling
  hypervisor/arch/x86/guest/vlapic.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2678 [RevertMe] dm: pci: restore workaround when alloc pci mem64 bar
  devicemodel/core/main.c
  devicemodel/hw/pci/core.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2679 Script: Fix snd_soc_skl typo in launch script
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: CI: apl_sdc_stable

#2682 dm: bios: update vsbl to v1.3
  devicemodel/bios/MD5SUM
  devicemodel/bios/SHA512SUM
  devicemodel/bios/VSBL.bin
  devicemodel/bios/VSBL_debug.bin
  devicemodel/bios/changelog.txt
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable, Coding Guidelines: PASS

#2680 hv: refine vlapic_calc_dest()
  hypervisor/arch/x86/guest/vlapic.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2686 hv: refined the pmu passthru irq handling
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/debug/profiling.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2688 dm: replace unsafe string api for acrn-dm
  devicemodel/include/dm_kmsg.h
  devicemodel/lib/dm_kmsg.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2692 HV: correct COM_IRQ default config type
  hypervisor/arch/x86/Kconfig
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2693 hv:validate ID and state of vCPU for related APIs
  hypervisor/common/hypercall.c
  hypervisor/debug/shell.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2697 hv:move several tsc APIs to timer.c
  doc/developer-guides/hld/hv-timer.rst
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/timer.c
  hypervisor/include/arch/x86/timer.h
  hypervisor/include/lib/rtl.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2698 dm: use power button acpi device to find its input event
  devicemodel/arch/x86/pm.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2665 doc: update the format in coding style part
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2664 doc: fix broken external links
  doc/api/devicemodel_api.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/hld/hld-security.rst
  doc/getting-started/apl-nuc.rst
  doc/getting-started/up2.rst
  doc/hardware.rst
  doc/tutorials/agl-vms.rst
  doc/tutorials/trustyACRN.rst
Labels: area: documentation

#2699 HV: refine location of platform_acpi_info header
  hypervisor/Makefile
  hypervisor/arch/x86/configs/apl-mrb/platform_acpi_info.h
  hypervisor/arch/x86/configs/platform_acpi_info.h
  hypervisor/arch/x86/guest/pm.c
  hypervisor/bsp/include/bsp_extern.h
  hypervisor/bsp/include/uefi/platform_acpi_info.h
  hypervisor/bsp/sbl/const_dmar.c
  hypervisor/include/arch/x86/default_acpi_info.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2696 HV: Fix modularization vm config code lost CAT code
  hypervisor/arch/x86/configs/vm_config.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2703 hv: destroy IOMMU domain after vpci_cleanup()
  hypervisor/arch/x86/guest/vm.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2667 doc: use the new board name for UP2 in create-up2-images.sh script
  doc/tutorials/create-up2-images.sh
Labels: area: documentation

#2702 doc: add some comments for coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2691 doc: add the doc for 'Error Detection and Handling'
  doc/developer-guides/images/work_flow_of_error_detection_and_error_handling.png
  doc/developer-guides/index.rst
  doc/developer-guides/sw_design_guidelines.rst
Labels: area: documentation

#2701 hv: Remove multiple definitions for dmar translation structures
  hypervisor/arch/x86/guest/assign.c
  hypervisor/arch/x86/vtd.c
  hypervisor/include/arch/x86/vtd.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2616 Add fatal warning PCI MSIX table count > conf max
  hypervisor/hw/pci.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2685 Documentation: update the "ACRN Shell Commands" user guide
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#2706 dm: passthru: fix potential memory leak
  devicemodel/hw/pci/passthrough.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2707 dm: fix possible memory leak in 'load_elf32()'
  devicemodel/core/sw_load_elf.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2718 acrn-dm: set realtime sched policy for vcpu thread
  devicemodel/core/main.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2714 doc: fix typos in coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2722 dm: virtio-net: fix memory leak
  devicemodel/hw/pci/virtio/virtio_net.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2728 dm: fix typo of path for cgroup cpu tasks
  devicemodel/core/main.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2715 HV: PAE: Add stac()/clac() in local_gva2gpa_pae
  hypervisor/arch/x86/guest/guest_memory.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2726 DM: Add sample script to launch zephyr as guest
  devicemodel/samples/nuc/launch_zephyr.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#2723 dm: virtio-net: fix memory leak
  devicemodel/hw/pci/virtio/virtio_net.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2731 dm: usb: fix possible memory leak
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2733 dm: virtio: add memory barrier before notify FE
  devicemodel/hw/pci/virtio/virtio.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2730 dm: usb: fix possible memory leak
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2735 tools: acrnctl fix potential buffer overflow
  tools/acrn-manager/acrnctl.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2736 tools: acrnctl fix potential buffer overflow for apl_sdc_stable
  tools/acrn-manager/acrnctl.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2746 hv: vtd: check bus limit when add/remove device
  hypervisor/arch/x86/vtd.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2751 hv: vtd: fix compile warning on UEFI platform
  hypervisor/arch/x86/vtd.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2750 move instr_emul_ctxt instance to struct vcpu
  hypervisor/arch/x86/guest/instr_emul.c
  hypervisor/arch/x86/guest/io_emul.c
  hypervisor/arch/x86/pm.c
  hypervisor/arch/x86/timer.c
  hypervisor/arch/x86/vmx.c
  hypervisor/include/arch/x86/guest/instr_emul.h
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/arch/x86/per_cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2690 HV: Modularize boot folder
  hypervisor/arch/x86/guest/guest_memory.c
  hypervisor/boot/dmar_parse.c
  hypervisor/boot/sbl/abl_seed_parse.c
  hypervisor/boot/sbl/multiboot.c
  hypervisor/boot/sbl/sbl_seed_parse.c
  hypervisor/boot/uefi/uefi_boot.c
  hypervisor/include/arch/x86/abl_seed_parse.h
  hypervisor/include/arch/x86/guest/guest_memory.h
  hypervisor/include/arch/x86/sbl_seed_parse.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2757 dm: passthru: fix potentail mem leaks
  devicemodel/hw/pci/passthrough.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2729 hv: refactor seed management
  hypervisor/Makefile
  hypervisor/arch/x86/guest/trusty.c
  hypervisor/arch/x86/init.c
  hypervisor/arch/x86/seed/seed.c
  hypervisor/arch/x86/seed/seed_abl.c
  hypervisor/arch/x86/seed/seed_abl.h
  hypervisor/arch/x86/seed/seed_sbl.c
  hypervisor/arch/x86/seed/seed_sbl.h
  hypervisor/boot/sbl/multiboot.c
  hypervisor/include/arch/x86/guest/trusty.h
  hypervisor/include/arch/x86/seed.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2747 audio-mediator: load updated audio kernel modules
  devicemodel/samples/apl-mrb/launch_uos.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#2761 Makefile: make UP2 sample directory name consistent with board name
  devicemodel/Makefile
  devicemodel/samples/apl-up2/launch_uos.sh
  devicemodel/samples/apl-up2/sos_bootargs_debug.txt
  devicemodel/samples/apl-up2/sos_bootargs_release.txt
Labels: Automerge: Pass, CI: Tracked On Pass

#2759 hv: vtd: check bus number when assign/unassign device
  hypervisor/arch/x86/vtd.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2758 doc: add 0.7 release notes
  doc/release_notes_0.7.rst
Labels: area: documentation

#2765 DM: fix memory leak
  devicemodel/hw/block_if.c
  devicemodel/hw/pci/core.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2770 doc: remove apl_sdc_stable branch story
  doc/release_notes_0.7.rst
Labels: area: documentation

#2771 DM: Mark thre_int_pending as true when THR is empty
  devicemodel/hw/uart_core.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2776 doc: add v0.7 version to master branch (/latest)
  doc/conf.py
Labels: area: documentation

#2749 doc: fix wrong desciption of trusty's memory mapping
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/images/security-image8.png
Labels: area: documentation

#2710 doc: fix utf-8 punctuation, branding, spelling
  doc/api/GVT-g_api.rst
  doc/developer-guides/hld/hld-APL_GVT-g.rst
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/developer-guides/hld/hv-ioc-virt.rst
  doc/developer-guides/hld/usb-virt-hld.rst
  doc/developer-guides/l1tf.rst
  doc/developer-guides/modularity.rst
  doc/developer-guides/primer.rst
  doc/getting-started/apl-nuc.rst
  doc/introduction/index.rst
  doc/release_notes_0.2.rst
  doc/release_notes_0.4.rst
  doc/release_notes_0.5.rst
  doc/release_notes_0.6.rst
  doc/tutorials/agl-vms.rst
  doc/tutorials/skl-nuc.rst
  doc/tutorials/using_agl_as_uos.rst
  doc/tutorials/using_sbl_on_up2.rst
  doc/tutorials/using_ubuntu_as_sos.rst
  doc/user-guides/acrn-dm-parameters.rst
  hypervisor/README.rst
  tools/README.rst
  tools/acrn-crashlog/README.rst
  tools/acrn-crashlog/usercrash/README.rst
Labels: area: documentation

#2767 hv: cleanup some hva/hpa conversion code
  hypervisor/arch/x86/e820.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/mmu.c
  hypervisor/boot/reloc.c
  hypervisor/common/hypercall.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2775 doc: add some rules related to naming convention
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2774 hv: trusty: refine control registers switching method
  hypervisor/arch/x86/guest/trusty.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2754 Tools: Acrnd fix reporting unnecessary error on NUC and UP2
  tools/acrn-manager/acrnd.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2778 hv: seed: refine header file
  hypervisor/arch/x86/seed/seed.c
  hypervisor/arch/x86/seed/seed_abl.c
  hypervisor/arch/x86/seed/seed_sbl.c
  hypervisor/include/arch/x86/guest/trusty.h
  hypervisor/include/arch/x86/seed.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2781 Makefile: build for apl-nuc by default
  Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#2783 hv: fix wrong comment message about CLOS usage in vm config
  hypervisor/include/arch/x86/vm_config.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2802 DM USB: xHCI: Fix CTS test failure
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
  devicemodel/include/usb_core.h
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2803 hv: update CR0/CR4 on demand in run_vcpu()
  hypervisor/arch/x86/guest/vcpu.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2804 acrn-dm: revert the change which apply realtime schedule to vcpu0
  devicemodel/core/main.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2809 HV: add vrtc for sharing mode
  hypervisor/Makefile
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2810 hv: remove CONFIG_PARTITION_MODE for pre-launched VM vE820 creation
  hypervisor/Makefile
  hypervisor/arch/x86/configs/apl-mrb/ve820.c
  hypervisor/arch/x86/configs/apl-up2/ve820.c
  hypervisor/arch/x86/configs/dnv-cb2/ve820.c
  hypervisor/arch/x86/configs/nuc6cayh/ve820.c
  hypervisor/arch/x86/configs/nuc7i7bnh/ve820.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/board.h
  hypervisor/include/arch/x86/e820.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2811 config: unify board names to lowercase
  hypervisor/arch/x86/configs/apl-up2.config
  hypervisor/arch/x86/configs/nuc6cayh.config
  hypervisor/arch/x86/configs/nuc7i7bnh.config
Labels: Automerge: Pass, CI: Tracked On Pass

#2812 hv: vmconfig: minor fix about regression of commit 79cfb1
  hypervisor/arch/x86/configs/dnv-cb2/partition_config.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2779 doc: add rules related to implementation-specific behaviors
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2815 doc: add rdmsr/wrmsr to the "ACRN Shell Commands" documentation
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#2805 doc: add tutorial on how to increase the UOS disk size
  doc/tutorials/increase-uos-disk-size.rst
Labels: area: documentation

#2818 hv: minor fixes to a few calls to strncpy_s()
  hypervisor/boot/sbl/multiboot.c
  hypervisor/debug/shell.c
  hypervisor/debug/uart16550.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2739 hv: Use domain/device specific invalidation for DMAR translation caches
  hypervisor/arch/x86/vtd.c
  hypervisor/include/arch/x86/vtd.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2825 Fix two stability issues
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#2822 hv: disable mpx capability for guest
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/cpu.h
  hypervisor/include/arch/x86/cpuid.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2814 hv: passthru TSC_ADJUST to VM with lapic pt
  hypervisor/arch/x86/guest/vmsr.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2826 hv: fix potential buffer overflow in sbl_init_vm_boot_info()
  hypervisor/boot/sbl/multiboot.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2816 hv: enhance ACRN shell interactive help
  hypervisor/debug/shell_priv.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2721 Doc: Add tutorial about using zephyr as uos
  doc/tutorials/using_zephyr_as_uos.rst
Labels: area: documentation

#2832 HV: Fix a compiler warning in firmware.h
  hypervisor/bsp/include/firmware.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2827 hv: seed: remove unused seed parsing source files
  hypervisor/boot/sbl/abl_seed_parse.c
  hypervisor/boot/sbl/sbl_seed_parse.c
  hypervisor/include/arch/x86/abl_seed_parse.h
  hypervisor/include/arch/x86/sbl_seed_parse.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2833 DM: virtio-gpio: implement GPIO IRQ
  devicemodel/hw/pci/virtio/virtio_gpio.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2831 hv: replace MEM_2K with a new macro MAX_BOOTARGS_SIZE for bootargs size
  hypervisor/arch/x86/seed/seed.c
  hypervisor/boot/sbl/multiboot.c
  hypervisor/common/vm_load.c
  hypervisor/include/arch/x86/multiboot.h
  hypervisor/include/arch/x86/vm_config.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2836 hv:move 'udelay' to timer.c
  hypervisor/Makefile
  hypervisor/arch/x86/timer.c
  hypervisor/include/arch/x86/timer.h
  hypervisor/include/lib/rtl.h
  hypervisor/lib/misc.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2768 doc: Add 2 new FAQs
  doc/faq.rst
Labels: area: documentation

#2769 doc: update UP2 sample directory name in create-up2-image.sh
  doc/tutorials/create-up2-images.sh
Labels: area: documentation

#2801 DOC:Update standard reference of SW design guidelines
  doc/developer-guides/sw_design_guidelines.rst
Labels: area: documentation

#2819 doc: add some rules related to language extensions
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2839 doc: update the instructions to increase the size of a UOS disk image
  doc/tutorials/increase-uos-disk-size.rst
Labels: area: documentation

#2675 doc: update OVMF image location
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#2840 HV: Remove hypervisor.h from bsp folder
  hypervisor/bsp/const_dmar.c
  hypervisor/bsp/firmware_sbl.c
  hypervisor/bsp/firmware_uefi.c
  hypervisor/bsp/firmware_wrapper.c
  hypervisor/include/arch/x86/multiboot.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2847 dm: leave a gap for 32-bit PCI hole in E820 map
  devicemodel/core/sw_load_common.c
  devicemodel/hw/pci/core.c
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/include/pci_core.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2853 dm: remove smbios
  devicemodel/Makefile
  devicemodel/core/main.c
  devicemodel/core/smbiostbl.c
  devicemodel/include/smbiostbl.h
Labels: Automerge: Pass, CI: Tracked On Pass

#2850 hv: fix vulnerability when VM is destroyed
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#2845 doc: update coding guidelines
  doc/developer-guides/coding_guidelines.rst
Labels: area: documentation

#2859 hv: Debug messages from a CPU are overlapped with other CPUs messages
  hypervisor/debug/dump.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2864 Tools: acrnlog: fix confusing message "bad file descriptor" when star…
  tools/acrnlog/acrnlog.c
Labels: Automerge: Pass, CI: Tracked On Pass

#2838 doc: update software design guidelines
  doc/developer-guides/images/boot_information_parsing_module.png
  doc/developer-guides/sw_design_guidelines.rst
Labels: area: documentation

#2808 doc: Add tutorial about how to use CAT on UP2
  doc/tutorials/images/acrn_cat_hld.png
  doc/tutorials/images/using_cat_up2.png
  doc/tutorials/using_cat_on_up2.rst
Labels: area: documentation
