Repository projectacrn/acrn-hypervisor, pull requests merged in 2019-07, with the labels that each got.

#3339 doc:add more description about application constraints
  doc/developer-guides/c_coding_guidelines.rst
  doc/developer-guides/sw_design_guidelines.rst
Labels: area: documentation

#3319 tools: add check to verify that running with root privileges
  tools/acrn-manager/README.rst
  tools/acrn-manager/acrnctl.c
  tools/acrn-manager/acrnd.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3353 hv: ept: mask EPT leaf entry bit 52 to bit 63 in gpa2hpa
  hypervisor/arch/x86/guest/ept.c
  hypervisor/include/arch/x86/pgtable.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3348 Revert "dm: add "noapic" to rt-linux kernel parameters"
  devicemodel/samples/nuc/launch_hard_rt_vm.sh
Labels: Automerge: Pass, CI: Tracked On Pass

#3365 dm: cleanup assert in core.c
  devicemodel/core/vrpmb.c
  devicemodel/hw/pci/core.c
  devicemodel/hw/platform/debugexit.c
  devicemodel/hw/platform/tpm/tpm.c
  devicemodel/hw/platform/tpm/tpm_crb.c
  devicemodel/hw/platform/tpm/tpm_emulator.c
  devicemodel/hw/platform/usb_mouse.c
  devicemodel/hw/platform/usb_pmapper.c
  devicemodel/hw/usb_core.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3366 dm: clean up assert in virtio_rnd.c
  devicemodel/hw/pci/virtio/virtio_rnd.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3361 hv: vmexit: ecx should be checked instead of rcx when xsetbv
  hypervisor/arch/x86/guest/vmexit.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3359 dm: remove Execute attribute of usb_pmapper.c
  devicemodel/hw/platform/usb_pmapper.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3363 hv: vioapic: fix interrupt lost of external device
  hypervisor/arch/x86/guest/assign.c
  hypervisor/dm/vioapic.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3364 MDS mitigation for ACRN Hypervisor
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/security.c
  hypervisor/include/arch/x86/cpufeatures.h
  hypervisor/include/arch/x86/msr.h
  hypervisor/include/arch/x86/security.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3367 makefile: fix parallel build
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3373 HV: remove instr_emul.c dead code
  hypervisor/arch/x86/guest/instr_emul.c
  hypervisor/include/arch/x86/guest/instr_emul.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3375 hv:fix "no prototype for non-static function"
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/seed/seed_abl.c
  hypervisor/arch/x86/vmx.c
  hypervisor/boot/cmdline.c
  hypervisor/boot/guest/vboot_info.c
  hypervisor/common/hypercall.c
  hypervisor/common/trusty_hypercall.c
  hypervisor/debug/console.c
  hypervisor/debug/dbg_cmd.c
  hypervisor/debug/dump.c
  hypervisor/debug/hypercall.c
  hypervisor/debug/npk_log.c
  hypervisor/debug/shell.c
  hypervisor/debug/trace.c
  hypervisor/dm/vuart.c
  hypervisor/lib/stack_protector.c
  hypervisor/release/console.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3324 doc: Add introduction of launching Celadon User OS
  doc/tutorials/using_celadon_as_uos.rst
Labels: area: documentation

#3343 doc: add guideline for RTVM workload design
  doc/tutorials/rtvm_workload_design_guideline.rst
Labels: area: documentation

#3380 DM: Increase hugetlbfs MAX_PATH_LEN from 128 to 256
  devicemodel/core/hugetlb.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3386 HV: check security mitigation support for SSBD
  hypervisor/arch/x86/security.c
  hypervisor/include/arch/x86/cpufeatures.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3382 HV: fix violations touched type conversion
  hypervisor/arch/x86/configs/vmptable.c
  hypervisor/arch/x86/guest/trusty.c
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/ioapic.c
  hypervisor/arch/x86/seed/seed.c
  hypervisor/boot/cmdline.c
  hypervisor/boot/guest/vboot_info.c
  hypervisor/debug/console.c
  hypervisor/debug/profiling.c
  hypervisor/debug/shell.c
  hypervisor/dm/vrtc.c
  hypervisor/include/arch/x86/apicreg.h
  hypervisor/include/dm/mptable.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3391 doc: Add platform sos info and GUI screenshots against Celadon Guest OS
  doc/tutorials/images/Celadon_apps.png
  doc/tutorials/images/Celadon_home.png
  doc/tutorials/using_celadon_as_uos.rst
Labels: area: documentation

#3388 HV: fix "use -- or ++ operations"
  hypervisor/arch/x86/guest/vcpu.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3403 HV: add kata support on sdc scenario
  hypervisor/arch/x86/Kconfig
  hypervisor/common/hypercall.c
  hypervisor/include/public/acrn_hv_defs.h
  hypervisor/scenarios/hybrid/vm_configurations.h
  hypervisor/scenarios/industry/vm_configurations.h
  hypervisor/scenarios/sdc/vm_configurations.c
  hypervisor/scenarios/sdc/vm_configurations.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3399 tools: acrn-manager: fix headers install for ioc cbc tools
  tools/acrn-manager/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3412 doc:Update Getting started guide for Intel NUC
  doc/getting-started/apl-nuc.rst
Labels: area: documentation

#3411 tools:acrn-crashlog: detect the panic event from all pstore files
  tools/acrn-crashlog/acrnprobe/channels.c
  tools/acrn-crashlog/acrnprobe/crash_reclassify.c
  tools/acrn-crashlog/acrnprobe/include/crash_reclassify.h
  tools/acrn-crashlog/acrnprobe/include/load_conf.h
  tools/acrn-crashlog/acrnprobe/load_conf.c
  tools/acrn-crashlog/acrnprobe/sender.c
  tools/acrn-crashlog/common/fsutils.c
  tools/acrn-crashlog/data/acrnprobe.xml
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3421 HV: change param type of init_pcpu_pre
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/init.c
  hypervisor/include/arch/x86/cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3389 doc: Add introduction of using Windows Guest OS
  doc/scripts/Virtio-Inject.bat
  doc/scripts/mkisofs_both_legacy_and_uefi.bat
  doc/tutorials/images/adk_install_1.png
  doc/tutorials/images/adk_install_2.png
  doc/tutorials/images/install_wim_index.png
  doc/tutorials/images/windows_install_1.png
  doc/tutorials/images/windows_install_10.png
  doc/tutorials/images/windows_install_11.png
  doc/tutorials/images/windows_install_12.png
  doc/tutorials/images/windows_install_2.png
  doc/tutorials/images/windows_install_3.png
  doc/tutorials/images/windows_install_4.png
  doc/tutorials/images/windows_install_5.png
  doc/tutorials/images/windows_install_6.png
  doc/tutorials/images/windows_install_7.png
  doc/tutorials/images/windows_install_8.png
  doc/tutorials/images/windows_install_9.png
  doc/tutorials/install_by_vga_gsg.tar.gz
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#3426 doc: fix format in WaaG document
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#3424 hv: vuart: bugfix for communication vuart
  hypervisor/dm/vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3430 HV: add SDC2 config in hypervisor/arch/x86/Kconfig
  hypervisor/Makefile
  hypervisor/arch/x86/Kconfig
  hypervisor/scenarios/sdc2/vm_configurations.c
  hypervisor/scenarios/sdc2/vm_configurations.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3415 doc: update CODEOWNERS for doc reviews
  CODEOWNERS
Labels: CI: Tracked On Pass, CI: pending approve

#3438 dm: virtio-i2c: minor fix
  devicemodel/hw/pci/virtio/virtio_i2c.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3435 apl_sdc_stable:hv: fix symbols not stripped from release binaries
  devicemodel/Makefile
  hypervisor/Makefile
  tools/acrn-manager/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass, CI: apl_sdc_stable

#3439 doc: update WaaG doc
  doc/scripts/Virtio-Inject.bat
  doc/scripts/mkisofs_both_legacy_and_uefi.bat
  doc/tutorials/install_by_vga_gsg.tar.gz
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#3432 doc: Add tutorial to learn to sign binaries of a Clear Linux image.
  doc/scripts/sign_image.sh
  doc/tutorials/sign_clear_linux_image.rst
Labels: area: documentation

#3422 doc: Add ACRN tag or Clear Linux version info for some tutorials
  doc/tutorials/acrn-dm_QoS.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_up2.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
Labels: area: documentation

#3416 doc: remove vuart configuration in nuc and up2
  doc/getting-started/apl-nuc.rst
  doc/getting-started/up2.rst
Labels: area: documentation

#3445 HV:refine the handler for 'invept' vmexit
  hypervisor/arch/x86/guest/vmexit.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3447 HV: rename nuc7i7bnh to nuc7i7dnb
  hypervisor/arch/x86/configs/kbl-nuc-i7
  hypervisor/arch/x86/configs/kbl-nuc-i7.config
  hypervisor/arch/x86/configs/nuc7i7dnb.config
  hypervisor/arch/x86/configs/nuc7i7dnb/board.c
  hypervisor/arch/x86/configs/nuc7i7dnb/misc_cfg.h
  hypervisor/arch/x86/configs/nuc7i7dnb/pci_devices.h
  hypervisor/arch/x86/configs/nuc7i7dnb/ve820.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3436 vpci: fix coding style issue
  hypervisor/dm/vpci/vhostbridge.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/dm/vpci.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3451 HV: move vbar info to board specific pci_devices.h
  hypervisor/arch/x86/configs/apl-mrb/pci_devices.h
  hypervisor/arch/x86/configs/nuc7i7dnb/pci_devices.h
  hypervisor/scenarios/logical_partition/pt_dev.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3455 HV: allow write 0 to MSR_IA32_MCG_STATUS
  hypervisor/arch/x86/guest/vmsr.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3450 doc: update using_partition_mode_on_nuc nuc7i7bnh to nuc7i7dnb
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#3448 doc: remove deprecated sos_bootargs
  doc/tutorials/create-up2-images.sh
Labels: area: documentation

#3458 hv: refine handler to 'rdpmc' vmexit
  hypervisor/arch/x86/guest/vmexit.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3460 hv: uart: make uart base address more readable
  hypervisor/debug/uart16550.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3461 dm: support VMs communication with virtio-console
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3457 doc: organize release notes into a folder
  doc/index.rst
  doc/release_notes/index.rst
  doc/release_notes/release_notes_0.1.rst
  doc/release_notes/release_notes_0.2.rst
  doc/release_notes/release_notes_0.3.rst
  doc/release_notes/release_notes_0.4.rst
  doc/release_notes/release_notes_0.5.rst
  doc/release_notes/release_notes_0.6.rst
  doc/release_notes/release_notes_0.7.rst
  doc/release_notes/release_notes_0.8.rst
  doc/release_notes/release_notes_1.0.rst
  doc/release_notes/release_notes_1.1.rst
Labels: area: documentation

#3468 dm: array bound and NULL pointer issue fix
  devicemodel/hw/pci/virtio/virtio_console.c
  devicemodel/hw/pci/virtio/virtio_i2c.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3471 hv: schedule: schedule to idel after SOS resume form S3
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/vpic.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3474 dm: bugfix for remote launch guest issue
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3476 More vpci cleanup
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vmsi.c
  hypervisor/dm/vpci/vmsix.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpci/vpci_priv.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3478 HV: add board specific cpu state table to support Px Cx
  hypervisor/arch/x86/configs/apl-mrb/board.c
  hypervisor/arch/x86/configs/apl-up2/board.c
  hypervisor/arch/x86/configs/dnv-cb2/board.c
  hypervisor/arch/x86/configs/generic/board.c
  hypervisor/arch/x86/configs/nuc6cayh/board.c
  hypervisor/arch/x86/configs/nuc7i7dnb/board.c
  hypervisor/arch/x86/cpu_state_tbl.c
  hypervisor/include/arch/x86/board.h
  hypervisor/include/arch/x86/host_pm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3479 HV: correct CONFIG_BOARD string of apl up2
  hypervisor/arch/x86/configs/apl-up2.config
Labels: Automerge: Pass, CI: Tracked On Pass

#3490 doc: Add ovmf NV storage writeback option description
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#3472 acrn-hv: code review fix lib/string.c
  hypervisor/lib/string.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#3496 hv: fix debug message format in 'init_pci_pdev_list'
  hypervisor/hw/pci.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3481 Makefile: Add install for uefi firmware
  Makefile
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#3502 HV: Enable vART support by intercepting TSC_ADJUST MSR
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmsr.c
Labels: Automerge: Pass, CI: Tracked On Pass

#3500 HV: return extended info in vCPUID leaf 0x40000001
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/include/arch/x86/guest/vcpuid.h
Labels: Automerge: Pass, CI: Tracked On Pass

#3492 doc: Update WaaG tutorial launch script and OVMF binary
  doc/tutorials/OVMF.fd
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation
