Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-10, with the labels that each got.

#5381 doc: tweak 2.2 release notes
  doc/release_notes/release_notes_2.2.rst
Labels: area: documentation

#5382 doc: update breadcrumb to include release version
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/conf.py
Labels: area: documentation

#5383 doc: spelling and grammar improvements
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/introduction/index.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/acrn_on_qemu.rst
  doc/tutorials/cpu_sharing.rst
  doc/tutorials/debug.rst
  doc/tutorials/docbuild.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/realtime_performance_tuning.rst
  doc/tutorials/rtvm_performance_tips.rst
  doc/tutorials/rtvm_workload_design_guideline.rst
  doc/tutorials/run_kata_containers.rst
  doc/tutorials/running_deb_as_serv_vm.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/setup_openstack_libvirt.rst
  doc/tutorials/sgx_virtualization.rst
  doc/tutorials/sriov_virtualization.rst
  doc/tutorials/using_grub.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_windows_as_uos.rst
  doc/tutorials/using_xenomai_as_uos.rst
  doc/tutorials/using_yp.rst
  doc/tutorials/using_zephyr_as_uos.rst
  doc/tutorials/vuart_configuration.rst
  doc/tutorials/waag-secure-boot.rst
Labels: area: documentation

#5384 doc: more spelling and grammar fixes
  doc/developer-guides/GVT-g-porting.rst
  doc/developer-guides/VBSK-analysis.rst
  doc/developer-guides/asm_coding_guidelines.rst
  doc/developer-guides/c_coding_guidelines.rst
  doc/developer-guides/contribute_guidelines.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/graphviz.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/hld-power-management.rst
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/hld-trace-log.rst
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/developer-guides/hld/index.rst
  doc/developer-guides/l1tf.rst
  doc/developer-guides/modularity.rst
  doc/developer-guides/sw_design_guidelines.rst
  doc/developer-guides/trusty.rst
Labels: area: documentation

#5393 acrn-config: Add Px / Cx state info for tgl-rvp
  misc/vm_configs/xmls/board-xmls/tgl-rvp.xml
Labels: CI: Tracked On Pass

#5396 acrn-config: increase hv ram size for 7 VMs
  misc/acrn-config/hv_config/board_defconfig.py
Labels: CI: Tracked On Pass

#5395 acrn-config: fix hang issue for board EHL (hybrid_rt)
  misc/acrn-config/board_config/board_info_h.py
  misc/vm_configs/scenarios/hybrid/ehl-crb-b/misc_cfg.h
  misc/vm_configs/scenarios/hybrid_rt/ehl-crb-b/misc_cfg.h
Labels: CI: Tracked On Pass

#5400 dm: fix fault Injection into VirtIO console backend
  devicemodel/hw/pci/virtio/virtio.c
Labels: CI: Tracked On Pass

#5405 acrn-config: update logical_partition for ehl-crb-b
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/logical_partition.xml
Labels: CI: Tracked On Pass, release_2.2

#5402 dm: fix typo error to pass through TPM device
  devicemodel/core/main.c
Labels: CI: Tracked On Pass

#5413 doc: update coding guidelines
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation

#5412 doc: update doxygen configuration
  doc/acrn.doxyfile
Labels: area: documentation

#5423 acrn-config: Get vbar base and index for vmsix supported devices
  misc/acrn-config/board_config/vbar_base_h.py
  misc/acrn-config/scenario_config/pci_dev_c.py
Labels: CI: Tracked On Pass

#5431 hv: don't need to save boot context
  hypervisor/Makefile
  hypervisor/arch/x86/boot/cpu_primary.S
  hypervisor/arch/x86/boot/cpu_save_boot_ctx.S
  hypervisor/boot/guest/vboot_info.c
  hypervisor/include/arch/x86/boot/boot_context.h
  misc/hv_prebuild/static_checks.c
Labels: CI: Tracked On Pass

#5432 acrn-config: minor change hybrid_rt scenario for ehl
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt_fusa.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/industry.xml
Labels: CI: Tracked On Pass

#5433 Vmsix vbar gpa
  hypervisor/dm/vpci/vmsix_on_msi.c
Labels: CI: Tracked On Pass

#5386 doc: fix doxygen 1.8.17 issues
  hypervisor/include/arch/x86/guest/ept.h
  hypervisor/include/common/ptdev.h
Labels: CI: Tracked On Pass

#5434 acrn-config: minor change scenario xml for cfl-k700-i7
  misc/vm_configs/xmls/board-xmls/cfl-k700-i7.xml
  misc/vm_configs/xmls/config-xmls/cfl-k700-i7/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/cfl-k700-i7/industry.xml
Labels: CI: Tracked On Pass

#5438 acrn-config: fix the bug of resolved nested mmio address
  misc/acrn-config/board_config/vbar_base_h.py
Labels: CI: Tracked On Pass

#5441 cleanup vpci structure when shutdown_vm
  hypervisor/dm/vpci/vpci.c
Labels: CI: Tracked On Pass

#5388 acrn-config: fix the wrong vuart name in launch script
  misc/acrn-config/launch_config/com.py
Labels: CI: Tracked On Pass

#5439 doc: doc spelling and grammar fixes
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/docbuild.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/realtime_performance_tuning.rst
  doc/tutorials/rtvm_performance_tips.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/setup_openstack_libvirt.rst
  doc/tutorials/sgx_virtualization.rst
  doc/tutorials/sriov_virtualization.rst
Labels: area: documentation

#5443 doc: update coding guidelines
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation
