Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-04, with the labels that each got.

#4561 acrn-config: Limit check on Pre-Launched VM RAM size
  misc/acrn-config/library/scenario_cfg_lib.py
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4568 Doc: update building acrn in docker for V1.6
  doc/tutorials/building_acrn_in_docker.rst
Labels: area: documentation

#4567 Doc: releasenotes_1.6
  doc/release_notes/release_notes_1.6.rst
Labels: area: documentation

#4559 doc: update industry gsg to v1.6 release
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/rt_industry.rst
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4564 hv: Reserve space for VMs' EPT 4k pages after boot
  hypervisor/Makefile
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/e820.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/page.c
  hypervisor/boot/guest/direct_boot.c
  hypervisor/include/arch/x86/e820.h
  hypervisor/include/arch/x86/page.h
  hypervisor/include/arch/x86/vm_config.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4573 Doc: Minor grammatical updates to rt_industry.html and building_acrn_…
  doc/getting-started/rt_industry.rst
  doc/tutorials/building_acrn_in_docker.rst
Labels: area: documentation

#4574 Doc: Grammatical edits to Release Notes 1.6
  doc/release_notes/release_notes_1.6.rst
Labels: area: documentation

#4576 Doc: Release Notes update based on DKinder edits
  doc/release_notes/release_notes_1.6.rst
Labels: area: documentation

#4577 doc: add 1.6 to doc version menu
  doc/conf.py
Labels: area: documentation

#4555 hv: vtd: use local var instead of global var
  hypervisor/arch/x86/vtd.c
Labels: CI: Tracked On Pass

#4549 HV: misra fix for multiboot2.c
  hypervisor/boot/include/boot.h
  hypervisor/boot/multiboot2.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4581 hv: Fix minor issues with the patch to reserve EPT 4K pages after boot
  hypervisor/arch/x86/page.c
  hypervisor/include/arch/x86/vm_config.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4534 Makefile: patch set to enhance build HV with optional configuration source
  Makefile
  hypervisor/Makefile
  hypervisor/scripts/makefile/cfg_update.mk
  hypervisor/scripts/makefile/kconfig.mk
Labels: CI: Tracked On Pass

#4583 acrn-config: update IOMEM_INFO of tgl-rvp board
  misc/acrn-config/xmls/board-xmls/tgl-rvp.xml
Labels: Automerge: Pass, CI: Tracked On Pass

#4587 acrn-config: Fixes for BAR remapping logic
  misc/acrn-config/board_config/pci_devices_h.py
  misc/acrn-config/library/board_cfg_lib.py
  misc/acrn-config/library/common.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4591 doc: add google analytics tag
  doc/conf.py
Labels: area: documentation

#4578 doc: remove "Glossary" icon box on home page
  doc/index.rst
Labels: area: documentation

#4579 doc: organize security advisory doc
  doc/asa.rst
Labels: area: documentation

#4592 doc: some additional google analytics code
  doc/conf.py
  doc/static/acrn-custom.js
Labels: area: documentation

#4580 hv: vm: refine the devices unregistration sequence of vm shutdown
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/dm/vpci.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4589 hv: vpci: detail comment for pci_vdev_update_vbar_base
  hypervisor/dm/vpci/vdev.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4512 sample: add sample script for launching xenomai RTVM
  devicemodel/samples/nuc/launch_xenomai.sh
Labels: CI: Tracked On Pass

#4584 doc: gsg quick setup script issue fix.
  doc/getting-started/acrn_quick_setup.sh
Labels: area: documentation

#4596 doc: add a custom 404 page
  doc/404.rst
  doc/Makefile
  doc/images/ACRN-fall-from-tree-small.png
Labels: area: documentation

#4597 doc: fix 404 processing
  doc/Makefile
  doc/images/ACRN-fall-from-tree-small.png
  doc/scripts/publish-404.html
Labels: area: documentation

#4598 doc: fix image size on 404 page
  doc/404.rst
Labels: area: documentation

#4599 doc: update custom CSS with additional styles
  doc/static/acrn-custom.css
Labels: area: documentation

#4600 doc: fix 404 display on mobile devices
  doc/404.rst
Labels: area: documentation

#4601 doc: tweak 404 page for phone display
  doc/404.rst
  doc/images/ACRN-fall-from-tree-small.png
Labels: area: documentation

#4602 doc: update robots.txt exclusion list
  doc/scripts/publish-robots.txt
Labels: area: documentation

#4593 hv: virq: refine pending event inject sequence
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4594 hv: vmcs: remove vmcs field check for a vcpu
  hypervisor/arch/x86/guest/vmcs.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4607 doc: remove /404.html redirect
  doc/Makefile
  doc/scripts/publish-404.html
Labels: area: documentation

#4608 doc: fix misspellings
  doc/contribute.rst
  doc/develop.rst
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/hld-power-management.rst
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/hostbridge-virt-hld.rst
  doc/developer-guides/hld/hv-memmgt.rst
  doc/developer-guides/hld/hv-rdt.rst
  doc/developer-guides/hld/hv-startup.rst
  doc/developer-guides/hld/hv-virt-interrupt.rst
  doc/developer-guides/hld/hv-vm-management.rst
  doc/developer-guides/hld/hv-vt-d.rst
  doc/introduction/index.rst
  doc/release_notes/release_notes_1.1.rst
  doc/release_notes/release_notes_1.2.rst
  doc/release_notes/release_notes_1.4.rst
  doc/release_notes/release_notes_1.5.rst
  doc/release_notes/release_notes_1.6.rst
  doc/tutorials/acrn_ootb.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/realtime_performance_tuning.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/sign_clear_linux_image.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_sdc2_mode_on_nuc.rst
  doc/tutorials/using_xenomai_as_uos.rst
Labels: area: documentation

#4603 hv: add lock for ept add/modify/del
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4614 hv: add lock for ept add/modify/del
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: 1.6.1, CI: Tracked On Pass

#4621 hv: fix for waag 2 core reboot issue
  hypervisor/arch/x86/guest/virq.c
  hypervisor/include/arch/x86/irq.h
Labels: 1.6.1, Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4626 acrn-config: support passthroug GVT for WaaG by default
  misc/acrn-config/launch_config/com.py
  misc/acrn-config/launch_config/pt.py
  misc/acrn-config/library/launch_cfg_lib.py
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_hardrt.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_vxworks.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_waag.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_2uos.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_laag.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_zephyr.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_hardrt.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_vxworks.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_waag.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_2uos.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_laag.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_zephyr.xml
Labels: 1.6.1, CI: Tracked On Pass

#4612 hv: fix SOS vapic_id assignment issue
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4622 hv:print relocation delta
  hypervisor/debug/dump.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4629 hv: guest: fix bug in get_vcpu_paging_mode
  hypervisor/arch/x86/guest/guest_memory.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4632 hv: fix for waag 2 core reboot issue
  hypervisor/arch/x86/guest/virq.c
  hypervisor/include/arch/x86/irq.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4627 acrn-config: support passthroug GVT for WaaG by default
  misc/acrn-config/launch_config/com.py
  misc/acrn-config/launch_config/pt.py
  misc/acrn-config/library/launch_cfg_lib.py
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_hardrt.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_vxworks.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_waag.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_2uos.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_laag.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_zephyr.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_hardrt.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_vxworks.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_waag.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_2uos.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_laag.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_zephyr.xml
Labels: Automerge: Pass, CI: Tracked On Pass

#4617 doc: clean up utf8 characters
  doc/developer-guides/c_coding_guidelines.rst
  doc/developer-guides/hld/ahci-hld.rst
  doc/developer-guides/hld/virtio-gpio.rst
  doc/developer-guides/hld/virtio-i2c.rst
  doc/getting-started/rt_industry.rst
  doc/introduction/index.rst
  doc/reference/hardware.rst
  doc/release_notes/release_notes_1.1.rst
  doc/release_notes/release_notes_1.2.rst
  doc/release_notes/release_notes_1.4.rst
  doc/release_notes/release_notes_1.5.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/realtime_performance_tuning.rst
  doc/tutorials/run_kata_containers.rst
  doc/tutorials/sriov_virtualization.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4611 doc: change UOS/SOS to User VM/Service VM
  doc/api/devicemodel_api.rst
  doc/developer-guides/VBSK-analysis.rst
  doc/developer-guides/c_coding_guidelines.rst
  doc/developer-guides/hld/ahci-hld.rst
  doc/developer-guides/hld/hld-APL_GVT-g.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-trace-log.rst
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/developer-guides/hld/hv-console.rst
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/hv-interrupt.rst
  doc/developer-guides/hld/hv-io-emulation.rst
  doc/developer-guides/hld/hv-ioc-virt.rst
  doc/developer-guides/hld/hv-memmgt.rst
  doc/developer-guides/hld/hv-partitionmode.rst
  doc/developer-guides/hld/hv-startup.rst
  doc/developer-guides/hld/hv-virt-interrupt.rst
  doc/developer-guides/hld/hv-vm-management.rst
  doc/developer-guides/hld/uart-virt-hld.rst
  doc/developer-guides/hld/usb-virt-hld.rst
  doc/developer-guides/hld/virtio-blk.rst
  doc/developer-guides/hld/virtio-console.rst
  doc/developer-guides/hld/virtio-gpio.rst
  doc/developer-guides/hld/virtio-i2c.rst
  doc/developer-guides/hld/virtio-input.rst
  doc/developer-guides/hld/virtio-net.rst
  doc/developer-guides/hld/virtio-rnd.rst
  doc/developer-guides/hld/watchdog-hld.rst
  doc/developer-guides/l1tf.rst
  doc/developer-guides/modularity.rst
  doc/tutorials/acrn-dm_QoS.rst
  doc/tutorials/acrn_ootb.rst
  doc/tutorials/building_uos_from_clearlinux.rst
  doc/tutorials/cpu_sharing.rst
  doc/tutorials/debug.rst
  doc/tutorials/increase-uos-disk-size.rst
  doc/tutorials/sgx_virtualization.rst
  doc/tutorials/skl-nuc.rst
  doc/tutorials/trustyACRN.rst
  doc/tutorials/using_agl_as_uos.rst
  doc/tutorials/using_partition_mode_on_up2.rst
  doc/tutorials/using_sbl_on_up2.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
  doc/tutorials/vuart_configuration.rst
  doc/user-guides/acrn-dm-parameters.rst
  doc/user-guides/acrn-shell.rst
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#4618 doc: Known Limitation regarding PCI devices and resources assignment
  doc/reference/hardware.rst
Labels: area: documentation

#4642 doc: remove trailing spaces
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/developer-guides/hld/hv-pm.rst
  doc/faq.rst
  doc/introduction/index.rst
  doc/release_notes/release_notes_0.4.rst
  doc/release_notes/release_notes_0.5.rst
  doc/release_notes/release_notes_0.6.rst
  doc/release_notes/release_notes_1.3.rst
  doc/release_notes/release_notes_1.4.rst
  doc/tutorials/docbuild.rst
  doc/tutorials/increase-uos-disk-size.rst
  doc/tutorials/kbl-nuc-sdc.rst
  doc/tutorials/trustyACRN.rst
  doc/tutorials/up2.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#4624 hv: provide vm_config information in get_platform_info hypercall
  hypervisor/common/hypercall.c
  hypervisor/include/public/acrn_hv_defs.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4649 hv: wrap a function to initialize pCPU for second phase
  hypervisor/arch/x86/init.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4619 acrnprobe: avoid race condition
  misc/tools/acrn-crashlog/acrnprobe/Makefile
  misc/tools/acrn-crashlog/usercrash/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#4646 dm:refine pm_vuart code
  devicemodel/core/pm_vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4647 life_mngr:fix resend shutdown cmd fail
  misc/life_mngr/life_mngr.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4653 dm: add vm_pause before vm_destroy
  devicemodel/core/main.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4643 doc: update doc guidelines
  doc/developer-guides/doc_guidelines.rst
Labels: area: documentation

#4658 Doc: Initial version of ARCN RTVM Perf Tips
  doc/develop.rst
  doc/tutorials/rtvm_performance_tips.rst
Labels: area: documentation

#4656 HV: fix wrong gpa start of hpa2 in ve820.c
  hypervisor/arch/x86/guest/ve820.c
Labels: 1.6.1, Automerge: Pass, CI: Tracked On Pass

#4659 HV: set default MCFG base for generic board
  hypervisor/arch/x86/Kconfig
  hypervisor/arch/x86/configs/platform_acpi_info.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4655 HV: fix wrong gpa start of hpa2 in ve820.c
  hypervisor/arch/x86/guest/ve820.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4662 HV: Kconfig: enable CPU sharing by default
  hypervisor/arch/x86/Kconfig
  hypervisor/scenarios/industry/vm_configurations.c
  hypervisor/scenarios/industry/vm_configurations.h
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry.xml
Labels: 1.6.1, CI: Tracked On Pass, config_tool_modified

#4651 doc: update partition mode tutorial to use whl board.
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#4663 Doc: Minor grammatical edits to GSG for ACRN logical part mode
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#4665 hv: Wake up vCPU for interrupts from vPIC
  hypervisor/arch/x86/guest/virq.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4671 crashlog: fix build issue under latest clearlinux
  misc/tools/acrn-crashlog/acrnprobe/loop.c
Labels: CI: Tracked On Pass

#4673 crashlog: fix build issue under latest clearlinux
  misc/tools/acrn-crashlog/acrnprobe/loop.c
Labels: CI: Tracked On Pass

#4667 acrn-config: Generate info in pci_dev file for Pre-Launched VMs
  misc/acrn-config/board_config/pci_devices_h.py
  misc/acrn-config/library/board_cfg_lib.py
  misc/acrn-config/scenario_config/pci_dev_c.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4668 hv: Wake up vCPU for interrupts from vPIC
  hypervisor/arch/x86/guest/virq.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4676 acrn-config: Generate info in pci_dev file for Pre-Launched VMs
  misc/acrn-config/board_config/pci_devices_h.py
  misc/acrn-config/library/board_cfg_lib.py
  misc/acrn-config/scenario_config/pci_dev_c.py
Labels: 1.6.1, CI: Tracked On Pass

#4672 doc: remove the kbl-nuc flow pic from the partition mode gsg.
  doc/tutorials/images/logical_partition_scenario_on_nuc.png
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#4657 doc: add sphinx-tabs extension
  doc/conf.py
  doc/scripts/requirements.txt
Labels: area: documentation

#4687 doc: update doc guidelines for sphinx-tabs
  doc/developer-guides/doc_guidelines.rst
Labels: area: documentation

#4595 acrn-config: fix typos and text in board_parser.py tool
  misc/acrn-config/target/board_parser.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4682 hv: vtd: fix potential dead loop if qi request timeout
  hypervisor/arch/x86/vtd.c
Labels: 1.6.1, CI: Tracked On Pass

#4689 Makefile: do not override RELEASE when build with XML
  Makefile
  hypervisor/scripts/makefile/cfg_update.mk
  hypervisor/scripts/makefile/kconfig.mk
Labels: 1.6.1, CI: Tracked On Pass, Coding Guidelines: PASS

#4690 Makefile: do not override RELEASE when build with XML
  Makefile
  hypervisor/scripts/makefile/cfg_update.mk
  hypervisor/scripts/makefile/kconfig.mk
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4686 doc: edits for rtvm_performance_tips doc
  doc/tutorials/rtvm_performance_tips.rst
Labels: area: documentation

#4696 doc: fix a coupe of typos in rtvm_performance_tips.rst doc
  doc/tutorials/rtvm_performance_tips.rst
Labels: area: documentation

#4704 hv: Enable accessed bit in EPT paging
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/arch/x86/page.c
  hypervisor/include/arch/x86/guest/ept.h
  hypervisor/include/arch/x86/page.h
  hypervisor/include/arch/x86/pgtable.h
Labels: 1.6.1, CI: Tracked On Pass, Coding Guidelines: PASS

#4707 acrn-dm: change command option name from "pcpu_list" to "cpu_affinity"
  devicemodel/core/main.c
  devicemodel/core/vmmapi.c
  devicemodel/include/vmmapi.h
Labels: 1.6.1, CI: Tracked On Pass

#4705 dm:refine graphics data stolen memory passthru for EHL platform
  devicemodel/hw/pci/passthrough.c
  devicemodel/include/pcireg.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4708 acrn-dm: change command option name from "pcpu_list" to "cpu_affinity"
  devicemodel/core/main.c
  devicemodel/core/vmmapi.c
  devicemodel/include/vmmapi.h
Labels: CI: Tracked On Pass

#4712 DM USB: xHCI: Drop commands if the slot is disabled
  devicemodel/hw/pci/xhci.c
Labels: 1.6.1, CI: Tracked On Pass

#4714 Doc: Modify Getting Started and Advanced Guides sections (navigation)
  doc/develop.rst
  doc/release_notes/release_notes_1.2.rst
  doc/try.rst
  doc/tutorials/using_agl_as_uos.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_up2.rst
  doc/tutorials/using_sdc2_mode_on_nuc.rst
Labels: area: documentation

#4715 doc: update docker build with numbered steps
  doc/tutorials/building_acrn_in_docker.rst
Labels: area: documentation

#4679 sample: don't restore passthrough devices on exit by default
  devicemodel/samples/nuc/launch_xenomai.sh
Labels: CI: Tracked On Pass

#4720 ACRN/DM: Reset the passthrough device to fix garbage display issue
  devicemodel/hw/pci/passthrough.c
Labels: 1.6.1, CI: Tracked On Pass

#4723 doc: add dynamic config in web app of acrn configuration tool
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/images/choose_scenario.png
  doc/tutorials/images/configure_scenario.png
  doc/tutorials/images/configure_vm_add.png
Labels: area: documentation

#4726 Doc: Grammatical edits to acrn config tool doc
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#4717 local_gpa2hpa: INVALID_GPA also means failure of address conversion
  hypervisor/arch/x86/guest/guest_memory.c
Labels: 1.6.1, CI: Tracked On Pass

#4702 Doc: HLD for Split-locked Access Handling
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hld-splitlock.rst
Labels: area: documentation

#4734 doc: update to splitlock hld document
  doc/developer-guides/hld/hld-splitlock.rst
Labels: area: documentation

#4739 HV: add a specific stack space used in CPU booting
  hypervisor/arch/x86/boot/cpu_primary.S
  hypervisor/bsp/ld/link_ram.ld.in
Labels: Automerge: Pass, CI: Tracked On Pass

#4736 acrn-dm: fix corner cases in acrn_parse_cpu_affinity()
  devicemodel/core/vmmapi.c
Labels: 1.6.1, CI: Tracked On Pass

#4743 hv: don't overwrite the statically configured vm_configs[] in hypercall
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/vm_config.h
Labels: 1.6.1, CI: Tracked On Pass, config_tool_modified

#4728 acrn-config: assign PCPU0~3 to post vm by default
  hypervisor/arch/x86/configs/nuc7i7dnb.config
  hypervisor/scenarios/industry/vm_configurations.h
  misc/acrn-config/hv_config/hv_item.py
  misc/acrn-config/library/scenario_cfg_lib.py
  misc/acrn-config/scenario_config/scenario_cfg_gen.py
  misc/acrn-config/scenario_config/vm_configurations_h.py
  misc/acrn-config/xmls/config-xmls/apl-mrb/hybrid.xml
  misc/acrn-config/xmls/config-xmls/apl-mrb/industry.xml
  misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/apl-mrb/sdc.xml
  misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/hybrid.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/industry.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/apl-up2/sdc.xml
  misc/acrn-config/xmls/config-xmls/generic/hybrid.xml
  misc/acrn-config/xmls/config-xmls/generic/industry.xml
  misc/acrn-config/xmls/config-xmls/generic/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/generic/sdc.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/hybrid.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_waag.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_2uos.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/hybrid.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_waag.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_2uos.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc.xml
  misc/acrn-config/xmls/config-xmls/template/HV.xml
  misc/acrn-config/xmls/config-xmls/tgl-rvp/industry.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/hybrid.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/hybrid.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml
  misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc.xml
Labels: 1.6.1, CI: Tracked On Pass, CI: pending approve, config_tool_modified

#4735 doc: add VT-d posted interrupt documentation
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/images/passthru-image50.png
Labels: area: documentation

#4747 doc: add note about capricious UP2 EFI firmware
  doc/tutorials/up2.rst
Labels: area: documentation

#4729 doc:update waag gsg after enabling gvt-d and cpu-sharing.
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4748 doc: update windows as UOS tutorial
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4746 ACRN/DM: Initialize the igd_lpc bridge to ISA_BRIDGE to make Linux gu…
  devicemodel/hw/pci/lpc.c
Labels: 1.6.1, CI: Tracked On Pass
