Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-11, with the labels that each got.

#5447 doc: more prep for upgrading doc build tools
  doc/.known-issues/doc/dupdecl.conf
  doc/.known-issues/doc/kerneldoc.conf
  doc/glossary.rst
Labels: area: documentation

#5459 acrn-config: remove PSRAM_PASSTHROUGH_PRE_RTVM in PSRAM config
  misc/acrn-config/acpi_gen/asl_gen.py
  misc/acrn-config/hv_config/board_defconfig.py
  misc/acrn-config/hv_config/hv_item.py
  misc/acrn-config/library/hv_cfg_lib.py
  misc/acrn-config/scenario_config/scenario_cfg_gen.py
  misc/vm_configs/xmls/config-xmls/generic/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/template/HV.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass, release_2.3

#5462 acrn-config: disable psram config
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass, release_2.3

#5458 doc: bring back prev/next buttons
  doc/conf.py
Labels: area: documentation

#5404 Doc: Update Debian as Service Vm
  doc/tutorials/running_deb_as_serv_vm.rst
Labels: area: documentation

#5471 doc: improve GSG navigation
  doc/getting-started/building-from-source.rst
  doc/getting-started/rt_industry_ubuntu.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#5467 ACRN:DM:xHCI Fix the unsigned integer conversion bug
  devicemodel/hw/platform/usb_pmapper.c
Labels: CI: Tracked On Pass, release_2.3

#5469 acrn-config: removed_nested returns None instead return Error
  misc/acrn-config/board_config/vbar_base_h.py
Labels: CI: Tracked On Pass, release_2.3

#5460 acrn-config: remove PSRAM_PASSTHROUGH_PRE_RTVM in PSRAM config
  misc/acrn-config/acpi_gen/asl_gen.py
  misc/acrn-config/hv_config/board_defconfig.py
  misc/acrn-config/hv_config/hv_item.py
  misc/acrn-config/library/hv_cfg_lib.py
  misc/acrn-config/scenario_config/scenario_cfg_gen.py
  misc/vm_configs/xmls/config-xmls/generic/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/template/HV.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass

#5464 ACRN:DM:xHCI Fix the unsigned integer conversion bug
  devicemodel/hw/platform/usb_pmapper.c
Labels: CI: Tracked On Pass

#5455 acrn-config: removed_nested returns None instead return Error
  misc/acrn-config/board_config/vbar_base_h.py
Labels: CI: Tracked On Pass

#5466 DM: gvt: Identical mapping for GPU DSM
  devicemodel/core/sw_load_common.c
  devicemodel/hw/pci/passthrough.c
  devicemodel/include/sw_load.h
Labels: CI: Tracked On Pass, release_2.3

#5465 DM: gvt: Identical mapping for GPU DSM
  devicemodel/core/sw_load_common.c
  devicemodel/hw/pci/passthrough.c
  devicemodel/include/sw_load.h
Labels: CI: Tracked On Pass

#5476 doc: add sphinx-generated index to leftnav
  doc/genindex.rst
  doc/index.rst
Labels: area: documentation

#5472 doc: add extension to create files and raw links
  doc/conf.py
  doc/developer-guides/contribute_guidelines.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/hld/virtio-net.rst
  doc/extensions/eager_only.py
  doc/extensions/link_roles.py
  doc/index.rst
  doc/introduction/index.rst
  doc/tutorials/setup_openstack_libvirt.rst
  misc/acrn-manager/README.rst
Labels: area: documentation

#5474 hv: remove vm_lock in hcall_destroy_vm()
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass, release_2.3

#5453 dm: virtio: check for paddr_guest2host return value
  devicemodel/hw/pci/virtio/virtio.c
Labels: CI: Tracked On Pass

#5475 hv: remove vm_lock in hcall_destroy_vm()
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass

#5481 acrn-config: insert vbdf in hex format and vuart vbdf logic
  misc/acrn-config/scenario_config/pci_dev_c.py
Labels: CI: Tracked On Pass, release_2.3

#5483 acrn-config: insert legacy vuart0 base by its enablement status
  misc/acrn-config/scenario_config/vm_configurations_c.py
Labels: CI: Tracked On Pass, release_2.3

#5484 acrn-config: insert legacy vuart0 base by its enablement status
  misc/acrn-config/scenario_config/vm_configurations_c.py
Labels: CI: Tracked On Pass

#5485 acrn-config: insert vbdf in hex format and vuart vbdf logic
  misc/acrn-config/scenario_config/pci_dev_c.py
Labels: CI: Tracked On Pass

#5493 TGL: Fix sos can't boot with 6 pci-vuarts
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass, release_2.3

#5486 doc: update ivshmem feature HLD
  doc/developer-guides/hld/ivshmem-hld.rst
Labels: area: documentation

#5496 Fix: HV: VM OS failed to assign new address to pci-vuart BARs
  hypervisor/dm/vpci/vmcs9900.c
Labels: CI: Tracked On Pass, release_2.3

#5497 TGL: Fix sos can't boot with 6 pci-vuarts
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass

#5499 HV: hide CONFIG_SERIAL_PIO_BASE IO port for SOS
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass, CI: no coding guideline, release_2.3

#5479 hv: pm: avoid duplicate shutdowns on RTVM
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: CI: Tracked On Pass

#5503 Fix: do not need to hide IO 0x3f8 for SOS on EHL
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass, release_2.3

#5502 acrn-config: modify the cmd args in pre-launched rt xml
  misc/vm_configs/xmls/config-xmls/cfl-k700-i7/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid_rt.xml
Labels: CI: Tracked On Pass, release_2.3

#5500 hv: bugfix for hv-emulated device de-init
  hypervisor/common/hypercall.c
  hypervisor/dm/vpci/ivshmem.c
  hypervisor/dm/vpci/vpci.c
Labels: CI: Tracked On Pass

#5505 hv: pci: Hide PCI bridge 00:1c.0 from SOS
  hypervisor/arch/x86/configs/pci_dev.c
Labels: CI: Tracked On Pass, release_2.3

#5509 hv: bugfix for hv-emulated device de-init -v2.3
  hypervisor/common/hypercall.c
  hypervisor/dm/vpci/ivshmem.c
  hypervisor/dm/vpci/vpci.c
Labels: CI: Tracked On Pass, release_2.3

#5516 hv: fix nr_bars for hv-land ivshmem devices
  hypervisor/dm/vpci/ivshmem.c
Labels: CI: Tracked On Pass, release_2.3

#5446 dm: update acrn-dm built-in list and description of args
  devicemodel/core/main.c
Labels: CI: Tracked On Pass

#5449 dm: mei: vmei_proc_tx check buffer length before accessing the memory
  devicemodel/hw/pci/virtio/virtio_mei.c
Labels: CI: Tracked On Pass

#5513 acrn-config: modify the cmd args in pre-launched rt xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
Labels: CI: Tracked On Pass, release_2.3

#5519 dm: virtio: check for paddr_guest2host return value-v2.3 branch
  devicemodel/hw/pci/virtio/virtio.c
Labels: CI: Tracked On Pass, release_2.3

#5520 DM: Fix the security issues in the DM.
  devicemodel/core/pm_vuart.c
  devicemodel/hw/pci/ahci.c
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass, release_2.3

#5523 DM: Add the return value check in case cause Null pointer exception
  devicemodel/core/pm_vuart.c
  devicemodel/hw/pci/ahci.c
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass

#5504 Doc: update document to remove CL Service VM dependence
  doc/getting-started/rt_industry_ubuntu.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
  doc/tutorials/vuart_configuration.rst
  misc/packaging/README.rst
Labels: area: documentation

#5527 doc: update the steps of enable ivshmem
  doc/tutorials/enable_ivshmem.rst
Labels: area: documentation

#5477 doc: fix breathe config for C vs CPP
  doc/.known-issues/doc/dupdecl.conf
  doc/conf.py
Labels: area: documentation

#5526 doc: update the steps of enable ivshmem
  doc/tutorials/enable_ivshmem.rst
Labels: area: documentation

#5529 doc: correct 'gvtg' parameters for acrn-dm
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#5533 doc: correct typo (missing space)
  doc/tutorials/running_ubun_as_user_vm.rst
Labels: area: documentation, no Signed-off-by

#5534 Disable AC for split-lock by default
  hypervisor/arch/x86/Kconfig
Labels: CI: Tracked On Pass, release_2.3

#5521 hv: fix nr_bars for hv-land ivshmem devices
  hypervisor/dm/vpci/ivshmem.c
Labels: CI: Tracked On Pass

#5525 acrn-config: update default pci_dev.c
  misc/vm_configs/scenarios/hybrid/ehl-crb-b/pci_dev.c
  misc/vm_configs/scenarios/hybrid/nuc7i7dnb/pci_dev.c
  misc/vm_configs/scenarios/hybrid/whl-ipc-i5/pci_dev.c
  misc/vm_configs/scenarios/hybrid/whl-ipc-i7/pci_dev.c
  misc/vm_configs/scenarios/hybrid_rt/cfl-k700-i7/pci_dev.c
  misc/vm_configs/scenarios/hybrid_rt/ehl-crb-b/pci_dev.c
  misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i5/pci_dev.c
  misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i7/pci_dev.c
  misc/vm_configs/scenarios/industry/cfl-k700-i7/pci_dev.c
  misc/vm_configs/scenarios/industry/ehl-crb-b/pci_dev.c
  misc/vm_configs/scenarios/industry/nuc7i7dnb/pci_dev.c
  misc/vm_configs/scenarios/industry/whl-ipc-i5/pci_dev.c
  misc/vm_configs/scenarios/industry/whl-ipc-i7/pci_dev.c
Labels: CI: Tracked On Pass

#5531 acrn-config: refine the ivshmem for pre-launched vm
  misc/acrn-config/board_config/vbar_base_h.py
  misc/acrn-config/scenario_config/pci_dev_c.py
Labels: CI: Tracked On Pass

#5539 misc: life_mngr: prevent log flooding after SOS socket is closed
  misc/life_mngr/life_mngr.c
Labels: CI: Tracked On Pass, release_2.3

#5546 dm: virtio_console: read only when the virtqueue is ready.
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass, release_2.3

#5550 acrn-config: update default pci_dev.c
  misc/vm_configs/scenarios/hybrid/ehl-crb-b/pci_dev.c
  misc/vm_configs/scenarios/hybrid/nuc7i7dnb/pci_dev.c
  misc/vm_configs/scenarios/hybrid/whl-ipc-i5/pci_dev.c
  misc/vm_configs/scenarios/hybrid/whl-ipc-i7/pci_dev.c
  misc/vm_configs/scenarios/hybrid_rt/cfl-k700-i7/pci_dev.c
  misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i5/pci_dev.c
  misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i7/pci_dev.c
  misc/vm_configs/scenarios/industry/cfl-k700-i7/pci_dev.c
  misc/vm_configs/scenarios/industry/ehl-crb-b/pci_dev.c
  misc/vm_configs/scenarios/industry/nuc7i7dnb/pci_dev.c
  misc/vm_configs/scenarios/industry/whl-ipc-i5/pci_dev.c
  misc/vm_configs/scenarios/industry/whl-ipc-i7/pci_dev.c
Labels: CI: Tracked On Pass, release_2.3

#5547 hv: vmexit: refine xsetbv_vmexit_handler API
  hypervisor/arch/x86/guest/virtual_cr.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/arch/x86/seed/seed.c
Labels: CI: Tracked On Pass

#5540 misc: life_mngr: prevent log flooding after SOS socket is closed
  misc/life_mngr/life_mngr.c
Labels: CI: Tracked On Pass

#5538 misc: add the s5_trigger.sh script
  misc/life_mngr/s5_trigger.sh
Labels: CI: Tracked On Pass, release_2.3

#5552 misc: add the s5_trigger.sh script
  misc/life_mngr/s5_trigger.sh
Labels: CI: Tracked On Pass

#5557 hv: hypercall: hot fix call assign/deassign mmiodev could crash hv
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass, release_2.3

#5545 dm: virtio_console: read only when the virtqueue is ready.
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass

#5556 hv: coding style clean-up related to Boolean
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/irq.c
  hypervisor/arch/x86/rdt.c
  hypervisor/common/hypercall.c
  hypervisor/debug/dbg_cmd.c
  hypervisor/dm/vpci/vsriov.c
Labels: CI: Tracked On Pass

#5554 misc: adjust compiler options for gcc-10
  misc/hv_prebuild/vm_cfg_checks.c
  misc/tools/acrn-crashlog/acrnprobe/Makefile
Labels: CI: Tracked On Pass
