Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-05, with the labels that each got.

#4754 doc: update for cpu-sharing and vuart
  doc/tutorials/cpu_sharing.rst
  doc/tutorials/images/cpu_sharing_framework.png
Labels: area: documentation

#4764 doc: fix misspellings
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#4731 gpa2hva: add INVAVLID_HPA return value check
  hypervisor/arch/x86/configs/vacpi.c
  hypervisor/arch/x86/guest/guest_memory.c
  hypervisor/common/vm_load.c
Labels: Automerge: Pass, CI: Tracked On Pass, config_tool_modified

#4718 acrn-config: update tgl-rvp board information
  misc/acrn-config/xmls/board-xmls/tgl-rvp.xml
Labels: CI: Tracked On Pass

#4750 Ptdev
  hypervisor/arch/x86/guest/assign.c
  hypervisor/debug/shell.c
  hypervisor/dm/vpci/vmsi.c
  hypervisor/dm/vpci/vmsix.c
  hypervisor/include/arch/x86/guest/assign.h
  hypervisor/include/common/ptdev.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4766 HV: Config Splitlock Detection to be disable
  hypervisor/arch/x86/Kconfig
  hypervisor/arch/x86/cpu.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4774 doc: add note to the Celadon User VM tutorial
  doc/tutorials/using_celadon_as_uos.rst
Labels: area: documentation

#4767 doc: update Zephyr document to indicate a serial port is needed
  doc/tutorials/using_zephyr_as_uos.rst
Labels: area: documentation

#4776 doc: edit notes on serial connection need
  doc/tutorials/using_celadon_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
Labels: area: documentation

#4773 doc: update security advisory for 1.6.1 release
  doc/asa.rst
Labels: area: documentation

#4775 doc: update hvlog kernel parameter descriptions
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#4769 Doc: Initial file: Config ACRN using OpenStack & libvert
  doc/develop.rst
  doc/tutorials/setup_openstack_libvert.rst
  doc/tutorials/using_ubuntu_as_sos.rst
Labels: area: documentation

#4778 hv: Offload syncing PIR to vIRR to processor hardware
  hypervisor/arch/x86/guest/vlapic.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4783 doc: cpu-sharing doc update
  doc/tutorials/cpu_sharing.rst
  doc/tutorials/images/cpu_sharing_affinity.png
Labels: area: documentation

#4780 doc: update libvirt guide
  doc/develop.rst
  doc/tutorials/setup_openstack_libvert.rst
  doc/tutorials/setup_openstack_libvirt.rst
Labels: area: documentation

#4784 doc: update industry getting started guide to v1.6.1
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#4787 doc: update GSG for ACRN V1.6.1.
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4788 doc: update build ACRN doc
  doc/getting-started/building-from-source.rst
  doc/tutorials/building_acrn_in_docker.rst
Labels: area: documentation

#4789 Doc: releasenotes_1.6.1
  doc/release_notes/release_notes_1.6.1.rst
Labels: area: documentation

#4785 doc: update release_1.6 with master docs
  doc/asa.rst
  doc/develop.rst
  doc/getting-started/rt_industry.rst
  doc/tutorials/cpu_sharing.rst
  doc/tutorials/images/cpu_sharing_affinity.png
  doc/tutorials/setup_openstack_libvirt.rst
  doc/tutorials/using_celadon_as_uos.rst
  doc/tutorials/using_ubuntu_as_sos.rst
  doc/tutorials/using_zephyr_as_uos.rst
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#4793 doc: add 1.6.1 docs version menu choice
  doc/conf.py
Labels: area: documentation

#4792 doc: edit 1.6.1 release notes
  doc/release_notes/release_notes_1.6.1.rst
Labels: area: documentation

#4794 doc: update 1.6.1 docs from master
  doc/getting-started/building-from-source.rst
  doc/release_notes/release_notes_1.6.1.rst
  doc/tutorials/building_acrn_in_docker.rst
  doc/tutorials/cpu_sharing.rst
  doc/tutorials/images/logical_partition_scenario_on_nuc.png
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4795 doc: fix malformed acrn-issue references
  doc/release_notes/release_notes_1.6.1.rst
Labels: area: documentation

#4796 doc: fix malformed acrn-issue role in release notes
  doc/release_notes/release_notes_1.6.1.rst
Labels: area: documentation

#4806 doc: Update acrn edk2 download path
  doc/tutorials/waag-secure-boot.rst
Labels: area: documentation, no Signed-off-by

#4807 doc: remove duplicate 1.6 version menu choice
  doc/conf.py
Labels: area: documentation

#4805 acrn-dm: add some logs for vm state transition
  devicemodel/core/main.c
  devicemodel/core/monitor.c
  devicemodel/core/pm.c
  devicemodel/core/vmmapi.c
  devicemodel/hw/pci/wdt_i6300esb.c
  devicemodel/include/vmm.h
  devicemodel/include/vmmapi.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4804 hv:fix rtvm hang with maxcpus=0/1 in bootargs
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4819 Doc: Supported hardware update
  doc/reference/hardware.rst
Labels: area: documentation

#4782 doc: update cpu affinity related docs
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/tutorials/cpu_sharing.rst
Labels: area: documentation

#4821 Doc: Grammatical edits to CPU Virtualization doc.
  doc/developer-guides/hld/hv-cpu-virt.rst
Labels: area: documentation

#4815 acrn-config: generate pci_dev.c file for logical partition
  misc/acrn-config/scenario_config/scenario_cfg_gen.py
Labels: CI: Tracked On Pass

#4781 doc:add tutorial about enabling GVT-d
  doc/develop.rst
  doc/release_notes/release_notes_0.5.rst
  doc/release_notes/release_notes_1.0.rst
  doc/static/downloads/Integrate-IntelGopDriver-into-OVMF.patch
  doc/static/downloads/Use-the-default-vbt-released-with-GOP-driver.patch
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/skl-nuc.rst
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4818 hv: debug: reboot directly when issue 'reboot' shell cmd
  hypervisor/debug/shell.c
Labels: CI: Tracked On Pass

#4823 hv:cleanup vcpu state
  doc/developer-guides/hld/hv-cpu-virt.rst
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/common/hv_main.c
  hypervisor/common/hypercall.c
  hypervisor/debug/shell.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#4816 hv: pause all other vCPUs in same VM when do wbinvd emulation
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#4829 hv: ptirq : fix a bug in ptirq_release_entry
  hypervisor/common/ptdev.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#4825 doc: Add visual OpenStack setup instructions
  doc/tutorials/0001-devstack-installation-for-acrn.patch
  doc/tutorials/images/OpenStack-01-login.png
  doc/tutorials/images/OpenStack-02-topology.png
  doc/tutorials/images/OpenStack-03-create-router.png
  doc/tutorials/images/OpenStack-03a-create-router.png
  doc/tutorials/images/OpenStack-03b-created-router.png
  doc/tutorials/images/OpenStack-04a-add-interface.png
  doc/tutorials/images/OpenStack-04b-add-interface.png
  doc/tutorials/images/OpenStack-04c-add-interface.png
  doc/tutorials/images/OpenStack-05-topology.png
  doc/tutorials/images/OpenStack-06-create-image.png
  doc/tutorials/images/OpenStack-06a-create-image-browse.png
  doc/tutorials/images/OpenStack-06b-create-image-select.png
  doc/tutorials/images/OpenStack-06e-create-image.png
  doc/tutorials/images/OpenStack-07a-create-flavor.png
  doc/tutorials/images/OpenStack-07b-flavor-created.png
  doc/tutorials/images/OpenStack-08-security-group.png
  doc/tutorials/images/OpenStack-08a-create-security-group.png
  doc/tutorials/images/OpenStack-08b-add-rule.png
  doc/tutorials/images/OpenStack-08c-add-SSH-rule.png
  doc/tutorials/images/OpenStack-08d-add-All-ICMP-rule.png
  doc/tutorials/images/OpenStack-09a-create-key-pair.png
  doc/tutorials/images/OpenStack-09c-key-pair-private-key.png
  doc/tutorials/images/OpenStack-10a-launch-instance-name.png
  doc/tutorials/images/OpenStack-10b-no-new-vol-select-allocated.png
  doc/tutorials/images/OpenStack-10c-select-flavor.png
  doc/tutorials/images/OpenStack-10d-flavor-selected.png
  doc/tutorials/images/OpenStack-10d-only-acrn-security-group.png
  doc/tutorials/images/OpenStack-10e-select-network.png
  doc/tutorials/images/OpenStack-10f-select-security-group.png
  doc/tutorials/images/OpenStack-10g-show-keypair-launch.png
  doc/tutorials/images/OpenStack-11-wait-for-running-create-snapshot.png
  doc/tutorials/images/OpenStack-11a-manage-floating-ip.png
  doc/tutorials/images/OpenStack-11b-allocate-floating-ip.png
  doc/tutorials/images/OpenStack-11c-allocate-floating-ip-success-associate.png
  doc/tutorials/images/OpenStack-12b-running-topology-instance.png
  doc/tutorials/images/OpenStack-12d-compute-hypervisor.png
  doc/tutorials/setup_openstack_libvirt.rst
Labels: area: documentation

#4836 Doc: Grammatical edits to GVT-d docs.
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4837 doc: fix rst-columns display
  doc/contribute.rst
  doc/develop.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/hld/index.rst
  doc/release_notes/index.rst
  doc/static/acrn-custom.css
Labels: area: documentation

#4830 HV: explicitly init pci device lock
  hypervisor/debug/logmsg.c
  hypervisor/hw/pci.c
Labels: CI: Tracked On Pass

#4839 dm: Do not link to zlib
  devicemodel/Makefile
Labels: CI: Tracked On Pass

#4851 HV: fix bug to clear guest flags after it not used
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass

#4850 HV: Fix MP Init sequence hang by adding a delay
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/lapic.c
  hypervisor/include/arch/x86/lapic.h
Labels: CI: Tracked On Pass

#4841 dm: bzimage: dynamically adapt to ramdisk size
  devicemodel/core/sw_load_bzimage.c
Labels: CI: Tracked On Pass

#4852 CODEOWNERS: Update the maintainer of misc folder
  CODEOWNERS
Labels: CI: Tracked On Pass

#4847 dm: acpi: validate minimal length of PSDS
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/include/acpi.h
Labels: CI: Tracked On Pass

#4854 Support shared memory based inter-vm communication for ACRN post-launched VMs
  devicemodel/Makefile
  devicemodel/hw/pci/ivshmem.c
Labels: CI: Tracked On Pass

#4843 Modify Makefile to add acrn.bin after install
  hypervisor/Makefile
Labels: CI: Tracked On Pass

#4737 acrn-dm: fix corner cases in acrn_parse_cpu_affinity()
  devicemodel/core/vmmapi.c
Labels: CI: Tracked On Pass

#4849 doc: Remove zlib from the list of build dependencies
  doc/getting-started/building-from-source.rst
Labels: area: documentation
