Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-03, with the labels that each got.

#4432 dm: remove vdev_update_bar_map callback for PCIe device
  devicemodel/hw/pci/core.c
  devicemodel/hw/pci/passthrough.c
  devicemodel/include/pci_core.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4440 dm: avoid clear guest memory content if guest is RTVM
  devicemodel/core/vmmapi.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4444 acrn-config: Fix vbar address generated by the offline tool
  misc/acrn-config/board_config/pci_devices_h.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4452 acrn-config: correct console argument for logical partition scenario
  misc/acrn-config/scenario_config/vm_configurations_h.py
Labels: Automerge: Pass, CI: Tracked On Pass

#3868 doc: update hld for device passthrough
  doc/acrn.doxyfile
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/images/passthru-image22.png
  doc/developer-guides/hld/images/passthru-image72.png
  hypervisor/include/common/ptdev.h
Labels: CI: Tracked On Pass, area: documentation

#4454 hv: refine pci_read_cap and pci_read_ext_cap
  hypervisor/hw/pci.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4456 hv: minor fixes in init_paging()
  hypervisor/arch/x86/mmu.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4462 doc: fix a missing argument in the function description
  doc/developer-guides/hld/hv-dev-passthrough.rst
  hypervisor/include/common/ptdev.h
Labels: CI: Tracked On Pass, CI: pending approve

#4455 hv: pci: add some pre-assumption for PCIe ECAM
  hypervisor/arch/x86/cpu.c
  hypervisor/hw/pci.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4461 dm: don't deassign pass through PCIe device in DM
  devicemodel/core/main.c
  devicemodel/hw/pci/passthrough.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4464 HV: sanitize config file for whl-ipc-i5
  hypervisor/arch/x86/configs/whl-ipc-i5.config
  hypervisor/arch/x86/configs/whl-ipc-i5/misc_cfg.h
  hypervisor/arch/x86/configs/whl-ipc-i5/platform_acpi_info.h
Labels: Automerge: Pass, CI: Tracked On Pass, config_tool_modified

#4466 acrn-config: Generate target xml and board.c file with MBA RDT resource
  misc/acrn-config/board_config/board_c.py
  misc/acrn-config/target/clos.py
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4448 hv: Variable/macro renaming for handling PT dev interrupts using IOAPIC/PIC
  hypervisor/arch/x86/guest/assign.c
  hypervisor/debug/shell.c
  hypervisor/dm/vioapic.c
  hypervisor/dm/vpic.c
  hypervisor/include/arch/x86/guest/assign.h
  hypervisor/include/common/ptdev.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4467 hv: vpci: add a global CFG header configuration access handler
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpci/vpci_priv.h
  hypervisor/include/hw/pci.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4473 hv: mmu: minor fix about add_pte
  hypervisor/arch/x86/pagetable.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4471 acrn-config: remove redundant sos bootargs from vm config
  misc/acrn-config/scenario_config/vm_configurations_h.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4475 hv: Refine code for API reduction
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vdev.c
  hypervisor/dm/vpci/vhostbridge.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpci/vpci_bridge.c
  hypervisor/dm/vpci/vpci_priv.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4476 hv: vpci: add _v prefix for some function name
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vdev.c
  hypervisor/dm/vpci/vhostbridge.c
  hypervisor/dm/vpci/vmsi.c
  hypervisor/dm/vpci/vmsix.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpci/vpci_bridge.c
  hypervisor/dm/vpci/vpci_priv.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4465 hv: add static check for CONFIG_HV_RAM_START and CONFIG_HV_RAM_SIZE
  hypervisor/pre_build/static_checks.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4480 hv: vpci: pass through stolen memory and opregion memory for GVT-D
  devicemodel/hw/pci/passthrough.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/hw/pci.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4478 hv:rename several variables and api for ioapic
  hypervisor/arch/x86/ioapic.c
  hypervisor/debug/shell.c
  hypervisor/include/arch/x86/ioapic.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4479 support S5 by RTVM
  devicemodel/core/pm_vuart.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4484 doc: add site under construction page header
  doc/static/acrn-custom.css
Labels: area: documentation

#4481 misc:life_mngr: support S5 triggered by RTVM
  misc/life_mngr/life_mngr.c
Labels: CI: Tracked On Pass, CI: pending approve

#4483 hv: pci: rename CFG read/write function for PCI-compatible Configurat…
  hypervisor/debug/uart16550.c
  hypervisor/hw/pci.c
  hypervisor/include/debug/uart16550.h
  hypervisor/release/uart16550.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4460 hv: refine read/write configuration APIs for vmsi/vmsix
  hypervisor/dm/vpci/vmsi.c
  hypervisor/dm/vpci/vmsix.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpci/vpci_priv.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4486 hv:Rename two VM states
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/common/hypercall.c
  hypervisor/debug/shell.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4491 OVMF release v1.6
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#4493 acrn-config: add missed include in pci_dev.c for logical partition
  misc/acrn-config/scenario_config/pci_dev_c.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4495 acrn-config: fix missing passthru parameter for launch config
  misc/acrn-config/launch_config/launch_cfg_gen.py
  misc/acrn-config/library/launch_cfg_lib.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4500 doc: Update build celadon instruction link
  doc/tutorials/using_celadon_as_uos.rst
Labels: area: documentation

#4501 hv: unmap SR-IOV VF MMIO when the VF physical device is disabled
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpci/vpci_priv.h
  hypervisor/dm/vpci/vsriov.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4482 hv: introduce SR-IOV feature for ACRN
  doc/develop.rst
  doc/tutorials/images/sriov-image1.png
  doc/tutorials/images/sriov-image10.png
  doc/tutorials/images/sriov-image11.png
  doc/tutorials/images/sriov-image12.png
  doc/tutorials/images/sriov-image2.png
  doc/tutorials/images/sriov-image3.png
  doc/tutorials/images/sriov-image4.png
  doc/tutorials/images/sriov-image5.png
  doc/tutorials/images/sriov-image6.png
  doc/tutorials/images/sriov-image7.png
  doc/tutorials/images/sriov-image8.png
  doc/tutorials/images/sriov-image9.png
  doc/tutorials/sriov_virtualization.rst
Labels: area: documentation

#4511 hv: change GPU passthru translation mode to TT_PASSTHROUGH
  hypervisor/arch/x86/vtd.c
Labels: CI: Tracked On Pass, CI: pending approve, Coding Guidelines: PASS

#4507 doc: fix docs with broken links
  doc/developer-guides/c_coding_guidelines.rst
  doc/developer-guides/contribute_guidelines.rst
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/l1tf.rst
  doc/tutorials/acrn_ootb.rst
  doc/tutorials/agl-vms.rst
  doc/tutorials/increase-uos-disk-size.rst
  doc/tutorials/kbl-nuc-sdc.rst
  doc/tutorials/realtime_performance_tuning.rst
  doc/tutorials/trustyACRN.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_up2.rst
  doc/tutorials/using_ubuntu_as_sos.rst
  misc/acrn-manager/README.rst
Labels: area: documentation

#4468 doc: update waag GSG according to the latest method
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4516 hv: a few fixes for multiboot2 boot
  hypervisor/Makefile
  hypervisor/arch/x86/Kconfig
  hypervisor/arch/x86/boot/cpu_primary.S
  hypervisor/boot/guest/vboot_wrapper.c
  hypervisor/boot/multiboot.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4515 Doc: add space at the end of efibootmgr bootloader
  doc/getting-started/rt_industry.rst
  doc/tutorials/using_ubuntu_as_sos.rst
Labels: area: documentation

#4527 hv: cpuid: remove cpuid()
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/guest/ucode.c
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/timer.c
  hypervisor/include/arch/x86/cpuid.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4521 efi-stub: fix wrong bootloader name issue
  misc/efi-stub/boot.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4525 doc: fix docs with windows line endings
  doc/tutorials/running_deb_as_serv_vm.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/vuart_configuration.rst
Labels: area: documentation

#4523 acrn-config: create temporary scenario file folder if it doesn't exist
  misc/acrn-config/config_app/views.py
Labels: CI: Tracked On Pass

#4539 doc: update security advisory for v1.6 release
  doc/asa.rst
Labels: area: documentation

#4513 Doc: add instructions for using Xenomai as UOS
  doc/develop.rst
  doc/tutorials/using_xenomai_as_uos.rst
Labels: area: documentation

#4528 doc: introduce Split Device Model feature for ACRN
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/images/split-dm-image1.png
  doc/developer-guides/hld/images/split-dm-image2.png
  doc/developer-guides/hld/images/split-dm-image3.png
  doc/developer-guides/hld/images/split-dm-image4.png
  doc/developer-guides/hld/split-dm.rst
Labels: area: documentation

#4537 doc: Add MBA documentation and update doc for CAT
  doc/develop.rst
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/hld/hv-partitionmode.rst
  doc/developer-guides/hld/hv-rdt.rst
  doc/developer-guides/hld/images/cat-objective.png
  doc/developer-guides/hld/images/cat_mba_software_flow.png
  doc/developer-guides/hld/images/mba_data_structures.png
  doc/developer-guides/hld/images/mba_objective.png
  doc/developer-guides/hld/images/no_mba_objective.png
  doc/getting-started/rt_industry.rst
  doc/glossary.rst
  doc/release_notes/release_notes_0.8.rst
  doc/release_notes/release_notes_1.0.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/images/menuconfig-rdt.png
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/rtvm_workload_design_guideline.rst
  doc/tutorials/using_cat_on_up2.rst
Labels: area: documentation

#4536 dm: correct PCI configures of igd-lpc
  devicemodel/hw/pci/lpc.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4556 hv: vlapic: minor fix about dereference vcpu from vlapic
  hypervisor/arch/x86/guest/vlapic.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4548 doc: vt-d: update the description of snoop control
  doc/developer-guides/hld/hv-vt-d.rst
Labels: area: documentation

#4562 Minor edits to VT-d page.
  doc/developer-guides/hld/hv-vt-d.rst
Labels: area: documentation
