Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-08, with the labels that each got.

#5121 HV: Make: remove sdc scenario build support
  Makefile
  hypervisor/arch/x86/Kconfig
Labels: CI: Tracked On Pass, release_2.1

#5126 HV: correct RO mask of MSI cap structure
  hypervisor/dm/vpci/vmsi.c
Labels: CI: Tracked On Pass

#5124 Doc: Getting Started Guide Update for hybrid mode
  doc/tutorials/using_hybrid_mode_on_nuc.rst
Labels: area: documentation

#5123 [release2_1] [whl] fix stability problem: failed to boot up SOS in cold boot
  hypervisor/common/schedule.c
Labels: CI: Tracked On Pass, release_2.1

#5130 [Release 2.1]Makefile: fix issue on make menuconfig
  hypervisor/scripts/makefile/kconfig.mk
Labels: CI: Tracked On Pass, release_2.1

#5134 doc: update vm configuration related path
  doc/getting-started/building-from-source.rst
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#5131 Doc:Update Logical Partition Getting Started Guide
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#5127 HV: correct RO mask of MSI cap structure
  hypervisor/dm/vpci/vmsi.c
Labels: CI: Tracked On Pass, release_2.0

#5128 hv:refine vm & vcpu lock
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/io_req.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/dm/io_req.h
Labels: CI: Tracked On Pass

#5135 Doc: Update Using GRUB to boot ACRN
  doc/tutorials/using_grub.rst
Labels: area: documentation

#5140 doc: fix references to misc/vm_configs folder
  doc/developer-guides/hld/vuart-virt-hld.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/debug.rst
  doc/tutorials/vuart_configuration.rst
Labels: area: documentation

#5141 doc: fix more references to hypervisor folders
  doc/introduction/index.rst
  doc/tutorials/docbuild.rst
Labels: area: documentation

#5142 doc: draft v2.1 release notes
  doc/release_notes/release_notes_2.1.rst
Labels: area: documentation

#5143 doc: remove invalid kernel parameters for gvt-g
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#5136 Doc: update user guide for Pre-Launched RT mode
  doc/tutorials/pre-launched-rt.rst
Labels: area: documentation

#5145 doc: use kbd consistently and fix misspellings
  doc/developer-guides/hld/hv-console.rst
  doc/developer-guides/hld/ivshmem-hld.rst
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#5158 Doc:release_notes_2.1 update
  doc/release_notes/release_notes_2.1.rst
Labels: area: documentation

#5159 doc: add known issue:5157 for building-from-source.rst
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#5156 doc: update security advisory for v2.1 release
  doc/asa.rst
Labels: area: documentation

#5160 doc: fix mismatched ACRN version
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#5161 doc: update release notes about LAPIC timer in OVMF
  doc/release_notes/release_notes_2.1.rst
Labels: area: documentation

#5162 doc: update release_2.1 with new docs
  doc/asa.rst
  doc/develop.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hv-console.rst
  doc/developer-guides/hld/hv-rdt.rst
  doc/developer-guides/hld/ivshmem-hld.rst
  doc/developer-guides/hld/mmio-dev-passthrough.rst
  doc/developer-guides/hld/virtio-net.rst
  doc/developer-guides/hld/vuart-virt-hld.rst
  doc/getting-started/building-from-source.rst
  doc/introduction/index.rst
  doc/release_notes/release_notes_2.1.rst
  doc/scripts/filter-known-issues.py
  doc/scripts/genrest.py
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/debug.rst
  doc/tutorials/docbuild.rst
  doc/tutorials/images/pre_launched_rt.png
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/rtvm_performance_tips.rst
  doc/tutorials/using_grub.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/vuart_configuration.rst
  doc/user-guides/acrn-shell.rst
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#5163 doc: add v2.1 to doc version menu
  doc/conf.py
Labels: area: documentation

#5147 Makefile: modify the realpath to abspath function
  hypervisor/scripts/makefile/cfg_update.mk
Labels: CI: Tracked On Pass

#5139 hv: enlarge vuart number from 2 to 4 for each vm
  hypervisor/dm/vuart.c
  hypervisor/include/arch/x86/guest/vmx_io.h
  hypervisor/include/arch/x86/vm_config.h
Labels: CI: Tracked On Pass, release_2.1

#5167 doc: use consistent month names in release notes
  doc/release_notes/release_notes_1.0.2.rst
  doc/release_notes/release_notes_1.1.rst
  doc/release_notes/release_notes_2.0.rst
  doc/release_notes/release_notes_2.1.rst
Labels: area: documentation

#5166 hv: fix stos and stosq asm instruction emulation error
  hypervisor/arch/x86/guest/instr_emul.c
Labels: CI: Tracked On Pass, release_2.0

#5171 DM: PT: Add "d3hot_reset" sub-parameter for passthrough device
  devicemodel/hw/pci/passthrough.c
Labels: CI: Tracked On Pass, release_2.0

#5173 DM: xHCI: Extend the max Native Bus number
  devicemodel/include/usb_core.h
Labels: CI: Tracked On Pass

#5179 acrn-config: set CONFIG_MAX_MSIX_TABLE_NUM to 16 in the qemu sdc xml
  misc/vm_configs/xmls/config-xmls/qemu/sdc.xml
Labels: CI: Tracked On Pass

#5175 [release 2.1]Makefile: modify the realpath to abspath function
  hypervisor/scripts/makefile/cfg_update.mk
Labels: CI: Tracked On Pass, release_2.1

#5180 HV: comment SOS_VM as VMx in vm_configurations.h
  misc/acrn-config/scenario_config/vm_configurations_h.py
  misc/vm_configs/scenarios/hybrid/vm_configurations.h
  misc/vm_configs/scenarios/hybrid_rt/vm_configurations.h
  misc/vm_configs/scenarios/industry/vm_configurations.h
Labels: CI: Tracked On Pass

#5182 hv:cpuid:refine cpuid_subleaf interface
  hypervisor/include/arch/x86/cpuid.h
Labels: CI: Tracked On Pass

#5187 doc: update coding guidelines
  doc/developer-guides/asm_coding_guidelines.rst
  doc/developer-guides/c_coding_guidelines.rst
Labels: area: documentation

#5177 doc: update document for "--acpidev_pt" and "--mmiodev_pt" features
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#5189 acrn-config: update TGL platform and SOS RAM size
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/industry.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/sdc.xml
Labels: Automerge: Pass, CI: Tracked On Pass

#5191 hv: Fix thread status mess if wake_thread() happens in transition stage
  hypervisor/common/schedule.c
Labels: CI: Tracked On Pass

#5195 doc: spelling and grammar fixes
  doc/developer-guides/GVT-g-porting.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/hld/hv-ioc-virt.rst
  doc/developer-guides/hld/hv-vm-management.rst
  doc/developer-guides/trusty.rst
  doc/getting-started/building-from-source.rst
  doc/try.rst
  doc/tutorials/agl-vms.rst
  doc/tutorials/building_uos_from_clearlinux.rst
  doc/tutorials/debug.rst
  doc/tutorials/kbl-nuc-sdc.rst
  doc/tutorials/open_vswitch.rst
  doc/tutorials/running_deb_as_serv_vm.rst
  doc/tutorials/using_grub.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_sbl_on_up2.rst
  doc/tutorials/using_ubuntu_as_sos.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_windows_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
  doc/tutorials/waag-secure-boot.rst
  doc/user-guides/acrn-dm-parameters.rst
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#5186 acrn-config: add hybrid_rt scenario xml config for TGL
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Labels: Automerge: Pass, CI: Tracked On Pass

#5170 misc:update packaging tool,add pre-check scripts/ add patch function …
  misc/packaging/acrn-hypervisor.postinst
  misc/packaging/acrn-hypervisor.preinst
  misc/packaging/install_uSoS.py
  misc/packaging/release.json
Labels: CI: Tracked On Pass

#5207 acrn-config: get the max number with integer list
  misc/acrn-config/target/misc.py
Labels: CI: Tracked On Pass, release_2.1

#5224 doc: remove the vboot module design example from sw_design_guidelines.rst
  doc/developer-guides/images/boot_information_parsing_module.png
  doc/developer-guides/sw_design_guidelines.rst
Labels: area: documentation

#5204 doc: add hybrid_rt to "What is ACRN" and Kconfig
  doc/introduction/images/ACRN-Hybrid-RT.png
  doc/introduction/images/ACRN-Hybrid.png
  doc/introduction/index.rst
Labels: area: documentation

#5228 doc: update docbuild instructions for 2.2 release
  doc/tutorials/docbuild.rst
Labels: area: documentation

#5198 acrn-config: Enable pre-launch VM sharing CPU with other VMs
  misc/acrn-config/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass

#5227 doc: update FAQ
  doc/faq.rst
Labels: area: documentation

#5217 hv: enhance help text for the scenario option in Kconfig
  hypervisor/arch/x86/Kconfig
Labels: CI: Tracked On Pass

#5213 acrn-config: add cfl-k700-i7 industry xmls
  misc/vm_configs/xmls/board-xmls/cfl-k700-i7.xml
  misc/vm_configs/xmls/config-xmls/cfl-k700-i7/industry.xml
Labels: CI: Tracked On Pass

#5223 refine hypercall
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vmcall.c
  hypervisor/common/hypercall.c
  hypervisor/debug/hypercall.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/common/hypercall.h
  hypervisor/include/public/acrn_hv_defs.h
  hypervisor/release/hypercall.c
Labels: CI: Tracked On Pass

#5219 misc/packaging: remove efi support
  misc/packaging/acrn-hypervisor.postinst
  misc/packaging/acrn-kernel.postinst
Labels: CI: Tracked On Pass

#5218 doc: remove UEFI/de-privilege boot mode from docs
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/hostbridge-virt-hld.rst
  doc/developer-guides/hld/hv-startup.rst
  doc/developer-guides/hld/ivshmem-hld.rst
  doc/developer-guides/sw_design_guidelines.rst
  doc/getting-started/building-from-source.rst
  doc/introduction/index.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/user-guides/hv-parameters.rst
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#5225 acrn-config: add maxcpus to sos kernel cmdline in hybrid scenario
  misc/acrn-config/board_config/misc_cfg_h.py
  misc/acrn-config/config_app/views.py
  misc/acrn-config/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass

#5230 acrn-config: add IVSHMEM config in hybrid_rt of tgl-rvp
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass
