Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-09, with the labels that each got.

#5209 hv: Add severity check against SOS hypercalls
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass

#5239 acrn-config: add hybrid_rt scenario xml config for ehl-crb-b
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
Labels: CI: Tracked On Pass

#5250 hv: passthru DHRD-ignored device
  hypervisor/arch/x86/vtd.c
Labels: CI: Tracked On Pass

#5251 acrn-config: make HV_RAM_SIZE include IVSHMEM_SHM_SIZE
  misc/acrn-config/hv_config/board_defconfig.py
  misc/acrn-config/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass

#5254 doc: update inclusive language terms in docs
  doc/developer-guides/contribute_guidelines.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/hld/hv-ioc-virt.rst
  doc/developer-guides/hld/ivshmem-hld.rst
  doc/developer-guides/hld/virtio-i2c.rst
  doc/developer-guides/modularity.rst
  doc/tutorials/acrn_on_qemu.rst
  doc/tutorials/docbuild.rst
  doc/tutorials/using_celadon_as_uos.rst
Labels: area: documentation

#5253 doc: remove docs referencing Clear Linux
  doc/develop.rst
  doc/getting-started/building-from-source.rst
  doc/reference/hardware.rst
  doc/release_notes/release_notes_0.5.rst
  doc/release_notes/release_notes_0.6.rst
  doc/release_notes/release_notes_0.7.rst
  doc/release_notes/release_notes_0.8.rst
  doc/release_notes/release_notes_1.0.rst
  doc/release_notes/release_notes_1.1.rst
  doc/release_notes/release_notes_1.2.rst
  doc/release_notes/release_notes_1.3.rst
  doc/release_notes/release_notes_1.4.rst
  doc/release_notes/release_notes_1.5.rst
  doc/release_notes/release_notes_1.6.1.rst
  doc/release_notes/release_notes_1.6.rst
  doc/release_notes/release_notes_2.0.rst
  doc/tutorials/acrn-dm_QoS.rst
  doc/tutorials/acrn_ootb.rst
  doc/tutorials/agl-vms.rst
  doc/tutorials/building_acrn_in_docker.rst
  doc/tutorials/building_uos_from_clearlinux.rst
  doc/tutorials/cl_servicevm.rst
  doc/tutorials/debug.rst
  doc/tutorials/enable_laag_secure_boot.rst
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/images/NUC-serial-port.jpg
  doc/tutorials/increase-uos-disk-size.rst
  doc/tutorials/kbl-nuc-sdc.rst
  doc/tutorials/open_vswitch.rst
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/running_deb_as_serv_vm.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/setup_openstack_libvirt.rst
  doc/tutorials/sign_clear_linux_image.rst
  doc/tutorials/static-ip.rst
  doc/tutorials/up2.rst
  doc/tutorials/using_celadon_as_uos.rst
  doc/tutorials/using_sbl_on_up2.rst
  doc/tutorials/using_serial_port.rst
  doc/tutorials/using_ubuntu_as_sos.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
  misc/acrn-manager/README.rst
Labels: area: documentation

#5011 script: fix a minor bug in launch_xenomai.sh
  misc/vm_configs/sample_launch_scripts/nuc/launch_xenomai.sh
Labels: CI: Tracked On Pass

#5260 acrn-config: zephyr entry and load address update
  misc/vm_configs/scenarios/hybrid/vm_configurations.c
  misc/vm_configs/xmls/config-xmls/apl-mrb/hybrid.xml
  misc/vm_configs/xmls/config-xmls/apl-up2/hybrid.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid.xml
  misc/vm_configs/xmls/config-xmls/generic/hybrid.xml
  misc/vm_configs/xmls/config-xmls/nuc6cayh/hybrid.xml
  misc/vm_configs/xmls/config-xmls/nuc7i7dnb/hybrid.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid.xml
Labels: CI: Tracked On Pass

#5270 doc: update virtio-i2c inclusive language
  doc/developer-guides/hld/virtio-i2c.rst
Labels: area: documentation

#5261 acrn-config: add pse-gpio to vmsix_on_msi devices list
  misc/acrn-config/board_config/board_c.py
  misc/acrn-config/board_config/board_info_h.py
  misc/acrn-config/library/board_cfg_lib.py
  misc/vm_configs/xmls/board-xmls/ehl-crb-b.xml
Labels: CI: Tracked On Pass

#5264 DM: xHCI: Fix WaaG crash issue caused by Transfer TRBS.
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass

#5272 hv: support PIO access to platform hidden devices
  hypervisor/dm/vpci/vpci.c
Labels: CI: Tracked On Pass

#5279 acrn-config: update the size range of ivshmem memory region
  misc/acrn-config/library/scenario_cfg_lib.py
  misc/acrn-config/scenario_config/ivshmem_cfg_h.py
  misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i5/ivshmem_cfg.h
Labels: CI: Tracked On Pass

#5277 HV: set CONFIG_HV_RAM_START as min addr when RELOC enabled
  hypervisor/arch/x86/Kconfig
  hypervisor/arch/x86/boot/cpu_primary.S
Labels: CI: Tracked On Pass

#5280 acrn-config: fix csme passthrough issue for launch setting
  doc/tutorials/launch_uos.sh
  misc/acrn-config/launch_config/pt.py
  misc/vm_configs/sample_launch_scripts/apl-mrb/launch_uos.sh
  misc/vm_configs/sample_launch_scripts/apl-up2/launch_uos.sh
Labels: CI: Tracked On Pass

#5258 HV: Fix SR-IOV problem on EHL
  hypervisor/dm/vpci/vhostbridge.c
Labels: CI: Tracked On Pass

#5271 acrn-manager: build and install 'acrnctl' (release and debug)
  misc/acrn-manager/Makefile
Labels: CI: Tracked On Pass

#5284 acrn-config: fix the issue of failure to create a new launch setting.
  misc/acrn-config/config_app/static/main.js
  misc/acrn-config/config_app/views.py
  misc/acrn-config/library/launch_cfg_lib.py
Labels: CI: Tracked On Pass

#5283 acrn-config: add swiotlb to sos kernel bootargs to increase bounce bufs
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/industry.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/sdc.xml
Labels: CI: Tracked On Pass

#5287 config: EHL passthough network to pre-launched VM for hybrid_rt
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
Labels: CI: Tracked On Pass

#5290 acrn-config: enable TPM2 config on ehl-crb-b board
  misc/acrn-config/library/board_cfg_lib.py
  misc/acrn-config/library/scenario_cfg_lib.py
  misc/acrn-config/scenario_config/scenario_cfg_gen.py
  misc/acrn-config/scenario_config/scenario_item.py
  misc/vm_configs/xmls/config-xmls/apl-mrb/hybrid.xml
  misc/vm_configs/xmls/config-xmls/apl-mrb/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/apl-up2/hybrid.xml
  misc/vm_configs/xmls/config-xmls/apl-up2/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt_fusa.xml
  misc/vm_configs/xmls/config-xmls/generic/hybrid.xml
  misc/vm_configs/xmls/config-xmls/generic/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/generic/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/nuc6cayh/hybrid.xml
  misc/vm_configs/xmls/config-xmls/nuc6cayh/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/template/PRE_RT_VM.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid_rt.xml
Labels: CI: Tracked On Pass

#5289 HV: fix uart hang issue caused by bdf overridden
  hypervisor/debug/uart16550.c
Labels: CI: Tracked On Pass

#5293 Revert "hv:refine vm & vcpu lock" for release2.2_branch
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/io_req.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/dm/io_req.h
Labels: CI: Tracked On Pass, release_2.2

#5291 doc: add pointers to meta-acrn layer repo docs
  doc/develop.rst
  doc/tutorials/using_yp.rst
Labels: area: documentation

#5302 doc: fix source code folder and use 'User VM'
  misc/acrn-manager/README.rst
Labels: area: documentation

#5308 acrn-config: remove uuid in config
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/generic/logical_partition.xml
Labels: CI: Tracked On Pass, release_2.2

#5301 acrn-config: fix issue of acrn build failed on industry scenario when…
  misc/acrn-config/scenario_config/vm_configurations_c.py
Labels: CI: Tracked On Pass

#5307 acrn-config: remove uuid in config
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/logical_partition.xml
  misc/vm_configs/xmls/config-xmls/generic/logical_partition.xml
Labels: CI: Tracked On Pass

#5313 [Release 2.2]HV: correct hpa calculation for pre-launched VM
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass, release_2.2

#5306 dm: refine ivshmem usage interface
  devicemodel/hw/pci/ivshmem.c
Labels: CI: Tracked On Pass, release_2.2

#5310 OVMF release v2.2
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass, release_2.2

#5311 OVMF release v2.2
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#5262 doc: add ivhshmem hv-land introduction
  doc/develop.rst
  doc/developer-guides/hld/ivshmem-hld.rst
  doc/tutorials/enable_ivshmem.rst
Labels: area: documentation

#5300 acrn-config: fix issue of acrn build failed on industry scenario when…
  misc/acrn-config/scenario_config/vm_configurations_c.py
Labels: CI: Tracked On Pass, release_2.2

#5305 dm: refine ivshmem usage interface
  devicemodel/hw/pci/ivshmem.c
Labels: CI: Tracked On Pass

#5312 HV: correct hpa calculation for pre-launched VM
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass

#5323 doc: update pre-launched VMs with offline ACPI
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#5324 doc: continue CL cleanup
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#5325 doc: edit intro grammar
  doc/introduction/index.rst
Labels: area: documentation

#5317 hv: vmsi: add default BAR GPA for vmsi over msi
  hypervisor/dm/vpci/vmsix_on_msi.c
Labels: CI: Tracked On Pass, release_2.2

#5332 OVMF release v2.2 (updated)
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass, release_2.2

#5335 doc: Add note about the maximum number of regions for hv-land
  doc/tutorials/enable_ivshmem.rst
Labels: area: documentation

#5337 acrn-config: add the TSN device passthrough to pre-launched VM on TGL
  misc/vm_configs/xmls/board-xmls/tgl-rvp.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass, release_2.2

#5341 acrn-config: fix hang issue for board EHL (hybrid_rt)
  misc/acrn-config/board_config/board_info_h.py
  misc/vm_configs/scenarios/hybrid/ehl-crb-b/misc_cfg.h
  misc/vm_configs/scenarios/hybrid_rt/ehl-crb-b/misc_cfg.h
Labels: CI: Tracked On Pass, release_2.2

#5339 acrn-config: add the TSN device passthrough to pre-launched VM on TGL
  misc/vm_configs/xmls/board-xmls/tgl-rvp.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass

#5334 doc: add IVSHMEM, mmio_resources, pt_intx in configuration tool
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#5345 doc: update IVSHMEM config detail
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#5347 Hide pci bridge 00:1C.0
  hypervisor/arch/x86/configs/pci_dev.c
Labels: CI: Tracked On Pass, release_2.2

#5344 virtio: add virtio callbacks check
  devicemodel/hw/pci/virtio/virtio.c
Labels: CI: Tracked On Pass

#5349 hv: remove UNCACHED for pSRAM EPT memmap segment
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass, release_2.2

#5354 doc: update HW to include new processors
  doc/reference/hardware.rst
Labels: area: documentation

#5356 doc: Spelling and grammar tweaks
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/developer-guides/hld/hv-ioc-virt.rst
  doc/developer-guides/hld/hv-partitionmode.rst
  doc/developer-guides/hld/hv-rdt.rst
  doc/developer-guides/hld/ivshmem-hld.rst
  doc/developer-guides/hld/system-timer-hld.rst
  doc/developer-guides/hld/virtio-gpio.rst
  doc/developer-guides/hld/watchdog-hld.rst
  doc/developer-guides/l1tf.rst
  doc/developer-guides/sw_design_guidelines.rst
  doc/faq.rst
  doc/getting-started/building-from-source.rst
  doc/getting-started/rt_industry_ubuntu.rst
  doc/introduction/index.rst
  doc/reference/hardware.rst
  doc/release_notes/release_notes_1.0.rst
  doc/release_notes/release_notes_1.3.rst
  doc/release_notes/release_notes_1.6.rst
  doc/release_notes/release_notes_2.0.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/acrn_on_qemu.rst
  doc/tutorials/debug.rst
  doc/tutorials/docbuild.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/realtime_performance_tuning.rst
  doc/tutorials/rtvm_performance_tips.rst
  doc/tutorials/rtvm_workload_design_guideline.rst
  doc/tutorials/run_kata_containers.rst
  doc/tutorials/running_deb_as_serv_vm.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/sgx_virtualization.rst
  doc/tutorials/trustyACRN.rst
  doc/tutorials/using_grub.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_serial_port.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_windows_as_uos.rst
  doc/tutorials/using_xenomai_as_uos.rst
  doc/tutorials/using_yp.rst
  doc/tutorials/using_zephyr_as_uos.rst
  doc/tutorials/vuart_configuration.rst
  doc/user-guides/acrn-dm-parameters.rst
  doc/user-guides/hv-parameters.rst
  doc/user-guides/kernel-parameters.rst
  misc/packaging/README.rst
  misc/tools/acrn-crashlog/README.rst
  misc/tools/acrn-crashlog/acrnprobe/README.rst
  misc/tools/acrn-crashlog/acrnprobe/conf.rst
  misc/tools/acrn-crashlog/usercrash/README.rst
  misc/tools/acrntrace/README.rst
Labels: area: documentation

#5362 dm: fix fault Injection into VirtIO console backend
  devicemodel/core/vmmapi.c
  devicemodel/hw/pci/virtio/virtio.c
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass, release_2.2

#5361 dm: fix fault Injection into VirtIO console backend
  devicemodel/core/vmmapi.c
  devicemodel/hw/pci/virtio/virtio.c
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass

#5367 doc: update doc for #5157 is closed as fix
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#5351 doc: add the iasl dependence
  doc/getting-started/building-from-source.rst
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#5372 doc: update rt_industry GSG and v2.2 release notes
  doc/getting-started/rt_industry_ubuntu.rst
  doc/release_notes/release_notes_2.2.rst
Labels: area: documentation

#5374 doc: add v2.2 to doc menu choices
  doc/conf.py
Labels: area: documentation

#5376 Doc: release_notes_2.2 update
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#5375 doc: tweak 2.2 release notes
  doc/release_notes/release_notes_2.2.rst
Labels: area: documentation

#5377 doc: doc fixes post 2.2 release
  doc/getting-started/rt_industry_ubuntu.rst
  doc/release_notes/release_notes_2.2.rst
Labels: area: documentation

#5380 doc: redirect to 2.1 version for delete docs
  doc/conf.py
  doc/nocl.rst
Labels: area: documentation
