Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-01, with the labels that each got.

#4331 doc: fix wrong Docker container image in tutorial
  doc/tutorials/building_acrn_in_docker.rst
Labels: area: documentation

#4326 HV: do not offline pcpu when lapic pt disabled
  hypervisor/arch/x86/guest/vm.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4340 Doc: releasenotes_1.5
  doc/release_notes/release_notes_1.5.rst
Labels: area: documentation

#4341 Doc: Grammatical edits to RN 1.5.
  doc/release_notes/release_notes_1.5.rst
Labels: area: documentation

#4333 dm:replace perror with pr_err
  devicemodel/core/hugetlb.c
  devicemodel/core/mevent.c
  devicemodel/core/timer.c
  devicemodel/hw/block_if.c
  devicemodel/hw/pci/core.c
  devicemodel/hw/pci/gvt.c
  devicemodel/hw/pci/virtio/virtio_block.c
  devicemodel/hw/pci/wdt_i6300esb.c
  devicemodel/log/disk_logger.c
  devicemodel/log/kmsg_logger.c
Labels: CI: Tracked On Pass

#4342 Doc: document update base on release_v1.5
  doc/getting-started/rt_industry.rst
  doc/tutorials/acrn_ootb.rst
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4345 Doc: Grammar update to arcn_ootd.rst.
  doc/tutorials/acrn_ootb.rst
Labels: area: documentation

#4344 Doc: releasenotes_1.5 update
  doc/release_notes/release_notes_1.5.rst
Labels: area: documentation

#4337 hv:validate input in 'deinit_postlaunched_vm_vpci()'
  hypervisor/dm/vpci/vpci.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4346 doc: change version info
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#4347 doc: update getting start guide about clear version and ootb command
  doc/getting-started/rt_industry.rst
  doc/tutorials/acrn_ootb.rst
Labels: area: documentation

#4338 doc: update some xml elements description
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#4351 Doc: Style and grammar edits to GSG for ACRN Industry Scenario.
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#4352 Doc: Fixed spelling error in the acrn_config_tool file.
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#4353 Doc: Updated one paragraph in re_industry doc.
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#4364 Doc: Clarify Post-Launch VM data flow discussion for vuart conf
  doc/tutorials/images/vuart-config-post-launch.png
  doc/tutorials/vuart_configuration.rst
Labels: area: documentation

#4362 doc: update the "Using SDC Mode on the NUC" tutorial
  doc/tutorials/kbl-nuc-sdc.rst
  doc/tutorials/run_kata_containers.rst
Labels: area: documentation

#4368 doc: reset clear linux version and ootb command in getting start guide
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#4363 HV: init local variable before it is used.
  hypervisor/hw/pci.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4374 doc: Modify CL version from 32030 to 31670
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#4377 Updated grammer in ACRN industry scenario doc
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#4372 doc: update project's target max LOC
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#4382 Doc: Style updates to Building from Source doc
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#4376 doc: update Kata and ACRN tutorial
  doc/tutorials/run_kata_containers.rst
Labels: area: documentation
