Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-02, with the labels that each got.

#4384 fix typos in board gen script
  misc/acrn-config/board_config/new_board_kconfig.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4385 Python scripts discovering CPU IDs are off by 1
  misc/acrn-config/target/misc.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4391 acrn: rename param in uart16550_init
  hypervisor/debug/uart16550.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4392 doc: update Grub configuration instructions for Ubuntu (Service VM)
  doc/tutorials/using_ubuntu_as_sos.rst
Labels: area: documentation

#4381 hv: enable early pr_xxx() logs
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/init.c
  hypervisor/arch/x86/timer.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4395 DOC: Edits to Ubuntu SOS; changed SOS/UOS to Service VM/User VM
  doc/tutorials/using_ubuntu_as_sos.rst
Labels: area: documentation

#4370 Delete pass-through audio to WaaG in default
  devicemodel/samples/nuc/launch_win.sh
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4394 acrn-config: a few changes on vm_config[] clos generation
  misc/acrn-config/scenario_config/vm_configurations_c.py
Labels: Automerge: Pass, CI: Tracked On Pass

#4383 Add PXE boot loader string to known boot loaders
  hypervisor/boot/guest/vboot_wrapper.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4396 Makefile: disable fcf-protection for some build env
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4398 hv: CAT is supposed to be enabled in the system level
  hypervisor/arch/x86/Kconfig
  hypervisor/arch/x86/cat.c
  hypervisor/arch/x86/configs/vm_config.c
  hypervisor/arch/x86/cpu.c
  hypervisor/include/arch/x86/cat.h
  hypervisor/include/arch/x86/vm_config.h
  hypervisor/include/public/acrn_common.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4403 Doc: VM2 vCPU affinity info update
  doc/tutorials/cpu_sharing.rst
Labels: area: documentation

#4404 hv: reset vcpu events in reset_vcpu
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/common/event.c
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4408 Makefile: fix build issue on old gcc
  hypervisor/Makefile
Labels: Automerge: Pass, CI: Tracked On Pass

#4411 hv: use BOOT_CPU_ID instead of hardcoded value
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/arch/x86/guest/vmx_io.c
  hypervisor/arch/x86/init.c
  hypervisor/arch/x86/irq.c
  hypervisor/arch/x86/timer.c
  hypervisor/boot/guest/vboot_info.c
  hypervisor/common/hypercall.c
  hypervisor/common/ptdev.c
  hypervisor/common/vm_load.c
  hypervisor/debug/profiling.c
  hypervisor/debug/shell.c
  hypervisor/dm/vpic.c
  hypervisor/include/arch/x86/cpu.h
  hypervisor/include/arch/x86/guest/vcpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4416 Makefile: Fix build issue if the ld is updated to 2.34
  hypervisor/Makefile
Labels: CI: Tracked On Pass

#4425 hv: refine retpoline speculation barriers
  hypervisor/arch/x86/lib/retpoline-thunk.S
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4429 hv:refine comment about intel integrated gpu dmar
  hypervisor/acpi_parser/dmar_parse.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4431 hv: xsave: bugfix for init value
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass

#4434 HV: add vpci bridge operations support
  hypervisor/Makefile
  hypervisor/dm/vpci/vpci.c
  hypervisor/dm/vpci/vpci_bridge.c
  hypervisor/include/dm/vpci.h
  hypervisor/include/hw/pci.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#4439 hv: refine confusing e820 table logging layout
  hypervisor/arch/x86/e820.c
Labels: Automerge: Pass, CI: Tracked On Pass

#4437 hv: xsave: change to pure assembler
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/cpu.h
Labels: Automerge: Pass, CI: Tracked On Pass
