Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-07, with the labels that each got.

#4996 HV: restrict conditions to assign/deassign pcidev
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass

#5002 debug: BOARD_ENABLE: update the debug serial port info of SOS
  hypervisor/debug/dbg_cmd.c
Labels: CI: Tracked On Pass, release_2.0

#5001 hv: vpci: minor refine about MSI/MSI-X de-initialization
  hypervisor/dm/vpci/vmsi.c
  hypervisor/dm/vpci/vmsix.c
  hypervisor/dm/vpci/vpci_priv.h
Labels: CI: Tracked On Pass

#5000 tools: improve Makefile to build life-mngr
  misc/Makefile
  misc/life_mngr/Makefile
Labels: CI: Tracked On Pass

#5006 hv:use spinlock_irqsave_obtain api for uart
  hypervisor/debug/uart16550.c
Labels: CI: Tracked On Pass

#4992 doc:update WaaG GSG based on Ubuntu.
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#5009 doc: tweak link in waag tutorial
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#5019 dm: Data Stolen Memory (DSM) passthrough support for GVT-d on TGL
  devicemodel/hw/pci/passthrough.c
  devicemodel/include/pcireg.h
Labels: CI: Tracked On Pass

#5018 dm: Fix wrong hugetlb_lv_max
  devicemodel/core/hugetlb.c
Labels: CI: Tracked On Pass

#5010 doc: Update contribution guide instructions
  doc/developer-guides/contribute_guidelines.rst
Labels: area: documentation

#4692 hv: vioapic: expose ioapic to guest unconditionally
  devicemodel/hw/platform/acpi/acpi.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/vioapic.c
  hypervisor/include/dm/vioapic.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#5017 doc: Update Inter-VM Communication with Security Hardening Guidelines
  doc/developer-guides/hld/ivshmem-hld.rst
Labels: area: documentation

#5026 doc: keep doxygen group descriptions in doc output
  doc/static/acrn-custom.css
Labels: area: documentation

#5025 HV: restrict conditions to assign/deassign pcidev
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass, release_2.0

#5032 doc: update intro link to project roadmap
  doc/introduction/index.rst
Labels: area: documentation

#5030 acrn-config: enable only 4 vms for TGL
  misc/acrn-config/xmls/config-xmls/tgl-rvp/industry.xml
Labels: CI: Tracked On Pass

#5031 DM: Add macvtap support to virtio-net
  devicemodel/hw/pci/virtio/virtio_net.c
Labels: CI: Tracked On Pass

#5034 DM USB: xHCI: Fix XHCI_GET_SLOT value check issue
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass

#5037 OVMF release v2.1
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#5042 acrn-config: minor fix mac seed for launch config
  misc/acrn-config/launch_config/com.py
Labels: CI: Tracked On Pass

#5035 dm: Increase OpRegion size for bigger VBT
  devicemodel/hw/pci/passthrough.c
Labels: CI: Tracked On Pass

#5040 acrn-config: minor fix mac seed for launch config
  misc/acrn-config/launch_config/com.py
Labels: CI: Tracked On Pass, release_2.0

#5045 acrn-config: update board xml for ehl-crb-b
  misc/acrn-config/xmls/board-xmls/ehl-crb-b.xml
Labels: CI: Tracked On Pass

#5050 acrn-config: generate '-s 1:0,lpc ' for non-hart rt in launch script
  misc/acrn-config/launch_config/com.py
Labels: CI: Tracked On Pass

#5051 acrn-config: generate '-s 1:0,lpc ' for non-hart rt in launch script
  misc/acrn-config/launch_config/com.py
Labels: CI: Tracked On Pass, release_2.0

#5023 create acrn hypervisor/kernel deb
  doc/develop.rst
  misc/packaging/50-acrn.netdev
  misc/packaging/50-acrn.network
  misc/packaging/50-eth.network
  misc/packaging/50-tap0.netdev
  misc/packaging/README.rst
  misc/packaging/acrn-hypervisor.postinst
  misc/packaging/acrn-kernel.postinst
  misc/packaging/compile_iasl.py
  misc/packaging/deb.json
  misc/packaging/install_uSoS.py
  misc/packaging/release.json
Labels: CI: Tracked On Pass

#5054 hv:add per-vm lock for vm & vcpu state change
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vm_reset.c
  hypervisor/arch/x86/guest/vmcall.c
  hypervisor/common/hv_main.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/guest/vm.h
Labels: Automerge: Pass, CI: Tracked On Pass, Coding Guidelines: PASS

#5072 DM: xHCI: Release all device resource when received HCRST.
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#5058 Refine status transition of thread object
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/common/schedule.c
  hypervisor/include/arch/x86/guest/vcpu.h
  hypervisor/include/common/schedule.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#5065 hv: fix possible SSE region mismatch issue
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/cpu.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#5069 DM: PT: Add "d3hot_reset" sub-parameter for passthrough device
  devicemodel/hw/pci/passthrough.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#5079 acrn-config: refine mac seed for launch config
  misc/acrn-config/launch_config/com.py
Labels: CI: Tracked On Pass

#5080 acrn-config: refine mac seed for launch config
  misc/acrn-config/launch_config/com.py
Labels: CI: Tracked On Pass, release_2.0

#5071 HV: inject physical PCIEXBAR into vhostbridge to better emulate vhostbridge
  hypervisor/dm/vpci/vhostbridge.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#5076 DM: xHCI: Implement reset/stop endpiont error handler
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass

#5073 doc: update debian packaging documentation
  misc/packaging/README.rst
  misc/packaging/release.json
Labels: Automerge: Pass, CI: Tracked On Pass, area: documentation

#5087 HV: fix hide all sriov in ecap
  hypervisor/dm/vpci/vpci.c
Labels: CI: Tracked On Pass

#5096 HV: fix hide all sriov in ecap
  hypervisor/dm/vpci/vpci.c
Labels: CI: Tracked On Pass, release_2.1

#5104 doc: fixing the intel_pstate kernel command line setting
  doc/tutorials/rtvm_performance_tips.rst
Labels: area: documentation, no Signed-off-by

#5064 doc: update documentation for configuring ACRN RDT features
  doc/developer-guides/hld/hv-rdt.rst
  doc/getting-started/building-from-source.rst
  doc/tutorials/rdt_configuration.rst
Labels: area: documentation

#5086 doc: add mmio device passthrough introduction
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/mmio-dev-passthrough.rst
Labels: area: documentation

#5105 doc: add mmio-dev-passthrough to TOC
  doc/developer-guides/hld/hld-hypervisor.rst
Labels: area: documentation

#5055 doc: update virtio-net documentation with macvtap support.
  doc/developer-guides/hld/virtio-net.rst
Labels: area: documentation

#5101 Doc: The user guide for Pre-Launched RT mode
  doc/develop.rst
  doc/tutorials/images/pre_launched_rt.png
  doc/tutorials/pre-launched-rt.rst
Labels: area: documentation

#5114 doc: add copyright/license header to doc scripts
  doc/scripts/filter-known-issues.py
  doc/scripts/genrest.py
Labels: area: documentation

#5116 hv: fix deadloop in sleep_thread_sync
  hypervisor/common/schedule.c
Labels: CI: Tracked On Pass

#5111 hv: Fix size issue used for memset in create_vm
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass, release_2.1

#5117 hv: fix deadloop in sleep_thread_sync
  hypervisor/common/schedule.c
Labels: CI: Tracked On Pass, release_2.1
