Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-12, with the labels that each got.

#5563 doc: add v2.3 release notes draft
  doc/release_notes/release_notes_2.3.rst
Labels: area: documentation

#5536 doc: update configuration tool description of vuarts
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#5537 Doc: pci-vuart-guide
  doc/tutorials/vuart_configuration.rst
Labels: area: documentation

#5568 doc: update 'asa.rst' for 2.3 release
  doc/asa.rst
Labels: area: documentation

#5567 doc: update 'enable_ivshmem'
  doc/tutorials/enable_ivshmem.rst
Labels: area: documentation

#5569 doc: doc cleanup for v2.3 release
  doc/.known-issues/doc/dupdecl.conf
  doc/asa.rst
  doc/nocl.rst
  doc/try.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/running_deb_as_serv_vm.rst
Labels: area: documentation

#5562 hv: fix formatting for cfg.log output
  Makefile
Labels: CI: Tracked On Pass

#5566 acrn-config: remove hardcoded device in launch script
  misc/acrn-config/launch_config/com.py
Labels: CI: Tracked On Pass

#5541 doc: add documentation for graceful system shutdown
  doc/tutorials/enable_s5.rst
  doc/tutorials/images/system_shutdown.png
Labels: CI: Tracked On Pass, area: documentation

#5551 Doc: GSG update for ACRN Industry Scenario with Ubuntu Service VM
  doc/getting-started/building-from-source.rst
  doc/getting-started/rt_industry_ubuntu.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#5532 doc: Add ACRN secureboot setup with GRUB
  doc/develop.rst
  doc/tutorials/acrn-secure-boot-with-grub.rst
  doc/tutorials/images/acrn_secureboot_flow.png
  doc/tutorials/waag-secure-boot.rst
Labels: area: documentation

#5560 doc: update the doc to setup openstack with ACRN
  doc/getting-started/rt_industry_ubuntu.rst
  doc/tutorials/setup_openstack_libvirt.rst
Labels: area: documentation

#5574 doc: update v2.3 release notes
  doc/release_notes/release_notes_2.3.rst
Labels: area: documentation

#5575 Doc: release_notes_2.3 update
  doc/release_notes/release_notes_2.3.rst
Labels: area: documentation

#5576 doc: release notes tweaks for v2.3
  doc/release_notes/release_notes_2.3.rst
Labels: area: documentation

#5577 doc: update release branch with new docs
  doc/.known-issues/doc/dupdecl.conf
  doc/asa.rst
  doc/conf.py
  doc/develop.rst
  doc/developer-guides/contribute_guidelines.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/hld/ivshmem-hld.rst
  doc/developer-guides/hld/virtio-net.rst
  doc/extensions/eager_only.py
  doc/extensions/link_roles.py
  doc/genindex.rst
  doc/getting-started/building-from-source.rst
  doc/getting-started/rt_industry_ubuntu.rst
  doc/index.rst
  doc/introduction/index.rst
  doc/nocl.rst
  doc/release_notes/release_notes_2.3.rst
  doc/try.rst
  doc/tutorials/acrn-secure-boot-with-grub.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/images/acrn_secureboot_flow.png
  doc/tutorials/images/system_shutdown.png
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/running_deb_as_serv_vm.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/setup_openstack_libvirt.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
  doc/tutorials/vuart_configuration.rst
  doc/tutorials/waag-secure-boot.rst
  doc/user-guides/acrn-dm-parameters.rst
  misc/acrn-manager/README.rst
  misc/packaging/README.rst
Labels: area: documentation

#5578 doc: update doc version selector for v2.3
  doc/conf.py
Labels: area: documentation

#5582 doc: tweak to 2.3 release notes
  doc/release_notes/release_notes_2.3.rst
Labels: area: documentation

#5579 acrn-config: modify the cmd args in pre-launched rt xml
  misc/vm_configs/xmls/config-xmls/cfl-k700-i7/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid_rt.xml
Labels: CI: Tracked On Pass

#5585 doc: update HLD of HV-Land Ivshmem
  doc/developer-guides/hld/images/ivshmem-hv-land-doorbell.png
  doc/developer-guides/hld/ivshmem-hld.rst
Labels: area: documentation

#5584 doc: update acrn secureboot enablement
  doc/tutorials/acrn-secure-boot-with-grub.rst
Labels: area: documentation

#5591 acrn-config: update function for xml.etree.ElementTree to compatible …
  misc/acrn-config/acpi_gen/asl_gen.py
  misc/acrn-config/config_app/controller.py
  misc/acrn-config/config_app/templates/launch.html
  misc/acrn-config/config_app/templates/scenario.html
  misc/acrn-config/config_app/views.py
  misc/acrn-config/library/launch_cfg_lib.py
Labels: CI: Tracked On Pass

#5583 doc: add ROScube GSG
  doc/getting-started/roscube/images/rqi-acrn-architecture.png
  doc/getting-started/roscube/images/rqi-acrn-blkid.png
  doc/getting-started/roscube/images/rqi-acrn-config-export-xml-submit.png
  doc/getting-started/roscube/images/rqi-acrn-config-export-xml.png
  doc/getting-started/roscube/images/rqi-acrn-config-generate-config-submit.png
  doc/getting-started/roscube/images/rqi-acrn-config-generate-config.png
  doc/getting-started/roscube/images/rqi-acrn-config-hv-settings.png
  doc/getting-started/roscube/images/rqi-acrn-config-import-board.png
  doc/getting-started/roscube/images/rqi-acrn-config-scenario-settings.png
  doc/getting-started/roscube/images/rqi-acrn-config-select-board.png
  doc/getting-started/roscube/images/rqi-acrn-config-vm0-settings.png
  doc/getting-started/roscube/images/rqi-acrn-config-vm1-settings.png
  doc/getting-started/roscube/images/rqi-acrn-config-vm2-settings1.png
  doc/getting-started/roscube/images/rqi-acrn-config-vm2-settings2.png
  doc/getting-started/roscube/images/rqi-acrn-config-web.png
  doc/getting-started/roscube/images/rqi-acrn-dmesg.png
  doc/getting-started/roscube/images/rqi-acrn-ethernet-lspci.png
  doc/getting-started/roscube/images/rqi-acrn-grub.png
  doc/getting-started/roscube/images/rqi-acrn-grun-40_custom.png
  doc/getting-started/roscube/images/rqi-acrn-hw-connection.jpg
  doc/getting-started/roscube/images/rqi-acrn-kvm-choose-iso.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-cpu-ram.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-firmware.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-name.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-new-vm.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-storage.png
  doc/getting-started/roscube/images/rqi-acrn-rtos-clone.png
  doc/getting-started/roscube/images/rqi-acrn-rtos-ready.png
  doc/getting-started/roscube/images/rqi-acrn-usb-port.png
  doc/getting-started/roscube/images/rqi-pin-definition.png
  doc/getting-started/roscube/roscube-gsg.rst
  doc/try.rst
Labels: area: documentation

#5595 doc: small updates to the GSG
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#5597 doc: small updates to ROScube-I Installation Guide
  doc/getting-started/roscube/roscube-gsg.rst
Labels: area: documentation

#5590 Properly fix formatting for 'cfg.log' file
  Makefile
Labels: CI: Tracked On Pass

#5593 acrn-config: fix the logic of get_vuart1_vmid
  misc/acrn-config/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass

#5604 doc: automate copyright year footer
  doc/conf.py
Labels: area: documentation

#5607 misc: add more boot arguments for EHL preempt-rt
  misc/vm_configs/scenarios/hybrid_rt/ehl-crb-b/misc_cfg.h
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
Labels: CI: Tracked On Pass

#5616 acrn-config: add cfl-k700-i7 into tpm supported boards
  misc/acrn-config/library/board_cfg_lib.py
Labels: CI: Tracked On Pass

#5610 doc: update LICENSE copyright years
  LICENSE
Labels: CI: Tracked On Pass

#5613 doc: tweak to copyright footer
  doc/conf.py
Labels: area: documentation

#5619 doc: specify the version of 'sphinx-tabs' to install
  doc/scripts/requirements.txt
Labels: area: documentation

#5617 Doc: update WaaG image creation with GVT-d GOP
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#5618 doc: fix 'cp' command in instructions
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation

#5620 doc: remove exec attribute for 'acrn-secure-boot-with-grub.rst'
  doc/tutorials/acrn-secure-boot-with-grub.rst
Labels: area: documentation

#5622 doc: remove stray x attrib on png and rst files
  doc/developer-guides/hld/images/atkbdc-virt-hld.png
  doc/developer-guides/hld/images/ivshmem-hv-land-doorbell.png
  doc/developer-guides/hld/images/uart-virt-hld-1.png
  doc/developer-guides/hld/images/uart-virt-hld-2.png
  doc/developer-guides/hld/images/uart-virt-hld-3.png
  doc/developer-guides/hld/images/virtio-gpio-1.png
  doc/developer-guides/hld/images/virtio-gpio-2.png
  doc/developer-guides/hld/images/virtio-hld-image61.png
  doc/developer-guides/hld/ivshmem-hld.rst
  doc/developer-guides/images/modularity-architecture.png
  doc/tutorials/images/menuconfig-partition-mode.png
Labels: area: documentation

#5621 acrn-config: config the entry number of vcpu_clos same as that of pcp…
  misc/vm_configs/xmls/config-xmls/apl-mrb/hybrid.xml
  misc/vm_configs/xmls/config-xmls/apl-up2/hybrid.xml
  misc/vm_configs/xmls/config-xmls/cfl-k700-i7/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt_fusa.xml
  misc/vm_configs/xmls/config-xmls/generic/hybrid.xml
  misc/vm_configs/xmls/config-xmls/generic/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/nuc6cayh/hybrid.xml
  misc/vm_configs/xmls/config-xmls/nuc7i7dnb/hybrid.xml
  misc/vm_configs/xmls/config-xmls/qemu/sdc.xml
  misc/vm_configs/xmls/config-xmls/template/SOS_VM.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid.xml
  misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid_rt.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid.xml
  misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid_rt.xml
Labels: CI: Tracked On Pass

#5624 Doc: update Debian and Ubuntu as the User VM
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
Labels: area: documentation

#5627 doc: fix formatting in windows as UOS doc
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#5628 doc: spelling fixes
  doc/developer-guides/hld/hld-APL_GVT-g.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-power-management.rst
  doc/developer-guides/hld/hld-trace-log.rst
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/hld/hv-hypercall.rst
  doc/developer-guides/hld/hv-interrupt.rst
  doc/developer-guides/hld/hv-vm-management.rst
  doc/developer-guides/hld/virtio-console.rst
  doc/developer-guides/hld/virtio-gpio.rst
  doc/developer-guides/hld/virtio-i2c.rst
  doc/developer-guides/hld/virtio-net.rst
  doc/developer-guides/hld/virtio-rnd.rst
  doc/developer-guides/hld/vuart-virt-hld.rst
Labels: area: documentation

#5631 doc: prep for upgrading doc build tools
  doc/.known-issues/doc/dupdecl.conf
  doc/conf.py
Labels: area: documentation

#5632 doc: upgrade doc-build tools
  doc/scripts/requirements.txt
  doc/tutorials/docbuild.rst
Labels: area: documentation
