Repository projectacrn/acrn-hypervisor, pull requests merged in 2020-06, with the labels that each got.

#4859 porting patch: hv: virq: refine pending event inject sequence
  hypervisor/arch/x86/guest/virq.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/include/arch/x86/guest/vlapic.h
Labels: CI: Tracked On Pass

#4867 OVMF release v2.0
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#4877 acrn-config: refine sanity check for MASK_CLOS number
  misc/acrn-config/library/hv_cfg_lib.py
  misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
Labels: CI: Tracked On Pass

#4881 doc: rst syntax tweaks
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/trusty.rst
  doc/faq.rst
  doc/index.rst
  doc/introduction/index.rst
  doc/release_notes/release_notes_0.5.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/run_kata_containers.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/using_celadon_as_uos.rst
  doc/tutorials/using_windows_as_uos.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#4882 doc: update Kata tutorial for Ubuntu Service VM
  doc/tutorials/run_kata_containers.rst
Labels: area: documentation

#4875 Makefile: minor fix on hypervisor dependency
  hypervisor/Makefile
  hypervisor/scripts/makefile/kconfig.mk
Labels: CI: Tracked On Pass

#4884 Grammatical updates to GSG Indust Scen Ubuntu
  doc/getting-started/images/DVMT-reallocated-64mb.png
  doc/getting-started/images/PM-support-enabled.png
  doc/getting-started/images/native-ubuntu-on-NVME-1.png
  doc/getting-started/images/native-ubuntu-on-NVME-2.png
  doc/getting-started/images/native-ubuntu-on-SATA-1.png
  doc/getting-started/images/native-ubuntu-on-SATA-2.png
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#4883 doc: rename rt_industry GSG
  doc/conf.py
  doc/develop.rst
  doc/try.rst
  doc/tutorials/cl_servicevm.rst
  doc/tutorials/images/KBL-serial-port-header-to-RS232-cable.jpg
  doc/tutorials/images/KBL-serial-port-header.png
Labels: area: documentation

#4887 hv: vtd: fix potential dead loop if qi request timeout
  hypervisor/arch/x86/vtd.c
Labels: CI: Tracked On Pass

#4890 acrn-config: add RDT configurable item for QEMU sdc xml
  misc/acrn-config/xmls/config-xmls/qemu/sdc.xml
Labels: CI: Tracked On Pass

#4858 use variables for installation directories.
  devicemodel/Makefile
  hypervisor/Makefile
  misc/acrn-manager/Makefile
  misc/acrnbridge/Makefile
  misc/tools/acrn-crashlog/Makefile
  misc/tools/acrnlog/Makefile
  misc/tools/acrntrace/Makefile
  paths.make
Labels: CI: Tracked On Pass

#4891 DM USB: xHCI: Drop commands if slot is disabled
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass

#4888 hv: pci: remove some unnecessary functions
  hypervisor/hw/pci.c
  hypervisor/include/hw/pci.h
Labels: CI: Tracked On Pass

#4895 DM USB: xHCI: [REVERTME] release memory on port resetting.
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
  devicemodel/include/usb_core.h
Labels: CI: Tracked On Pass, release_2.0

#4894 doc: specify component versions used by Kata-on-ACRN tutorial
  doc/tutorials/run_kata_containers.rst
Labels: area: documentation

#4899 doc: tweak kata tutorial pre-requisites
  doc/tutorials/run_kata_containers.rst
Labels: area: documentation

#4865 doc: add shared memory based inter-vm communication introduction
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/images/ivshmem-image1.png
  doc/developer-guides/hld/ivshmem-hld.rst
Labels: area: documentation

#4902 doc: edit ivshmem hld doc
  doc/developer-guides/hld/ivshmem-hld.rst
Labels: area: documentation

#4903 doc: fix columns issue with 404 page display
  doc/404.rst
Labels: area: documentation

#4905 doc: update ivshmem image with corrections
  doc/developer-guides/hld/images/ivshmem-image1.png
Labels: area: documentation

#4909 debug: dump more info when walk guest page table.
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/guest/guest_memory.c
  hypervisor/arch/x86/guest/instr_emul.c
  hypervisor/arch/x86/guest/vlapic.c
  hypervisor/debug/sbuf.c
  hypervisor/include/arch/x86/cpu.h
  hypervisor/include/arch/x86/guest/guest_memory.h
Labels: CI: Tracked On Pass, Coding Guidelines: PASS, release_2.0

#4911 doc: add dependencies for building acrn-libvirt independently
  doc/tutorials/setup_openstack_libvirt.rst
Labels: area: documentation

#4919 doc: update tools docs to use vm-ubuntu name
  misc/acrn-manager/README.rst
Labels: area: documentation

#4906 doc:Refine GVT-d tutorial
  doc/tutorials/gpu-passthru.rst
Labels: area: documentation

#4917 doc: more updates to ivshmem image and doc
  doc/developer-guides/hld/images/ivshmem-image1.png
  doc/developer-guides/hld/ivshmem-hld.rst
Labels: area: documentation

#4920 DM USB: xHCI: Fix XHCI_GET_SLOT value check issue
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass, release_2.0

#4922 doc: fix broken links to pre-built images (release 1.6.1)
  doc/tutorials/cl_servicevm.rst
Labels: area: documentation

#4923 doc: update links to pre-built images
  doc/getting-started/rt_industry.rst
Labels: area: documentation

#4921 doc: add inter-vm communication example
  doc/developer-guides/hld/ivshmem-hld.rst
Labels: area: documentation

#4915 HV: correct mmap info for multiboot2
  hypervisor/boot/multiboot.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#4929 doc: update the 'ivshmem' HLD
  doc/developer-guides/hld/images/ivshmem-architecture.png
  doc/developer-guides/hld/images/ivshmem-image1.png
  doc/developer-guides/hld/ivshmem-hld.rst
Labels: area: documentation

#4927 doc: update acrn_configuration_tool tutorial for RDT feature
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#4931 doc: Update the GSG for the Industrial scenario with Ubuntu
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#4968 HV: Fix split-locked access detection is disabled by default
  hypervisor/arch/x86/cpu.c
Labels: release_2.0

#4971 release_2.0: hv: vpci: a minor fix about is_zombie_vf
  hypervisor/dm/vpci/vpci_priv.h
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/dm/vpci.h
Labels: release_2.0

#4961 hv: ept: wrap a function to do guest ept flush
  hypervisor/arch/x86/guest/ept.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS

#4972 doc: more release notes 2.0 edits
  doc/develop.rst
  doc/release_notes/release_notes_2.0.rst
Labels: area: documentation

#4969 doc: refine ivshmem architecture diagram
  doc/developer-guides/hld/images/ivshmem-architecture.png
Labels: area: documentation

#4974 Build: disable zero length array warning
  hypervisor/Makefile
Labels: CI: Tracked On Pass

#4977 acrn-config: Add missing MBA_delay configuration in scenario xml
  misc/acrn-config/board_config/board_c.py
  misc/acrn-config/hv_config/hv_item.py
  misc/acrn-config/library/common.py
  misc/acrn-config/library/hv_cfg_lib.py
  misc/acrn-config/scenario_config/scenario_cfg_gen.py
Labels: CI: Tracked On Pass

#4985 doc: update Ubuntu GSG for ACRN V2.0.
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#4984 Doc: v2.0 release notes
  doc/release_notes/release_notes_2.0.rst
Labels: area: documentation

#4986 doc: add 2.0 to doc version selector
  doc/conf.py
Labels: area: documentation

#4988 doc: update Ubuntu GSG with 2.0 fixes
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#4979 Change to a permissive check with broken DMAR table
  hypervisor/acpi_parser/dmar_parse.c
  hypervisor/hw/pci.c
Labels: CI: Tracked On Pass, Coding Guidelines: PASS
