Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-09, with the labels that each got.

#6529 release_2.6: hv: minor change to SMBIOS version check
  hypervisor/quirks/security_vm_fixup.c
Labels: CI: Tracked On Pass, release_2.6

#6524 hv: initialize host IA32_PAT MSR
  hypervisor/arch/x86/mmu.c
Labels: CI: Tracked On Pass

#6531 config_tools: update scenario xml file on ehl-crb-b platform
  misc/config_tools/data/ehl-crb-b/hybrid.xml
Labels: CI: Tracked On Pass

#6532 config_tools: update scenario xml file on ehl-crb-b platform
  misc/config_tools/data/ehl-crb-b/hybrid.xml
Labels: CI: Tracked On Pass, release_2.6

#6472 Doc: ACRN on QEMU changed to CPU Named Model
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation

#6512 doc: update usage of zephyr as pre-launched VM kernel
  doc/tutorials/using_hybrid_mode_on_nuc.rst
Labels: area: documentation

#6543 doc: fix broken links to network scripts in HLD
  doc/developer-guides/hld/virtio-net.rst
Labels: area: documentation

#6536 HV: Fix the problem of copy fail when booting pre-launched VMs
  hypervisor/arch/x86/guest/ve820.c
  hypervisor/include/dm/vacpi.h
Labels: CI: Tracked On Pass, release_2.5

#6534 ACRN:DM Release resource when destroy the device
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
  devicemodel/include/usb_core.h
  devicemodel/include/usb_pmapper.h
Labels: CI: Tracked On Pass

#6540 [release 2.5]board_inspector/cli: export PATH to the legacy board parser
  misc/config_tools/board_inspector/cli.py
Labels: CI: Tracked On Pass, release_2.5

#6537 config_tools: support SRIOV based GPU sharing in launch script
  misc/config_tools/launch_config/com.py
  misc/config_tools/launch_config/pt.py
Labels: CI: Tracked On Pass, release_2.6

#6541 release_2.6: hv: mmiodev: a minor bug fix about refine acrn_mmiodev data structure
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/vgpio.c
  hypervisor/include/dm/vgpio.h
Labels: CI: Tracked On Pass, release_2.6

#6546 hv: Avoid using SMBIOS major version
  hypervisor/quirks/security_vm_fixup.c
Labels: CI: Tracked On Pass

#6550 doc: tweak GSG DX issues
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6526 config-tools: refine misc_cfg.h.xsl and lib.xsl
  misc/config_tools/xforms/lib.xsl
  misc/config_tools/xforms/misc_cfg.h.xsl
Labels: CI: Tracked On Pass

#6483 config_tools: update the regex range of online cpu
  misc/config_tools/launch_config/com.py
Labels: CI: Tracked On Pass

#6549 config_tools: rename UI menu
  misc/config_tools/config_app/templates/base.html
  misc/config_tools/config_app/templates/launch.html
  misc/config_tools/config_app/templates/scenario.html
Labels: CI: Tracked On Pass

#6548 hv: v2.5: enable CAT for tgl-rvp
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/arch/x86/rdt.c
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/tgl-rvp.xml
Labels: CI: Tracked On Pass, release_2.5

#6535 crashlog: fix build issue with e2fsprogs v1.46.2
  misc/debug_tools/acrn_crashlog/acrnprobe/loop.c
Labels: CI: Tracked On Pass

#6555 config_tools: populate default values in scenario XML
  hypervisor/scripts/makefile/config.mk
  misc/config_tools/scenario_config/default_populator.py
Labels: CI: Tracked On Pass

#6361 Makefile: add missing deps in top-level and hypervisor Makefile
  Makefile
  hypervisor/Makefile
Labels: CI: Tracked On Pass

#6556 hv: nested: improvement and performance optimization
  hypervisor/arch/x86/guest/nested.c
  hypervisor/include/arch/x86/asm/guest/nested.h
Labels: CI: Tracked On Pass

#6558 dm: pci: destory reseverd PIO BAR when deinit passthrough PCI device
  devicemodel/hw/pci/passthrough.c
Labels: CI: Tracked On Pass, release_2.6

#6560 doc: Remove empty section marked "TBD"
  doc/developer-guides/hld/hv-ioc-virt.rst
Labels: area: documentation

#6506 config-tools: assign a fixed address to log area start address
  misc/config_tools/static_allocators/gpa.py
Labels: CI: Tracked On Pass

#6567 doc: starting draft for v2.6 release notes
  doc/release_notes/release_notes_2.6.rst
Labels: area: documentation

#6568 doc: update enable PTM instructions
  doc/tutorials/enable_ptm.rst
Labels: area: documentation

#6569 doc: add documentation updates to release notes
  doc/release_notes/release_notes_2.6.rst
Labels: area: documentation

#6566 config_tools: adjust the execution order of pci_stub command
  misc/config_tools/launch_config/pt.py
Labels: CI: Tracked On Pass

#6570 hv: pci: fix a minor bug about is_pci_cfg_multifunction
  hypervisor/include/hw/pci.h
Labels: CI: Tracked On Pass

#6573 misc: acrn_trace: enlarge DEV_PATH_LEN
  misc/debug_tools/acrn_trace/acrntrace.h
Labels: CI: Tracked On Pass

#6539 ACRN:HV: Normalize hypervisor help output format
  hypervisor/debug/shell.c
Labels: CI: Tracked On Pass

#6581 doc: update README for TCM meeting change
  README.rst
Labels: area: documentation

#6586 add vmx capability check
  hypervisor/arch/x86/cpu_caps.c
Labels: CI: Tracked On Pass

#6580 doc: Add project CONTRIBUTING repo page
  CONTRIBUTING.rst
  doc/developer-guides/contribute_guidelines.rst
Labels: area: documentation

#6579 doc: update What is ACRN introduction
  doc/developer-guides/hld/hld-overview.rst
  doc/introduction/images/ACRN-Hybrid-RT.png
  doc/introduction/images/ACRN-Industry.png
  doc/introduction/images/ACRN-Logical-Partition.png
  doc/introduction/images/ACRN-V2-SDC-scenario.png
  doc/introduction/images/ACRN-V2-industrial-scenario.png
  doc/introduction/images/ACRN-hybrid-rt-example.png
  doc/introduction/images/ACRN-industry-example.png
  doc/introduction/images/ACRN-partitioned-example.png
  doc/introduction/images/VMX-brief.png
  doc/introduction/images/architecture.png
  doc/introduction/images/boot-flow-2.dot
  doc/introduction/images/boot-flow.dot
  doc/introduction/images/device-model.png
  doc/introduction/images/io-emulation-path.png
  doc/introduction/images/virtio-architecture.png
  doc/introduction/images/virtio-framework-kernel.png
  doc/introduction/images/virtio-framework-userland.png
  doc/introduction/index.rst
Labels: area: documentation

#6593 Makefile: fix wrong reference to board XML and skip binary in diffconfig
  hypervisor/scripts/makefile/config.mk
Labels: CI: Tracked On Pass, release_2.6

#6594 Makefile: fix wrong reference to board XML and skip binary in diffconfig
  hypervisor/scripts/makefile/config.mk
Labels: CI: Tracked On Pass

#6583 doc: update documentation and grub file
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6589 doc: add virtio input element in config doc
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#6595 doc: fix mispellings and formatting
  doc/developer-guides/c_coding_guidelines.rst
  doc/developer-guides/contribute_guidelines.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/graphviz.rst
  doc/developer-guides/hld/hld-APL_GVT-g.rst
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/hv-interrupt.rst
  doc/developer-guides/hld/hv-rdt.rst
  doc/developer-guides/hld/hv-startup.rst
  doc/developer-guides/hld/hv-vm-management.rst
  doc/developer-guides/hld/virtio-console.rst
  doc/developer-guides/trusty.rst
  doc/getting-started/getting-started.rst
  doc/introduction/index.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/rtvm_performance_tips.rst
  doc/tutorials/sgx_virtualization.rst
  doc/tutorials/using_serial_port.rst
  doc/tutorials/waag-secure-boot.rst
Labels: area: documentation

#6596 doc: finish renaming vmh to hsm
  doc/developer-guides/VBSK-analysis.rst
  doc/developer-guides/hld/hld-APL_GVT-g.rst
  doc/developer-guides/hld/virtio-net.rst
Labels: area: documentation

#6597 doc: cleanup obsolete nocl redirect doc
  doc/nocl.rst
Labels: area: documentation

#6600 doc: update release notes for v2.6 on configuration upgrades
  doc/release_notes/release_notes_2.6.rst
Labels: area: documentation

#6604 doc: remove remaining GVT-g documentation
  doc/developer-guides/hld/hld-APL_GVT-g.rst
  doc/developer-guides/hld/hld-emulated-devices.rst
  doc/developer-guides/hld/hv-vt-d.rst
  doc/developer-guides/hld/images/APL_GVT-g-DM.png
  doc/developer-guides/hld/images/APL_GVT-g-access-patterns.png
  doc/developer-guides/hld/images/APL_GVT-g-api-forwarding.png
  doc/developer-guides/hld/images/APL_GVT-g-arch.png
  doc/developer-guides/hld/images/APL_GVT-g-direct-display.png
  doc/developer-guides/hld/images/APL_GVT-g-display-virt.png
  doc/developer-guides/hld/images/APL_GVT-g-full-pic.png
  doc/developer-guides/hld/images/APL_GVT-g-graphics-arch.png
  doc/developer-guides/hld/images/APL_GVT-g-hyper-dma.png
  doc/developer-guides/hld/images/APL_GVT-g-indirect-display.png
  doc/developer-guides/hld/images/APL_GVT-g-interrupt-virt.png
  doc/developer-guides/hld/images/APL_GVT-g-ive-use-case.png
  doc/developer-guides/hld/images/APL_GVT-g-mediated-pass-through.png
  doc/developer-guides/hld/images/APL_GVT-g-mem-part.png
  doc/developer-guides/hld/images/APL_GVT-g-pass-through.png
  doc/developer-guides/hld/images/APL_GVT-g-per-vm-shadow.png
  doc/developer-guides/hld/images/APL_GVT-g-perf-critical.png
  doc/developer-guides/hld/images/APL_GVT-g-plane-based.png
  doc/developer-guides/hld/images/APL_GVT-g-scheduling-policy.png
  doc/developer-guides/hld/images/APL_GVT-g-scheduling.png
  doc/developer-guides/hld/images/APL_GVT-g-shared-shadow.png
  doc/developer-guides/hld/images/APL_GVT-g-workload.png
  doc/developer-guides/images/GVT-g-porting-image1.png
  doc/glossary.rst
  doc/release_notes/release_notes_0.1.rst
  doc/release_notes/release_notes_1.0.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/user-guides/acrn-dm-parameters.rst
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#6599 config_tools: populate default values to all nodes
  misc/config_tools/scenario_config/default_populator.py
Labels: CI: Tracked On Pass

#6563 config-tools: refine acrn:is-tpm-passthrough-board
  misc/config_tools/xforms/lib.xsl
  misc/config_tools/xforms/misc_cfg.h.xsl
Labels: CI: Tracked On Pass

#6605 doc: Add CODE_OF_CONDUCT to project repo
  CODE_OF_CONDUCT.rst
Labels: area: documentation

#6607 doc: update release notes with new features
  doc/release_notes/release_notes_2.6.rst
Labels: area: documentation

#6576 Doc: launch L2 guest with ovmf for ACRN on QEMU
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation

#6601 doc: Steps to update hybrid and logic_Partition documents
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#6614 doc: update serial port instructions in scenario GSGs
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#6591 hv: add priority based scheduler
  hypervisor/Makefile
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/common/hv_main.c
  hypervisor/common/sched_prio.c
  hypervisor/common/schedule.c
  hypervisor/include/arch/x86/asm/per_cpu.h
  hypervisor/include/arch/x86/asm/vm_config.h
  hypervisor/include/common/schedule.h
  misc/config_tools/library/hv_cfg_lib.py
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
  misc/config_tools/xforms/vm_configurations.c.xsl
Labels: CI: Tracked On Pass, doc: needed

#6602 hv:change log level for check_vmx_ctrl
  hypervisor/arch/x86/guest/vmcs.c
Labels: CI: Tracked On Pass

#6619 doc: add iomem kernel parameter for board inspector
  doc/getting-started/getting-started.rst
  misc/config_tools/board_inspector/README
Labels: area: documentation, CI: Tracked On Pass

#6622 doc: remove enable ptm tutorial
  doc/develop.rst
  doc/release_notes/release_notes_2.6.rst
  doc/tutorials/enable_ptm.rst
Labels: area: documentation

#6621 config-tools: pci devices' io-ports passthrough
  misc/config_tools/acpi_gen/asl_gen.py
  misc/config_tools/static_allocators/gpa.py
Labels: CI: Tracked On Pass

#6617 HV: init e820 before init paging
  hypervisor/arch/x86/cpu.c
  hypervisor/boot/boot.c
  hypervisor/boot/multiboot/multiboot2.c
Labels: CI: Tracked On Pass

#6616 doc: Update logical_partition documentation
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#6624 doc: update 'asa.rst' for 2.6 release
  doc/asa.rst
Labels: area: documentation

#6628 doc: cleanup/update glossary terms
  doc/glossary.rst
Labels: area: documentation

#6629 doc: update checkout branch in GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6632 Doc: Add known issue and fixed issue in release note
  doc/release_notes/release_notes_2.6.rst
Labels: area: documentation

#6633 doc: fix utf8 chars and missing EOF newlines
  doc/develop.rst
  doc/reference/hv-make-options.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/acrn_configurator_tool.rst
  doc/tutorials/board_inspector_tool.rst
Labels: area: documentation

#6634 doc: remove draft status on 2.6 release notes
  doc/release_notes/release_notes_2.6.rst
Labels: area: documentation

#6635 doc: update redirects for deleted docs
  doc/conf.py
  doc/getting-started/roscube/roscube-gsg.rst
Labels: area: documentation

#6638 doc: add v2.6 to doc menu selector
  doc/conf.py
Labels: area: documentation

#6590 config_tools: clean up board folders under data directory
  misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/partitioned.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_laag.xml
  misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/ehl-crb-b/shared.xml
  misc/config_tools/data/ehl-crb-b/shared_launch_1uos_hardrt.xml
  misc/config_tools/data/ehl-crb-b/shared_launch_1uos_vxworks.xml
  misc/config_tools/data/ehl-crb-b/shared_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/shared_launch_2uos.xml
  misc/config_tools/data/ehl-crb-b/shared_launch_6uos.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/nuc7i7dnb/nuc7i7dnb.xml
  misc/config_tools/data/nuc7i7dnb/partitioned.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/nuc7i7dnb/sdc_launch_1uos_laag.xml
  misc/config_tools/data/nuc7i7dnb/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/nuc7i7dnb/shared.xml
  misc/config_tools/data/nuc7i7dnb/shared_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc7i7dnb/shared_launch_1uos_vxworks.xml
  misc/config_tools/data/nuc7i7dnb/shared_launch_1uos_waag.xml
  misc/config_tools/data/nuc7i7dnb/shared_launch_2uos.xml
  misc/config_tools/data/nuc7i7dnb/shared_launch_6uos.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/tgl-rvp/partitioned.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/tgl-rvp/sdc_launch_1uos_laag.xml
  misc/config_tools/data/tgl-rvp/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/tgl-rvp/shared.xml
  misc/config_tools/data/tgl-rvp/shared_launch_1uos_waag.xml
  misc/config_tools/data/tgl-rvp/shared_launch_2uos.xml
  misc/config_tools/data/tgl-rvp/shared_launch_6uos.xml
  misc/config_tools/data/tgl-rvp/tgl-rvp.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i7/partitioned.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
  misc/config_tools/data/whl-ipc-i7/sdc_launch_1uos_laag.xml
  misc/config_tools/data/whl-ipc-i7/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/whl-ipc-i7/shared.xml
  misc/config_tools/data/whl-ipc-i7/shared_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i7/shared_launch_1uos_vxworks.xml
  misc/config_tools/data/whl-ipc-i7/shared_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i7/shared_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i7/shared_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i7/whl-ipc-i7.xml
Labels: CI: Tracked On Pass

#6639 config_tools: schema: revert to old schema
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass, release_2.6

#6640 config_tools: update board name in makefile
  hypervisor/scripts/makefile/config.mk
Labels: CI: Tracked On Pass

#6642 doc: update images with VHM to use HSM
  doc/developer-guides/hld/images/dm-image108.png
  doc/developer-guides/hld/images/dm-image80.png
  doc/developer-guides/hld/images/dm-image94.png
  doc/developer-guides/hld/images/dm-image96.png
  doc/developer-guides/hld/images/dm-image99.png
  doc/developer-guides/hld/images/hld-pm-image28.png
  doc/developer-guides/hld/images/ioem-image92.png
  doc/developer-guides/hld/images/network-virt-arch.png
  doc/developer-guides/hld/images/security-image-HC-interface-restriction.png
  doc/developer-guides/hld/images/split-dm-image2.png
  doc/developer-guides/hld/images/split-dm-image3.png
  doc/developer-guides/hld/images/virtio-blk-image01.png
  doc/developer-guides/hld/images/virtio-gpio-1.png
  doc/developer-guides/hld/images/virtio-hld-image58.png
  doc/developer-guides/hld/images/virtio-hld-image60.png
  doc/developer-guides/hld/images/virtio-hld-image71.png
  doc/developer-guides/hld/images/virtio-i2c-1.png
  doc/developer-guides/images/vbsk-image2.png
Labels: area: documentation

#5893 doc: Update "Enable S5 in ACRN" tutorial
  doc/tutorials/enable_s5.rst
Labels: area: documentation

#6641 doc: GSG apt install command DX improvement
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6646 doc: missed one more VHM in images
  doc/developer-guides/hld/images/virtio-hld-image58.png
Labels: area: documentation
