Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-02, with the labels that each got.

#5679 dm: fix compilation issue with gcc10
  devicemodel/include/acpi.h
Labels: CI: Tracked On Pass

#5680 doc: update CODEOWNERS for tech docs
  CODEOWNERS
Labels: CI: Tracked On Pass

#5685 config-tools: validate the scenario against schema
  misc/config_tools/library/common.py
  misc/config_tools/scenario_config/scenario_cfg_gen.py
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass

#5686 hv: hypercall: prevent sos can touch hv/pre-launched VM resource
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/rtcm.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/guest/ept.h
Labels: CI: Tracked On Pass

#5694 config-tools: check vmsix enablement for ehl-crb-b
  misc/config_tools/board_config/vbar_base_h.py
Labels: CI: Tracked On Pass

#5696 config_tools: addSW SRAM config
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/tgl-rvp/industry.xml
Labels: CI: Tracked On Pass

#5691 doc: remove Kconfig reference documentation
  doc/Makefile
  doc/develop.rst
  doc/developer-guides/hld/hld-trace-log.rst
  doc/developer-guides/hld/hv-config.rst
  doc/faq.rst
  doc/reference/kconfig/readme.txt
  doc/release_notes/release_notes_0.1.rst
  doc/scripts/genrest.py
  doc/scripts/requirements.txt
  doc/tutorials/rtvm_performance_tips.rst
  doc/tutorials/using_grub.rst
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#5701 doc: cleanup xsd-derived config doc text
  doc/reference/config-options.rst
  doc/scripts/configdoc.xsl
  doc/tutorials/enable_ivshmem.rst
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass

#5703 doc: remove obsolete GVT-g kernel parameters
  doc/user-guides/images/i915-image1.png
  doc/user-guides/images/i915-image2.png
  doc/user-guides/images/i915-image3.png
  doc/user-guides/images/i915-image4.png
  doc/user-guides/images/i915-image5.png
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#5709 dm: resize the vm_config buffer in 'vm_get_config()'
  devicemodel/core/vmmapi.c
Labels: CI: Tracked On Pass

#5713 DM: xHCI: Fix the USB3.2 device recognition problem.
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
Labels: CI: Tracked On Pass

#5715 [ACRN-v2.4 branch]dm: resize the vm_config buffer in 'vm_get_config()'
  devicemodel/core/vmmapi.c
Labels: CI: Tracked On Pass, release_2.4

#5706 config-tools: add validate_scenario_schema
  misc/config_tools/scenario_config/scenario_cfg_gen.py
Labels: CI: Tracked On Pass, release_2.4

#5707 config-tools: add validate_scenario_schema
  misc/config_tools/scenario_config/scenario_cfg_gen.py
Labels: CI: Tracked On Pass

#5711 config_tools: is_tpm_passthru is checked by scenario config
  misc/config_tools/library/board_cfg_lib.py
Labels: CI: Tracked On Pass, release_2.4

#5716 config_tools: is_tpm_passthru is checked by scenario config
  misc/config_tools/library/board_cfg_lib.py
Labels: CI: Tracked On Pass

#5663 doc: add script to build acrn ovmf with GOP driver
  doc/static/downloads/build_acrn_ovmf.sh
  doc/tutorials/gpu-passthru.rst
Labels: area: documentation

#5727 doc: update debian ISO image version number
  doc/tutorials/running_deb_as_serv_vm.rst
Labels: area: documentation

#5728 doc: fix layout of dm-params
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#5729 doc: update title and headings for doc build
  doc/tutorials/docbuild.rst
Labels: area: documentation

#5724 config_tools: change generic folder to generic_board folder in config
  misc/config_tools/config_app/controller.py
  misc/config_tools/config_app/views.py
  misc/config_tools/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass

#5725 config_tools: change generic folder to generic_board folder in config…
  misc/config_tools/config_app/controller.py
  misc/config_tools/config_app/views.py
  misc/config_tools/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass, release_2.4

#5734 OVMF release v2.4
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_CODE.fd
  devicemodel/bios/OVMF_CODE_debug.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#5730 doc: test for simple xsd edit
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass

#5739 config_tools: update fusa_partition scenario
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
Labels: CI: Tracked On Pass, release_2.4

#5745 doc: update OpenStack and libvirt tutorial
  doc/tutorials/images/OpenStack-06a-create-image-browse.png
  doc/tutorials/images/OpenStack-06b-create-image-select.png
  doc/tutorials/images/OpenStack-06e-create-image.png
  doc/tutorials/images/OpenStack-07a-create-flavor.png
  doc/tutorials/images/OpenStack-07b-flavor-created.png
  doc/tutorials/images/OpenStack-10a-launch-instance-name.png
  doc/tutorials/images/OpenStack-10b-no-new-vol-select-allocated.png
  doc/tutorials/images/OpenStack-10c-select-flavor.png
  doc/tutorials/images/OpenStack-10d-flavor-selected.png
  doc/tutorials/images/OpenStack-10f-select-security-group.png
  doc/tutorials/images/OpenStack-11-wait-for-running-create-snapshot.png
  doc/tutorials/images/OpenStack-11a-manage-floating-ip.png
  doc/tutorials/images/OpenStack-12b-running-topology-instance.png
  doc/tutorials/images/OpenStack-12d-compute-hypervisor.png
  doc/tutorials/setup_openstack_libvirt.rst
Labels: area: documentation

#5748 doc: fix layout of release notes after title case fix
  doc/release_notes/release_notes_0.7.rst
  doc/release_notes/release_notes_0.8.rst
  doc/release_notes/release_notes_1.0.rst
  doc/release_notes/release_notes_1.1.rst
  doc/release_notes/release_notes_1.2.rst
Labels: area: documentation

#5743 doc: fix misspellings in config option doc
  doc/scripts/configdoc.xsl
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass

#5750 doc: update a few mis-handled titles
  doc/asa.rst
  doc/developer-guides/hld/hld-security.rst
  doc/release_notes/release_notes_0.1.rst
  doc/release_notes/release_notes_0.2.rst
  doc/release_notes/release_notes_0.3.rst
  doc/release_notes/release_notes_0.4.rst
  doc/release_notes/release_notes_0.5.rst
  doc/release_notes/release_notes_0.6.rst
  doc/release_notes/release_notes_0.7.rst
  doc/release_notes/release_notes_0.8.rst
  doc/release_notes/release_notes_1.0.1.rst
  doc/release_notes/release_notes_1.0.2.rst
  doc/release_notes/release_notes_1.0.rst
  doc/release_notes/release_notes_1.1.rst
  doc/release_notes/release_notes_1.2.rst
  doc/release_notes/release_notes_1.3.rst
  doc/release_notes/release_notes_1.4.rst
  doc/release_notes/release_notes_1.5.rst
  doc/release_notes/release_notes_1.6.1.rst
  doc/release_notes/release_notes_1.6.rst
  doc/release_notes/release_notes_2.0.rst
  doc/release_notes/release_notes_2.1.rst
  doc/release_notes/release_notes_2.2.rst
  doc/release_notes/release_notes_2.3.rst
Labels: area: documentation

#5733 OVMF release v2.4
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_CODE.fd
  devicemodel/bios/OVMF_CODE_debug.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass, release_2.4

#5751 doc: update doc build instructions
  doc/tutorials/docbuild.rst
  doc/tutorials/images/doc-gen-flow.dot
  doc/tutorials/images/doc-gen-flow.png
Labels: area: documentation

#5759 doc: update our FAQ section
  doc/faq.rst
Labels: area: documentation

#5757 config_tools: fix VM boot issue for fusa_partition scenario
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
Labels: CI: Tracked On Pass, release_2.4

#5755 config_tools: add PTCT configs
  misc/config_tools/acpi_template/ehl-crb-b/PTCT
  misc/config_tools/acpi_template/tgl-rvp/PTCT
  misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
Labels: CI: Tracked On Pass, release_2.4

#5756 config_tools: add PTCT configs
  misc/config_tools/acpi_template/ehl-crb-b/PTCT
  misc/config_tools/acpi_template/tgl-rvp/PTCT
  misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
Labels: CI: Tracked On Pass

#5762 config-tools: ivshmem support to be shared by multiple vms
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass, release_2.4

#5764 config_tools: update fusa_partition scenario
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
Labels: CI: Tracked On Pass

#5758 doc: update another few mis-handled titles
  doc/api/GVT-g_api.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-trace-log.rst
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/developer-guides/hld/hv-partitionmode.rst
  doc/developer-guides/hld/ivshmem-hld.rst
  doc/developer-guides/hld/virtio-blk.rst
  doc/developer-guides/hld/virtio-gpio.rst
  doc/developer-guides/hld/virtio-i2c.rst
  doc/tutorials/acrn-secure-boot-with-grub.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/realtime_performance_tuning.rst
  doc/tutorials/trustyACRN.rst
  doc/tutorials/using_windows_as_uos.rst
  doc/tutorials/using_yp.rst
  doc/user-guides/acrn-shell.rst
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#5765 DM: xHCI: Fix the USB3.2 device recognition problem.
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
Labels: CI: Tracked On Pass, release_2.4

#5774 hv: Fix incorrect struct definition for ir_bits
  hypervisor/include/arch/x86/apicreg.h
Labels: CI: Tracked On Pass

#5760 acrn-config: remove obsolete kernel parameters from APL configurations
  misc/config_tools/data/apl-mrb/hybrid.xml
  misc/config_tools/data/apl-mrb/industry.xml
  misc/config_tools/data/apl-mrb/sdc.xml
  misc/config_tools/data/apl-up2/hybrid.xml
  misc/config_tools/data/apl-up2/industry.xml
  misc/config_tools/data/apl-up2/sdc.xml
Labels: CI: Tracked On Pass

#5763 config-tools: ivshmem support to be shared by multiple vms
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass

#5787 config_tools: update sbl version of ehl-crb-b.xml
  misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
Labels: CI: Tracked On Pass, release_2.4

#5786 config_tools: add sanity check for PSRAM and RDT
  misc/config_tools/schema/config.xsd
Labels: CI: Tracked On Pass

#5784 config-tools: remove "vuart" poweroff channel from default xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
  misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_laag.xml
  misc/config_tools/data/generic_board/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc6cayh/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_6uos.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_laag.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_2uos.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_6uos.xml
  misc/config_tools/data/nuc7i7dnb/sdc_launch_1uos_laag.xml
  misc/config_tools/data/tgl-rvp/industry_launch_2uos.xml
  misc/config_tools/data/tgl-rvp/sdc_launch_1uos_laag.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i5/sdc_launch_1uos_laag.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i7/sdc_launch_1uos_laag.xml
Labels: CI: Tracked On Pass, release_2.4

#5785 config_tools: add sanity check for PSRAM and RDT
  misc/config_tools/schema/config.xsd
Labels: CI: Tracked On Pass, release_2.4

#5783 config-tools: remove "vuart" poweroff channel from default xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
  misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_laag.xml
  misc/config_tools/data/generic_board/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc6cayh/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_6uos.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_laag.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_2uos.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_6uos.xml
  misc/config_tools/data/nuc7i7dnb/sdc_launch_1uos_laag.xml
  misc/config_tools/data/tgl-rvp/industry_launch_2uos.xml
  misc/config_tools/data/tgl-rvp/sdc_launch_1uos_laag.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i5/sdc_launch_1uos_laag.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i7/sdc_launch_1uos_laag.xml
Labels: CI: Tracked On Pass
