Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-06, with the labels that each got.

#6098 [mainline]hv: update RTCT ACPI table detecting
  hypervisor/acpi_parser/acpi_ext.c
  hypervisor/arch/x86/rtcm.c
  hypervisor/boot/include/acpi.h
  hypervisor/include/arch/x86/asm/rtcm.h
Labels: CI: Tracked On Pass

#6116 config_tools: replace illegal character with escaped character
  misc/config_tools/board_inspector/legacy/parser_lib.py
Labels: release_2.5

#6106 config_tools: add RTCT table support in pre-launched VMs
  misc/config_tools/acpi_gen/acpi_const.py
  misc/config_tools/acpi_gen/asl_gen.py
  misc/config_tools/acpi_gen/bin_gen.py
Labels: CI: Tracked On Pass

#6099 [mainline] Device Model RTCT V2 upgrade
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/hw/platform/acpi/rtct.c
  devicemodel/include/rtct.h
Labels: CI: Tracked On Pass

#6114 config_tools: replace illegal character with escaped character
  misc/config_tools/board_inspector/legacy/parser_lib.py
Labels: CI: Tracked On Pass

#6117 Config_tools: Update get slot logic
  misc/config_tools/data/sample_launch_scripts/nuc/launch_win.sh
  misc/config_tools/launch_config/com.py
  misc/config_tools/library/launch_cfg_lib.py
Labels: CI: Tracked On Pass, release_2.5

#6122 Config_tools: Update tgl-rvp scenario xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
Labels: CI: Tracked On Pass, release_2.5

#6121 dm: NULL check of vq->used in virtio_net_ping_rxq
  devicemodel/hw/pci/virtio/virtio_net.c
Labels: CI: Tracked On Pass, release_2.5

#6124 Config_tools: Update Hybrid Cores
  misc/config_tools/schema/checks/pre_launched_vm_support.xsd
Labels: CI: Tracked On Pass, release_2.5

#6141 config-tools: update qemu.xml
  misc/config_tools/data/qemu/qemu.xml
Labels: CI: Tracked On Pass, release_2.5

#6142 config-tools: update qemu.xml
  misc/config_tools/data/qemu/qemu.xml
Labels: CI: Tracked On Pass

#6127 Revert "config_tools: save board xml when loading from config tool UI"
  misc/config_tools/config_app/views.py
Labels: CI: Tracked On Pass, release_2.5

#6128 release2.5 HV: VPCI: Fix too much of pci_vdev_update_vbar_base log
  hypervisor/dm/vpci/vpci.c
Labels: CI: Tracked On Pass, release_2.5

#6139 config-tools: enable "allow_trigger_s5" through launch.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_aaag.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_aliaag.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_laag.xml
  misc/config_tools/data/apl-up2-n3350/sdc_launch_1uos_laag.xml
  misc/config_tools/data/apl-up2/sdc_launch_1uos_aaag.xml
  misc/config_tools/data/apl-up2/sdc_launch_1uos_laag.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
  misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_laag.xml
  misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/generic_board/industry_launch_2uos.xml
  misc/config_tools/data/nuc11tnbi5/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_waag.xml
  misc/config_tools/data/nuc6cayh/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_6uos.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_laag.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/nuc7i7dnb/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_waag.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_2uos.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_6uos.xml
  misc/config_tools/data/nuc7i7dnb/sdc_launch_1uos_laag.xml
  misc/config_tools/data/nuc7i7dnb/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/tgl-rvp/industry_launch_1uos_waag.xml
  misc/config_tools/data/tgl-rvp/industry_launch_2uos.xml
  misc/config_tools/data/tgl-rvp/industry_launch_6uos.xml
  misc/config_tools/data/tgl-rvp/sdc_launch_1uos_laag.xml
  misc/config_tools/data/tgl-rvp/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i5/sdc_launch_1uos_laag.xml
  misc/config_tools/data/whl-ipc-i5/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i7/sdc_launch_1uos_laag.xml
  misc/config_tools/data/whl-ipc-i7/sdc_launch_1uos_zephyr.xml
  misc/config_tools/launch_config/com.py
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/launch_config/launch_item.py
  misc/config_tools/library/launch_cfg_lib.py
Labels: CI: Tracked On Pass, release_2.5

#6140 config-tools: enable "allow_trigger_s5" through launch.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_aaag.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_aliaag.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_laag.xml
  misc/config_tools/data/apl-up2-n3350/sdc_launch_1uos_laag.xml
  misc/config_tools/data/apl-up2/sdc_launch_1uos_aaag.xml
  misc/config_tools/data/apl-up2/sdc_launch_1uos_laag.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
  misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_laag.xml
  misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/generic_board/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_waag.xml
  misc/config_tools/data/nuc6cayh/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_6uos.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_laag.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/nuc7i7dnb/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_waag.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_2uos.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_6uos.xml
  misc/config_tools/data/nuc7i7dnb/sdc_launch_1uos_laag.xml
  misc/config_tools/data/nuc7i7dnb/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/tgl-rvp/industry_launch_1uos_waag.xml
  misc/config_tools/data/tgl-rvp/industry_launch_2uos.xml
  misc/config_tools/data/tgl-rvp/industry_launch_6uos.xml
  misc/config_tools/data/tgl-rvp/sdc_launch_1uos_laag.xml
  misc/config_tools/data/tgl-rvp/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i5/sdc_launch_1uos_laag.xml
  misc/config_tools/data/whl-ipc-i5/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_waag.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i7/sdc_launch_1uos_laag.xml
  misc/config_tools/data/whl-ipc-i7/sdc_launch_1uos_zephyr.xml
  misc/config_tools/launch_config/com.py
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/launch_config/launch_item.py
  misc/config_tools/library/launch_cfg_lib.py
Labels: CI: Tracked On Pass

#6130 [release_v2.5] dm: validate inputs in vq_endchains
  devicemodel/hw/pci/virtio/virtio.c
Labels: CI: Tracked On Pass, release_2.5

#6148 dm: Reset virtio device before release
  devicemodel/hw/pci/virtio/virtio_audio.c
  devicemodel/hw/pci/virtio/virtio_block.c
  devicemodel/hw/pci/virtio/virtio_console.c
  devicemodel/hw/pci/virtio/virtio_coreu.c
  devicemodel/hw/pci/virtio/virtio_gpio.c
  devicemodel/hw/pci/virtio/virtio_hdcp.c
  devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c
  devicemodel/hw/pci/virtio/virtio_i2c.c
  devicemodel/hw/pci/virtio/virtio_input.c
  devicemodel/hw/pci/virtio/virtio_ipu.c
  devicemodel/hw/pci/virtio/virtio_mei.c
  devicemodel/hw/pci/virtio/virtio_net.c
  devicemodel/hw/pci/virtio/virtio_rnd.c
  devicemodel/hw/pci/virtio/virtio_rpmb.c
Labels: CI: Tracked On Pass, release_2.5

#6156 doc: tweak doc config for v2.3 for CI tool mismatch
  doc/.known-issues/doc/dupdecl.conf
  doc/conf.py
Labels: area: documentation, release_2.3

#6123 Config_tools: Update tgl-rvp scenario xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
Labels: CI: Tracked On Pass

#6150 dm: validate inputs in vq_endchains
  devicemodel/hw/pci/virtio/virtio.c
Labels: CI: Tracked On Pass

#6160 dm: fix memory leakage risk in create_and_inject_vrtct
  devicemodel/hw/platform/acpi/acpi.c
Labels: CI: Tracked On Pass

#6167 hv: deny access to HV owned legacy PIO UART from SOS
  hypervisor/arch/x86/guest/vm.c
  hypervisor/debug/uart16550.c
  hypervisor/include/debug/uart16550.h
  hypervisor/release/console.c
  hypervisor/release/uart16550.c
Labels: CI: Tracked On Pass

#6155 doc: add the content of hugepages/hugepagesz in generic kernel parame…
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation

#6169 hv: Enlarge E820_MAX_ENTRIES to 64
  hypervisor/include/arch/x86/asm/e820.h
Labels: CI: Tracked On Pass, release_2.5

#6171 hv: deny access to HV owned legacy PIO UART from SOS
  hypervisor/arch/x86/guest/vm.c
  hypervisor/debug/uart16550.c
  hypervisor/include/debug/uart16550.h
  hypervisor/release/console.c
  hypervisor/release/uart16550.c
Labels: CI: Tracked On Pass, release_2.5

#6179 config-tools: refine get_pt_intx_table and check_pt_intx
  misc/config_tools/library/common.py
  misc/config_tools/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass

#6180 config-tools: refine get_pt_intx_table and check_pt_intx
  misc/config_tools/library/common.py
  misc/config_tools/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass, release_2.5

#6174 DM: xHCI: Add the trb pointer check
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass, release_2.5

#6159 [release_2.5] dm: remove redundant null check in unregister_mem_init
  devicemodel/core/mem.c
Labels: CI: Tracked On Pass, release_2.5

#6107 Config_tools: Update XML and save board xml when loading from config tool UI
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_rt.xml
  misc/config_tools/data/nuc11tnbi5/industry.xml
  misc/config_tools/data/nuc11tnbi5/industry_launch_2uos.xml
  misc/config_tools/data/nuc11tnbi5/logical_partition.xml
  misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
  misc/config_tools/data/tgl-rvp/tgl-rvp.xml
Labels: CI: Tracked On Pass

#6161 [release_2.5] DM v2.5 bugfix create and inject vrtct
  devicemodel/hw/platform/acpi/acpi.c
Labels: CI: Tracked On Pass, release_2.5

#6158 dm: remove redundant null check in unregister_mem_init
  devicemodel/core/mem.c
Labels: CI: Tracked On Pass

#6182 hv: WA ACRN-6886: Interrupt the target CPU and let it do PI with VMENTRY
  hypervisor/arch/x86/guest/vlapic.c
Labels: CI: Tracked On Pass, release_2.5

#5937 doc: update the ACRN on QEMU tutorial to v2.5
  doc/tutorials/acrn_on_qemu.rst
  doc/tutorials/images/acrn_qemu_4.png
Labels: area: documentation

#6183 doc: fix config option display
  doc/scripts/configdoc.xsl
Labels: area: documentation

#6110 doc: add enabling PTM tutorial and PTM hld discussion
  doc/develop.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/images/PTM-hld-PTM-flow.png
  doc/developer-guides/hld/images/PTM-hld-PTM-passthru.png
  doc/tutorials/enable_ptm.rst
Labels: area: documentation

#6112 doc: update timer HLD doc after modularization
  doc/developer-guides/hld/hv-timer.rst
  hypervisor/include/arch/x86/asm/tsc.h
  hypervisor/include/common/ticks.h
Labels: CI: Tracked On Pass, area: documentation

#6137 doc: update the content about generating board xml
  doc/tutorials/acrn_configuration_tool.rst
  misc/config_tools/board_inspector/README
Labels: CI: Tracked On Pass, area: documentation

#6181 doc: add missing parameters description of launch script xml
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation, make doc fail

#6177 config_tools: clean up the board folders
  misc/config_tools/data/apl-mrb/apl-mrb.xml
  misc/config_tools/data/apl-mrb/hybrid.xml
  misc/config_tools/data/apl-mrb/industry.xml
  misc/config_tools/data/apl-mrb/logical_partition.xml
  misc/config_tools/data/apl-mrb/sdc.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_aaag.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_aliaag.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_laag.xml
  misc/config_tools/data/apl-up2-n3350/apl-up2-n3350.xml
  misc/config_tools/data/apl-up2-n3350/logical_partition.xml
  misc/config_tools/data/apl-up2-n3350/sdc_launch_1uos_laag.xml
  misc/config_tools/data/apl-up2/apl-up2.xml
  misc/config_tools/data/apl-up2/hybrid.xml
  misc/config_tools/data/apl-up2/industry.xml
  misc/config_tools/data/apl-up2/logical_partition.xml
  misc/config_tools/data/apl-up2/sdc.xml
  misc/config_tools/data/apl-up2/sdc_launch_1uos_aaag.xml
  misc/config_tools/data/apl-up2/sdc_launch_1uos_laag.xml
  misc/config_tools/data/generic_board/generic_board.xml
  misc/config_tools/data/nuc6cayh/hybrid.xml
  misc/config_tools/data/nuc6cayh/industry.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_waag.xml
  misc/config_tools/data/nuc6cayh/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_6uos.xml
  misc/config_tools/data/nuc6cayh/logical_partition.xml
  misc/config_tools/data/nuc6cayh/nuc6cayh.xml
  misc/config_tools/data/nuc6cayh/sdc.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_laag.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_zephyr.xml
Labels: CI: Tracked On Pass, release_2.5

#6164 config_tools: add hybrid, hybrid_rt, logical partition scenario on ad…
  misc/config_tools/data/adl-rvp/industry_launch_2uos.xml
  misc/config_tools/data/adl-s-crb/hybrid.xml
  misc/config_tools/data/adl-s-crb/hybrid_rt.xml
  misc/config_tools/data/adl-s-crb/industry_launch_2uos.xml
  misc/config_tools/data/adl-s-crb/logical_partition.xml
Labels: CI: Tracked On Pass, release_2.5

#6196 doc: update doc guidelines for ACRN config options
  doc/developer-guides/doc_guidelines.rst
  doc/tutorials/docbuild.rst
Labels: area: documentation

#6173 DM: xHCI: Check trb pointer before use it
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass

#6193 config-tools: allocate the first unused bar for vmsix
  misc/config_tools/static_allocators/gpa.py
Labels: CI: Tracked On Pass, release_2.5

#6195 config_tools: add the missing GUEST_FLAG_NVMX_ENABLED to common.py
  misc/config_tools/library/common.py
Labels: CI: Tracked On Pass

#6194 config-tools: allocate the first unused bar for vmsix
  misc/config_tools/static_allocators/gpa.py
Labels: CI: Tracked On Pass

#6201 config_tools: update clang-format file
  .clang-format
Labels: CI: Tracked On Pass

#6200 config_tools: update clang-format file
  .clang-format
Labels: CI: Tracked On Pass, release_2.5

#6188 update scenario xml
  misc/config_tools/data/adl-rvp/industry.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_rt.xml
  misc/config_tools/data/nuc11tnbi5/industry.xml
  misc/config_tools/data/nuc11tnbi5/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
Labels: CI: Tracked On Pass, release_2.5

#6187 Update scenario xml
  misc/config_tools/data/adl-rvp/industry.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_rt.xml
  misc/config_tools/data/nuc11tnbi5/industry.xml
  misc/config_tools/data/nuc11tnbi5/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
Labels: CI: Tracked On Pass

#6203 ACRN: DM: Free the console in the unify API
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass, release_2.5

#6205 [Release 2.5] HV: remove unused multiboot.h
  hypervisor/boot/include/multiboot.h
Labels: CI: Tracked On Pass, release_2.5

#6204 HV: ramdisk and kernel load addr improve
  hypervisor/boot/guest/vboot_info.c
Labels: CI: Tracked On Pass

#6210 doc: draft for 2.5 release notes contribution
  doc/release_notes/release_notes_2.5.rst
Labels: area: documentation

#6212 config_tools: Revert "update scenario xml" for MAX_MSIX_TABLE_NUM
  misc/config_tools/data/adl-rvp/industry.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_rt.xml
  misc/config_tools/data/nuc11tnbi5/industry.xml
  misc/config_tools/data/nuc11tnbi5/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
Labels: CI: Tracked On Pass, release_2.5

#6213 config_tools: modify README file
  misc/config_tools/board_inspector/README
Labels: CI: Tracked On Pass, release_2.5

#6220 doc: update TCC feature names in hld overview
  doc/developer-guides/hld/hld-overview.rst
Labels: area: documentation

#6218 doc: clarify doc guidelines
  doc/developer-guides/doc_guidelines.rst
Labels: area: documentation

#6176 config_tools: clean up the board folders
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/getting-started/building-from-source.rst
  doc/tutorials/rdt_configuration.rst
  misc/config_tools/data/apl-mrb/apl-mrb.xml
  misc/config_tools/data/apl-mrb/hybrid.xml
  misc/config_tools/data/apl-mrb/industry.xml
  misc/config_tools/data/apl-mrb/logical_partition.xml
  misc/config_tools/data/apl-mrb/sdc.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_aaag.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_aliaag.xml
  misc/config_tools/data/apl-mrb/sdc_launch_1uos_laag.xml
  misc/config_tools/data/apl-up2-n3350/apl-up2-n3350.xml
  misc/config_tools/data/apl-up2-n3350/logical_partition.xml
  misc/config_tools/data/apl-up2-n3350/sdc_launch_1uos_laag.xml
  misc/config_tools/data/apl-up2/apl-up2.xml
  misc/config_tools/data/apl-up2/hybrid.xml
  misc/config_tools/data/apl-up2/industry.xml
  misc/config_tools/data/apl-up2/logical_partition.xml
  misc/config_tools/data/apl-up2/sdc.xml
  misc/config_tools/data/apl-up2/sdc_launch_1uos_aaag.xml
  misc/config_tools/data/apl-up2/sdc_launch_1uos_laag.xml
  misc/config_tools/data/generic_board/generic_board.xml
  misc/config_tools/data/nuc6cayh/hybrid.xml
  misc/config_tools/data/nuc6cayh/industry.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_vxworks.xml
  misc/config_tools/data/nuc6cayh/industry_launch_1uos_waag.xml
  misc/config_tools/data/nuc6cayh/industry_launch_2uos.xml
  misc/config_tools/data/nuc6cayh/industry_launch_6uos.xml
  misc/config_tools/data/nuc6cayh/logical_partition.xml
  misc/config_tools/data/nuc6cayh/nuc6cayh.xml
  misc/config_tools/data/nuc6cayh/sdc.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_laag.xml
  misc/config_tools/data/nuc6cayh/sdc_launch_1uos_zephyr.xml
Labels: CI: Tracked On Pass, doc: needed

#6217 doc: update supported hardware document
  doc/reference/hardware.rst
Labels: area: documentation

#6215 doc: update GSG with NUC11TNHi5
  doc/getting-started/images/native-ubuntu-on-NVME-3.png
  doc/getting-started/images/native-ubuntu-on-SATA-3.png
  doc/getting-started/images/rt-ind-ubun-hw-1.png
  doc/getting-started/images/rt-ind-ubun-hw-2.png
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#6228 doc: update the "Supported Hardware" document
  doc/reference/hardware.rst
  doc/try.rst
Labels: area: documentation

#6226 doc: updates to the Getting Started Guide
  doc/getting-started/getting-started.rst
  doc/try.rst
Labels: area: documentation

#6230 doc: fix renaming of getting started guide
  doc/conf.py
  doc/getting-started/getting-started.rst
  doc/reference/hardware.rst
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/nvmx_virtualization.rst
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/run_kata_containers.rst
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#6231 doc: resove conflicting edits to supported hardware
  doc/reference/hardware.rst
Labels: area: documentation

#6232 doc: update changed does in release notes
  doc/release_notes/release_notes_2.5.rst
Labels: area: documentation

#6233 doc: fix broken links in redirect list
  doc/conf.py
Labels: area: documentation

#6234 doc: update security advisory for 2.5 release
  doc/asa.rst
Labels: area: documentation

#6222 Update Release Note 2.5 with Upgrade Recommendations
  doc/release_notes/release_notes_2.4.rst
  doc/release_notes/release_notes_2.5.rst
Labels: CI: Tracked On error, area: documentation

#6240 doc: release notes edits
  doc/release_notes/release_notes_2.5.rst
Labels: area: documentation

#6246 doc: add acrn efi-stub user guide
  doc/develop.rst
  doc/tutorials/acrn-secure-boot-with-efi-stub.rst
Labels: area: documentation

#6248 doc: edit efi-stub tutorial
  doc/tutorials/acrn-secure-boot-with-efi-stub.rst
Labels: area: documentation

#6250 doc: update nested virtualization user guide
  doc/tutorials/images/nvmx_cfg_1.png
  doc/tutorials/images/nvmx_cfg_2.png
  doc/tutorials/images/nvmx_cfg_3.png
  doc/tutorials/nvmx_virtualization.rst
Labels: area: documentation

#6251 doc: update v2.5 release notes highlights
  doc/release_notes/release_notes_2.5.rst
Labels: area: documentation

#6243 doc: fix documentation's issue
  doc/getting-started/getting-started.rst
  doc/reference/hardware.rst
  doc/tutorials/acrn_configuration_tool.rst
  misc/config_tools/schema/config.xsd
Labels: CI: Tracked On Pass

#6252 doc: update v2.5 release notes
  doc/release_notes/release_notes_2.5.rst
Labels: area: documentation

#6245 config_tools: remove nuc11tnbi5 scenario xml except industry.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_rt.xml
  misc/config_tools/data/nuc11tnbi5/industry_launch_2uos.xml
  misc/config_tools/data/nuc11tnbi5/logical_partition.xml
Labels: CI: Tracked On Pass, release_2.5

#6254 doc: fix link in hardware doc
  doc/reference/hardware.rst
Labels: area: documentation

#6255 release notes edits
  doc/release_notes/release_notes_2.5.rst
Labels: area: documentation

#6258 doc: remove PTM tutorial for v2.5
  doc/develop.rst
  doc/release_notes/release_notes_2.5.rst
  doc/tutorials/enable_ptm.rst
Labels: area: documentation

#6260 Doc: release notes update
  doc/release_notes/release_notes_2.5.rst
Labels: area: documentation

#6261 doc: push doc updates for v2.5 release
  doc/asa.rst
  doc/conf.py
  doc/develop.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/hld/ahci-hld.rst
  doc/developer-guides/hld/atkbdc-virt-hld.rst
  doc/developer-guides/hld/hld-APL_GVT-g.rst
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/hv-timer.rst
  doc/developer-guides/hld/images/PTM-hld-PTM-flow.png
  doc/developer-guides/hld/images/PTM-hld-PTM-passthru.png
  doc/getting-started/building-from-source.rst
  doc/getting-started/getting-started.rst
  doc/getting-started/images/native-ubuntu-on-NVME-3.png
  doc/getting-started/images/native-ubuntu-on-SATA-3.png
  doc/getting-started/images/rt-ind-ubun-hw-1.png
  doc/getting-started/images/rt-ind-ubun-hw-2.png
  doc/getting-started/rt_industry_ubuntu.rst
  doc/reference/hardware.rst
  doc/release_notes/release_notes_2.4.rst
  doc/release_notes/release_notes_2.5.rst
  doc/scripts/configdoc.xsl
  doc/try.rst
  doc/tutorials/acrn-secure-boot-with-efi-stub.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/acrn_on_qemu.rst
  doc/tutorials/docbuild.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/images/ACRN-Hybrid.png
  doc/tutorials/images/acrn_qemu_4.png
  doc/tutorials/images/hybrid_scenario_on_nuc.png
  doc/tutorials/images/nvmx_1.png
  doc/tutorials/images/nvmx_arch_1.png
  doc/tutorials/nvmx_virtualization.rst
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/run_kata_containers.rst
  doc/tutorials/running_deb_as_serv_vm.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_windows_as_uos.rst
  doc/user-guides/acrn-dm-parameters.rst
  doc/user-guides/kernel-parameters.rst
  misc/config_tools/schema/config.xsd
Labels: area: documentation, release_2.5

#6262 doc: add 2.5 to version menu choice
  doc/conf.py
Labels: area: documentation

#6263 doc: update known issues list in v2.5 release notes
  doc/release_notes/release_notes_2.5.rst
Labels: area: documentation

#6264 doc: update known issues in 2.5 release notes
  doc/release_notes/release_notes_2.5.rst
Labels: area: documentation, release_2.5

#6265 doc: fix doc reference using symbolic link
  doc/tutorials/enable_s5.rst
Labels: area: documentation
