Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-03, with the labels that each got.

#5800 config-tools: Add "ENFORCE_TURNOFF_AC" capability to xml
  misc/config_tools/data/apl-mrb/hybrid.xml
  misc/config_tools/data/apl-mrb/industry.xml
  misc/config_tools/data/apl-mrb/logical_partition.xml
  misc/config_tools/data/apl-mrb/sdc.xml
  misc/config_tools/data/apl-up2-n3350/logical_partition.xml
  misc/config_tools/data/apl-up2/hybrid.xml
  misc/config_tools/data/apl-up2/industry.xml
  misc/config_tools/data/apl-up2/logical_partition.xml
  misc/config_tools/data/apl-up2/sdc.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc6cayh/hybrid.xml
  misc/config_tools/data/nuc6cayh/industry.xml
  misc/config_tools/data/nuc6cayh/logical_partition.xml
  misc/config_tools/data/nuc6cayh/sdc.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: CI: Tracked On Pass, release_2.4

#5794 hv: two minor refine for PSCMCE
  hypervisor/arch/x86/guest/vmx_io.c
  hypervisor/arch/x86/page.c
  hypervisor/arch/x86/pagetable.c
  hypervisor/include/arch/x86/page.h
Labels: CI: Tracked On Pass

#5803 [release_v2.4] hv: fix potential crash in write_protect_page()
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass, release_2.4

#5708 refine ept_flush_leaf_page
  hypervisor/arch/x86/guest/ept.c
Labels: CI: Tracked On Pass

#5809 config_tools: add psram config in launch config
  misc/config_tools/launch_config/com.py
Labels: CI: Tracked On Pass

#5808 config_tools: add psram config in launch config
  misc/config_tools/launch_config/com.py
Labels: CI: Tracked On Pass, release_2.4

#5807 [release_2.4] hv: cpu: remove cache_flush_invalidate_all in cpu_dead
  hypervisor/arch/x86/cpu.c
Labels: CI: Tracked On Pass, release_2.4

#5796 DM: xHCI: Implement the USB PLS Machine flow spec.
  devicemodel/hw/pci/xhci.c
  devicemodel/hw/platform/usb_pmapper.c
Labels: CI: Tracked On Pass

#5799 config-tools: Add "ENFORCE_TURNOFF_AC" capability to xml
  misc/config_tools/data/apl-mrb/hybrid.xml
  misc/config_tools/data/apl-mrb/industry.xml
  misc/config_tools/data/apl-mrb/logical_partition.xml
  misc/config_tools/data/apl-mrb/sdc.xml
  misc/config_tools/data/apl-up2-n3350/logical_partition.xml
  misc/config_tools/data/apl-up2/hybrid.xml
  misc/config_tools/data/apl-up2/industry.xml
  misc/config_tools/data/apl-up2/logical_partition.xml
  misc/config_tools/data/apl-up2/sdc.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc6cayh/hybrid.xml
  misc/config_tools/data/nuc6cayh/industry.xml
  misc/config_tools/data/nuc6cayh/logical_partition.xml
  misc/config_tools/data/nuc6cayh/sdc.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: CI: Tracked On Pass

#5816 doc: reformat acrn-dm-parameters
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#5821 doc: add missing 'mmio@' description to hypervisor parameters
  doc/user-guides/hv-parameters.rst
Labels: area: documentation

#5813 doc: fix incorrect info about serial port availability
  doc/reference/hardware.rst
Labels: area: documentation

#5817 doc: update compile-time configuration HLD
  doc/developer-guides/hld/hv-config.rst
  doc/developer-guides/hld/images/config-image103.png
Labels: area: documentation

#5797 doc: start v2.4 release notes draft
  doc/release_notes/release_notes_2.4.rst
Labels: area: documentation

#5819 config_tools: disable AC
  misc/config_tools/data/apl-mrb/hybrid.xml
  misc/config_tools/data/apl-mrb/industry.xml
  misc/config_tools/data/apl-mrb/logical_partition.xml
  misc/config_tools/data/apl-mrb/sdc.xml
  misc/config_tools/data/apl-up2-n3350/logical_partition.xml
  misc/config_tools/data/apl-up2/hybrid.xml
  misc/config_tools/data/apl-up2/industry.xml
  misc/config_tools/data/apl-up2/logical_partition.xml
  misc/config_tools/data/apl-up2/sdc.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc6cayh/hybrid.xml
  misc/config_tools/data/nuc6cayh/industry.xml
  misc/config_tools/data/nuc6cayh/logical_partition.xml
  misc/config_tools/data/nuc6cayh/sdc.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
  misc/config_tools/schema/config.xsd
Labels: CI: Tracked On Pass, release_2.4

#5824 config_tools: update sbl version of ehl-crb-b.xml
  misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
Labels: CI: Tracked On Pass

#5831 hv: pgtable: rename 'struct memory_ops' to 'struct
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/guest/trusty.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/mmu.c
  hypervisor/arch/x86/page.c
  hypervisor/arch/x86/pagetable.c
  hypervisor/include/arch/x86/guest/vm.h
  hypervisor/include/arch/x86/mmu.h
  hypervisor/include/arch/x86/page.h
  hypervisor/include/arch/x86/pgtable.h
Labels: CI: Tracked On Pass

#5827 config_tools: disable AC
  misc/config_tools/data/apl-mrb/hybrid.xml
  misc/config_tools/data/apl-mrb/industry.xml
  misc/config_tools/data/apl-mrb/logical_partition.xml
  misc/config_tools/data/apl-mrb/sdc.xml
  misc/config_tools/data/apl-up2-n3350/logical_partition.xml
  misc/config_tools/data/apl-up2/hybrid.xml
  misc/config_tools/data/apl-up2/industry.xml
  misc/config_tools/data/apl-up2/logical_partition.xml
  misc/config_tools/data/apl-up2/sdc.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc6cayh/hybrid.xml
  misc/config_tools/data/nuc6cayh/industry.xml
  misc/config_tools/data/nuc6cayh/logical_partition.xml
  misc/config_tools/data/nuc6cayh/sdc.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
  misc/config_tools/schema/config.xsd
Labels: CI: Tracked On Pass

#5810 Makefile: enhance misc/Makefile for more intuitive usage
  Makefile
  devicemodel/Makefile
  misc/Makefile
Labels: CI: Tracked On Pass

#5837 config-tools: fix "is_tpm_passthru" always return "False"
  misc/config_tools/library/board_cfg_lib.py
Labels: CI: Tracked On Pass, release_2.4

#5835 config-tools: replace "PTDEV_HI_MMIO_START" with "HI_MMIO_START"
  misc/config_tools/board_config/vbar_base_h.py
  misc/config_tools/data/generic_board/generic_code/hybrid/vbar_base.h
  misc/config_tools/data/generic_board/generic_code/hybrid_rt/vbar_base.h
  misc/config_tools/data/generic_board/generic_code/industry/vbar_base.h
  misc/config_tools/data/generic_board/generic_code/logical_partition/vbar_base.h
Labels: CI: Tracked On Pass

#5839 config-tools: fix "is_tpm_passthru" always return "False"
  misc/config_tools/library/board_cfg_lib.py
Labels: CI: Tracked On Pass

#5843 HV: Revert "HV: remove efi support for SOS"
  hypervisor/arch/x86/boot/cpu_primary.S
  hypervisor/arch/x86/configs/vacpi.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/boot/acpi_base.c
  hypervisor/boot/include/acpi.h
  hypervisor/boot/include/multiboot.h
  hypervisor/boot/include/multiboot_std.h
  hypervisor/boot/multiboot/multiboot.c
  hypervisor/boot/multiboot/multiboot2.c
  hypervisor/boot/multiboot/multiboot_priv.h
  hypervisor/common/vm_load.c
  hypervisor/include/arch/x86/zeropage.h
  hypervisor/include/dm/vacpi.h
  hypervisor/include/lib/efi.h
Labels: CI: Tracked On Pass, config_tool_modified, release_2.4

#5846 config_tools: add passthru devices for logical partition scenario on ehl
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
Labels: CI: Tracked On Pass

#5845 config_tools: add passthru devices for logical partition scenario on ehl
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
Labels: CI: Tracked On Pass, release_2.4

#5862 doc: add 'libxml2-utils' to the list of build dependencies
  doc/getting-started/building-from-source.rst
  doc/getting-started/roscube/roscube-gsg.rst
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#5848 doc: update path for config editor and desc for some config items
  doc/tutorials/acrn_configuration_tool.rst
  misc/config_tools/schema/config.xsd
Labels: CI: Tracked On Pass, area: documentation

#5841 doc: update BDF information for 'uart=' hypervisor parameter
  doc/user-guides/hv-parameters.rst
  hypervisor/debug/dbg_cmd.c
Labels: CI: Tracked On Pass, area: documentation

#5867 hv: WA: Disable advanced feature of apicv to WA ACRN-6886
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/guest/vlapic.c
Labels: CI: Tracked On Pass, release_2.4

#5864 config-tools: loosen IVSHMEM_REGION restriction in schema
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass, release_2.4

#5851 hv: vpci: fix msi enable issue under some cases
  hypervisor/dm/vpci/vmsi.c
Labels: CI: Tracked On Pass

#5855 acrn_manager: create acrnctl configuration folder when starting
  misc/services/acrn_manager/acrnctl.c
Labels: CI: Tracked On Pass

#5856 Makefile: automatically determine the location of 'iasl'
  Makefile
Labels: CI: Tracked On Pass

#5865 config-tools: loosen IVSHMEM_REGION restriction in schema
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass

#5875 Makefile: add pre-requisite before building the hypervisor
  Makefile
Labels: CI: Tracked On Pass

#5884 Makefile: add missing dependencies for parallel execution of make
  hypervisor/Makefile
Labels: CI: Tracked On Pass

#5873 doc: add summary of config changes and upgrading guides
  doc/release_notes/release_notes_2.4.rst
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#5849 doc: update acpica-unix version to latest (20210105)
  doc/getting-started/building-from-source.rst
  doc/getting-started/roscube/roscube-gsg.rst
  doc/getting-started/rt_industry_ubuntu.rst
Labels: area: documentation

#5877 config-tools: modify sample launch scripts
  misc/config_tools/data/sample_launch_scripts/nuc/launch_hard_rt_vm.sh
  misc/config_tools/data/sample_launch_scripts/nuc/launch_uos.sh
Labels: CI: Tracked On Pass

#5878 config-tools: modify sample launch scripts
  misc/config_tools/data/sample_launch_scripts/nuc/launch_hard_rt_vm.sh
  misc/config_tools/data/sample_launch_scripts/nuc/launch_uos.sh
Labels: CI: Tracked On Pass, release_2.4

#5887 doc: update v2.4 release notes
  doc/getting-started/roscube/roscube-gsg.rst
  doc/release_notes/release_notes_2.4.rst
  doc/static/acrn-custom.css
Labels: area: documentation

#5883 Doc: Launch Windows as the Guest VM
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#5850 update-doc-GSG-rt_industry_ubuntu
  doc/getting-started/rt_industry_ubuntu.rst
  doc/tutorials/enable_s5.rst
Labels: area: documentation

#5890 doc: additional release notes edits
  doc/release_notes/release_notes_2.4.rst
Labels: area: documentation

#5892 Doc: update v2.4 release notes
  doc/release_notes/release_notes_2.4.rst
Labels: area: documentation

#5891 doc: update 'enable secure boot in windows'
  doc/tutorials/images/waag_secure_boot_image1.png
  doc/tutorials/images/waag_secure_boot_image2.png
  doc/tutorials/images/waag_secure_boot_image3.png
  doc/tutorials/waag-secure-boot.rst
Labels: area: documentation
