Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-04, with the labels that each got.

#5900 hv: Save/restore MSR_IA32_CSTAR during context switch
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/cpu.h
Labels: CI: Tracked On Pass, release_2.4

#5894 Doc: Update Launch Windows as the Guest VM
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#5902 DM: gvt: Identical mapping for GPU DSM refine to support EHL/TGL
  devicemodel/core/sw_load_common.c
  devicemodel/hw/pci/passthrough.c
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/hw/platform/acpi/rtct.c
  devicemodel/include/pci_core.h
  devicemodel/include/pcireg.h
  devicemodel/include/sw_load.h
Labels: CI: Tracked On Pass, release_2.4

#5904 doc: update release notes
  doc/release_notes/release_notes_2.4.rst
Labels: area: documentation

#5896 hv: Hide HLAT to guest
  hypervisor/arch/x86/guest/vmsr.c
Labels: CI: Tracked On Pass

#5901 DM: gvt: Identical mapping for GPU DSM refine to support EHL/TGL
  devicemodel/core/sw_load_common.c
  devicemodel/hw/pci/passthrough.c
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/hw/platform/acpi/rtct.c
  devicemodel/include/pci_core.h
  devicemodel/include/pcireg.h
  devicemodel/include/sw_load.h
Labels: CI: Tracked On Pass

#5908 doc: add 2.4 to doc version menu
  doc/conf.py
Labels: area: documentation

#5910 doc: remove obsolete .txt file
  doc/tutorials/acrn-config-details.txt
Labels: area: documentation

#5912 config-tools: find the unused bdf based on first unused "dev"
  misc/config_tools/scenario_config/pci_dev_c.py
Labels: CI: Tracked On Pass

#5926 doc: update doc build instructions
  doc/tutorials/docbuild.rst
Labels: area: documentation

#5935 config_tools: remove audio passthru in launch xmls on ehl-crb-b
  misc/config_tools/data/ehl-crb-b/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
Labels: CI: Tracked On Pass

#5933 config-tools: change default industry kata vm id to 7
  misc/config_tools/config_app/views.py
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/industry_launch_6uos.xml
Labels: CI: Tracked On Pass

#5906 doc: make the "logical partitioning" description more generic
  doc/introduction/images/ACRN-Logical-Partition.png
  doc/introduction/index.rst
Labels: area: documentation

#5944 hv: fix some minor bug part2
  hypervisor/arch/x86/cpu.c
Labels: CI: Tracked On Pass

#5945 doc/conf.py: enable formatting docs in a PDF file
  doc/conf.py
Labels: area: documentation

#5949 doc: tweaks for latexpdf build
  doc/Makefile
  doc/developer-guides/hld/hv-partitionmode.rst
  doc/developer-guides/hld/virtio-blk.rst
  doc/tutorials/trustyACRN.rst
Labels: area: documentation

#5942 acrn-config: add adl-rvp xml
  misc/config_tools/data/adl-rvp/adl-rvp.xml
  misc/config_tools/data/adl-rvp/industry.xml
Labels: CI: Tracked On Pass

#5952 hv: bugfix in min() and max() MACROs
  hypervisor/include/lib/util.h
Labels: CI: Tracked On Pass

#5957 Tlfs fix
  hypervisor/arch/x86/guest/hyperv.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/guest/hyperv.h
Labels: CI: Tracked On Pass

#5958 hv: Save/restore MSR_IA32_CSTAR during context switch
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/cpu.h
Labels: CI: Tracked On Pass

#5964 config_tools: update IVSHMEM_SHM_SIZE part for HV_RAM_SIZE calculation
  misc/config_tools/hv_config/board_defconfig.py
  misc/config_tools/static_allocators/hv_ram.py
Labels: CI: Tracked On Pass

#5967 doc: clean up PDF generation for ACRN docs
  doc/.known-issues/doc/pdf.conf
  doc/Makefile
  doc/conf.py
  doc/scripts/pullsource.sh
  doc/scripts/show-versions.py
  doc/tutorials/docbuild.rst
Labels: area: documentation

#5977 doc: tweak known-issues for PDF processing
  doc/.known-issues/doc/pdf.conf
Labels: area: documentation

#5974 dm: bugfix in create_and_inject_vrtct
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/hw/platform/acpi/rtct.c
Labels: CI: Tracked On Pass

#5978 doc: fix malformed code block in acrn config docs
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#5969 hv: enable uart=bdf@ for PCI serial ports which bar0 is not MMIO
  hypervisor/debug/uart16550.c
Labels: CI: Tracked On Pass

#5971 hv: mmu: fix a minor bug
  hypervisor/arch/x86/mmu.c
Labels: CI: Tracked On Pass

#5979 [release_2.4 hotfix] dm: bugfix in create_and_inject_vrtct
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/hw/platform/acpi/rtct.c
Labels: CI: Tracked On Pass, release_2.4
