Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-01, with the labels that each got.

#5633 doc: fix typo in docbuild.rst
  doc/tutorials/docbuild.rst
Labels: area: documentation, no Signed-off-by

#5494 Fix: HV: VM OS failed to assign new address to pci-vuart BARs
  hypervisor/dm/vpci/ivshmem.c
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vdev.c
  hypervisor/dm/vpci/vmcs9900.c
  hypervisor/dm/vpci/vmsix_on_msi.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/dm/vpci.h
  hypervisor/include/hw/pci.h
Labels: CI: Tracked On Pass, CI: pending approve

#5629 DM: samples: Enable VxWorks as normal VM by default
  misc/vm_configs/sample_launch_scripts/nuc/launch_vxworks.sh
Labels: CI: Tracked On Pass

#5636 dm: virtio-gpio: avoid flood messages in virtio_irq_evt_notify
  devicemodel/hw/pci/virtio/virtio_gpio.c
Labels: CI: Tracked On Pass

#5639 hv: vcpuid: expose mce feature to guest
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/virtual_cr.c
Labels: CI: Tracked On Pass

#5641 hv: ptirq: Shouldn't change sid if intx irq mapping was added
  hypervisor/arch/x86/guest/assign.c
Labels: CI: Tracked On Pass

#5643 hv: remove bitmap_clear_lock of split-lock after completing emulation
  hypervisor/arch/x86/guest/splitlock.c
Labels: CI: Tracked On Pass

#5642 Fix: HV: keep reshuffling on VBARs
  hypervisor/dm/vpci/ivshmem.c
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vdev.c
  hypervisor/dm/vpci/vmsix_on_msi.c
  hypervisor/include/dm/vpci.h
  hypervisor/include/hw/pci.h
Labels: CI: Tracked On Pass

#5651 hv: ptirq: Shouldn't change sid if intx irq mapping was added
  hypervisor/arch/x86/guest/assign.c
Labels: CI: Tracked On Pass, release_2.3

#5650 hv: ptirq: Shouldn't change sid if intx irq mapping was added
  hypervisor/arch/x86/guest/assign.c
Labels: CI: Tracked On Pass, release_2.0

#5652 doc: update doc build instructions
  doc/tutorials/docbuild.rst
Labels: area: documentation

#5648 acrn-config: reserve hostbirdge bdf of pre-launched vm
  misc/acrn-config/board_config/misc_cfg_h.py
  misc/acrn-config/board_config/vbar_base_h.py
  misc/acrn-config/library/scenario_cfg_lib.py
  misc/acrn-config/scenario_config/pci_dev_c.py
  misc/acrn-config/scenario_config/scenario_item.py
Labels: CI: Tracked On Pass

#5659 doc: use 'apt' to install GCC for Windows
  doc/tutorials/enable_s5.rst
Labels: area: documentation

#5664 Makefile: fix build issues due to reorg of misc/
  hypervisor/scripts/makefile/config.mk
Labels: CI: Tracked On Pass

#5655 tools: remove libtelemetry code from crashlog
  misc/debug_tools/acrn_crashlog/Makefile
  misc/debug_tools/acrn_crashlog/README.rst
  misc/debug_tools/acrn_crashlog/acrnprobe/sender.c
  misc/debug_tools/acrn_crashlog/data/acrn-crashlog-dirs.conf
  misc/debug_tools/acrn_crashlog/data/crashlogctl
  misc/debug_tools/acrn_crashlog/images/crashlog-workflow.dot
Labels: CI: Tracked On Pass

#5670 Makefile: make internal comment in doc Makefile silent
  doc/Makefile
Labels: area: documentation

#5667 acrn-config: update config folders used in config app
  misc/config_tools/config_app/configs.py
  misc/config_tools/config_app/static/main.js
  misc/config_tools/config_app/templates/scenario.html
Labels: CI: Tracked On Pass

#5666 acrn-config: add fusa_partition scenario on ehl-crb-b board
  misc/config_tools/acpi_gen/asl_gen.py
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
Labels: CI: Tracked On Pass

#5668 Update the CODEOWNERS information.
  CODEOWNERS
Labels: CI: Tracked On Pass

#5674 dm: refine comment on 'struct acrn_vm_config'
  devicemodel/include/public/vhm_ioctl_defs.h
Labels: CI: Tracked On Pass

#5675 acrn-config: Rename acpi generated asl folder name from VMx to ACPI_VMx
  misc/config_tools/acpi_gen/asl_gen.py
  misc/config_tools/acpi_gen/bin_gen.py
Labels: CI: Tracked On Pass

#5677 hv: remove the hardcoding of Software SRAM GPA base
  hypervisor/arch/x86/guest/ve820.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/rtct.h
Labels: CI: Tracked On Pass

#5682 doc: fix misspelling in hv-dev-passthrough
  doc/developer-guides/hld/hv-dev-passthrough.rst
Labels: area: documentation
