Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-05, with the labels that each got.

#5982 doc: fix missing codeblock directive
  doc/tutorials/using_windows_as_uos.rst
Labels: area: documentation

#5983 doc: add note to emphasize the need to use --windows for WaaG
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#5986 doc: add clang-format to setup package list
  doc/getting-started/building-from-source.rst
Labels: area: documentation

#5989 config-tools: fix a couple of typos in helper script
  hypervisor/scripts/genconf.sh
Labels: CI: Tracked On error, area: documentation

#5991 doc: copy edits in the developer reference
  doc/developer-guides/GVT-g-porting.rst
  doc/developer-guides/VBSK-analysis.rst
  doc/developer-guides/asm_coding_guidelines.rst
  doc/developer-guides/c_coding_guidelines.rst
  doc/developer-guides/coding_guidelines.rst
  doc/developer-guides/contribute_guidelines.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/graphviz.rst
  doc/developer-guides/l1tf.rst
  doc/developer-guides/modularity.rst
  doc/developer-guides/sw_design_guidelines.rst
  doc/developer-guides/trusty.rst
Labels: area: documentation

#5995 config_tools: enable features for default config on tgl-rvp and
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_waag.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
  misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_zephyr.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt_launch_1uos_waag.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/industry_launch_1uos_waag.xml
  misc/config_tools/data/tgl-rvp/industry_launch_2uos.xml
  misc/config_tools/data/tgl-rvp/industry_launch_6uos.xml
  misc/config_tools/data/tgl-rvp/sdc_launch_1uos_zephyr.xml
Labels: CI: Tracked On Pass

#5994 hv: hypercalls: refactor permission-checking and dispatching logic
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/hv-hypercall.rst
  hypervisor/arch/x86/guest/vmcall.c
  hypervisor/common/hypercall.c
  hypervisor/common/trusty_hypercall.c
  hypervisor/debug/hypercall.c
  hypervisor/include/common/hypercall.h
  hypervisor/release/hypercall.c
Labels: CI: Tracked On Pass, area: documentation

#5999 config-tools: add white space between arguments
  misc/config_tools/data/generic_board/generic_code/hybrid/misc_cfg.h
  misc/config_tools/data/generic_board/generic_code/hybrid_rt/misc_cfg.h
  misc/config_tools/data/generic_board/generic_code/industry/misc_cfg.h
  misc/config_tools/data/generic_board/generic_code/logical_partition/misc_cfg.h
  misc/config_tools/xforms/misc_cfg.h.xsl
Labels: CI: Tracked On Pass

#6007 hv: Support WAITPKG instructions in guest VM
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/asm/cpufeatures.h
  hypervisor/include/arch/x86/asm/guest/vcpu.h
  hypervisor/include/arch/x86/asm/msr.h
  hypervisor/include/arch/x86/asm/vmx.h
Labels: CI: Tracked On Pass

#6010 config-tools: fix the regular expression of ivshmem region name
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass

#6016 hv: rename some software SRAM local names
  hypervisor/arch/x86/rtcm.c
  hypervisor/include/arch/x86/asm/rtct.h
Labels: CI: Tracked On Pass

#6017 dm: clean legacy software SRAM names
  devicemodel/core/main.c
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/hw/platform/acpi/rtct.c
  devicemodel/include/dm.h
  devicemodel/include/rtct.h
Labels: CI: Tracked On Pass

#6014 config-tool: rename PSRARM to SSRAM
  hypervisor/arch/x86/Kconfig
  misc/config_tools/acpi_gen/asl_gen.py
  misc/config_tools/board_config/misc_cfg_h.py
  misc/config_tools/board_inspector/legacy/rtct.py
  misc/config_tools/config_app/templates/scenario.html
  misc/config_tools/data/adl-rvp/industry.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/hv_config/board_defconfig.py
  misc/config_tools/hv_config/hv_item.py
  misc/config_tools/launch_config/com.py
  misc/config_tools/library/hv_cfg_lib.py
  misc/config_tools/scenario_config/scenario_cfg_gen.py
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: CI: Tracked On Pass

#6021 hv: update RTCT parser to support RTCT version 2
  hypervisor/arch/x86/rtcm.c
  hypervisor/include/arch/x86/asm/rtct.h
Labels: CI: Tracked On Pass

#6023 config-tools: guest_flag must be assigned with a valid value
  misc/config_tools/data/apl-mrb/logical_partition.xml
  misc/config_tools/data/apl-up2-n3350/logical_partition.xml
  misc/config_tools/data/apl-up2/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc6cayh/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
Labels: CI: Tracked On Pass

#6022 Doc: update using serial port
  doc/tutorials/images/NUC-serial-port.png
  doc/tutorials/images/NUC11TNH-serial-port-header-to-RS232-cable.png
  doc/tutorials/images/NUC11TNH-serial-port-header.png
  doc/tutorials/images/NUC11TNH-serial-port.png
  doc/tutorials/images/NVMe-M.2-to-PCIe-adaptor.png
  doc/tutorials/images/PCIe-serial-Connection.png
  doc/tutorials/images/PCIe-serial-LeKuo.png
  doc/tutorials/images/PCIe-serial-StarTech.png
  doc/tutorials/using_serial_port.rst
Labels: area: documentation

#6030 doc: editing in using_serial_port.rst
  doc/tutorials/using_serial_port.rst
Labels: area: documentation

#6025 board_inspector/acpiparser: enable parsing RTCT v2
  misc/config_tools/board_inspector/acpiparser/__init__.py
  misc/config_tools/board_inspector/acpiparser/rtct.py
  misc/config_tools/board_inspector/extractors/20-cache.py
  misc/config_tools/board_inspector/legacy/board_parser.py
  misc/config_tools/board_inspector/legacy/rtct.py
  misc/config_tools/schema/checks/pre_launched_vm_support.xsd
  misc/config_tools/static_allocators/gpa.py
  misc/config_tools/xforms/misc_cfg.h.xsl
Labels: CI: Tracked On Pass

#6027 config_tools: update board XMLs of ehl-crb-b and tgl-rvp
  misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
  misc/config_tools/data/tgl-rvp/tgl-rvp.xml
Labels: CI: Tracked On Pass

#6019 build: fix dm and acrn_crashlog build error with gcc-11
  devicemodel/core/mevent.c
  misc/debug_tools/acrn_crashlog/acrnprobe/include/probeutils.h
Labels: CI: Tracked On Pass

#6032 doc: copy editing in the hld topics
  doc/developer-guides/hld/ahci-hld.rst
  doc/developer-guides/hld/atkbdc-virt-hld.rst
  doc/developer-guides/hld/hld-APL_GVT-g.rst
Labels: area: documentation

#6048 doc: fix indenting issues in tutorial
  doc/tutorials/running_deb_as_serv_vm.rst
Labels: area: documentation

#6042 dm: add allow_trigger_s5 mode to pm_notify_channel uart
  devicemodel/core/main.c
  devicemodel/core/pm_vuart.c
  devicemodel/include/pm.h
  devicemodel/include/pm_vuart.h
Labels: CI: Tracked On Pass, release_2.5

#6039 Config_tools: Update ramdisk logic
  misc/config_tools/xforms/vm_configurations.c.xsl
Labels: CI: Tracked On Pass

#6037 Fix page fault when HV flash its RAM cache
  hypervisor/arch/x86/cpu.c
Labels: CI: Tracked On Pass

#6046 OVMF release v2.5
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass, release_2.5

#6041 dm: add allow_trigger_s5 mode to pm_notify_channel uart
  devicemodel/core/main.c
  devicemodel/core/pm_vuart.c
  devicemodel/include/pm.h
  devicemodel/include/pm_vuart.h
Labels: CI: Tracked On Pass

#6045 OVMF release v2.5
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#6049 HV: cache: Fix page fault by flushing cache for VM trusty RAM in HV
  hypervisor/arch/x86/cpu.c
Labels: CI: Tracked On Pass, release_2.5

#6043 doc: add documentation for allow_trigger_s5 in pm_notify_channel
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/tutorials/enable_s5.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#6050 HV: Fix mistake use stac() & clac()
  hypervisor/arch/x86/cpu.c
Labels: CI: Tracked On Pass

#6057 dm: rb: only free rb_entry when we remove this entry from the rb tree
  devicemodel/core/mem.c
Labels: CI: Tracked On Pass

#6058 release_2.5: dm: rb: only free rb_entry when we remove this entry from the rb tree
  devicemodel/core/mem.c
Labels: CI: Tracked On Pass, release_2.5

#6036 Config_tools: Update board xml
  misc/config_tools/data/adl-rvp/adl-rvp.xml
  misc/config_tools/data/cfl-k700-i7/cfl-k700-i7.xml
  misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
  misc/config_tools/data/nuc7i7dnb/nuc7i7dnb.xml
  misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
  misc/config_tools/data/whl-ipc-i7/whl-ipc-i7.xml
Labels: CI: Tracked On Pass

#6070 release2.5:DM: change 32-bit mmio limit to 3.5G
  devicemodel/include/pci_core.h
Labels: CI: Tracked On Pass, release_2.5

#6073 config-tools: fix guest_flag issue in config xml for adl
  misc/config_tools/data/adl-rvp/industry.xml
Labels: CI: Tracked On Pass

#6076 config_tools: fix the guest_flag error when saving scenario xml
  misc/config_tools/library/common.py
Labels: CI: Tracked On Pass, release_2.5

#6063 release_2.5: dm: mitigate reset attack
  devicemodel/core/vmmapi.c
Labels: CI: Tracked On Pass, release_2.5

#6080 hv: VMPTRLD and VMCLEAR VMCS with the common APIs
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/vmx.c
Labels: CI: Tracked On Pass

#6071 DM: change 32-bit mmio limit to 3.5G
  devicemodel/include/pci_core.h
Labels: CI: Tracked On Pass

#6074 config-tools: fix guest_flag issue in config xml for adl
  misc/config_tools/data/adl-rvp/industry.xml
Labels: CI: Tracked On Pass, release_2.5

#6087 hv: vlapic: a minor refine about vlapic_x2apic_pt_icr_access
  hypervisor/arch/x86/guest/vlapic.c
Labels: CI: Tracked On Pass

#6093 dm: return error if PTM is not enabled on physical root port
  devicemodel/hw/pci/ptm.c
Labels: CI: Tracked On Pass, release_2.5

#6086 release_2.5: hv: vlapic: a minor refine about vlapic_x2apic_pt_icr_access
  hypervisor/arch/x86/guest/vlapic.c
Labels: CI: Tracked On Pass, release_2.5

#6094 [release_2.5] Device Model vRTCT V2 upgrade
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/hw/platform/acpi/rtct.c
  devicemodel/include/rtct.h
Labels: CI: Tracked On Pass, release_2.5

#6077 config_tools: fix the guest_flag error when saving scenario xml
  misc/config_tools/library/common.py
Labels: CI: Tracked On Pass

#6095 [release_v2.5] hv: update RTCT ACPI table detecting
  hypervisor/acpi_parser/acpi_ext.c
  hypervisor/arch/x86/rtcm.c
  hypervisor/boot/include/acpi.h
  hypervisor/include/arch/x86/asm/rtcm.h
Labels: CI: Tracked On Pass, release_2.5

#6096 misc: efi-stub: Set MOR bit before jumping to hypervisor
  misc/efi-stub/boot.c
  misc/efi-stub/boot.h
  misc/efi-stub/efilinux.h
Labels: CI: Tracked On Pass, release_2.5

#6103 config_tools: add RTCT table support in pre-launched VMs
  misc/config_tools/acpi_gen/acpi_const.py
  misc/config_tools/acpi_gen/asl_gen.py
  misc/config_tools/acpi_gen/bin_gen.py
Labels: CI: Tracked On Pass, release_2.5

#6109 doc: update ACRN version QEMU tutorial
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation

#6090 Config_tools: Update Hybrid Cores
  misc/config_tools/schema/checks/pre_launched_vm_support.xsd
Labels: CI: Tracked On Pass

#6091 Config_tools: Update get slot logic
  misc/config_tools/data/sample_launch_scripts/nuc/launch_win.sh
  misc/config_tools/launch_config/com.py
  misc/config_tools/library/launch_cfg_lib.py
Labels: CI: Tracked On Pass

#6111 config_tools: add adl-s-crb board and industry scenario
  misc/config_tools/data/adl-s-crb/adl-s-crb.xml
  misc/config_tools/data/adl-s-crb/industry.xml
Labels: release_2.5
