Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-08, with the labels that each got.

#6346 hv: SMBIOS: add check before SMBIOS probing
  hypervisor/quirks/smbios.c
Labels: CI: Tracked On Pass, release_2.5

#6335 [Release 2.5]HV: debug: support 64bit BAR pci uart with 32bit space
  hypervisor/debug/uart16550.c
Labels: CI: Tracked On Pass, release_2.5

#6349 config_tools: update ehl-crb-b xml with new uart
  misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
Labels: CI: Tracked On Pass, release_2.5

#6336 HV: debug: support 64bit BAR pci uart with 32bit space
  hypervisor/debug/uart16550.c
Labels: CI: Tracked On Pass

#6363 doc: remove obsolete kconfig references in Makefile
  doc/Makefile
Labels: area: documentation

#6358 config_tools: remove obsolete kconfig files
  hypervisor/Kconfig
  hypervisor/arch/x86/Kconfig
  hypervisor/scripts/makefile/cfg_update.mk
  hypervisor/scripts/makefile/kconfig.mk
  misc/config_tools/README
  misc/config_tools/board_config/board_c.py
  misc/config_tools/kconfig/LICENSE.kconfiglib
  misc/config_tools/kconfig/defconfig.py
  misc/config_tools/kconfig/generate_header.py
  misc/config_tools/kconfig/savedefconfig.py
  misc/config_tools/kconfig/silentoldconfig.py
Labels: CI: Tracked On Pass

#6356 Makefile:add targz-pkg entry in Makefile
  Makefile
  devicemodel/Makefile
  hypervisor/Makefile
Labels: CI: Tracked On Pass

#6353 hv: uc-lock: Fix do not trap #GP
  hypervisor/arch/x86/guest/vmcs.c
Labels: CI: Tracked On Pass

#6369 doc: add v2.5.1 release notes
  doc/release_notes/release_notes_2.5.1.rst
Labels: area: documentation

#6359 doc: update Kconfig related doc
  doc/tutorials/cpu_sharing.rst
Labels: area: documentation

#6370 config-tools: refine MAX_MSIX_TABLE_NUM
  misc/config_tools/xforms/config.h.xsl
  misc/config_tools/xforms/config.mk.xsl
  misc/config_tools/xforms/config_common.xsl
  misc/config_tools/xforms/lib.xsl
Labels: CI: Tracked On Pass

#6373 config_tools: remove adl-rvp
  misc/config_tools/data/adl-rvp/adl-rvp.xml
  misc/config_tools/data/adl-rvp/industry.xml
Labels: CI: Tracked On Pass

#6374 dm: mitigate reset attack
  devicemodel/core/vmmapi.c
Labels: CI: Tracked On Pass

#6341 config_tools: update lpc slot number
  misc/config_tools/library/launch_cfg_lib.py
Labels: CI: Tracked On Pass

#6354 config_tools: update launch xml for only one NVME
  misc/config_tools/data/ehl-crb-b/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml
  misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
  misc/config_tools/data/generic_board/industry_launch_6uos.xml
  misc/config_tools/data/nuc11tnbi5/industry_launch_6uos.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_2uos.xml
  misc/config_tools/data/nuc7i7dnb/industry_launch_6uos.xml
  misc/config_tools/data/tgl-rvp/industry_launch_2uos.xml
  misc/config_tools/data/tgl-rvp/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i5/industry_launch_6uos.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_hardrt.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_2uos.xml
  misc/config_tools/data/whl-ipc-i7/industry_launch_6uos.xml
Labels: CI: Tracked On Pass

#6378 config_tools: refine the configuration data description
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass

#6386 doc: update config data descriptions
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: CI: Tracked On Pass

#6379 config_tools: fix formatting of configured INTx allocation
  misc/config_tools/static_allocators/intx.py
  misc/config_tools/xforms/lib.xsl
Labels: CI: Tracked On Pass

#6382 hv: Squash warning of code scanning tool
  hypervisor/quirks/smbios.c
Labels: CI: Tracked On Pass, release_2.5

#6394 doc:add more explanation on parameter --windows
  doc/tutorials/using_windows_as_uos.rst
  doc/tutorials/waag-secure-boot.rst
Labels: area: documentation

#6390 dm: fix potential NULL pointer access in virtio_console.c
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass

#6393 config-tools: add native log area address
  misc/config_tools/board_inspector/extractors/50-acpi.py
  misc/config_tools/xforms/misc_cfg.h.xsl
  misc/config_tools/xforms/vm_configurations.c.xsl
Labels: CI: Tracked On Pass

#6375 config_tools: update the board xml files
  misc/config_tools/data/cfl-k700-i7/cfl-k700-i7.xml
  misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
  misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
  misc/config_tools/data/nuc7i7dnb/nuc7i7dnb.xml
  misc/config_tools/data/qemu/qemu.xml
  misc/config_tools/data/tgl-rvp/tgl-rvp.xml
  misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
  misc/config_tools/data/whl-ipc-i7/whl-ipc-i7.xml
Labels: CI: Tracked On Pass

#6392 hv: ivshmem: map SHM BAR with PAT ignored
  hypervisor/dm/vpci/ivshmem.c
  hypervisor/include/arch/x86/asm/pgtable.h
Labels: CI: Tracked On Pass

#6391 [release_2.5] dm: fix potential NULL pointer access in virtio_console.c
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass, release_2.5

#6400 hv: ivshmem: map SHM BAR with PAT ignored
  hypervisor/dm/vpci/ivshmem.c
  hypervisor/include/arch/x86/asm/pgtable.h
Labels: CI: Tracked On Pass, release_2.5

#6409 FIXME: temporarily disable TPM2 passthrough
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
Labels: CI: Tracked On Pass, release_2.6

#6410 FIXME: temporarily disable TPM2 passthrough
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
Labels: CI: Tracked On Pass

#6406 release_2.6: hv: Change sched_event structure to resolve data race in event handling
  hypervisor/common/event.c
  hypervisor/include/common/event.h
Labels: CI: Tracked On Pass, release_2.6

#6407 config_tools: remove some tags check for scenario.xml in generic_board folder
  misc/config_tools/config_app/views.py
Labels: CI: Tracked On Pass, release_2.6

#6419 config_tools: rename python script
  misc/config_tools/board_inspector/README
  misc/config_tools/board_inspector/board_inspector.py
  misc/config_tools/config_app/acrn_configurator.py
Labels: CI: Tracked On Pass, release_2.6

#6416 config_tools: disable TPM2 passthrough on other platforms
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
Labels: CI: Tracked On Pass, release_2.6

#6421 config_tools: rename two missed PSRAMs to SSRAMs
  misc/config_tools/schema/checks/pre_launched_vm_support.xsd
  misc/config_tools/static_allocators/gpa.py
Labels: CI: Tracked On Pass, release_2.6

#6424 release_2.6: hv: ve820: Minor changes to prelaunched VM ve820 mapping
  hypervisor/arch/x86/guest/ve820.c
Labels: CI: Tracked On Pass, release_2.6

#6404 doc: update hld-devicemodel with current e820 mem map
  doc/developer-guides/hld/hld-devicemodel.rst
Labels: area: documentation

#6427 config_tools: update lpc slot number in script
  misc/config_tools/launch_config/com.py
Labels: CI: Tracked On Pass, release_2.6

#6420 config_tools: rename two missed PSRAMs to SSRAMs
  misc/config_tools/schema/checks/pre_launched_vm_support.xsd
  misc/config_tools/static_allocators/gpa.py
Labels: CI: Tracked On Pass

#6395 hv:enable GVT-d for pre-launched linux guest in logical partion mode
  hypervisor/arch/x86/guest/ve820.c
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vpci.c
  hypervisor/include/common/ptdev.h
Labels: CI: Tracked On Pass

#6398 hv: mmiodev: a minor bug fix about refine acrn_mmiodev data structure
  hypervisor/arch/x86/guest/vm.c
  hypervisor/dm/vgpio.c
  hypervisor/include/dm/vgpio.h
Labels: CI: Tracked On Pass

#6399 dm: update the GPU OpRegion size to 20KB
  devicemodel/include/pci_core.h
Labels: CI: Tracked On Pass

#6401 config_tools: remove some tags check for scenario.xml in generic_board folder
  misc/config_tools/config_app/views.py
Labels: CI: Tracked On Pass

#6439 [for v2.6] hv: initialize the XSAVE related processor state for guest
  hypervisor/arch/x86/guest/vcpu.c
Labels: CI: Tracked On Pass, release_2.6

#6351 [release_v2.5] expose PMC to partition VM
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmsr.c
Labels: CI: Tracked On Pass, release_2.5

#6436 board_inspector: add _CID to vACPI device objects
  misc/config_tools/board_inspector/extractors/50-acpi.py
  misc/config_tools/data/tgl-rvp/tgl-rvp.xml
Labels: CI: Tracked On Pass, release_2.6

#6437 config_tools: fix the issue that fail to generate launch script
  misc/config_tools/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass

#6433 ACRN:DM: Fix the Null pointer error
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass, release_2.6

#6438 config_tools: fix the issue that fail to generate launch script
  misc/config_tools/library/scenario_cfg_lib.py
Labels: CI: Tracked On Pass, release_2.6

#6429 doc: update configuration tool names
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation

#6415 config_tools: disable TPM2 passthrough on other platforms
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
Labels: CI: Tracked On Pass

#6432 ACRN:DM: Fix the Null pointer error
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass

#6418 config_tools: rename python script
  misc/config_tools/board_inspector/README
  misc/config_tools/board_inspector/board_inspector.py
  misc/config_tools/config_app/acrn_configurator.py
Labels: CI: Tracked On Pass

#6426 config_tools: update lpc slot number in script
  misc/config_tools/launch_config/com.py
Labels: CI: Tracked On Pass

#6422 hv: Change sched_event structure to resolve data race in event handling
  hypervisor/common/event.c
  hypervisor/include/common/event.h
Labels: CI: Tracked On Pass

#6444 hv: nested: redundant permission check on nested_vmentry()
  hypervisor/arch/x86/guest/nested.c
Labels: CI: Tracked On Pass

#6413 hv: nested: fix bugs in init_vmx_msrs()
  hypervisor/arch/x86/guest/nested.c
Labels: CI: Tracked On Pass

#6435 hv: initialize the XSAVE related processor state for guest
  hypervisor/arch/x86/guest/vcpu.c
Labels: CI: Tracked On Pass

#6443 config_tools: add a new entry MAX_EFI_MMAP_ENTRIES
  hypervisor/common/efi_mmap.c
  hypervisor/include/common/efi_mmap.h
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/industry.xml
  misc/config_tools/data/nuc11tnbi5/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: CI: Tracked On Pass

#6449 config_tools: update vTPM2 revision to 4
  misc/config_tools/acpi_gen/bin_gen.py
Labels: CI: Tracked On Pass, release_2.6

#6446 config_tools: fix UI issue of creating new settings
  misc/config_tools/config_app/views.py
Labels: CI: Tracked On Pass, release_2.6

#6447 config_tools: fix UI issue of creating new settings
  misc/config_tools/config_app/views.py
Labels: CI: Tracked On Pass

#6451 config_tools: rename two missed PSRAMs to SSRAMs
  misc/config_tools/schema/checks/pre_launched_vm_support.xsd
  misc/config_tools/static_allocators/gpa.py
Labels: CI: Tracked On Pass, release_2.5

#6452 hv: dbg: sample vmexit data per-pCPU and per-vCPU
  hypervisor/common/hv_main.c
  hypervisor/debug/shell.c
  hypervisor/debug/shell_priv.h
  hypervisor/include/arch/x86/asm/guest/vcpu.h
  hypervisor/include/arch/x86/asm/per_cpu.h
  hypervisor/include/debug/profiling.h
  hypervisor/include/public/acrn_common.h
  hypervisor/release/profiling.c
Labels: CI: Tracked On Pass, release_2.5

#6450 [for v2.6] config_tools: add a new entry MAX_EFI_MMAP_ENTRIES
  hypervisor/common/efi_mmap.c
  hypervisor/include/common/efi_mmap.h
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/industry.xml
  misc/config_tools/data/nuc11tnbi5/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: CI: Tracked On Pass, release_2.6

#6448 doc: DX update for GSG
  doc/develop.rst
  doc/getting-started/building-from-source.rst
  doc/getting-started/getting-started.rst
  doc/getting-started/images/acrn_terms.png
  doc/getting-started/images/gsg_config_01.png
  doc/getting-started/images/gsg_config_board.png
  doc/getting-started/images/gsg_config_board.psd
  doc/getting-started/images/gsg_config_launch_default.png
  doc/getting-started/images/gsg_config_launch_default.psd
  doc/getting-started/images/gsg_config_launch_generate.png
  doc/getting-started/images/gsg_config_launch_generate.psd
  doc/getting-started/images/gsg_config_launch_load.png
  doc/getting-started/images/gsg_config_launch_load.psd
  doc/getting-started/images/gsg_config_launch_save.png
  doc/getting-started/images/gsg_config_launch_save.psd
  doc/getting-started/images/gsg_config_scenario_default.png
  doc/getting-started/images/gsg_config_scenario_default.psd
  doc/getting-started/images/gsg_config_scenario_load.png
  doc/getting-started/images/gsg_config_scenario_load.psd
  doc/getting-started/images/gsg_config_scenario_save.png
  doc/getting-started/images/gsg_config_scenario_save.psd
  doc/getting-started/images/gsg_host_target.png
  doc/getting-started/images/gsg_nuc.png
  doc/getting-started/images/gsg_overview_image_sources.pptx
  doc/getting-started/images/gsg_rootfs.png
  doc/getting-started/images/gsg_scenario.png
  doc/getting-started/images/gsg_ubuntu_install_01.png
  doc/getting-started/images/gsg_ubuntu_install_02.jpg
  doc/getting-started/images/gsg_ubuntu_install_02.png
  doc/getting-started/images/gsg_vm_iso.png
  doc/getting-started/images/gsg_vm_ubuntu_launch.png
  doc/getting-started/images/icon_host.png
  doc/getting-started/images/icon_light.png
  doc/getting-started/images/icon_target.png
  doc/getting-started/images/overview_flow.png
  doc/getting-started/images/overview_host_target.png
  doc/getting-started/overview_dev.rst
  doc/getting-started/roscube/roscube-gsg.rst
  doc/introduction/index.rst
  doc/reference/hardware.rst
  doc/try.rst
  doc/tutorials/acrn-secure-boot-with-efi-stub.rst
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/acrn_on_qemu.rst
  doc/tutorials/debug.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/nvmx_virtualization.rst
  doc/tutorials/pre-launched-rt.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/running_deb_as_serv_vm.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/setup_openstack_libvirt.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_vxworks_as_uos.rst
  doc/tutorials/using_zephyr_as_uos.rst
Labels: area: documentation

#6457 doc: GSG tweaks for DX
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6453 config_tools: remove the log of sucessfully generating board XML
  misc/config_tools/board_inspector/legacy/board_parser.py
Labels: CI: Tracked On Pass

#6454 config_tools: remove the log of sucessfully generating board XML
  misc/config_tools/board_inspector/legacy/board_parser.py
Labels: CI: Tracked On Pass, release_2.6

#6456 config-tools: refine log area start address allocation
  misc/config_tools/static_allocators/gpa.py
Labels: CI: Tracked On Pass

#6460 doc: additional DX edits to the new GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6459 doc: update UI tool instructions
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/images/choose_scenario.png
  doc/tutorials/images/click_import_board_info_button.png
  doc/tutorials/images/config_app_main_menu.png
  doc/tutorials/images/configure_scenario.png
  doc/tutorials/images/configure_vm_add.png
  doc/tutorials/images/err_acrn_configuration.png
  doc/tutorials/images/generate_launch_script.png
  doc/tutorials/images/select_board_info.png
Labels: area: documentation

#6470 doc: update GSG checkout commits
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6430 hv: optimize handling of IA32_EFER
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/arch/x86/mmu.c
  hypervisor/include/arch/x86/asm/guest/vcpu.h
  hypervisor/include/arch/x86/asm/guest/vmcs.h
Labels: CI: Tracked On Pass

#6479 doc: Add bc to build dependencies
  doc/getting-started/getting-started.rst
Labels: area: documentation, no Signed-off-by

#6466 hv: GSI of hcall_set_irqline should be checked against target_vm
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass

#6467 hv: GSI of hcall_set_irqline should be checked against target_vm
  hypervisor/common/hypercall.c
Labels: CI: Tracked On Pass, release_2.6

#6471 hv: minor cleanup of hv_main.c
  hypervisor/common/hv_main.c
  hypervisor/include/arch/x86/asm/guest/vcpu.h
Labels: CI: Tracked On Pass

#6475 ACRN:hv: Fix vcpu_dumpreg command hang issue
  hypervisor/debug/shell.c
Labels: CI: Tracked On Pass, release_2.6

#6474 ACRN:hv: Fix vcpu_dumpreg command hang issue
  hypervisor/debug/shell.c
Labels: CI: Tracked On Pass

#6455 config-tools: refine log area start address allocation
  misc/config_tools/static_allocators/gpa.py
Labels: area: documentation, CI: Tracked On Pass, release_2.6

#6462 config-tools: Kernel load and entry address accept empty string
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/types.xsd
  misc/config_tools/xforms/vm_configurations.c.xsl
Labels: CI: Tracked On Pass, release_2.6

#6463 config-tools: Kernel load and entry address accept empty string
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/types.xsd
  misc/config_tools/xforms/vm_configurations.c.xsl
Labels: CI: Tracked On Pass

#6477 ACRN:DM: Add pointer check before use the erst
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass

#6478 ACRN:DM: Add pointer check before use the erst
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass, release_2.6

#6469 hv: debug: add debug command inj_guest_exp
  hypervisor/debug/shell.c
  hypervisor/debug/shell_priv.h
  hypervisor/include/arch/x86/asm/guest/vcpu.h
Labels: CI: Tracked On Pass, release_2.5

#6487 [for v2.6] hv: check the capability of XSAVES/XRSTORS instructions before execution
  hypervisor/arch/x86/guest/vcpu.c
Labels: CI: Tracked On Pass, release_2.6

#6511 [release_2.6]DM: fix issue when pass-thru native RTCT SSRAM entries
  devicemodel/hw/platform/acpi/rtct.c
Labels: CI: Tracked On Pass, release_2.6

#6514 doc: use "ACRN configurator" name in Overview, GSG
  doc/getting-started/getting-started.rst
  doc/getting-started/images/gsg_overview_image_sources.pptx
  doc/getting-started/images/overview_flow.png
  doc/getting-started/overview_dev.rst
Labels: area: documentation

#6519 [release_2.6]dm: fix potential program crash issue in disk_logger
  devicemodel/log/disk_logger.c
Labels: CI: Tracked On Pass, release_2.6

#6521 dm: fix potential program crash issue in disk_logger
  devicemodel/log/disk_logger.c
Labels: CI: Tracked On Pass

#6522 config_tools: update scenario xml files on tgl-rvp platform
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass

#6523 config_tools: update scenario xml files on tgl-rvp platform
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
Labels: CI: Tracked On Pass, release_2.6
