Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-12, with the labels that each got.

#6906 config_tools: check VM number before filling with dynamic configured VM
  misc/config_tools/xforms/vm_configurations.c.xsl
Labels: approved, CI: Tracked On Pass, release_2.7

#6909 [v2.7]HV: update destination shorthand field in x2apic ICR emulation
  hypervisor/arch/x86/guest/vlapic.c
Labels: approved, CI: Tracked On Pass, release_2.7

#6917 config_tools: check VM number before filling with dynamic configured VM
  misc/config_tools/xforms/vm_configurations.c.xsl
Labels: approved, CI: Tracked On Pass

#6920 [release_2.7] dm: fix memory leakage issue in acrn_parse_cpu_affinity
  devicemodel/core/vmmapi.c
Labels: approved, CI: Tracked On Pass, release_2.7

#6910 hv: Add stateful VM check before system shutdown
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/arch/x86/asm/guest/vm.h
Labels: CI: Tracked On Pass, First_build

#6924 config_tools: remove LOG_BUF_SIZE
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/shared.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/partitioned.xml
  misc/config_tools/data/generic_board/shared.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/partitioned.xml
  misc/config_tools/data/nuc11tnbi5/shared.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/partitioned.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i5/shared.xml
  misc/config_tools/hv_config/board_defconfig.py
  misc/config_tools/hv_config/hv_item.py
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: approved, CI: Tracked On Pass

#6881 misc: update CODEOWNERS for debug tools
  CODEOWNERS
Labels: CI: Tracked On Pass, First_build

#6921 HV: update destination shorthand during x2apic ICR emulation
  hypervisor/arch/x86/guest/vlapic.c
Labels: CI: Tracked On Pass, First_build

#6930 hv: fix core type error when launch RTVM use atom core
  hypervisor/arch/x86/guest/vcpuid.c
Labels: CI: Tracked On Pass, release_2.7

#6929 [v2.5]HV: update destination shorthand during x2apic ICR emulation
  hypervisor/arch/x86/guest/vlapic.c
Labels: release_2.5, CI: Tracked On Pass

#6928 dm/tools: compatible with openssl3.0
  devicemodel/hw/pci/ahci.c
  devicemodel/hw/pci/virtio/virtio_block.c
  devicemodel/hw/pci/virtio/virtio_i2c.c
  devicemodel/hw/pci/virtio/virtio_net.c
  devicemodel/hw/platform/rpmb/rpmb_sim.c
  misc/debug_tools/acrn_crashlog/acrnprobe/probeutils.c
Labels: CI: Tracked On Pass, release_2.7

#6932 hv: fix cpuid 0x2 mismatch when launch RTVM use atom core
  hypervisor/arch/x86/guest/vcpuid.c
Labels: CI: Tracked On Pass, release_2.7

#6925 doc: terminology cleanup in Hybrid GSG, tutorials
  doc/tutorials/nvmx_virtualization.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_windows_as_user_vm.rst
Labels: area: documentation, pending approve

#6923 doc: terminology cleanup in HLD overview
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/images/over-image29.png
Labels: area: documentation, pending approve, First_build

#6896 doc: terminology cleanup in secure boot GRUB
  doc/tutorials/acrn-secure-boot-with-grub.rst
  doc/tutorials/images/acrn_secureboot_flow.png
Labels: area: documentation, pending approve, First_build

#6841 doc: terminology cleanup in DM HLD
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/images/dm-image52.png
  doc/developer-guides/hld/images/dm-image75.png
Labels: area: documentation, approved

#6938 doc: terminology cleanup in openstack and hld images
  doc/developer-guides/hld/images/atkbdc-virt-hld.png
  doc/developer-guides/hld/images/hld-dm-timer-image1.png
  doc/developer-guides/hld/images/network-virt-service-vm-infrastruct.png
  doc/developer-guides/hld/images/virtio-console-arch.png
  doc/developer-guides/hld/images/virtio-hld-image3.png
  doc/developer-guides/hld/images/virtio-hld-image53.png
  doc/developer-guides/hld/images/watchdog-image1.png
  doc/developer-guides/hld/images/watchdog-image2.png
  doc/tutorials/setup_openstack_libvirt.rst
Labels: area: documentation

#6939 deb-pkg: Support specifying board.xml and scenario.xml
  Makefile
Labels: approved, CI: Tracked On Pass, release_2.7

#6922 deb-pkg: Support specifying board.xml and scenario.xml
  Makefile
Labels: pending approve, CI: Tracked On Pass, First_build

#6940 ACRN: Packaging: Terminology for UOS/SOS in Packaging script
  misc/packaging/100_ACRN
  misc/packaging/README.rst
  misc/packaging/install_uServiceVM.py
  misc/packaging/release.json
Labels: CI: Tracked On Pass, release_2.7

#6926 dm: fix memory leakage issue in acrn_parse_cpu_affinity
  devicemodel/core/vmmapi.c
Labels: approved, CI: Tracked On Pass

#6941 hv:remove 2 bits vmx capability check
  hypervisor/arch/x86/cpu_caps.c
Labels: approved, CI: Tracked On Pass, release_2.7

#6842 doc: terminology cleanup in RTVM tutorial
  doc/tutorials/images/pre_launched_rt.png
  doc/tutorials/pre-launched-rt.rst
Labels: area: documentation, pending approve, First_build

#6946 doc: terminology cleanup in hld/tutorial images
  doc/developer-guides/hld/images/ahci-image1.png
  doc/developer-guides/hld/images/log-image50.png
  doc/developer-guides/hld/images/log-image73.png
  doc/developer-guides/hld/images/static-core-image2.png
  doc/tutorials/images/vuart-config-post-launch.png
Labels: area: documentation, pending approve

#6947 doc: Remove placeholder text from acrntrace
  doc/developer-guides/hld/hld-trace-log.rst
Labels: area: documentation, pending approve

#6949 doc: update release notes for v2.7 on configuration upgrades
  doc/release_notes/release_notes_2.7.rst
Labels: area: documentation, pending approve

#6951 config_tools:doc: sync with release_2.7 for XSD files
  misc/config_tools/schema/VMtypes.xsd
Labels: CI: Tracked On error, pending approve

#6954 doc: update release notes with cpu_affinity notice
  doc/release_notes/release_notes_2.7.rst
Labels: area: documentation, pending approve

#6955 config_tools: rename sdc.xml to shared.xml on qemu platform
  misc/config_tools/data/qemu/shared.xml
Labels: CI: Tracked On Pass

#6956 config_tools: rename sdc.xml to shared.xml on qemu platform
  misc/config_tools/data/qemu/shared.xml
Labels: CI: Tracked On Pass, release_2.7

#6957 doc: update s5 document
  doc/tutorials/enable_s5.rst
  doc/tutorials/images/open-com-success.png
Labels: area: documentation

#6960 hv && config-tool: Add compilation option to disable all interrupts i…
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/arch/x86/pm.c
  hypervisor/common/hv_main.c
  hypervisor/common/irq.c
  hypervisor/common/softirq.c
  hypervisor/include/arch/x86/asm/cpu.h
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: CI: Tracked On Pass

#6958 hv:remove 2 bits vmx capability check
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/guest/vcpu.c
Labels: CI: Tracked On Pass

#6967 doc: add note about SRIOV disable
  doc/tutorials/enable_s5.rst
Labels: area: documentation

#6965 doc: update 'asa.rst' for 2.7 release
  doc/asa.rst
Labels: area: documentation

#6969 hv_prebuild: Support LAPIC-PT only VM
  misc/hv_prebuild/vm_cfg_checks.c
Labels: CI: Tracked On Pass

#6972 doc: update 2.7 release notes
  doc/release_notes/release_notes_2.7.rst
Labels: area: documentation

#6974 doc: fix $disk usage in GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6975 doc: add CSS color styles
  doc/developer-guides/doc_guidelines.rst
  doc/static/acrn-custom.css
Labels: area: documentation

#6971 doc: Supported HW
  doc/reference/hardware.rst
Labels: area: documentation

#6970 doc: update GSG and partitioned documentation
  doc/getting-started/getting-started.rst
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation

#6977 doc: Add formatting to Supported HW
  doc/reference/hardware.rst
Labels: area: documentation

#6976 config-tools: remove unused python scripts under scenario_config
  misc/config_tools/scenario_config/ivshmem_cfg_h.py
  misc/config_tools/scenario_config/pci_dev_c.py
  misc/config_tools/scenario_config/pt_intx_c.py
  misc/config_tools/scenario_config/scenario_cfg_gen.py
  misc/config_tools/scenario_config/vm_configurations_c.py
  misc/config_tools/scenario_config/vm_configurations_h.py
Labels: CI: Tracked On Pass

#6953 Doc: Launch script update for acrn on qemu
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation

#6979 Doc: release notes update
  doc/release_notes/release_notes_2.7.rst
Labels: area: documentation

#6980 doc: finalize 2.7 release notes
  doc/release_notes/release_notes_2.7.rst
Labels: area: documentation

#6985 doc: add v2.7 docs to version menu
  doc/conf.py
Labels: area: documentation

#6982 ACRN: xHCI: Check the value of Ring Segment Size
  devicemodel/hw/pci/xhci.c
Labels: CI: Tracked On Pass, release_2.7

#6989 ACRN/DM: Add the ADL-P GPU device_id to support GPU passthrough
  devicemodel/hw/pci/passthrough.c
Labels: CI: Tracked On Pass

#6997 doc: clarify 2.7 release notes
  doc/release_notes/release_notes_2.7.rst
Labels: area: documentation

#6998 doc: clarify 2.7 release notes
  doc/release_notes/release_notes_2.7.rst
Labels: area: documentation, release_2.7

#6999 deb-pkg: Support hybrid_rt scenario
  misc/packaging/acrn-hypervisor.postinst
Labels: CI: Tracked On Pass

#7000 config_tools: add cpu_affinity cmdline at scenario set "SCHED_NOOP"
  misc/config_tools/launch_config/com.py
Labels: CI: Tracked On Pass

#7002 dm: remove some dynamic parameters from acrn-dm usage
  devicemodel/core/main.c
  devicemodel/hw/pci/gvt.c
  devicemodel/hw/pci/npk.c
  devicemodel/hw/pci/virtio/virtio_coreu.c
  devicemodel/hw/pci/virtio/virtio_hdcp.c
  devicemodel/include/ioc.h
  devicemodel/include/pm_vuart.h
  devicemodel/include/sw_load.h
Labels: CI: Tracked On Pass
