Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-10, with the labels that each got.

#6647 doc: update docs and images to match scenario names
  doc/getting-started/getting-started.rst
  doc/getting-started/images/gsg_config_board.png
  doc/getting-started/images/gsg_config_launch_default.png
  doc/getting-started/images/gsg_config_launch_generate.png
  doc/getting-started/images/gsg_config_launch_load.png
  doc/getting-started/images/gsg_config_launch_save.png
  doc/getting-started/images/gsg_config_scenario_default.png
  doc/getting-started/images/gsg_config_scenario_load.png
  doc/getting-started/images/gsg_config_scenario_save.png
  doc/introduction/index.rst
  doc/reference/hv-make-options.rst
  doc/tutorials/cpu_sharing.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/images/choose_scenario.png
  doc/tutorials/images/configure_launch.png
  doc/tutorials/images/configure_launch_add.png
  doc/tutorials/images/configure_scenario.png
  doc/tutorials/images/configure_vm_add.png
  doc/tutorials/images/generate_launch_script.png
  doc/tutorials/using_partition_mode_on_nuc.rst
  doc/tutorials/using_serial_port.rst
Labels: area: documentation

#6643 hv: nested: refine vmcs12_read/write_field APIs
  hypervisor/arch/x86/guest/nested.c
Labels: CI: Tracked On Pass

#6649 hv: call vcpu_inject_exception() only when ACRN_REQUEST_EXCP is set
  hypervisor/arch/x86/guest/virq.c
Labels: CI: Tracked On Pass

#6659 doc: update GSG with DX recommendations
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6660 doc: remove unreferenced images
  doc/getting-started/roscube/images/rqi-acrn-architecture.png
  doc/getting-started/roscube/images/rqi-acrn-blkid.png
  doc/getting-started/roscube/images/rqi-acrn-config-export-xml-submit.png
  doc/getting-started/roscube/images/rqi-acrn-config-export-xml.png
  doc/getting-started/roscube/images/rqi-acrn-config-generate-config-submit.png
  doc/getting-started/roscube/images/rqi-acrn-config-generate-config.png
  doc/getting-started/roscube/images/rqi-acrn-config-hv-settings.png
  doc/getting-started/roscube/images/rqi-acrn-config-import-board.png
  doc/getting-started/roscube/images/rqi-acrn-config-scenario-settings.png
  doc/getting-started/roscube/images/rqi-acrn-config-select-board.png
  doc/getting-started/roscube/images/rqi-acrn-config-vm0-settings.png
  doc/getting-started/roscube/images/rqi-acrn-config-vm1-settings.png
  doc/getting-started/roscube/images/rqi-acrn-config-vm2-settings1.png
  doc/getting-started/roscube/images/rqi-acrn-config-vm2-settings2.png
  doc/getting-started/roscube/images/rqi-acrn-config-web.png
  doc/getting-started/roscube/images/rqi-acrn-dmesg.png
  doc/getting-started/roscube/images/rqi-acrn-ethernet-lspci.png
  doc/getting-started/roscube/images/rqi-acrn-grub.png
  doc/getting-started/roscube/images/rqi-acrn-grun-40_custom.png
  doc/getting-started/roscube/images/rqi-acrn-hw-connection.jpg
  doc/getting-started/roscube/images/rqi-acrn-kvm-choose-iso.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-cpu-ram.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-firmware.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-name.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-new-vm.png
  doc/getting-started/roscube/images/rqi-acrn-kvm-storage.png
  doc/getting-started/roscube/images/rqi-acrn-rtos-clone.png
  doc/getting-started/roscube/images/rqi-acrn-rtos-ready.png
  doc/getting-started/roscube/images/rqi-acrn-usb-port.png
  doc/getting-started/roscube/images/rqi-pin-definition.png
  doc/tutorials/images/click_import_board_info_button.png
  doc/tutorials/images/config_app_main_menu.png
  doc/tutorials/images/offline_tools_workflow.png
  doc/tutorials/images/select_board_info.png
Labels: area: documentation

#6662 hv: optimize run_vcpu() for nested
  hypervisor/arch/x86/guest/vcpu.c
Labels: CI: Tracked On Pass

#6658 hv: support at most MAX_VUART_NUM_PER_VM legacy vuarts
  hypervisor/dm/vuart.c
  hypervisor/include/arch/x86/asm/guest/vmx_io.h
Labels: Tracked On Pass, CI: Tracked On Pass

#6672 config_tools: add Board Inspector tool success message
  misc/config_tools/board_inspector/board_inspector.py
Labels: CI: Tracked On Pass

#6645 doc: update uses of VHM in doxygen comments
  hypervisor/include/arch/x86/asm/guest/guest_memory.h
  hypervisor/include/public/acrn_common.h
  hypervisor/include/public/acrn_hv_defs.h
Labels: CI: Tracked On Pass

#6697 doc: terminology cleanup in hv-dev-passthrough.rst
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/developer-guides/hld/images/PTM-hld-PTM-flow.png
  doc/developer-guides/hld/images/passthru-image102.png
  doc/developer-guides/hld/images/passthru-image30.png
  doc/developer-guides/hld/images/passthru-image42.png
  doc/developer-guides/hld/images/passthru-image77.png
  doc/developer-guides/hld/images/passthru-image86.png
  doc/developer-guides/hld/images/passthru-image98.png
Labels: area: documentation

#6741 doc: fix broken links
  doc/reference/hardware.rst
  doc/tutorials/trustyACRN.rst
Labels: area: documentation
