Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-11, with the labels that each got.

#6742 hv: Fix vcpu signaling racing problem in lock instruction emulation
  hypervisor/arch/x86/guest/lock_instr_emul.c
  hypervisor/arch/x86/guest/virq.c
  hypervisor/include/arch/x86/asm/guest/virq.h
Labels: approved, CI: Tracked On Pass

#6750 OVMF release v2.7
  devicemodel/bios/MD5SUM_ovmf
  devicemodel/bios/OVMF.fd
  devicemodel/bios/OVMF_CODE.fd
  devicemodel/bios/OVMF_CODE_debug.fd
  devicemodel/bios/OVMF_debug.fd
  devicemodel/bios/SHA512SUM_ovmf
  devicemodel/bios/changelog_ovmf.txt
Labels: CI: Tracked On Pass

#6695 deb-pkg: add acrn-hypervisor and acrn-board-inspector into debian pac…
  .deb.conf
  Makefile
  misc/config_tools/acpi_gen/bin_gen.py
  misc/config_tools/board_inspector/acpiparser/_utils.py
  misc/config_tools/board_inspector/acpiparser/apic.py
  misc/config_tools/board_inspector/acpiparser/asf.py
  misc/config_tools/board_inspector/acpiparser/dmar.py
  misc/config_tools/board_inspector/acpiparser/facp.py
  misc/config_tools/board_inspector/acpiparser/rdt.py
  misc/config_tools/board_inspector/acpiparser/rtct.py
  misc/config_tools/board_inspector/acpiparser/tpm2.py
  misc/config_tools/board_inspector/inspectorlib/bitfields.py
  misc/config_tools/board_inspector/inspectorlib/cdata.py
  misc/config_tools/board_inspector/inspectorlib/mmio.py
  misc/config_tools/board_inspector/inspectorlib/unpack.py
  misc/config_tools/board_inspector/pcieparser/caps.py
  misc/config_tools/board_inspector/pcieparser/extcaps.py
  misc/config_tools/board_inspector/pcieparser/header.py
  misc/config_tools/board_inspector/smbiosparser/smbios.py
  misc/packaging/100_ACRN
  misc/packaging/acrn-board-inspector.postinst
  misc/packaging/acrn-board-inspector.prerm
  misc/packaging/acrn-hypervisor.postinst
  misc/packaging/acrn-kernel.postinst
  misc/packaging/gen_acrn_deb.py
Labels: Coding Guidelines: PASS, doc: needed, approved, CI: Tracked On Pass

#6764 doc: tweak CSS for Sphinx/Breathe API documents
  doc/static/acrn-custom.css
Labels: area: documentation

#6763 doc: clean up UOS/SOS and scenario names in glossary
  doc/glossary.rst
Labels: area: documentation

#6762 doc: draft release notes for v2.7
  doc/release_notes/release_notes_2.7.rst
Labels: area: documentation

#6721 misc: config_tools: add vuart for communication
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/shared.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/shared.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/shared.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i5/shared.xml
Labels: pending approve, CI: Tracked On Pass

#6753 config-tools: refine MMIO32/64_START and MMIO32/64_END
  misc/config_tools/static_allocators/gpa.py
Labels: pending approve, CI: Tracked On Pass

#6725 config_tools: remove hvlog parameter and update HV_RAM_START default address
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/shared.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/hv_config/hv_item.py
  misc/config_tools/library/hv_cfg_lib.py
  misc/config_tools/schema/config.xsd
Labels: approved, CI: Tracked On Pass

#6761 config_tools: rename uos to user_vm in config UI
  misc/config_tools/config_app/controller.py
  misc/config_tools/config_app/static/main.js
  misc/config_tools/config_app/templates/launch.html
  misc/config_tools/config_app/templates/scenario.html
  misc/config_tools/config_app/views.py
Labels: CI: Tracked On Pass

#6768 config_tools: fix the duplicate PT_SLOT value issue
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/library/launch_cfg_lib.py
Labels: CI: Tracked On Pass

#6774 doc: update last updated information on page footers
  doc/Makefile
  doc/index.rst
  doc/scripts/fix-git-modified-date.sh
  doc/static/acrn-custom.css
Labels: area: documentation

#6771 config_tools: rename UOS to user vm in UI
  misc/config_tools/config_app/templates/launch.html
Labels: approved, CI: Tracked On Pass

#6772 Revert "misc: config_tools: add vuart for communication"
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/shared.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/shared.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/shared.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i5/shared.xml
Labels: approved, CI: Tracked On Pass

#6770 dm: minor fix: fix potential overflow in device model
  devicemodel/hw/mmio/core.c
Labels: approved, CI: Tracked On Pass

#6777 config_tools: fix UI issue don't expand the default value in xml file
  misc/config_tools/config_app/views.py
Labels: approved, CI: Tracked On Pass

#6715 doc: terminology cleanup in acrnlog readme
  misc/debug_tools/acrn_log/README.rst
Labels: area: documentation, approved

#6779 dm: fixup the alignment of software region address
  devicemodel/hw/platform/acpi/rtct.c
Labels: approved, CI: Tracked On Pass

#6766 misc: config_tools: generate serial configuration file
  hypervisor/Makefile
  misc/config_tools/service_vm_config/README
  misc/config_tools/service_vm_config/serial_config.py
Labels: approved, CI: Tracked On Pass

#6786 ACRN: DM: Vulnerable coding style in device-model
  devicemodel/hw/pci/core.c
  devicemodel/hw/pci/xhci.c
Labels: approved, CI: Tracked On Pass

#6782 doc: Update VT-d spec link
  doc/developer-guides/hld/hv-vt-d.rst
Labels: area: documentation, pending approve

#6800 doc: fix git clone and misspelling
  doc/developer-guides/hld/hld-power-management.rst
  doc/getting-started/getting-started.rst
Labels: area: documentation

#6796 doc: terminology cleanup in nvmx tutorial
  doc/tutorials/nvmx_virtualization.rst
Labels: area: documentation, approved

#6795 doc: terminology cleanup in DM params
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, approved

#6802 doc: terminology cleanup in What Is ACRN, HLD intro
  doc/developer-guides/hld/index.rst
  doc/introduction/index.rst
Labels: area: documentation, pending approve

#6808 deb-pkg: update deb configuration to install serial.conf
  .deb.conf
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6811 config_tools: fix the duplicate PT_SLOT value issue in UI
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: approved, CI: Tracked On Pass, release_2.7

#6812 config_tool: add cpu affinity check (release_2.7)
  misc/config_tools/launch_config/launch_item.py
  misc/config_tools/library/scenario_cfg_lib.py
  misc/config_tools/scenario_config/scenario_item.py
Labels: approved, CI: Tracked On Pass, release_2.7

#6803 doc: terminology cleanup in trusty doc
  doc/developer-guides/images/trusty-arch.png
  doc/developer-guides/images/trusty-boot-flow.dot
  doc/developer-guides/trusty.rst
Labels: area: documentation, pending approve

#6816 [for v2.7] hv: initialize and save/restore IA32_TSC_AUX MSR for guest
  hypervisor/arch/x86/guest/trusty.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/asm/cpu.h
  hypervisor/include/arch/x86/asm/guest/vcpu.h
Labels: approved, CI: Tracked On Pass, release_2.7

#6818 [for v2.7]misc: life_mngr: fix some typo issues
  misc/services/life_mngr/Makefile
  misc/services/life_mngr/command_handler.c
  misc/services/life_mngr/uart.h
  misc/services/life_mngr/uart_channel.c
  misc/services/life_mngr/uart_channel.h
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6819 config-tools: refine acrn:get-common-clos-max
  misc/config_tools/xforms/lib.xsl
  misc/config_tools/xforms/misc_cfg.h.xsl
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6822 doc: terminology cleanup in IOC virt
  doc/developer-guides/hld/hv-ioc-virt.rst
  doc/developer-guides/hld/images/ioc-image10.png
  doc/developer-guides/hld/images/ioc-image15.png
  doc/developer-guides/hld/images/ioc-image19.png
  doc/developer-guides/hld/images/ioc-image2.png
  doc/developer-guides/hld/images/ioc-image20.png
  doc/developer-guides/hld/images/ioc-image21.png
  doc/developer-guides/hld/images/ioc-image22.png
  doc/developer-guides/hld/images/ioc-image3.png
  doc/developer-guides/hld/images/ioc-image4.png
  doc/developer-guides/hld/images/ioc-image8.png
Labels: area: documentation, approved

#6815 hv: initialize and save/restore IA32_TSC_AUX MSR for guest
  hypervisor/arch/x86/guest/trusty.c
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/asm/cpu.h
  hypervisor/include/arch/x86/asm/guest/vcpu.h
Labels: approved, CI: Tracked On Pass

#6794 config-tools: enable hv features by default
  misc/config_tools/schema/config.xsd
Labels: approved, CI: Tracked On Pass

#6798 deb-pkg: update deb configuration to install serial.conf
  .deb.conf
Labels: approved, CI: Tracked On Pass

#6790 doc: Update nuc11 partitioned document and Scenario xml
  doc/tutorials/using_partition_mode_on_nuc.rst
  misc/config_tools/data/nuc11tnbi5/partitioned.xml
Labels: approved, CI: Tracked On Pass

#6820 [release_2.7]hv: reset CAT Capacity Bitmask(CBM) MSRs
  hypervisor/arch/x86/rtcm.c
  hypervisor/include/arch/x86/asm/cpuid.h
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6827 doc: terminology cleanup in partition mode
  doc/developer-guides/hld/hv-partitionmode.rst
  doc/developer-guides/hld/images/partition-image18.png
Labels: area: documentation, pending approve

#6809 hv: align the MAX_IR_ENTRIES to MAX_PT_IRQ_ENTRIES
  hypervisor/arch/x86/vtd.c
  hypervisor/include/arch/x86/asm/vtd.h
  hypervisor/include/lib/util.h
  misc/hv_prebuild/static_checks.c
Labels: approved, CI: Tracked On Pass

#6810 config_tools: fix the duplicate PT_SLOT value issue in UI
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: approved, CI: Tracked On Pass

#6756 config-tools: refine acrn:get-common-clos-max
  misc/config_tools/xforms/lib.xsl
  misc/config_tools/xforms/misc_cfg.h.xsl
Labels: approved, CI: Tracked On Pass

#6797 config-tools: refine MAX_MSIX_TABLE_NUM
  misc/config_tools/xforms/config.h.xsl
  misc/config_tools/xforms/config.mk.xsl
  misc/config_tools/xforms/config_common.xsl
  misc/config_tools/xforms/lib.xsl
Labels: pending approve, release_2.5, CI: Tracked On Pass

#6835 HV: fix build issue on RELEASE version
  hypervisor/common/efi_mmap.c
Labels: approved, CI: Tracked On Pass

#6838 config_tools: remove GUEST_FLAG_SECURITY_VM in DM_OWNED_GUEST_FLAG_MASK
  misc/config_tools/xforms/vm_configurations.h.xsl
Labels: CI: Tracked On Pass, release_2.7

#6836 [release 2.7]HV: fix build issue on RELEASE version
  hypervisor/common/efi_mmap.c
Labels: approved, CI: Tracked On Pass, release_2.7

#6845 doc: terminology cleanup in kernel params
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation, pending approve

#6852 [release_2.7] dm: validate input of virtio_console_control_tx()
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6813 doc: fix misspelling in memory management doc
  doc/developer-guides/hld/hv-memmgt.rst
Labels: area: documentation, approved

#6823 doc: refine enable s5 document
  doc/getting-started/getting-started.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/images/s5-scenario-2.dot
  doc/tutorials/images/s5_overall_architecture.png
Labels: area: documentation, pending approve

#6864 doc: fix 2.3 release notes broken link
  doc/release_notes/release_notes_2.3.rst
Labels: area: documentation, pending approve

#6872 doc: terminology cleanup in images (gpio)
  doc/developer-guides/hld/images/virtio-gpio-2.png
Labels: area: documentation, pending approve

#6870 doc: terminology cleanup in images (trusty tutorial)
  doc/tutorials/images/trustyacrn-image4.png
  doc/tutorials/images/trustyacrn-image6.png
  doc/tutorials/images/trustyacrn-image7.png
Labels: area: documentation, pending approve

#6869 doc: terminology cleanup in images (sriov)
  doc/tutorials/images/sriov-image12.png
  doc/tutorials/images/sriov-image3.png
  doc/tutorials/images/sriov-image4.png
  doc/tutorials/images/sriov-image7.png
Labels: area: documentation, pending approve

#6867 doc: terminology cleanup in image (Modular Design)
  doc/developer-guides/images/modularity-architecture.png
Labels: area: documentation, pending approve

#6866 doc: terminology cleanup in images (I/O HLD)
  doc/developer-guides/hld/images/ioem-image100.png
  doc/developer-guides/hld/images/ioem-image101.png
  doc/developer-guides/hld/images/ioem-image106.png
Labels: area: documentation, pending approve

#6833 doc: terminology cleanup in file names, labels
  doc/conf.py
  doc/develop.rst
  doc/developer-guides/hld/hld-security.rst
  doc/developer-guides/hld/images/network-virt-service-vm-infrastruct.png
  doc/developer-guides/hld/virtio-net.rst
  doc/tutorials/using_hybrid_mode_on_nuc.rst
  doc/tutorials/using_vxworks_as_user_vm.rst
  doc/tutorials/using_windows_as_user_vm.rst
  doc/tutorials/using_xenomai_as_user_vm.rst
  doc/tutorials/using_zephyr_as_user_vm.rst
Labels: area: documentation, pending approve

#6854 doc: update CODEOWNERS for documentation reviewers
  CODEOWNERS
Labels: pending approve, CI: Tracked On Pass

#6824 doc: remove VBSK related content
  doc/contribute.rst
  doc/developer-guides/VBSK-analysis.rst
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, pending approve, make doc fail

#6868 doc: terminology cleanup in image (Shell)
  doc/user-guides/images/shell_image8.png
Labels: area: documentation, pending approve

#6871 doc: terminology cleanup in images (uart)
  doc/developer-guides/hld/images/uart-image1.png
Labels: area: documentation, pending approve

#6829 doc: terminology cleanup in RTC virt
  doc/developer-guides/hld/rtc-virt-hld.rst
Labels: area: documentation, approved

#6887 [release 2.7]HV: correct hv_ram_size when hv is relocated
  hypervisor/arch/x86/boot/cpu_primary.S
  hypervisor/arch/x86/mmu.c
  hypervisor/bsp/ld/link_ram.ld.in
  hypervisor/include/arch/x86/asm/boot/ld_sym.h
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6880 dm: fix mevent timing issue to master branch
  devicemodel/core/mevent.c
Labels: approved, CI: Tracked On Pass

#6876 config_tools: remove LOW_RAM_SIZE
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/shared.xml
  misc/config_tools/data/generic_board/generic_code/hybrid/generic_board.config
  misc/config_tools/data/generic_board/generic_code/partitioned/generic_board.config
  misc/config_tools/data/generic_board/generic_code/shared/generic_board.config
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/partitioned.xml
  misc/config_tools/data/generic_board/shared.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/partitioned.xml
  misc/config_tools/data/nuc11tnbi5/shared.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/partitioned.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i5/shared.xml
  misc/config_tools/hv_config/board_defconfig.py
  misc/config_tools/hv_config/hv_item.py
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: approved, CI: Tracked On Pass

#6884 doc: terminology cleanup in partitioned GSG
  doc/tutorials/using_partition_mode_on_nuc.rst
Labels: area: documentation, pending approve

#6804 doc: terminology cleanup in usb doc
  doc/developer-guides/hld/images/usb-image10.png
  doc/developer-guides/hld/images/usb-image31.png
  doc/developer-guides/hld/images/usb-image51.png
  doc/developer-guides/hld/usb-virt-hld.rst
Labels: area: documentation, approved

#6828 doc: terminology cleanup in DM readme
  devicemodel/README.rst
Labels: area: documentation, pending approve

#6825 doc: add vCAT documentation
  doc/develop.rst
  doc/developer-guides/hld/hld-hypervisor.rst
  doc/developer-guides/hld/hv-vcat.rst
  doc/developer-guides/hld/images/vcat-hld.png
  doc/tutorials/vcat_configuration.rst
Labels: area: documentation, pending approve

#6898 doc: terminology cleanup in sgx
  doc/tutorials/sgx_virtualization.rst
Labels: area: documentation, pending approve

#6895 doc: terminology cleanup in virtio-rnd
  doc/developer-guides/hld/images/virtio-hld-image61.png
  doc/developer-guides/hld/virtio-rnd.rst
Labels: area: documentation, pending approve

#6878 Dm: fix mevent timing issue to v2.7
  devicemodel/core/mevent.c
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6882 config_tools: remove CONFIG_MAX_IR_ENTRIES
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/shared.xml
  misc/config_tools/data/generic_board/generic_code/hybrid/generic_board.config
  misc/config_tools/data/generic_board/generic_code/partitioned/generic_board.config
  misc/config_tools/data/generic_board/generic_code/shared/generic_board.config
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/partitioned.xml
  misc/config_tools/data/generic_board/shared.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/partitioned.xml
  misc/config_tools/data/nuc11tnbi5/shared.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/partitioned.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i5/shared.xml
  misc/config_tools/hv_config/board_defconfig.py
  misc/config_tools/hv_config/hv_item.py
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: approved, CI: Tracked On Pass

#6860 dm: minor fix: add check for malloc result
  devicemodel/hw/platform/acpi/acpi_parser.c
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6863 config_tool: load default cpu affinity config by vm_name (release_2.7)
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/launch_config/launch_item.py
  misc/config_tools/library/scenario_cfg_lib.py
  misc/config_tools/scenario_config/scenario_item.py
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6889 hv: sched: fix bug when reboot vm
  hypervisor/common/sched_bvt.c
Labels: pending approve, CI: Tracked On Pass, release_2.7

#6901 doc: replace UUID with vm name to identify a vm
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-security.rst
  doc/tutorials/rdt_configuration.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, pending approve

#6894 doc: terminology cleanup in ivshmem
  doc/tutorials/enable_ivshmem.rst
Labels: area: documentation, pending approve

#6893 doc: terminology cleanup in launch options
  doc/reference/config-options-launch.rst
Labels: area: documentation, pending approve

#6892 doc: terminology cleanup in hostbridge hld
  doc/developer-guides/hld/hostbridge-virt-hld.rst
Labels: area: documentation, pending approve

#6891 doc: terminology cleanup in config intro
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation, pending approve

#6801 doc: terminology cleanup in mem mgmt hld
  doc/developer-guides/hld/hv-memmgt.rst
  doc/developer-guides/hld/images/mem-image1.png
  doc/developer-guides/hld/images/mem-image18.png
  doc/developer-guides/hld/images/mem-image3.png
  doc/developer-guides/hld/images/mem-image69.png
  doc/developer-guides/hld/images/mem-image8.png
  doc/developer-guides/hld/images/mem-image84.png
Labels: area: documentation, approved

#6900 doc: update two scheduling algorithm
  doc/tutorials/cpu_sharing.rst
Labels: area: documentation, pending approve

#6857 dm: validate input of virtio_console_control_tx()
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: approved, CI: Tracked On Pass

#6886 HV: correct hv_ram_size when hv is relocated
  hypervisor/arch/x86/boot/cpu_primary.S
  hypervisor/arch/x86/mmu.c
  hypervisor/bsp/ld/link_ram.ld.in
  hypervisor/include/arch/x86/asm/boot/ld_sym.h
Labels: approved, CI: Tracked On Pass

#6862 config_tool: load default cpu affinity config by vm_name
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/launch_config/launch_item.py
  misc/config_tools/library/scenario_cfg_lib.py
  misc/config_tools/scenario_config/scenario_item.py
Labels: CI: Tracked On Pass

#6912 doc: update Linux Foundation copyright footer
  doc/conf.py
Labels: area: documentation, First_build, test_finished

#6914 doc: Add TSC and membership documentation
  CONTRIBUTING.rst
  doc/developer-guides/contribute_guidelines.rst
Labels: area: documentation, pending approve, First_build

#6905 hv: Fix minor coding style warnings
  hypervisor/arch/x86/guest/vm.c
Labels: approved, CI: Tracked On Pass, test_finished

#6915 doc: terminology cleanup in GSG
  doc/getting-started/getting-started.rst
  doc/getting-started/images/gsg_config_launch_generate.png
  doc/getting-started/images/gsg_config_launch_load.png
  doc/getting-started/images/gsg_config_launch_save.png
Labels: area: documentation, pending approve, First_build, test_finished

#6913 doc: terminology cleanup in ACRN Configurator Tool
  doc/tutorials/acrn_configurator_tool.rst
  doc/tutorials/images/choose_launch.png
  doc/tutorials/images/configure_launch.png
  doc/tutorials/images/configure_launch_add.png
  doc/tutorials/images/err_acrn_configuration.png
  doc/tutorials/images/generate_launch_script.png
Labels: area: documentation, pending approve, First_build
