Repository projectacrn/acrn-hypervisor, pull requests merged in 2021-07, with the labels that each got.

#6268 dm: Reset virtio device before release
  devicemodel/hw/pci/virtio/virtio_audio.c
  devicemodel/hw/pci/virtio/virtio_block.c
  devicemodel/hw/pci/virtio/virtio_console.c
  devicemodel/hw/pci/virtio/virtio_coreu.c
  devicemodel/hw/pci/virtio/virtio_gpio.c
  devicemodel/hw/pci/virtio/virtio_hdcp.c
  devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c
  devicemodel/hw/pci/virtio/virtio_i2c.c
  devicemodel/hw/pci/virtio/virtio_input.c
  devicemodel/hw/pci/virtio/virtio_ipu.c
  devicemodel/hw/pci/virtio/virtio_mei.c
  devicemodel/hw/pci/virtio/virtio_net.c
  devicemodel/hw/pci/virtio/virtio_rnd.c
  devicemodel/hw/pci/virtio/virtio_rpmb.c
Labels: CI: Tracked On Pass

#6272 dm: Add PCI IDS for EHL/TGL/ADL in GPU passthrough
  devicemodel/hw/pci/passthrough.c
  devicemodel/include/pcireg.h
Labels: CI: Tracked On Pass

#6271 config_tools: update board_inspector to copy RTCT file
  misc/config_tools/acpi_template/ehl-crb-b/PTCT
  misc/config_tools/acpi_template/tgl-rvp/PTCT
  misc/config_tools/board_inspector/legacy/acpi.py
Labels: CI: Tracked On Pass

#6274 config_tools: fix cpu offline issue in launch script
  misc/config_tools/launch_config/com.py
Labels: CI: Tracked On Pass

#6278 [Release_2.0] DM: port CVEs fix
  devicemodel/core/vmmapi.c
  devicemodel/hw/pci/virtio/virtio.c
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass, release_2.0

#6279 [apl_sdc_stable] port CVE Fix
  devicemodel/hw/pci/virtio/virtio.c
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: CI: Tracked On Pass, CI: apl_sdc_stable

#6267 doc: Update address to report security vulnerability
  README.rst
Labels: area: documentation

#6294 doc: remove doc dependency on kerneldoc and acrn-kernel repo
  doc/Makefile
  doc/api/GVT-g_api.rst
  doc/api/index.rst
  doc/conf.py
  doc/contribute.rst
  doc/developer-guides/GVT-g-porting.rst
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/hld/hld-virtio-devices.rst
  doc/release_notes/release_notes_2.3.rst
  doc/scripts/kernel-doc
  doc/scripts/pullsource.sh
  doc/tutorials/docbuild.rst
Labels: area: documentation

#6285 hv: minor coding style fix in list.h
  hypervisor/include/lib/list.h
Labels: CI: Tracked On Pass

#6300 [release_2.3.1] hv: minor coding style fix in list.h
  hypervisor/include/lib/list.h
Labels: CI: Tracked On Pass, release_2.3

#6286 config_tools: update board xml files for MAX_MSIX_TABLE_NUM fix
  misc/config_tools/data/adl-rvp/adl-rvp.xml
  misc/config_tools/data/cfl-k700-i7/cfl-k700-i7.xml
  misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
  misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
  misc/config_tools/data/nuc7i7dnb/nuc7i7dnb.xml
  misc/config_tools/data/tgl-rvp/tgl-rvp.xml
  misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
  misc/config_tools/data/whl-ipc-i7/whl-ipc-i7.xml
Labels: CI: Tracked On Pass

#6306 [Release 2.5]HV: vm_load: build vrsdp after VM image loaded
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass, release_2.5

#6302 doc: add enable PTM tutorial
  doc/develop.rst
  doc/tutorials/enable_ptm.rst
Labels: area: documentation

#6293 config_tools: update nuc11tnbi5 xml files
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_launch_2uos.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_rt.xml
  misc/config_tools/data/nuc11tnbi5/industry.xml
  misc/config_tools/data/nuc11tnbi5/industry_launch_2uos.xml
  misc/config_tools/data/nuc11tnbi5/industry_launch_6uos.xml
  misc/config_tools/data/nuc11tnbi5/logical_partition.xml
Labels: CI: Tracked On Pass

#6304 config_tools: enlarge max size to store RTCT table
  misc/config_tools/acpi_gen/acpi_const.py
Labels: CI: Tracked On Pass

#6219 config-tools: do not exit when the board inspector runs in hypervisor
  misc/config_tools/board_inspector/cli.py
  misc/config_tools/board_inspector/cpuparser/__init__.py
  misc/config_tools/board_inspector/cpuparser/cpuids.py
  misc/config_tools/board_inspector/extractors/10-processors.py
  misc/config_tools/board_inspector/legacy/board_parser.py
Labels: CI: Tracked On Pass

#6308 doc: update nested virtualization tutorial notation
  doc/tutorials/nvmx_virtualization.rst
Labels: area: documentation

#6309 doc: fix acrn shell command
  doc/user-guides/acrn-shell.rst
Labels: area: documentation

#6311 config-tools: add uclock GP switch
  misc/config_tools/data/adl-rvp/industry.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/industry.xml
  misc/config_tools/data/ehl-crb-b/fusa_partition.xml
  misc/config_tools/data/ehl-crb-b/hybrid.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
  misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
  misc/config_tools/data/ehl-crb-b/industry.xml
  misc/config_tools/data/ehl-crb-b/logical_partition.xml
  misc/config_tools/data/ehl-crb-b/sdc.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/industry.xml
  misc/config_tools/data/generic_board/logical_partition.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/industry.xml
  misc/config_tools/data/nuc11tnbi5/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/hybrid.xml
  misc/config_tools/data/nuc7i7dnb/industry.xml
  misc/config_tools/data/nuc7i7dnb/logical_partition.xml
  misc/config_tools/data/nuc7i7dnb/sdc.xml
  misc/config_tools/data/qemu/sdc.xml
  misc/config_tools/data/tgl-rvp/hybrid.xml
  misc/config_tools/data/tgl-rvp/hybrid_rt.xml
  misc/config_tools/data/tgl-rvp/industry.xml
  misc/config_tools/data/tgl-rvp/logical_partition.xml
  misc/config_tools/data/tgl-rvp/sdc.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/industry.xml
  misc/config_tools/data/whl-ipc-i5/logical_partition.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i7/hybrid.xml
  misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i7/industry.xml
  misc/config_tools/data/whl-ipc-i7/logical_partition.xml
  misc/config_tools/data/whl-ipc-i7/sdc.xml
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: CI: Tracked On Pass

#6313 hv: debug: Add hv console callback to VM-exit event
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/debug/console.c
  hypervisor/include/debug/console.h
  hypervisor/release/console.c
Labels: CI: Tracked On Pass

#6318 config_tools: add interface to save config xmls to user defined path …
  misc/config_tools/config_app/configs.py
  misc/config_tools/config_app/controller.py
  misc/config_tools/config_app/static/main.js
  misc/config_tools/config_app/templates/base.html
  misc/config_tools/config_app/templates/launch.html
  misc/config_tools/config_app/templates/scenario.html
  misc/config_tools/config_app/views.py
Labels: CI: Tracked On Pass

#6319 hv: expose PMC to core partition VM
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmsr.c
Labels: CI: Tracked On Pass

#6324 config_tools: enlarge max size to store RTCT table
  misc/config_tools/acpi_gen/acpi_const.py
Labels: CI: Tracked On Pass, release_2.5

#6325 config_tools: adjust the end of TPM log area
  misc/config_tools/static_allocators/gpa.py
Labels: CI: Tracked On Pass, release_2.5

#6327 Release 2.5：Mmiodev del before add
  hypervisor/arch/x86/guest/vm.c
Labels: CI: Tracked On Pass, release_2.5

#6328 release_2.5: hv: relocate ACPI DATA address to 0x7fe00000
  hypervisor/arch/x86/guest/ve820.c
  hypervisor/include/dm/vacpi.h
  misc/config_tools/acpi_gen/acpi_const.py
Labels: CI: Tracked On Pass, release_2.5

#6332 release_2.5: hv: vpci: modify Interrupt Line Register as writable
  hypervisor/dm/vpci/vpci.c
Labels: CI: Tracked On error, release_2.5

#6333 config_tools: config editor creates default xmls for a new board
  misc/config_tools/config_app/templates/base.html
  misc/config_tools/config_app/views.py
Labels: CI: Tracked On Pass
