Repository projectacrn/acrn-hypervisor, pull requests merged in 2022-05, with the labels that each got.

#7395 doc: fix malformed virtio gpu device description
  misc/config_tools/schema/config.xsd
Labels: master

#7340 doc: Update Configurator steps
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7403 doc: remove obsolete (and orphaned) docs
  doc/getting-started/roscube/roscube-gsg.rst
  doc/learn.rst
  doc/tutorials/running_deb_as_serv_vm.rst
  doc/tutorials/running_deb_as_user_vm.rst
  doc/tutorials/running_ubun_as_user_vm.rst
  doc/tutorials/using_yp.rst
Labels: area: documentation, master

#7397 dm: optimize the sub parameter of "-s" compatibility
  devicemodel/core/main.c
  devicemodel/hw/pci/core.c
Labels: master

#7406 config tool: add schema check for cpu_affinity
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: master

#7408 config tool:add restriction for some parameters
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
Labels: master

#7411 config tool:add vmname in launch script
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: master

#7386 Fix: write xmm registers correctly
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/include/arch/x86/asm/cpu.h
Labels: master

#7414 config-tools: add alert for non-exist file
  misc/config_tools/configurator/src/pages/Config/Scenario.vue
Labels: master

#7415 hv: fix post RTVM booting failure with SSRAM
  hypervisor/arch/x86/guest/vm.c
Labels: master

#7417 config-tools: board_inspector deb appends kernel CMDLINE
  misc/packaging/acrn-board-inspector.postinst
Labels: master

#7404 doc: fix the make configurator fails issue
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7412 doc: Copyedit upgrading_configuration.rst
  doc/tutorials/upgrading_configuration.rst
Labels: area: documentation, master

#7432 doc: Remove outdated ClearLinux Docker file
  doc/getting-started/Dockerfile
Labels: area: documentation, master

#7431 doc: Remove acrn quick setup script
  doc/getting-started/acrn_quick_setup.sh
  doc/getting-started/changelog_QuickSetupScript.txt
Labels: area: documentation, master

#7427 misc: deb: Fix the ServiceVM kernel line in ACRN grub entry
  misc/packaging/acrn-hypervisor.postinst
Labels: master

#7430 config-tools: Update board.xml file based on board inspector modifica…
  misc/config_tools/data/generic_board/generic_board.xml
  misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/tgl-vecow-spc-7100-Corei7.xml
  misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
Labels: master

#7433 Acrn edid fix
  devicemodel/hw/vdisplay_sdl.c
Labels: master

#7391 config_tools: update the hugepage algorithm
  misc/config_tools/static_allocators/memory_allocator.py
  misc/config_tools/xforms/misc_cfg.h.xsl
Labels: master

#7429 config-tools:Board Inspector Behaviors Improvement
  misc/config_tools/board_inspector/board_inspector.py
Labels: master

#7428 misc: configurator: Config usb mediator devices in dropdown list
  misc/config_tools/board_inspector/extractors/95-usb.py
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
Labels: master

#7439 config_tools: fix can't find deb in build stage issue
  misc/packaging/gen_acrn_deb.py
Labels: master

#7436 misc: configurator: Disable steps until prior step completed
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7441 config_tools: drop version constraints on elementpath and xmlschema
  misc/config_tools/requirements.txt
Labels: master

#7444 config_tools: update node-fetch version lock to 2.6.7
  misc/config_tools/configurator/packages/configurator/package.json
  misc/config_tools/configurator/yarn.lock
Labels: master

#7426 hv: update SSRAM regions EPT memory type to WB
  hypervisor/arch/x86/guest/vm.c
Labels: master

#7446 config-tools: limit the tooltip box max-width
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
Labels: master

#7449 config-tools: ivshmem.vm_name changes with name edit
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
Labels: master

#7452 config-tools: bugfix for file related issue in UI
  misc/config_tools/configurator/packages/configurator/src-tauri/src/configurator.rs
  misc/config_tools/configurator/packages/configurator/src-tauri/src/main.rs
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Welcome/NewConfiguration.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Welcome/UseExisting.vue
Labels: master

#7457 misc: configurator: Add vUART widget
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
Labels: master

#7460 config-tools: modify scenario.json in build directory
  misc/config_tools/configurator/packages/configurator/src/pyodide.js
  misc/config_tools/scenario_config/jsonschema/converter.py
Labels: master

#7458 config_tools: fix can't save cpu affinity config issue
  misc/config_tools/configurator/packages/configurator/package.json
  misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.lock
  misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.toml
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
  misc/config_tools/configurator/yarn.lock
Labels: master

#7448 doc: Remove outdated RT tutorial
  doc/develop.rst
  doc/tutorials/pre-launched-rt.rst
Labels: area: documentation, master

#7465 doc: update GSG for virtio-gpu dependency libraries
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7467 [config tool][doc]: remove old configurator
  doc/develop.rst
  doc/tutorials/acrn_configurator_tool.rst
  misc/config_tools/config_app/acrn_configurator.py
  misc/config_tools/config_app/configs.py
  misc/config_tools/config_app/controller.py
  misc/config_tools/config_app/requirements
  misc/config_tools/config_app/static/main.js
  misc/config_tools/config_app/static/styles.css
  misc/config_tools/config_app/templates/base.html
  misc/config_tools/config_app/templates/launch.html
  misc/config_tools/config_app/templates/scenario.html
  misc/config_tools/config_app/views.py
Labels: master

#7473 doc: remove unused images from get-started folder
  doc/getting-started/images/gsg_config_blk.png
  doc/getting-started/images/gsg_config_board.png
  doc/getting-started/images/gsg_config_launch_default.png
  doc/getting-started/images/gsg_config_launch_generate.png
  doc/getting-started/images/gsg_config_launch_load.png
  doc/getting-started/images/gsg_config_launch_save.png
  doc/getting-started/images/gsg_config_mem.png
  doc/getting-started/images/gsg_config_scenario_default.png
  doc/getting-started/images/gsg_config_scenario_load.png
  doc/getting-started/images/gsg_config_scenario_save.png
Labels: area: documentation, master

#7474 doc: remove unreferenced images in doc tree
  doc/developer-guides/hld/images/over-image110.png
  doc/developer-guides/hld/images/virtio-hld-image54.png
  doc/developer-guides/hld/images/virtio-hld-image8.png
  doc/developer-guides/images/vbsk-image1.png
  doc/developer-guides/images/vbsk-image2.png
  doc/developer-guides/images/vbsk-image3.png
  doc/tutorials/images/choose_launch.png
  doc/tutorials/images/choose_scenario.png
  doc/tutorials/images/configure_launch.png
  doc/tutorials/images/configure_launch_add.png
  doc/tutorials/images/configure_scenario.png
  doc/tutorials/images/configure_vm_add.png
  doc/tutorials/images/debian-uservm-0.png
  doc/tutorials/images/debian-uservm-1.png
  doc/tutorials/images/debian-uservm-2.png
  doc/tutorials/images/debian-uservm-3.png
  doc/tutorials/images/debian-uservm-4.png
  doc/tutorials/images/debian-uservm-5.png
  doc/tutorials/images/debian-uservm-6.png
  doc/tutorials/images/debian-uservm-7.png
  doc/tutorials/images/err_acrn_configuration.png
  doc/tutorials/images/generate_launch_script.png
  doc/tutorials/images/pre_launched_rt.png
  doc/tutorials/images/sgx-1.png
  doc/tutorials/images/sgx-2.jpg
  doc/tutorials/images/sgx-3.jpg
  doc/tutorials/images/trustyacrn-image1.png
  doc/tutorials/images/trustyacrn-image2.png
  doc/tutorials/images/trustyacrn-image3.png
  doc/tutorials/images/trustyacrn-image4.png
  doc/tutorials/images/trustyacrn-image5.png
  doc/tutorials/images/trustyacrn-image6.png
  doc/tutorials/images/trustyacrn-image7.png
  doc/tutorials/images/ubuntu-uservm-0.png
  doc/tutorials/images/ubuntu-uservm-1.png
  doc/tutorials/images/ubuntu-uservm-2.png
  doc/tutorials/images/ubuntu-uservm-3.png
  doc/tutorials/images/ubuntu-uservm-4.png
  doc/tutorials/images/ubuntu-uservm-5.png
Labels: area: documentation, master

#7468 config tool: fix d3hot_reset unbind tap create issue
  misc/config_tools/launch_config/launch_script_template.sh
Labels: master

#7454 hv: crypto: fix a minor build Werror
  hypervisor/lib/crypto/mbedtls/md.c
Labels: master

#7475 misc: configurator: Fix minor bug of vUART label error
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
Labels: master

#7476 misc: acrnd: fix a minor build Werror
  misc/services/acrn_manager/acrnctl.c
Labels: master

#7477 config_tools: add placeholders in input widgets
  doc/scripts/configdoc.xsl
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
  misc/config_tools/scenario_config/jsonschema/converter.py
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: master

#7478 schema changes for DX configurator option presentation
  doc/reference/config-options.rst
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: master

#7462 Fix make configurator not picking up schema changes
  misc/config_tools/configurator/README.md
  misc/packaging/gen_acrn_deb.py
Labels: master

#7485 misc: configurator: Fix user-input working directory not working
  misc/config_tools/configurator/packages/configurator/src/pages/Welcome/NewConfiguration.vue
Labels: master

#7489 misc: configurator: Use more precise acrn version identifier
  Makefile
  misc/config_tools/configurator/packages/configurator/src/components/common/Footer.vue
  misc/config_tools/configurator/packages/configurator/vite.config.js
  misc/packaging/gen_acrn_deb.py
Labels: master

#7491 misc: add assert for vUART connection
  misc/config_tools/schema/checks/vuart_config.xsd
  misc/config_tools/schema/datachecks.xsd
Labels: master

#7493 config-tools: fix configurator build issue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
Labels: master

#7487 [config_tool] Duplicate VM name
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7490 config_tools: using XPATH expression to handle input data
  misc/config_tools/configurator/pyodide/loadBoard.py
  misc/config_tools/schema/VMtypes.xsd
Labels: master

#7496 misc: configurator: remove config files when choosing a working folder
  misc/config_tools/configurator/packages/configurator/src/pages/Welcome/NewConfiguration.vue
Labels: master

#7499 board_inspector.py fails to run on target with clean Ubuntu installation
  misc/packaging/acrn-board-inspector.postinst
Labels: master

#7512 hv: fix build warning with gcc-11.2
  hypervisor/dm/vrtc.c
Labels: master

#7513 misc: configurator: validate user settings before writing down
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7382 hv: vtd: reset the one-shot bits for GCMD_REG
  hypervisor/arch/x86/vtd.c
Labels: master

#7515 config: restore FEATURES on the basic tab
  misc/config_tools/schema/config.xsd
Labels: master

#7517 misc: configurator:Fix delete vm button apearance
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7509 config_tools: clean up configurator
  Makefile
  misc/packaging/gen_acrn_deb.py
Labels: master

#7523 config_tools: fix option passing to device model in launch scripts
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: master

#7520 [config_tool] Duplicate VM name
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7518 misc: configurator: Remove acrn config files when selecting a working…
  misc/config_tools/configurator/packages/configurator/src/pages/Welcome/NewConfiguration.vue
Labels: master

#7527 misc: configurator: add check for uniqueness of cpus in Pre-launched VM
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: master

#7525 config-tools: correct the confirm log
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7522 config-tools: change name for board XML
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
  misc/config_tools/configurator/pyodide/loadBoard.py
  misc/config_tools/configurator/pyodide/pyodide.py
Labels: master

#7537 Fix acrn 8899 v2
  devicemodel/hw/vdisplay_sdl.c
Labels: master

#7536 config-tools: add vsock option in configurator
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/schema/config.xsd
Labels: master

#7543 config-tools: change the tooltip width to 60%
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
Labels: master

#7534 misc: fix the physical memory segmentation UI issue
  misc/config_tools/schema/config.xsd
Labels: master

#7548 hv: debug: fix type size mismatch in get_entry_info
  hypervisor/debug/shell.c
Labels: master

#7549 misc: hide RDT for basic mode
  misc/config_tools/schema/config.xsd
Labels: master

#7550 config_tools: add set default function for cat widget
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Labels: master

#7545 misc: modify the non stand s5 vUART generate logic
  misc/config_tools/service_vm_config/serial_config.py
  misc/config_tools/static_allocators/s5_vuart.py
Labels: master

#7552 config-tools: use VMname instead of VMId
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7554 [config_tool] IVSHMEM changes to Configurator 05.06 build
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
Labels: master

#7558 config-tools: Fix Enable SR-IOV build fail
  misc/config_tools/static_allocators/bdf.py
Labels: master

#7557 misc: configurator: Add entry "None" to HV console selector
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
  misc/config_tools/static_allocators/lib/lib.py
Labels: master

#7564 dm: fix SSRAM region unmap failure issue
  devicemodel/hw/platform/vssram/vssram.c
Labels: release_3.0

#7568 [release_3.0 branch] hv: sched_event: Change nqueued from int8_t to int32_t
  hypervisor/include/common/event.h
Labels: release_3.0

#7574 misc: CPU affinity error message cleanup
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: master

#7572 config-tools: fix board import bug
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
Labels: master

#7580 ACRN: DM: Fix the vsock error info.
  devicemodel/hw/pci/virtio/vhost_vsock.c
  devicemodel/include/vhost_vsock.h
Labels: release_3.0

#7584 misc: modify IVSHMEM virtual BDF validation check
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
Labels: release_3.0

#7583 [release_3.0] misc: configurator: bugfix: incorrect path split
  misc/config_tools/configurator/pyodide/loadBoard.py
Labels: release_3.0

#7587 doc: adjust views processing for schema documentation
  doc/scripts/configdoc.xsl
Labels: area: documentation, master

#7585 misc: CPU affinity error message cleanup
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: release_3.0

#7565 config-tools: show enumNames in vuart select-form
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
  misc/config_tools/schema/VMtypes.xsd
Labels: master

#7596 misc: config_tool: Add udmabuf.list_limit=8192 to ServiceVM bootargs
  misc/config_tools/xforms/misc_cfg.h.xsl
  misc/config_tools/xforms/vm_configurations.h.xsl
Labels: master

#7589 config: additional DX/UI option layout and descriptions
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
Labels: master

#7599 misc: configurator: Delete old .board.xml after reselect a new one
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
Labels: master

#7591 config: additional DX/UI option layout and descriptions
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
Labels: release_3.0

#7600 misc: config_tool: Add udmabuf.list_limit=8192 to ServiceVM bootargs
  misc/config_tools/xforms/misc_cfg.h.xsl
  misc/config_tools/xforms/vm_configurations.h.xsl
Labels: release_3.0

#7601 misc: configurator: Delete old .board.xml after reselect a new one
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
Labels: release_3.0

#7602 config_tools: hide vm_type for Service VM
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7598 config_tools: fix move_enablement in the upgrader
  misc/config_tools/scenario_config/upgrader.py
  misc/config_tools/schema/types.xsd
Labels: master

#7604 misc: add assert for duplicate vUART io_port
  misc/config_tools/schema/checks/vuart_config.xsd
Labels: master

#7603 misc: add assert for duplicate vUART io_port
  misc/config_tools/schema/checks/vuart_config.xsd
Labels: release_3.0

#7605 move buildtype above debugoptions in the scenario schema
  misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/partitioned.xml
  misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml
  misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/partitioned.xml
  misc/config_tools/data/generic_board/shared_launch_6user_vm.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml
  misc/config_tools/data/nuc11tnbi5/partitioned.xml
  misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml
  misc/config_tools/data/qemu/shared.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml
  misc/config_tools/data/whl-ipc-i5/partitioned.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml
  misc/config_tools/schema/config.xsd
Labels: release_3.0

#7607 [release_3.0] dm: fix uninitialized variable issue in hpet_mmio_read
  devicemodel/hw/platform/hpet.c
Labels: release_3.0

#7613 doc: properly handle empty and skipped acrn:title elements
  doc/scripts/configdoc.xsl
Labels: area: documentation, master

#7615 doc: properly handle empty and skipped acrn:title elements
  doc/scripts/configdoc.xsl
Labels: area: documentation, release_3.0

#7612 config_tools: fix load board issue
  misc/config_tools/configurator/pyodide/loadBoard.py
Labels: release_3.0

#7616 config: remove extraneous headings in UI
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
Labels: release_3.0

#7614 config: remove extraneous headings in UI
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
Labels: master

#7611 config-tools: remove empty cache_region entry
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Labels: master

#7617 RDT code refine
  misc/config_tools/static_allocators/clos.py
Labels: master

#7625 misc: configurator: Fix vUART and IVSHMEM select box missing problem
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
Labels: release_3.0

#7622 config_tools: pretty-print JSON schema violations
  misc/config_tools/scenario_config/jsonschema/converter.py
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: release_3.0

#7621 config_tools: hide vm_type for Service VM
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: release_3.0

#7626 misc: config_tool: fix passthrough device options in launch script
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: release_3.0

#7610 [release_3.0] config-tools: remove empty cache_region entry
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Labels: release_3.0

#7620 config_tools: fix move_enablement in the upgrader
  misc/config_tools/scenario_config/upgrader.py
  misc/config_tools/schema/types.xsd
Labels: release_3.0

#7635 ACRN: DM: Fix the vsock Guest Cid overflow issue
  devicemodel/hw/pci/virtio/vhost_vsock.c
  devicemodel/include/vhost_vsock.h
Labels: master

#7638 config-tools: refine vsock UI
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/checks/virtio_devices.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/datachecks.xsd
Labels: release_3.0

#7640 config-tools: add tooltips
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
Labels: release_3.0

#7645 hv: compile out unused function if CONFIG_MULTIBOOT2 is disabled
  hypervisor/boot/guest/bzimage_loader.c
Labels: release_3.0

#7636 ACRN: DM: Fix the vsock cid overflow issue.
  devicemodel/hw/pci/virtio/vhost_vsock.c
Labels: release_3.0

#7633 Packaging: update Debian packaging script to reflect all valid targets
  misc/packaging/gen_acrn_deb.py
Labels: master

#7647 config_tools: filter all pre launched pcpu for service vm's cat data
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Labels: release_3.0

#7649 config_tools: add notice message for RDT checkbox
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Labels: release_3.0
