Repository projectacrn/acrn-hypervisor, pull requests merged in 2022-02, with the labels that each got.

#7085 config-tool: append passthrough gpu bdf in hexadecimal format
  misc/config_tools/launch_config/com.py
Labels: master

#7088 dm: refine the mac check logic for virtio-net
  devicemodel/hw/pci/virtio/virtio_net.c
Labels: master

#7083 Makefile: fix typo in config.mk
  hypervisor/scripts/makefile/config.mk
Labels: master

#7089 hv: remove HC_GET_PLATFORM_INFO hypercall support
  hypervisor/arch/x86/guest/vmcall.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/asm/vm_config.h
  hypervisor/include/common/hypercall.h
  hypervisor/include/public/acrn_hv_defs.h
Labels: master

#7079 hv: refine the e820 add new entry logic
  hypervisor/arch/x86/e820.c
Labels: master

#7092 config_tools: fix illegal access to the level_types dictionary
  misc/config_tools/board_inspector/extractors/10-processors.py
Labels: master

#7093 dm: disable TCC strict CPU affinity check
  devicemodel/hw/platform/vssram/vssram.c
Labels: master

#7097 doc: show source file link on html pages
  doc/conf.py
Labels: area: documentation, master

#7091 doc: Update Debian packaging readme
  doc/getting-started/getting-started.rst
  misc/packaging/README.rst
Labels: area: documentation, master

#7102 Doc: qemu cmdline update for acrn on qemu
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation, master

#7104 doc: update cpu-checker instructions in qemu doc
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation, master

#7121 doc: Remove FAQ from TOC
  doc/faq.rst
  doc/index.rst
Labels: area: documentation, master

#7122 doc: Update terms in qemu tutorial
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation, master

#7120 config-tools: bring all cores online
  misc/config_tools/board_inspector/board_inspector.py
  misc/config_tools/board_inspector/cpuparser/__init__.py
Labels: master

#7116 config_tools: category based on different log levels
  misc/config_tools/board_inspector/acpiparser/aml/context.py
  misc/config_tools/board_inspector/acpiparser/aml/datatypes.py
  misc/config_tools/board_inspector/acpiparser/aml/interpreter.py
  misc/config_tools/board_inspector/acpiparser/aml/parser.py
  misc/config_tools/board_inspector/acpiparser/tpm2.py
  misc/config_tools/board_inspector/board_inspector.py
  misc/config_tools/board_inspector/cpuparser/platformbase.py
  misc/config_tools/board_inspector/extractors/20-cache.py
  misc/config_tools/board_inspector/extractors/50-acpi-namespace.py
  misc/config_tools/board_inspector/extractors/60-pci.py
  misc/config_tools/board_inspector/extractors/helpers.py
  misc/config_tools/board_inspector/legacy/acpi.py
  misc/config_tools/board_inspector/legacy/board_parser.py
  misc/config_tools/board_inspector/legacy/clos.py
  misc/config_tools/board_inspector/smbiosparser/smbios.py
Labels: master

#7117 config-tools: update board inspector to update pci.ids before fetchin…
  misc/config_tools/board_inspector/board_inspector.py
  misc/config_tools/board_inspector/legacy/pci_dev.py
Labels: master

#7105 Add codeowner
  CODEOWNERS
Labels: pending approve, master

#7108 Makefile: put 'serial.conf' in final location
  hypervisor/Makefile
  paths.make
Labels: master

#7114 hv:fix violations of coding guideline C-ST-04
  hypervisor/arch/x86/guest/pm.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/vtd.c
  hypervisor/boot/multiboot/multiboot.c
  hypervisor/common/hypercall.c
  hypervisor/dm/vpci/pci_pt.c
  hypervisor/dm/vpci/vdev.c
  hypervisor/dm/vpci/vmcs9900.c
  hypervisor/dm/vpci/vmsix.c
  hypervisor/hw/pci.c
Labels: master

#7130 doc: Style cleanup in doc guides
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/graphviz.rst
Labels: area: documentation, master

#7134 dm: fix mevent mutex deadlock issue
  devicemodel/core/mevent.c
Labels: master

#7135 ACRN:DM: Set the desired state to inject PCI legacy intx
  devicemodel/hw/pci/core.c
  devicemodel/hw/pci/irq.c
Labels: master

#7132 config_tools: remove PLATFORM_RAM_SIZE
  misc/config_tools/data/cfl-k700-i7/hybrid.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/partitioned.xml
  misc/config_tools/data/cfl-k700-i7/shared.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/partitioned.xml
  misc/config_tools/data/generic_board/shared.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/partitioned.xml
  misc/config_tools/data/nuc11tnbi5/shared.xml
  misc/config_tools/data/qemu/shared.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/partitioned.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i5/shared.xml
  misc/config_tools/hv_config/board_defconfig.py
  misc/config_tools/hv_config/hv_item.py
  misc/config_tools/schema/checks/.pre_launched_vm_support.xsd.swp
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: master

#7111 Makefile: detect if 'dpkg' is available
  Makefile
Labels: master

#7075 doc:add UID parameter for acpidev_pt
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/mmio-dev-passthrough.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, master

#7123 doc: Update terms in vUART tutorial
  doc/tutorials/vuart_configuration.rst
Labels: area: documentation, master

#7143 doc: limit search engines scan on older content
  doc/scripts/publish-robots.txt
Labels: area: documentation, master

#7140 doc: remove obsolete content in document
  doc/tutorials/realtime_performance_tuning.rst
Labels: area: documentation, master

#7152 doc: Style cleanup in dm, gpio, interrupt hld
  doc/developer-guides/hld/hv-virt-interrupt.rst
  doc/developer-guides/hld/split-dm.rst
  doc/developer-guides/hld/virtio-gpio.rst
Labels: area: documentation, master

#7148 doc: Style cleanup in usercrash, trusty, vuart docs
  doc/developer-guides/hld/vuart-virt-hld.rst
  doc/developer-guides/trusty.rst
  doc/tutorials/setup_openstack_libvirt.rst
  misc/debug_tools/acrn_crashlog/usercrash/README.rst
Labels: master

#7144 doc: Style cleanup in guides
  doc/api/devicemodel_api.rst
  doc/api/hypercall_api.rst
  doc/user-guides/acrn-shell.rst
  doc/user-guides/hv-parameters.rst
Labels: area: documentation, master

#7096 doc: Tar file installation
  doc/develop.rst
  doc/tutorials/tar_installation.rst
Labels: area: documentation, master

#7126 Makefile: remove default BOARD and SCENARIO values
  hypervisor/scripts/makefile/config.mk
Labels: master

#7149 config_tools: fix the board inspector exit issue
  misc/config_tools/board_inspector/board_inspector.py
Labels: master

#7163 doc: fix docs with missing newline at EOF
  doc/getting-started/overview_dev.rst
  doc/tutorials/enable_s5.rst
  doc/tutorials/tar_installation.rst
  doc/tutorials/vuart_configuration.rst
Labels: area: documentation, master

#7164 doc: Style cleanup in timer hld
  doc/developer-guides/hld/hv-timer.rst
Labels: area: documentation, master
