Repository projectacrn/acrn-hypervisor, pull requests merged in 2022-06, with the labels that each got.

#7651 misc: configurator: fix IVSHMEM size missing bug
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
Labels: release_3.0

#7656 board_inspector:refine board_inspector.py
  misc/config_tools/board_inspector/board_inspector.py
Labels: release_3.0

#7659 misc: config_tools: fix make deadloop on release build with debug sce…
  misc/config_tools/xforms/config_common.xsl
Labels: release_3.0

#7658 [release_3.0] config-tools: refine the vuart widget's text
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
  misc/config_tools/schema/VMtypes.xsd
Labels: release_3.0

#7663 config_tools: schema of 'VM_NAME' for 'IVSHMEMVM'
  misc/config_tools/schema/types.xsd
Labels: release_3.0

#7666 doc: fix failure to make pdf output for project docs
  doc/.known-issues/doc/pdf.conf
  doc/Makefile
  doc/conf.py
  doc/reference/config-options.rst
  doc/reference/images/Advanced.png
  doc/reference/images/Basic.png
  doc/reference/images/Hypervisor.png
  doc/reference/images/Not-available.png
  doc/reference/images/Post-launched-VM.png
  doc/reference/images/Pre-launched-VM.png
  doc/reference/images/Service-VM.png
Labels: area: documentation, master

#7671 Change sense of some schema config options
  misc/config_tools/schema/config.xsd
Labels: release_3.0

#7675 config tool: refine cpu_affinity
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
  misc/config_tools/schema/VMtypes.xsd
Labels: release_3.0

#7670 Change sense of some schema config options
  misc/config_tools/schema/config.xsd
Labels: master

#7665 board_inspector: refine board_inspector.py
  misc/config_tools/board_inspector/board_inspector.py
Labels: release_3.0

#7664 config-tools: tiny fix for tooltip
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
Labels: release_3.0

#7677 dm: vdisplay: terminate acrn-dm process when SDL init failed
  devicemodel/core/main.c
  devicemodel/hw/vdisplay_sdl.c
  devicemodel/include/vdisplay.h
Labels: release_3.0

#7681 dm: Fix uninitialized variable in AHCI
  devicemodel/hw/pci/ahci.c
Labels: master

#7680 dm: Fix uninitialized variable in AHCI
  devicemodel/hw/pci/ahci.c
Labels: release_3.0

#7590 doc: Create doc for Configurator UI
  doc/develop.rst
  doc/tutorials/acrn_configurator_tool.rst
  doc/tutorials/images/config-file.png
  doc/tutorials/images/configurator-addvm.png
  doc/tutorials/images/configurator-backintro.png
  doc/tutorials/images/configurator-board01.png
  doc/tutorials/images/configurator-board02.png
  doc/tutorials/images/configurator-board03.png
  doc/tutorials/images/configurator-configscreen.png
  doc/tutorials/images/configurator-deletevm.png
  doc/tutorials/images/configurator-exconfig.png
  doc/tutorials/images/configurator-expand.png
  doc/tutorials/images/configurator-exscenario.png
  doc/tutorials/images/configurator-intro.png
  doc/tutorials/images/configurator-newconfig.png
  doc/tutorials/images/configurator-newscenario01.png
  doc/tutorials/images/configurator-newscenario02.png
  doc/tutorials/images/configurator-rederror.png
  doc/tutorials/images/configurator-save.png
  doc/tutorials/images/configurator-selecthypervisor.png
  doc/tutorials/images/tooltip.png
Labels: area: documentation, master

#7684 misc: add assert to check ivsh memory region name
  misc/config_tools/schema/checks/ivsh_memory.xsd
  misc/config_tools/schema/datachecks.xsd
Labels: release_3.0

#7691 ACRN: xHCI: Check the value of Ring Segment Size
  devicemodel/hw/pci/xhci.c
Labels: master

#7689 misc: config_tool: allow cpu sharing among standard VMs
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: release_3.0

#7690 [release_3.0]ACRN: xHCI: Check the value of Ring Segment Size
  devicemodel/hw/pci/xhci.c
Labels: release_3.0

#7676 config-tools: fix vBDF issue for IVSHMEM
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
  misc/config_tools/schema/types.xsd
Labels: release_3.0

#7686 doc: edit schema assert messages for clarity and grammar
  misc/config_tools/schema/checks/cpu_assignment.xsd
  misc/config_tools/schema/checks/ivsh_memory.xsd
  misc/config_tools/schema/checks/passthrough_devices.xsd
  misc/config_tools/schema/checks/rdt_support.xsd
  misc/config_tools/schema/checks/vbdf_assignment.xsd
  misc/config_tools/schema/checks/virtio_devices.xsd
  misc/config_tools/schema/checks/vm_types.xsd
  misc/config_tools/schema/checks/vuart_config.xsd
Labels: release_3.0

#7701 config tool:add schema check for UI name validation
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/checks/ivsh_memory.xsd
  misc/config_tools/schema/checks/vuart_config.xsd
Labels: release_3.0

#7702 config_tools: CAT is no longer unchecked when VCAT is unchecked
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Labels: release_3.0

#7699 ACRN:DM: Fix USB msi capability access issue.
  devicemodel/hw/pci/core.c
Labels: release_3.0

#7693 hv: sched: fix bug when reboot vm
  hypervisor/common/sched_bvt.c
Labels: release_3.0

#7715 config_tools: clear schema files
  misc/packaging/gen_acrn_deb.py
Labels: release_3.0

#7682 misc: modify the logic of generate HV_RAM_START
  misc/config_tools/hv_config/board_defconfig.py
  misc/config_tools/library/common.py
  misc/config_tools/schema/config.xsd
  misc/config_tools/static_allocators/hv_ram.py
  misc/config_tools/xforms/config_common.xsl
Labels: release_3.0

#7708 doc: edit RDT_ENABLED tooltip
  misc/config_tools/schema/types.xsd
Labels: release_3.0

#7710 config_tools: refine issues in the upgrader
  misc/config_tools/scenario_config/upgrader.py
Labels: release_3.0

#7717 doc: parameterize hidden config option doc generation
  doc/Makefile
  doc/scripts/configdoc.xsl
Labels: area: documentation, master

#7718 misc: configurator: fix minor bug of IVSHMEM region name
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
Labels: release_3.0

#7643 Makefile: remove obsolete targets
  Makefile
Labels: master

#7648 Update TSC members and maintainers
  CONTRIBUTING.rst
  devicemodel/MAINTAINERS
  hypervisor/MAINTAINERS
Labels: master

#7608 dm: fix uninitialized variable issue in hpet_mmio_read
  devicemodel/hw/platform/hpet.c
Labels: master

#7705 doc: Update Configuration and Development Overview
  doc/getting-started/overview_dev.rst
Labels: area: documentation, master

#7722 ACRN: DM: Fix the MSI mask and pending bit bugs
  devicemodel/hw/pci/core.c
  devicemodel/include/pci_core.h
Labels: release_3.0

#7723 misc: modify the HV start address
  misc/config_tools/static_allocators/hv_ram.py
Labels: release_3.0

#7724 doc: update VM types description to use DX-friendly title
  misc/config_tools/schema/config.xsd
Labels: release_3.0

#7725 Merge RDT refine patch to 3.0
  misc/config_tools/static_allocators/clos.py
Labels: release_3.0

#7728 config_tools: add default value to 'vm_type'
  misc/config_tools/schema/config.xsd
Labels: release_3.0

#7727 config_tools: refine issues in the upgrader
  misc/config_tools/scenario_config/upgrader.py
Labels: release_3.0

#7736 [release_2.5] hv: reserve smbios table region in ve820
  hypervisor/quirks/smbios.c
Labels: release_2.5

#7740 Revert "config_tools: add SyntacticValidationStage before save scenario"
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/configurator/pyodide/validateScenario.py
Labels: release_3.0

#7734 Improve description and title for vUART connection end point VM name
  misc/config_tools/schema/VMtypes.xsd
Labels: release_3.0

#7742 config_tools: add * in cpu_affinity widget first line of pcpu config
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
Labels: release_3.0

#7744 doc: update release_3.0 docs for draft publishing
  CONTRIBUTING.rst
  doc/.known-issues/doc/pdf.conf
  doc/Makefile
  doc/conf.py
  doc/develop.rst
  doc/getting-started/overview_dev.rst
  doc/reference/config-options-launch.rst
  doc/reference/config-options.rst
  doc/reference/images/Advanced.png
  doc/reference/images/Basic.png
  doc/reference/images/Hypervisor.png
  doc/reference/images/Not-available.png
  doc/reference/images/Post-launched-VM.png
  doc/reference/images/Pre-launched-VM.png
  doc/reference/images/Service-VM.png
  doc/scripts/configdoc.xsl
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/acrn_configurator_tool.rst
  doc/tutorials/images/config-file.png
  doc/tutorials/images/configurator-addvm.png
  doc/tutorials/images/configurator-backintro.png
  doc/tutorials/images/configurator-board01.png
  doc/tutorials/images/configurator-board02.png
  doc/tutorials/images/configurator-board03.png
  doc/tutorials/images/configurator-configscreen.png
  doc/tutorials/images/configurator-deletevm.png
  doc/tutorials/images/configurator-exconfig.png
  doc/tutorials/images/configurator-expand.png
  doc/tutorials/images/configurator-exscenario.png
  doc/tutorials/images/configurator-intro.png
  doc/tutorials/images/configurator-newconfig.png
  doc/tutorials/images/configurator-newscenario01.png
  doc/tutorials/images/configurator-newscenario02.png
  doc/tutorials/images/configurator-rederror.png
  doc/tutorials/images/configurator-save.png
  doc/tutorials/images/configurator-selecthypervisor.png
  doc/tutorials/images/tooltip.png
  doc/tutorials/nvmx_virtualization.rst
Labels: release_3.0

#7743 misc: move the RDT interface to common libary
  misc/config_tools/library/rdt.py
  misc/config_tools/scenario_config/elementpath_overlay.py
  misc/config_tools/schema/checks/rdt_support.xsd
  misc/config_tools/schema/datachecks.xsd
  misc/config_tools/static_allocators/clos.py
Labels: release_3.0

#7746 configurator: Remove duplicate vCPU assignment error message
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: release_3.0

#7754 misc: modify the vUART index order and irq
  misc/config_tools/static_allocators/intx.py
  misc/config_tools/static_allocators/s5_vuart.py
Labels: release_3.0

#7720 misc: fix the secure coding style violations
  devicemodel/hw/pci/virtio/virtio_net.c
  devicemodel/hw/platform/tpm/tpm.c
Labels: release_3.0

#7750 dm: vdisplay: fix comment typos.
  devicemodel/hw/vdisplay_sdl.c
Labels: master

#7739 doc: add doc for required systemd services
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7758 config_tools: fix the issue that fail to import scenario
  misc/config_tools/configurator/pyodide/validateScenario.py
Labels: release_3.0

#7751 Fix SDL init error message
  devicemodel/hw/vdisplay_sdl.c
Labels: release_3.0

#7763 ACRN: DM: Fix the MSI mask and unmask bugs.
  devicemodel/hw/pci/core.c
  devicemodel/include/pci_core.h
Labels: master

#7764 misc: fix the secure coding style violations of tpm
  devicemodel/hw/mmio/core.c
  devicemodel/hw/platform/tpm/tpm.c
  devicemodel/include/mmio_dev.h
Labels: release_3.0

#7767 config_tools: remove VMX and VT-d invalid BIOS check in acrn-board-inspector
  debian/acrn-board-inspector/acrn-board-inspector
Labels: release_3.0

#7768 config_tools: refine vm_type in upgrader
  misc/config_tools/scenario_config/upgrader.py
Labels: release_3.0

#7733 doc: Update Intro to ACRN Configuration
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/upgrading_configuration.rst
Labels: area: documentation, master

#7771 config_tools: fix the issue Service VM type is updated by UI automatically
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/scenario_config/jsonschema/converter.py
  misc/config_tools/schema/VMtypes.xsd
Labels: release_3.0

#7773 config_tools: clean up RDT-related assertions
  misc/config_tools/schema/checks/rdt_support.xsd
Labels: release_3.0

#7774 config_tools: add error icon for hypervisor tab
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/TabBox.vue
Labels: release_3.0

#7777 config_tools: hide syntactic error message from configurator ui
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: release_3.0

#7775 doc: Update Board Inspector
  doc/tutorials/board_inspector_tool.rst
Labels: area: documentation, master

#7769 doc: Update GSG
  doc/getting-started/getting-started.rst
  doc/getting-started/images/configurator-board01.png
  doc/getting-started/images/configurator-buildtype.png
  doc/getting-started/images/configurator-newconfig.png
  doc/getting-started/images/configurator-newscenario01.png
  doc/getting-started/images/configurator-newscenario02.png
  doc/getting-started/images/configurator-postvm.png
  doc/getting-started/images/configurator-servicevm.png
  doc/tutorials/acrn_configurator_tool.rst
Labels: area: documentation, master

#7782 doc: update GSG to use sudo with systemctl command
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7784 doc: update draft 3.0 published docs to include changes on master
  doc/getting-started/getting-started.rst
  doc/getting-started/images/configurator-board01.png
  doc/getting-started/images/configurator-buildtype.png
  doc/getting-started/images/configurator-newconfig.png
  doc/getting-started/images/configurator-newscenario01.png
  doc/getting-started/images/configurator-newscenario02.png
  doc/getting-started/images/configurator-postvm.png
  doc/getting-started/images/configurator-servicevm.png
  doc/tutorials/acrn_configuration_tool.rst
  doc/tutorials/acrn_configurator_tool.rst
  doc/tutorials/board_inspector_tool.rst
  doc/tutorials/upgrading_configuration.rst
Labels: area: documentation, release_3.0

#7781 doc: Update Configurator
  doc/tutorials/acrn_configurator_tool.rst
  doc/tutorials/images/configurator-erroricon.png
Labels: area: documentation, master

#7788 doc: Update GSG HW pic and typo
  doc/getting-started/getting-started.rst
  doc/getting-started/images/configurator-postvm.png
  doc/getting-started/images/gsg_vecow.png
Labels: area: documentation, master

#7789 doc: Update Configurator doc
  doc/tutorials/acrn_configurator_tool.rst
Labels: area: documentation, master

#7786 misc: set the communication vUART default type to PCI
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
  misc/config_tools/schema/VMtypes.xsd
Labels: release_3.0

#7792 misc: add assert to check the missing of CLOS MASK
  misc/config_tools/schema/checks/rdt_support.xsd
Labels: release_3.0

#7800 config-tools: fix assertions against scenario XML
  misc/config_tools/schema/checks/cpu_assignment.xsd
  misc/config_tools/schema/checks/rdt_support.xsd
Labels: release_3.0

#7791 ACRN:DM: Correct vhost_ext_features network bit
  devicemodel/hw/pci/virtio/virtio_net.c
Labels: release_3.0

#7799 misc: fix PCI vUART issue
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/static_allocators/gpa.py
  misc/config_tools/xforms/lib.xsl
  misc/config_tools/xforms/pci_dev.c.xsl
  misc/config_tools/xforms/vm_configurations.c.xsl
Labels: release_3.0

#7805 config_toos: add default value for some elements
  misc/config_tools/data/generic_board/shared.xml
  misc/config_tools/data/generic_board/shared_launch_2user_vm.xml
  misc/config_tools/data/generic_board/shared_launch_6user_vm.xml
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
Labels: release_3.0

#7804 ACRN:DM: Free virtio_vsock struct resource in deinit function
  devicemodel/hw/pci/virtio/vhost_vsock.c
Labels: release_3.0

#7810 acrn_config: update text when loading the Configurator
  misc/config_tools/configurator/packages/configurator/index.html
Labels: release_3.0

#7813 config_tools: remove minOccurs from items that have default values
  misc/config_tools/schema/VMtypes.xsd
Labels: release_3.0

#7811 config_tools: add default value for virtio console
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue
Labels: release_3.0

#7812 config_tools: fix configForm character display issue
  misc/config_tools/configurator/packages/configurator/src/assets/css/index.scss
Labels: release_3.0

#7814 Release_3.0:Update Debian control file to add missing dependencies
  debian/control
Labels: release_3.0

#7808 doc: update supported hardware doc with TGL Vecow system
  doc/reference/hardware.rst
Labels: area: documentation, master

#7817 config_tools: mark os_config item as required in scenario XML
  misc/config_tools/schema/config.xsd
Labels: release_3.0

#7821 doc: Remove OpenStack tutorial
  doc/develop.rst
  doc/tutorials/setup_openstack_libvirt.rst
Labels: area: documentation, master

#7815 doc: Update GSG/Hybrid HW pic and pictures
  doc/getting-started/getting-started.rst
  doc/getting-started/images/configurator-postvm.png
  doc/tutorials/using_hybrid_mode_on_nuc.rst
Labels: area: documentation, master

#7802 doc: Add launch script document
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, master

#7826 doc: update some dm parameter
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, master

#7822 doc: Update IVSHMEM tutorial
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/images/configurator-ivshmem01.png
  doc/tutorials/images/configurator-ivshmem02.png
  doc/tutorials/inter-vm_communication.rst
Labels: area: documentation, master

#7833 doc: Update GSG
  doc/getting-started/getting-started.rst
  doc/getting-started/images/configurator-buildtype.png
  doc/getting-started/images/configurator-postvm.png
  doc/getting-started/images/configurator-servicevm.png
  doc/getting-started/images/gsg_nuc.png
Labels: area: documentation, master

#7832 doc: rearrange "What is ACRN" for better presentation
  doc/introduction/index.rst
Labels: area: documentation, master

#7830 doc: Update GVT-d tutorial
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/images/configurator-gvtd01.png
  doc/tutorials/images/configurator-gvtd02.png
Labels: area: documentation, master

#7841 doc: Update Configurator UI doc
  doc/tutorials/acrn_configurator_tool.rst
Labels: area: documentation, master

#7828 doc: update release notes for v3.0
  doc/release_notes/release_notes_3.0.rst
Labels: area: documentation, master

#7842 doc: update passthrough image in intro
  doc/introduction/images/device-passthrough.png
Labels: area: documentation, master

#7823 doc: User VM guide
  doc/develop.rst
  doc/introduction/index.rst
  doc/tutorials/images/ubuntu-uservm-0.png
  doc/tutorials/images/ubuntu-uservm-1.png
  doc/tutorials/images/ubuntu-uservm-2.png
  doc/tutorials/images/ubuntu-uservm-3.png
  doc/tutorials/images/ubuntu-uservm-4.png
  doc/tutorials/images/ubuntu-uservm-5.png
  doc/tutorials/images/ubuntu_uservm_01.png
  doc/tutorials/images/ubuntu_uservm_02.png
  doc/tutorials/images/ubuntu_uservm_03.png
  doc/tutorials/images/ubuntu_uservm_begin_install.png
  doc/tutorials/images/ubuntu_uservm_customize.png
  doc/tutorials/images/ubuntu_uservm_storage.png
  doc/tutorials/images/ubuntu_uservm_virtioblock.png
  doc/tutorials/images/vm-guide-create-new-scenario.png
  doc/tutorials/images/vm-guide-image-virtio-block.png
  doc/tutorials/images/vm-guide-set-vm-basic-parameters.png
  doc/tutorials/user_vm_guide.rst
  doc/tutorials/using_ubuntu_as_user_vm.rst
  doc/tutorials/using_vxworks_as_user_vm.rst
  doc/tutorials/using_windows_as_user_vm.rst
  doc/tutorials/using_xenomai_as_user_vm.rst
  doc/tutorials/using_zephyr_as_user_vm.rst
Labels: area: documentation, master

#7843 doc: Update RDT/vCAT tutorial
  doc/develop.rst
  doc/developer-guides/hld/hv-vcat.rst
  doc/tutorials/images/configurator-cache01.png
  doc/tutorials/images/configurator-cache02.png
  doc/tutorials/images/configurator-cache03.png
  doc/tutorials/images/configurator-cache04.png
  doc/tutorials/images/configurator-cache05.png
  doc/tutorials/images/configurator-rt01.png
  doc/tutorials/images/configurator-vcat01.png
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/vcat_configuration.rst
Labels: area: documentation, master

#7795 Doc: ACRN on Qemu Update
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation, master

#7845 doc: update GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7846 doc: update release notes for v3.0
  doc/release_notes/release_notes_3.0.rst
Labels: area: documentation, master

#7848 doc: update acrn-kernel repo tag
  doc/getting-started/getting-started.rst
  doc/tutorials/acrn_on_qemu.rst
Labels: area: documentation, master

#7849 doc: more edits for final 3.0 release notes
  doc/release_notes/release_notes_3.0.rst
Labels: area: documentation, master

#7851 doc: add 3.0 release docs to menu choice
  doc/conf.py
Labels: area: documentation, master

#7852 doc: add 3.0 to /latest header note
  doc/_templates/layout.html
Labels: area: documentation, master

#7853 doc: update release notes 3.0 year
  doc/release_notes/release_notes_3.0.rst
Labels: area: documentation, master

#7854 doc: add link to configurator debian package in tag assets
  doc/release_notes/release_notes_3.0.rst
Labels: area: documentation, master

#7855 doc: update release notes wtih configurator debian package from tag …
  doc/release_notes/release_notes_3.0.rst
Labels: area: documentation, release_3.0

#7859 doc: fix gsg instructions for building the acrn-kernel
  doc/getting-started/getting-started.rst
Labels: area: documentation, release_3.0

#7858 doc: fix gsg instructions for building the acrn-kernel
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7857 doc: update GSG picture
  doc/getting-started/getting-started.rst
  doc/getting-started/images/configurator-postvm.png
Labels: area: documentation, release_3.0

#7856 doc: update GSG picture
  doc/getting-started/getting-started.rst
  doc/getting-started/images/configurator-postvm.png
Labels: area: documentation, master

#7861 dm: virtio-console: change STDIO BE attribute
  devicemodel/hw/pci/virtio/virtio_console.c
Labels: master
