Repository projectacrn/acrn-hypervisor, pull requests merged in 2022-01, with the labels that each got.

#7005 Misc: acrnd: fix acrnd start failure
  misc/services/acrn_manager/acrnd.service
Labels: CI: Tracked On Pass

#7004 deb-pkg: rename acrn-sos to acrn-service-vm
  misc/packaging/100_ACRN
Labels: CI: Tracked On Pass

#6995 hv: fix clang analyzer deadcode
  hypervisor/arch/x86/guest/instr_emul.c
  hypervisor/arch/x86/guest/ve820.c
Labels: CI: Tracked On Pass

#7009 board_inspector/pcieparser: check config space size of PCIe devices
  misc/config_tools/board_inspector/pcieparser/__init__.py
Labels: CI: Tracked On Pass

#6973 doc: ACRN Inter-VM Communication
  doc/develop.rst
  doc/tutorials/images/Inter-VM_data_transfer_state_machine.png
  doc/tutorials/images/Inter-VM_handshake_communication_two_machine.png
  doc/tutorials/images/Inter-VM_network_communication_overview.png
  doc/tutorials/images/Inter-VM_shared_memory_communication_overview.png
  doc/tutorials/images/Inter-VM_vUART_communication_overview.png
  doc/tutorials/inter-vm_communication.rst
Labels: area: documentation

#7021 doc: remove obsolete TARGET_DIR Makefile parameter from tutorial
  doc/tutorials/enable_ivshmem.rst
Labels: area: documentation

#7008 hv: fix violations of coding guideline C-FN-16
  hypervisor/arch/x86/guest/vcpu.c
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/include/arch/x86/asm/cpu.h
Labels: CI: Tracked On Pass

#7012 doc: editorial cleanup in enable s5 guide
  doc/tutorials/enable_s5.rst
  doc/tutorials/images/system_shutdown.png
Labels: area: documentation

#7023 [for v2.7]deb-pkg: Delete the folder name of acrn-hypervisor in the configuration file
  .deb.conf
  misc/packaging/gen_acrn_deb.py
Labels: CI: Tracked On Pass, release_2.7

#7007 doc: remove some dynamic parameters from acrn-dm usage
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hld-overview.rst
  doc/developer-guides/hld/hostbridge-virt-hld.rst
  doc/developer-guides/hld/virtio-blk.rst
  doc/reference/config-options-launch.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/launch_uos.sh
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation

#7039 config_tools: merge board_private.rootfs/bootargs to os_config.bootargs
  misc/config_tools/data/cfl-k700-i7/hybrid.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/shared.xml
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/shared.xml
  misc/config_tools/data/nuc11tnbi5/hybrid.xml
  misc/config_tools/data/nuc11tnbi5/shared.xml
  misc/config_tools/data/qemu/shared.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml
  misc/config_tools/data/whl-ipc-i5/sdc.xml
  misc/config_tools/data/whl-ipc-i5/shared.xml
  misc/config_tools/library/scenario_cfg_lib.py
  misc/config_tools/scenario_config/scenario_cfg_gen.py
  misc/config_tools/scenario_config/scenario_item.py
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/misc_cfg.h.xsl
Labels: depend on 1 source

#7044 hv: improve vmexit array size to avoid overflow
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/debug/shell.c
  hypervisor/include/arch/x86/asm/guest/vcpu.h
  hypervisor/include/arch/x86/asm/guest/vmexit.h
  hypervisor/include/arch/x86/asm/per_cpu.h
Labels: release_2.5

#7042 deb-pkg: Delete the pre-condition checks in install the Debian package
  misc/packaging/acrn-hypervisor.preinst
  misc/packaging/gen_acrn_deb.py
  misc/packaging/install_uSoS.py
Labels: master

#7047 doc: Update debug tools path
  doc/tutorials/debug.rst
Labels: area: documentation, master

#7049 dm: remove dynamic param '-A'
  devicemodel/core/main.c
Labels: master

#7048 dm: fix the bug that infinite calls to vq_getchain()
  devicemodel/hw/pci/virtio/virtio_console.c
  devicemodel/hw/pci/virtio/virtio_gpio.c
  devicemodel/hw/pci/virtio/virtio_rnd.c
  devicemodel/include/virtio.h
Labels: master

#7034 hv: fix bug when set MSR_IA32_COPY_PLATFORM_TO_LOCAL before setting M…
  hypervisor/arch/x86/guest/vmsr.c
Labels: pending approve

#7053 doc: Update images
  doc/getting-started/getting-started.rst
  doc/getting-started/images/ACRN_terms-1-0.75x.png
  doc/getting-started/images/acrn_terms.png
  doc/getting-started/images/gsg_host_target.png
  doc/getting-started/images/gsg_overview_image_sources.pptx
  doc/getting-started/images/gsg_scenario-1-0.75x.png
  doc/getting-started/images/gsg_scenario.png
  doc/getting-started/images/icon_host.png
  doc/getting-started/images/icon_light.png
  doc/getting-started/images/icon_target.png
  doc/getting-started/images/overview_flow-1-0.6x.png
  doc/getting-started/images/overview_flow.png
  doc/getting-started/images/overview_host_target.png
  doc/getting-started/overview_dev.rst
  doc/introduction/images/ACRN-Hybrid.png
  doc/introduction/images/ACRN-V2-high-level-arch-1-0.75x.png
  doc/introduction/images/ACRN-V2-high-level-arch.png
  doc/introduction/images/ACRN-hybrid-rt-example-1-0.75x.png
  doc/introduction/images/ACRN-hybrid-rt-example.png
  doc/introduction/images/ACRN-industry-example-1-0.75x.png
  doc/introduction/images/ACRN-industry-example.png
  doc/introduction/images/ACRN-partitioned-example-1-0.75x.png
  doc/introduction/images/ACRN-partitioned-example.png
  doc/introduction/index.rst
  doc/release_notes/release_notes_2.0.rst
  doc/tutorials/acrn_configuration_tool.rst
Labels: area: documentation, master

#7050 doc: remove dm dynamic param '-A'
  doc/developer-guides/hld/hld-devicemodel.rst
  doc/developer-guides/hld/hostbridge-virt-hld.rst
  doc/developer-guides/hld/hv-dev-passthrough.rst
  doc/getting-started/getting-started.rst
  doc/tutorials/acrn_on_qemu.rst
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/launch_uos.sh
  doc/tutorials/using_windows_as_user_vm.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, master

#7016 deb-pkg: Delete the folder name of acrn-hypervisor in the configurati…
  .deb.conf
  misc/packaging/gen_acrn_deb.py
Labels: pending approve, CI: Tracked On Pass

#7055 config_tools: add a script that focuses on XML validation
  hypervisor/scripts/genconf.sh
  misc/config_tools/scenario_config/validator.py
Labels: master

#7060 hv:refine the min address logic of high memory
  hypervisor/arch/x86/mmu.c
Labels: master

#7066 doc: add community support and resources to introduction
  README.rst
  doc/introduction/index.rst
Labels: area: documentation, master

#7020 config_tool: Add tgl-vecow-spc-7100-Corei7 board/scenario/launch xml files
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/tgl-vecow-spc-7100-Corei7.xml
Labels: pending approve, CI: Tracked On Pass, master

#7068 config-tools: update qemu board xml
  misc/config_tools/data/qemu/qemu.xml
Labels: master

#7074 dm: fix: TSN in multi-hostbridge could crash
  devicemodel/core/main.c
  devicemodel/hw/pci/pci_util.c
  devicemodel/hw/pci/ptm.c
  devicemodel/include/pci_util.h
Labels: master

#7065 dm:add UID parameter for acpidev_pt
  devicemodel/hw/platform/tpm/tpm.c
Labels: pending approve, master

#7078 config-tool: find pci hole based on all pci hostbridge
  misc/config_tools/static_allocators/gpa.py
Labels: master
