Repository projectacrn/acrn-hypervisor, pull requests merged in 2022-04, with the labels that each got.

#7236 configurator: update configurator dependencies to latest version
  misc/config_tools/configurator/yarn.lock
Labels: master

#7225 config_tools: Update Configurator UI XSD
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: master

#7243 doc: fix exception error in last_modified processing
  doc/extensions/last_updated.py
Labels: master

#7244 doc: fix Makefile to report errors if exception raised
  doc/Makefile
Labels: master

#7251 doc: handle last updated footer for new document
  doc/extensions/last_updated.py
Labels: master

#7253 doc: properly handle last_updated info for new docs
  doc/extensions/last_updated.py
Labels: master

#7245 config_tools: fix the issue that fail to read XSD file
  misc/config_tools/board_inspector/board_inspector.py
Labels: master

#7247 configurator: fix can't load scenario without pci_devs issue
  misc/config_tools/configurator/src/index.css
  misc/config_tools/configurator/src/lib/acrn.jsx
Labels: master

#7263 config tool: service vm parameter display
  misc/config_tools/schema/config.xsd
Labels: master

#7264 mise: life_mngr: fix some minor bugs
  misc/services/life_mngr/life_mngr_win.c
  misc/services/life_mngr/uart.c
  misc/services/life_mngr/uart.h
Labels: master

#7260 doc: fix hardware.rst line endings
  doc/reference/hardware.rst
Labels: master

#7266 ACRN:DM: Add the pci msi per-vector masking capable
  devicemodel/hw/pci/core.c
  devicemodel/include/pcireg.h
Labels: master

#7268 config tool: Fix service vm cpu affinity issue
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/static_allocators/cpu_affinity.py
Labels: master

#7269 config tool: hide PTM in schema
  misc/config_tools/schema/config.xsd
Labels: master

#7278 config tool: update virtio block setting
  misc/config_tools/schema/config.xsd
Labels: master

#7274 config tool/doc:update SCHED_IORR in schema
  doc/developer-guides/hld/hv-cpu-virt.rst
  doc/tutorials/cpu_sharing.rst
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/types.xsd
Labels: master

#7273 deb-pkg: add OVMF_debug.fd in acrn deb
  misc/packaging/deb.json
Labels: master

#7280 config tool: generate HV land ivshmem parameter
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: master

#7288 config tool: update cpu affinity check algorithm
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: master

#7300 remove repetitive erasing for guest memory
  devicemodel/core/hugetlb.c
  devicemodel/core/vmmapi.c
Labels: master

#7293 packaging: error while loading shared libraries: libSDL2-2.0.so.0
  misc/packaging/gen_acrn_deb.py
Labels: master

#7299 config tool: update schema
  misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/partitioned.xml
  misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml
  misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/partitioned.xml
  misc/config_tools/data/generic_board/shared_launch_6user_vm.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml
  misc/config_tools/data/nuc11tnbi5/partitioned.xml
  misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml
  misc/config_tools/data/qemu/shared.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml
  misc/config_tools/data/whl-ipc-i5/partitioned.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml
  misc/config_tools/hv_config/hv_item.py
  misc/config_tools/scenario_config/scenario_cfg_gen.py
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: master

#7240 doc: virtio-gpu parameters of acrn-dm
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, master

#7285 doc: Fix links
  doc/developer-guides/asm_coding_guidelines.rst
  doc/developer-guides/hld/hld-splitlock.rst
  doc/developer-guides/hld/hv-rdt.rst
  doc/developer-guides/l1tf.rst
  doc/tutorials/rdt_configuration.rst
  doc/tutorials/rtvm_performance_tips.rst
Labels: area: documentation, master

#7284 doc: Capitalize Board Inspector and ACRN Configurator
  doc/developer-guides/doc_guidelines.rst
  doc/developer-guides/hld/hld-splitlock.rst
  doc/glossary.rst
  doc/introduction/index.rst
  doc/reference/hv-make-options.rst
  doc/tutorials/cpu_sharing.rst
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, master

#7283 doc: Add note to GSG about optional upgrade
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7306 doc: fix table CSS font size changing with lists
  doc/static/acrn-custom.css
Labels: area: documentation, master

#7308 config tool:add support for bootargs missing
  misc/config_tools/acpi_gen/asl_gen.py
Labels: master

#7276 hv: ptdev: address vector scalability problem by interrupt posting
  hypervisor/common/ptdev.c
Labels: pending approve, master

#7320 config-tools: update nuc11/whl/generic_board board files
  misc/config_tools/data/generic_board/generic_board.xml
  misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml
  misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
Labels: master

#7319 packaging: error while loading shared libraries: libSDL2-2.0.so.0
  misc/packaging/gen_acrn_deb.py
Labels: master

#7323 deb-pkg: add OVMF_debug.fd in .deb.conf
  .deb.conf
Labels: master

#7321 hv: remove an unnecessary code line
  hypervisor/boot/guest/elf_loader.c
Labels: master

#7324 hv: fix cpuid 0x2 mismatch when launch RTVM use atom core
  hypervisor/arch/x86/guest/vcpuid.c
Labels: master

#7328 hv: remove pgentry_present field in struct pgtable
  hypervisor/arch/x86/guest/ept.c
  hypervisor/arch/x86/mmu.c
  hypervisor/arch/x86/pagetable.c
  hypervisor/include/arch/x86/asm/pgtable.h
Labels: master

#7326 doc: Fix virtio-blk.html/hv-rdt.html statement error
  doc/developer-guides/hld/hv-rdt.rst
  doc/developer-guides/hld/virtio-blk.rst
Labels: area: documentation, master

#7312 doc: add a tutorial on how to upgrade configuration files
  doc/develop.rst
  doc/tutorials/upgrading_configuration.rst
Labels: area: documentation, master

#7332 doc: update schema type documentation
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/schema/types.xsd
Labels: master

#7329 hv: fix core type error when launch RTVM use atom core
  hypervisor/arch/x86/guest/vcpuid.c
Labels: master

#7334 board_inspector: parse cpu IDs in decimal rather than hexadecimal
  misc/config_tools/board_inspector/extractors/20-cache.py
Labels: master

#7339 config_tools: add virtio gpu
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/schema/config.xsd
Labels: master

#7341 config-tools: update xmls due to cpu_id parser changed
  misc/config_tools/data/generic_board/generic_board.xml
  misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
  misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
Labels: master

#7336 config tool: Fix parameters in Configurator UI
  misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml
  misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
  misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml
  misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/shared_launch_6user_vm.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml
  misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml
  misc/config_tools/data/qemu/shared.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
  misc/config_tools/data/whl-ipc-i5/hybrid.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/config.xsd
Labels: master

#7295 config tool:update vbootloader xsd file
  misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml
  misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml
  misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml
  misc/config_tools/data/generic_board/shared_launch_6user_vm.xml
  misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml
  misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml
  misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
  misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml
  misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/schema/config.xsd
Labels: master

#7309 dm: optimize the parameter compatibility
  devicemodel/core/main.c
Labels: master

#7347 config_tools: list dependencies on Python libraries in requirements.txt
  misc/config_tools/requirements.txt
Labels: master

#7352 config tool:Fix tap name filter error
  misc/config_tools/launch_config/launch_script_template.sh
Labels: master

#7350 configurator: bugfix for removing Service VM
  misc/config_tools/configurator/src/lib/acrn.jsx
  misc/config_tools/configurator/src/pages/Config/ConfigureSettingsForScenario/ConfigureSettingsForScenario.jsx
Labels: master

#7364 config tool: add d3hot_reset in launch script
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: master

#7362 misc: config_tools: Add Check for RTVM pCPU assignment
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: master

#7359 hv: remove obsolete declarations related to RDT
  hypervisor/arch/x86/rdt.c
  hypervisor/include/arch/x86/asm/board.h
Labels: master

#7360 board_inspector: transform non-viewable characters in brand string
  misc/config_tools/board_inspector/extractors/10-processors.py
Labels: master

#7357 config_tools: add 'configurator' to error message
  misc/packaging/gen_acrn_deb.py
Labels: master

#7369 [acrn-configuration tool] make scenario shared file error cp error
  misc/packaging/gen_acrn_deb.py
Labels: master

#7373 [acrn-deb] install_compile_package function is not consistent with gsg
  misc/packaging/install_uSoS.py
Labels: master

#7385 [acrn-configuration tool] make scenario shared file error cp error
  misc/packaging/gen_acrn_deb.py
Labels: master

#7389 misc: fix the issue of create hv node
  misc/config_tools/static_allocators/clos.py
  misc/config_tools/static_allocators/main.py
Labels: master

#7390 config_tools: do not apply distinct-values on a union of node-set
  misc/config_tools/schema/checks/vbdf_assignment.xsd
Labels: master

#7333 doc: use DX-friendly names in configuration option documentation
  doc/developer-guides/doc_guidelines.rst
  doc/glossary.rst
  doc/reference/config-options.rst
  doc/reference/images/Advanced.svg
  doc/reference/images/Basic.svg
  doc/reference/images/Hypervisor.svg
  doc/reference/images/Not-available.svg
  doc/reference/images/Post-launched-VM.svg
  doc/reference/images/Pre-launched-VM.svg
  doc/reference/images/README
  doc/reference/images/Service-VM.svg
  doc/scripts/configdoc.xsl
  doc/static/acrn-custom.css
  doc/static/acrn-custom.js
  doc/tutorials/nvmx_virtualization.rst
  doc/tutorials/vcat_configuration.rst
Labels: area: documentation, master

#7394 doc: tweak option config doc processing for missing attributes
  doc/scripts/configdoc.xsl
Labels: area: documentation, master

#7388 dm: acpi: refine CPU Definition Blocks name
  devicemodel/hw/platform/acpi/acpi_pm.c
Labels: master

#7396 config-tools: remove 'nomwait' from board_inspector's requirement
  misc/config_tools/board_inspector/README
  misc/config_tools/board_inspector/legacy/acpi.py
  misc/packaging/acrn-board-inspector.postinst
Labels: doc: needed, master
