Repository projectacrn/acrn-hypervisor, pull requests merged in 2022-07, with the labels that each got.

#7863 doc: remove images no longer referenced
  doc/reference/images/Advanced.svg
  doc/reference/images/Basic.svg
  doc/reference/images/Hypervisor.svg
  doc/reference/images/Not-available.svg
  doc/reference/images/Post-launched-VM.svg
  doc/reference/images/Pre-launched-VM.svg
  doc/reference/images/Service-VM.svg
  doc/tutorials/images/OpenStack-01-login.png
  doc/tutorials/images/OpenStack-02-topology.png
  doc/tutorials/images/OpenStack-03-create-router.png
  doc/tutorials/images/OpenStack-03a-create-router.png
  doc/tutorials/images/OpenStack-03b-created-router.png
  doc/tutorials/images/OpenStack-04a-add-interface.png
  doc/tutorials/images/OpenStack-04b-add-interface.png
  doc/tutorials/images/OpenStack-04c-add-interface.png
  doc/tutorials/images/OpenStack-05-topology.png
  doc/tutorials/images/OpenStack-06-create-image.png
  doc/tutorials/images/OpenStack-06a-create-image-browse.png
  doc/tutorials/images/OpenStack-06b-create-image-select.png
  doc/tutorials/images/OpenStack-06e-create-image.png
  doc/tutorials/images/OpenStack-07a-create-flavor.png
  doc/tutorials/images/OpenStack-07b-flavor-created.png
  doc/tutorials/images/OpenStack-08-security-group.png
  doc/tutorials/images/OpenStack-08a-create-security-group.png
  doc/tutorials/images/OpenStack-08b-add-rule.png
  doc/tutorials/images/OpenStack-08c-add-SSH-rule.png
  doc/tutorials/images/OpenStack-08d-add-All-ICMP-rule.png
  doc/tutorials/images/OpenStack-09a-create-key-pair.png
  doc/tutorials/images/OpenStack-09c-key-pair-private-key.png
  doc/tutorials/images/OpenStack-10a-launch-instance-name.png
  doc/tutorials/images/OpenStack-10b-no-new-vol-select-allocated.png
  doc/tutorials/images/OpenStack-10c-select-flavor.png
  doc/tutorials/images/OpenStack-10d-flavor-selected.png
  doc/tutorials/images/OpenStack-10d-only-acrn-security-group.png
  doc/tutorials/images/OpenStack-10e-select-network.png
  doc/tutorials/images/OpenStack-10g-show-keypair-launch.png
  doc/tutorials/images/OpenStack-11-wait-for-running-create-snapshot.png
  doc/tutorials/images/OpenStack-11a-manage-floating-ip.png
  doc/tutorials/images/OpenStack-11b-allocate-floating-ip.png
  doc/tutorials/images/OpenStack-11c-allocate-floating-ip-success-associate.png
  doc/tutorials/images/OpenStack-12b-running-topology-instance.png
  doc/tutorials/images/OpenStack-12d-compute-hypervisor.png
  doc/tutorials/images/configurator-rederror.png
  doc/tutorials/images/nvmx_1.png
  doc/tutorials/images/nvmx_arch_1.png
  doc/tutorials/images/ubuntu-uservm-0.png
  doc/tutorials/images/ubuntu-uservm-1.png
  doc/tutorials/images/ubuntu-uservm-2.png
  doc/tutorials/images/ubuntu-uservm-3.png
  doc/tutorials/images/ubuntu-uservm-4.png
  doc/tutorials/images/ubuntu-uservm-5.png
  doc/tutorials/images/vuart-config-1.png
  doc/tutorials/images/vuart-config-2.png
  doc/tutorials/images/vuart-config-post-launch.png
Labels: area: documentation, master

#7837 Remove "All Rights Reserved" string from license header
  misc/config_tools/board_inspector/extractors/95-usb.py
Labels: master

#7806 Makefile: remove old samples (Apollo Lake)
  devicemodel/Makefile
  misc/config_tools/data/sample_launch_scripts/apl-mrb/acrn_guest.service
  misc/config_tools/data/sample_launch_scripts/apl-mrb/launch_uos.args
  misc/config_tools/data/sample_launch_scripts/apl-mrb/launch_uos.sh
  misc/config_tools/data/sample_launch_scripts/apl-mrb/runC.json
  misc/config_tools/data/sample_launch_scripts/apl-up2/launch_uos.sh
Labels: master

#7873 [Release_3.0]update debian control file typo issue is a missing ,
  debian/control
Labels: release_3.0

#7869 hv: compile out unused function if CONFIG_MULTIBOOT2 is disabled
  hypervisor/boot/guest/bzimage_loader.c
Labels: master

#7879 config_tools: update loading msr driver logic
  misc/config_tools/board_inspector/legacy/board_parser.py
Labels: master

#7874 doc: elementpath version must be 2.5.0 in the GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7866 misc: refine the assert of duplicate IO port
  misc/config_tools/schema/checks/vuart_config.xsd
Labels: master

#7865 config_tools: hide required checkbox's label
  misc/config_tools/configurator/packages/vue-json-schema-form/vue3/vue3-core/src/components/Widget.js
Labels: master

#7875 config-tools: refine memory allocation for pre-launch vm
  misc/config_tools/static_allocators/memory_allocator.py
Labels: master

#7891 config_tools: resolve incompatibility with elementpath 2.5.3
  misc/config_tools/scenario_config/elementpath_overlay.py
Labels: master

#7885 config_tool: Move "BIOS Revision" line in Configurator UI
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
Labels: master

#7894 config-tools: hide the 'update-pciids: download failed' message
  misc/config_tools/board_inspector/board_inspector.py
Labels: master

#7890 hv: tsc: calibrate TSC by HPET
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/tsc.c
  hypervisor/boot/acpi_base.c
  hypervisor/boot/include/acpi.h
  hypervisor/include/arch/x86/asm/tsc.h
Labels: master

#7895 hv: tlfs: add tlfs TSC freq MSR support for WaaG
  hypervisor/arch/x86/guest/hyperv.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/asm/guest/hyperv.h
Labels: master

#7877 config_tools: update gpu passthru doc
  doc/tutorials/gpu-passthru.rst
  doc/tutorials/images/kernel_cmd_line.png
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation, master

#7878 [Release_3.0]modify elementpath version ==2.5.0
  debian/control
  doc/getting-started/getting-started.rst
Labels: release_3.0

#7896 doc: update vUART tutorials
  doc/tutorials/images/configurator-vuartconn01.png
  doc/tutorials/vuart_configuration.rst
Labels: area: documentation, master

#7807 Update Debian control file to add missing dependencies.
  debian/control
Labels: master

#7911 config_tools: left-align plus icon and add tooltips for virtio devices
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Input.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Network.vue
Labels: master

#7912 config-tools: fix board inspector crashed error
  misc/config_tools/board_inspector/extractors/40-acpi-tables.py
Labels: master

#7908 [release_3.0] hv: cve hotfix: Disable RRSBA on platform using retpoline
  hypervisor/arch/x86/cpu.c
  hypervisor/arch/x86/cpu_caps.c
  hypervisor/arch/x86/security.c
  hypervisor/include/arch/x86/asm/cpu_caps.h
  hypervisor/include/arch/x86/asm/cpufeatures.h
  hypervisor/include/arch/x86/asm/msr.h
  hypervisor/include/arch/x86/asm/security.h
Labels: release_3.0

#7916 config_tools: add two spaces for error messgae.
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7919 [ACRN3.0-branch]hv: shell: add cmd to sample vmexit data per-vCPU
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/common/hv_main.c
  hypervisor/debug/shell.c
  hypervisor/debug/shell_priv.h
  hypervisor/include/arch/x86/asm/guest/vcpu.h
  hypervisor/include/arch/x86/asm/guest/vmexit.h
  hypervisor/include/debug/profiling.h
  hypervisor/release/profiling.c
Labels: release_3.0

#7918 hv: tlfs: fix the incorrect vLAPIC freq MSR
  hypervisor/arch/x86/guest/hyperv.c
Labels: master

#7905 doc: explain configurator error check and display model
  doc/tutorials/acrn_configurator_tool.rst
  doc/tutorials/images/config-out-of-range-error.png
  doc/tutorials/images/config-required-value-error.png
  doc/tutorials/images/config-tab-errors.png
  doc/tutorials/images/config-tab-errors2.png
Labels: area: documentation, master

#7928 config_tools: show warning message when users attempt to create a new scenario
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario.vue
Labels: master

#7924 config_tools: order of plus and minus icons is inconsistent
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
Labels: master

#7929 doc: update security advisory for 3.0.1 release
  doc/asa.rst
Labels: area: documentation, master

#7930 doc: add v3.0.1 release notes
  doc/release_notes/release_notes_3.0.1.rst
Labels: area: documentation, master

#7903 hv: validate inputs in vpci_mmio_cfg_access
  hypervisor/dm/vpci/vpci.c
Labels: master

#7937 misc: refine slot issue of launch script
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: master
