Repository projectacrn/acrn-hypervisor, pull requests merged in 2022-08, with the labels that each got.

#7939 config_tool: Instruction missing for L2-only users
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Labels: master

#7904 dm: fix the secure coding style violations
  devicemodel/hw/mmio/core.c
  devicemodel/hw/pci/virtio/virtio_net.c
  devicemodel/hw/platform/tpm/tpm.c
  devicemodel/include/mmio_dev.h
Labels: master

#7943 misc: add assert to check the duplicate devices
  misc/config_tools/schema/checks/pci_config.xsd
  misc/config_tools/schema/datachecks.xsd
Labels: master

#7936 SampleApplication: Add Makefile for the entire SampleApplication
  misc/sample_application/Makefile
  misc/sample_application/rtvm/Makefile
  misc/sample_application/uservm/Makefile
Labels: master

#7946 hv: sched: fix bug when reboot vm
  hypervisor/common/sched_bvt.c
  hypervisor/include/common/schedule.h
Labels: master

#7951 doc: update documents for 3.0.1 release
  doc/release_notes/release_notes_3.0.1.rst
  doc/user-guides/acrn-shell.rst
  doc/user-guides/images/vmexit-example.png
Labels: area: documentation, release_3.0

#7950 doc: update 3.0.1 release notes
  doc/release_notes/release_notes_3.0.1.rst
Labels: area: documentation, master

#7955 vUART and IVSHMEM widgets don't generate address
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7954 sample_app: Add scripts to create RT and HMI VM images
  misc/sample_application/image_builder/README.rst
  misc/sample_application/image_builder/configRTcores.sh
  misc/sample_application/image_builder/create_image.sh
  misc/sample_application/image_builder/logger.sh
  misc/sample_application/image_builder/setup_hmi_vm.sh
  misc/sample_application/image_builder/setup_rt_vm.sh
Labels: master

#7957 config_tools: fix vBDF schema pattern issue
  misc/config_tools/schema/types.xsd
Labels: master

#7966 [config_tool][patch v2] Cache widget: Instructions missing for L2-only users
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Labels: master

#7952 doc: fix Build EFI-Stub fail problem
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7967 doc: add proxy note to GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7959 doc: update rdt config tutorial
  doc/tutorials/rdt_configuration.rst
Labels: area: documentation, master

#7969 doc: update Security VM Features config option
  doc/glossary.rst
  misc/config_tools/schema/config.xsd
Labels: master

#7963 SampleApplication: Add the proxy setting for HMI
  misc/sample_application/image_builder/create_image.sh
  misc/sample_application/image_builder/setup_hmi_vm.sh
Labels: master

#7961 dm: bugfix for iothread
  devicemodel/core/iothread.c
Labels: master

#7972 doc: update GSG version for xmlschema
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7971 doc: update hypervisor shell usage
  doc/user-guides/acrn-shell.rst
Labels: area: documentation, master

#7976 misc: add assert to check the vBDF conflict
  misc/config_tools/schema/checks/vbdf_assignment.xsd
Labels: master

#7977 doc: clarify and improve GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7981 config-tools: solve hv and vm memory address conflict
  misc/config_tools/static_allocators/memory_allocator.py
Labels: master

#7979 doc: add MCE check avoidance explanation
  misc/config_tools/schema/config.xsd
Labels: master

#7985 doc: add libelf-dev dependency to GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7987 ACRN:SampleApplication: Copy RT kernel scripts
  misc/sample_application/image_builder/create_image.sh
  misc/sample_application/image_builder/setup_rt_vm.sh
Labels: master

#7990 config_tools: highlight success or fail status in save window
  misc/config_tools/configurator/packages/configurator/src-tauri/icons/Config_save_success.png
  misc/config_tools/configurator/packages/configurator/src-tauri/icons/Config_save_warningfail.png
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/SaveScenario.vue
Labels: master

#7992 doc: fix order of steps in GSG setup
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#7993 Acrn waag multi
  devicemodel/hw/vdisplay_sdl.c
Labels: master

#7995 configurator does not consider L3 CAT config when opening an exiting …
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
Labels: master

#7983 config-tools: modified requirements.txt and update GSG
  doc/getting-started/getting-started.rst
  doc/tutorials/acrn_configurator_tool.rst
  misc/config_tools/requirements.txt
Labels: area: documentation, master

#7996 doc: update rdt doc with real-time vCPU option clarification
  doc/tutorials/rdt_configuration.rst
Labels: area: documentation, master

#7994 Focus change to new VM when added
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#7998 doc: add tooltip for real-time vCPU option checkbox
  misc/config_tools/schema/VMtypes.xsd
Labels: master

#7999 doc: remove use of :term: role in tooltip
  misc/config_tools/schema/config.xsd
Labels: master

#8004 misc: add a uio init setting
  misc/sample_application/image_builder/create_image.sh
Labels: release_3.1

#8003 SampleApplication: Update the image create scripts
  misc/sample_application/image_builder/create_image.sh
  misc/sample_application/image_builder/setup_hmi_vm.sh
  misc/sample_application/image_builder/setup_rt_vm.sh
Labels: release_3.1

#8009 [config_tool] Real time vCPU checkbox is confusing to users
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
Labels: master

#8007 [config_tool] v2 show warning message when users attempt to create a …
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/OverwriteMessage.vue
Labels: master, release_3.1

#8006 [config_tool] Real time vCPU checkbox is confusing to users
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
Labels: master, release_3.1

#8002 misc: add a uio init setting
  misc/sample_application/image_builder/create_image.sh
Labels: master

#8001 SampleApplication: Update the image create scripts
  misc/sample_application/image_builder/create_image.sh
  misc/sample_application/image_builder/setup_hmi_vm.sh
  misc/sample_application/image_builder/setup_rt_vm.sh
Labels: master

#8015 doc: revert to not using requirements.txt in the GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#8014 SampleApplication: Add dhclient command
  misc/sample_application/image_builder/create_image.sh
Labels: release_3.1

#8011 SampleApplication: Update the image create scripts
  misc/sample_application/image_builder/create_image.sh
Labels: master

#8012 SampleApplication: Update the image create scripts
  misc/sample_application/image_builder/create_image.sh
Labels: release_3.1

#8013 SampleApplication: Add dhclient command
  misc/sample_application/image_builder/create_image.sh
Labels: master

#8020 doc: add sample application user guide
  doc/getting-started/images/image001.png
  doc/getting-started/images/image002.png
  doc/getting-started/images/image003.png
  doc/getting-started/images/image004.png
  doc/getting-started/images/image004a.png
  doc/getting-started/images/image005.png
  doc/getting-started/images/image006.png
  doc/getting-started/images/image007.png
  doc/getting-started/images/image008.png
  doc/getting-started/images/image009.png
  doc/getting-started/images/image010.png
  doc/getting-started/images/image011.png
  doc/getting-started/images/image012.png
  doc/getting-started/images/image013.png
  doc/getting-started/images/image014.png
  doc/getting-started/images/image015.png
  doc/getting-started/images/image016.png
  doc/getting-started/images/image017.png
  doc/getting-started/images/image018.png
  doc/getting-started/sample-app.rst
  doc/try.rst
Labels: area: documentation, master

#8021 doc: fix typos in sample app guide
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8022 doc: update sample app user guide
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8023 ACRN: Doc: Modify the SampleApplication document
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8024 doc: update sample app guide
  doc/getting-started/images/image001.png
  doc/getting-started/images/samp-image001.png
  doc/getting-started/images/samp-image002.png
  doc/getting-started/images/samp-image003.png
  doc/getting-started/images/samp-image004.png
  doc/getting-started/images/samp-image004a.png
  doc/getting-started/images/samp-image005.png
  doc/getting-started/images/samp-image006.png
  doc/getting-started/images/samp-image007.png
  doc/getting-started/images/samp-image008.png
  doc/getting-started/images/samp-image009.png
  doc/getting-started/images/samp-image010.png
  doc/getting-started/images/samp-image011.png
  doc/getting-started/images/samp-image012.png
  doc/getting-started/images/samp-image013.png
  doc/getting-started/images/samp-image014.png
  doc/getting-started/images/samp-image015.png
  doc/getting-started/images/samp-image016.png
  doc/getting-started/images/samp-image017.png
  doc/getting-started/images/samp-image018.png
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8026 Fix sample app histogram display
  misc/sample_application/uservm/histapp.py
Labels: master

#8027 Fix sample app histogram display release_3.1
  misc/sample_application/uservm/histapp.py
Labels: release_3.1

#8028 Fix sample app histogram display sample-application
  misc/sample_application/uservm/histapp.py
Labels: sample_application

#8036 doc: update sample app guide
  doc/getting-started/images/samp-image015a.png
  doc/getting-started/images/samp-image018.png
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8035 misc: add cpu details to launch script
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: release_3.1

#8034 misc: add cpu details to launch script
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: master

#8041 [config_tool] vUART widget address for pre-launched VM doesn't update
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
Labels: release_3.1

#8038 misc: add assert to check the RTVM CPU affinity
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: release_3.1

#8032 misc: refine the ACRN Configurator error message
  misc/config_tools/schema/config.xsd
Labels: release_3.1

#8037 misc: add assert to check the RTVM CPU affinity
  misc/config_tools/schema/checks/cpu_assignment.xsd
Labels: master

#8043 [Workshop] Configurator create scenario popup window disappear sometimes
  misc/config_tools/configurator/packages/configurator/src/pages/Config/NewBoard.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue
Labels: release_3.1

#8040 [config_tool] vUART widget address for pre-launched VM doesn't update
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
Labels: master

#8042 [Workshop] Configurator create scenario popup window disappear sometimes
  misc/config_tools/configurator/packages/configurator/src/pages/Config/NewBoard.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue
Labels: master

#8044 doc: update GSG to include scp instructions
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#8057 doc: update sample app doc to use sudo
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8048 SampleApplicaton: Change schroot data mapping to desktop
  misc/sample_application/image_builder/create_image.sh
  misc/sample_application/image_builder/setup_hmi_vm.sh
  misc/sample_application/uservm/histapp.py
Labels: sample_application

#8049 SampleApplicaton: Change schroot data mapping to desktop
  misc/sample_application/image_builder/create_image.sh
  misc/sample_application/image_builder/setup_hmi_vm.sh
  misc/sample_application/uservm/histapp.py
Labels: release_3.1

#8056 Update virtio-i2c driver according to virtio spec v1.2
  devicemodel/hw/pci/virtio/virtio_i2c.c
  devicemodel/include/virtio.h
Labels: master

#8060 doc: fix typo in sample app doc
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8062 doc: update GSG and sample app guide
  doc/getting-started/getting-started.rst
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8061 doc: draft of 3.1 release notes
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, master

#8065 [config_tool] Configurator creates duplicate VM name
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: release_3.1

#8064 [config_tool] Configurator creates duplicate VM name
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#8053 life_mngr: permit life_mngr in windows to assign VM name
  misc/services/life_mngr/life_mngr_win.c
Labels: release_3.1

#8017 config-tools: modified requirements.txt and update GSG
  doc/getting-started/getting-started.rst
  doc/tutorials/acrn_configurator_tool.rst
  misc/config_tools/configurator/requirements.txt
  misc/config_tools/requirements.txt
Labels: release_3.1

#8058 misc: add assert to check the total memory size of User VMs
  misc/config_tools/schema/checks/vm_memory.xsd
  misc/config_tools/schema/datachecks.xsd
Labels: release_3.1

#8016 config-tools: modified requirements.txt and update configurator build doc
  doc/tutorials/acrn_configurator_tool.rst
  misc/config_tools/configurator/requirements.txt
  misc/config_tools/requirements.txt
Labels: master

#8071 config-tools: add progress bar and timeout mechanism for board_inspe…
  misc/config_tools/board_inspector/board_inspector.py
Labels: master

#8070 config_tools/upgrader: keep cache allocation policies properly
  misc/config_tools/scenario_config/upgrader.py
Labels: release_3.1

#8072 config-tools: add progress bar and timeout mechanism for board_inspe…
  misc/config_tools/board_inspector/board_inspector.py
Labels: release_3.1

#8074 [config_tool] Imported scenarios not populating CAT widget
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#8059 misc: add assert to check the total memory size of User VMs
  misc/config_tools/schema/checks/vm_memory.xsd
  misc/config_tools/schema/datachecks.xsd
Labels: master

#8069 config_tools/upgrader: keep cache allocation policies properly
  misc/config_tools/scenario_config/upgrader.py
Labels: master

#8073 [config_tool] Imported scenarios not populating CAT widget
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: release_3.1

#8075 doc: fix typo in GSG
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#8076 doc: tweak CSS to outdent numbered step icons
  doc/static/acrn-custom.css
Labels: area: documentation, master

#8067 [release_3.1] dm: fix SSRAM region unmap failure issue
  devicemodel/hw/platform/vssram/vssram.c
Labels: release_3.1

#8077 config_tools: UC_LOCK_DETECTION_ENABLED default value
  misc/config_tools/schema/config.xsd
Labels: release_3.1

#8047 SampleApplicaton: Change schroot data mapping to desktop
  misc/sample_application/image_builder/create_image.sh
  misc/sample_application/image_builder/setup_hmi_vm.sh
  misc/sample_application/uservm/histapp.py
Labels: master

#8079 misc: update elementpath to 2.5.0
  misc/config_tools/configurator/packages/configurator/src/pyodide.js
  misc/config_tools/configurator/packages/configurator/thirdLib/library.json
Labels: release_3.1

#8082 misc: update elementpath to 2.5.0
  misc/config_tools/configurator/packages/configurator/src/pyodide.js
  misc/config_tools/configurator/packages/configurator/thirdLib/library.json
Labels: master

#8083 config_tool: modify the launchscript template
  misc/config_tools/launch_config/launch_script_template.sh
Labels: release_3.1

#8080 config_tool: modify the launchscript template
  misc/config_tools/launch_config/launch_script_template.sh
Labels: master

#8084 doc: update 3.1 release notes draft
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, master

#8086 misc: refine the vCPU sort for cpu_affinity and CAT
  misc/config_tools/library/rdt.py
  misc/config_tools/static_allocators/clos.py
  misc/config_tools/static_allocators/cpu_affinity.py
Labels: master

#8085 misc: refine the vCPU sort for cpu_affinity and CAT
  misc/config_tools/library/rdt.py
  misc/config_tools/static_allocators/clos.py
  misc/config_tools/static_allocators/cpu_affinity.py
Labels: release_3.1

#8089 config_tools: enable RDT and CDP after launch scenario
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
Labels: master

#8088 config_tools: enable RDT and CDP after launch scenario
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
Labels: release_3.1

#8090 doc: update 3.1 release notes draft
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, master

#8092 doc: add a doc helper script
  doc/scripts/changed-docs.awk
  doc/scripts/changed-docs.sh
Labels: area: documentation, master

#8093 doc: v3.1 release notes draft update
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, master

#8095 doc: clarify sample app instructions
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8096 misc: add config for P2SB
  misc/config_tools/board_config/board_c.py
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/checks/vbdf_assignment.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/lib.xsl
Labels: release_3.1

#8097 misc: add config for P2SB
  misc/config_tools/board_config/board_c.py
  misc/config_tools/schema/VMtypes.xsd
  misc/config_tools/schema/checks/vbdf_assignment.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/lib.xsl
Labels: master

#8091 config: update CPU and memory size assert messages
  misc/config_tools/schema/checks/cpu_assignment.xsd
  misc/config_tools/schema/checks/vm_memory.xsd
Labels: master
