Repository projectacrn/acrn-hypervisor, pull requests merged in 2022-11, with the labels that each got.

#8276 doc: update changes to 22.04 on sample app guide
  doc/getting-started/sample-app.rst
  misc/sample_application/image_builder/create_image.sh
  misc/sample_application/image_builder/setup_hmi_vm.sh
Labels: master

#8280 debian: create script to build acrn with debuild
  debian/debian_build.sh
  debian/rules
Labels: master

#8279 debian/rules: Dynamically generate acrn-hypervisor.install
  debian/acrn-hypervisor.install
  debian/rules
Labels: master

#8127 dm: vga: remove all the assertion.
  devicemodel/hw/pci/virtio/virtio_gpu.c
  devicemodel/hw/vga.c
Labels: master

#8285 doc: Upgrade RT kernel to 5.15 in sample app guide
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8287 doc: update doc build requirements
  doc/scripts/requirements.txt
Labels: area: documentation, master

#8289 config-tools: re-rendering the data after importing different board XML
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#8291 misc: update ASRock board XML
  misc/config_tools/data/adl-asrock/adl-asrock.xml
Labels: master

#8284 hv: hide mwait from guest.
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vm.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmexit.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/asm/cpuid.h
  hypervisor/include/arch/x86/asm/guest/vm.h
Labels: master

#8294 static_allocator: skip ACPI objects referring all functions of a PCI device
  misc/config_tools/static_allocators/bdf.py
Labels: master

#8295 config-tools: fix virio GPU rendering issue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/GPU.vue
  misc/config_tools/launch_config/launch_cfg_gen.py
  misc/config_tools/schema/checks/virtio_devices.xsd
  misc/config_tools/schema/config.xsd
Labels: master

#8296 config tool: combine multiple xhci to one line
  misc/config_tools/launch_config/launch_cfg_gen.py
Labels: master

#8299 config-tools: refine print out message after running board inspector
  misc/config_tools/board_inspector/board_inspector.py
Labels: master

#8302 debian/rules: adapt to configurator-generated work folders
  debian/rules
Labels: master

#8309 config-tools: generate config_summary.rst
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/configurator/packages/configurator/src/pyodide.js
  misc/config_tools/configurator/packages/configurator/thirdLib/library.json
  misc/config_tools/configurator/pyodide/generateConfigSummary.py
  misc/config_tools/scenario_config/config_summary.py
Labels: master

#8286 misc: Update CODEOWNER for doc reviewer changed.
  CODEOWNERS
Labels: master

#8308 config_tools: add the dummy address to let anonymous trial of ACRN
  debian/debian_build.sh
Labels: master

#8305 misc: refine the calculate logic of hv_ram_size
  misc/config_tools/static_allocators/hv_ram.py
Labels: master

#8307 misc: fix the vCPU number issue of document
  misc/config_tools/scenario_config/config_summary.py
Labels: master

#8283 misc: rename common.py to avoid private library conflict
  misc/config_tools/acpi_gen/acpi_const.py
  misc/config_tools/acpi_gen/asl_gen.py
  misc/config_tools/acpi_gen/bin_gen.py
  misc/config_tools/board_config/acpi_platform_h.py
  misc/config_tools/board_config/board_c.py
  misc/config_tools/board_config/board_cfg_gen.py
  misc/config_tools/board_config/board_info_h.py
  misc/config_tools/board_config/pci_devices_h.py
  misc/config_tools/board_config/vbar_base_h.py
  misc/config_tools/hv_config/board_defconfig.py
  misc/config_tools/hv_config/hv_item.py
  misc/config_tools/library/acrn_config_utilities.py
  misc/config_tools/library/board_cfg_lib.py
  misc/config_tools/library/hv_cfg_lib.py
  misc/config_tools/library/launch_cfg_lib.py
  misc/config_tools/library/rdt.py
  misc/config_tools/library/scenario_cfg_lib.py
  misc/config_tools/scenario_config/scenario_cfg_gen.py
  misc/config_tools/scenario_config/scenario_item.py
  misc/config_tools/service_vm_config/serial_config.py
  misc/config_tools/static_allocators/bdf.py
  misc/config_tools/static_allocators/board_capability.py
  misc/config_tools/static_allocators/clos.py
  misc/config_tools/static_allocators/cpu_affinity.py
  misc/config_tools/static_allocators/cpu_freq.py
  misc/config_tools/static_allocators/gpa.py
  misc/config_tools/static_allocators/guest_flags.py
  misc/config_tools/static_allocators/hv_ram.py
  misc/config_tools/static_allocators/intx.py
  misc/config_tools/static_allocators/lib/lib.py
  misc/config_tools/static_allocators/main.py
  misc/config_tools/static_allocators/memory_allocator.py
  misc/config_tools/static_allocators/pio.py
  misc/config_tools/static_allocators/s5_vuart.py
Labels: master

#8313 static_allocator/gpa: deduplicate secondary PCI window list
  misc/config_tools/static_allocators/gpa.py
Labels: master

#8317 board_inspector: use executables found under system paths
  misc/config_tools/board_inspector/board_inspector.py
  misc/config_tools/board_inspector/cpuparser/platformbase.py
  misc/config_tools/board_inspector/extractors/10-processors.py
  misc/config_tools/board_inspector/inspectorlib/external_tools.py
  misc/config_tools/board_inspector/legacy/acpi.py
  misc/config_tools/board_inspector/legacy/board_parser.py
  misc/config_tools/board_inspector/legacy/clos.py
  misc/config_tools/board_inspector/legacy/dmar.py
  misc/config_tools/board_inspector/legacy/misc.py
  misc/config_tools/board_inspector/legacy/parser_lib.py
Labels: master

#8318 board_inspector: use executables found under system paths (for v3.0.x)
  misc/config_tools/board_inspector/board_inspector.py
  misc/config_tools/board_inspector/cpuparser/platformbase.py
  misc/config_tools/board_inspector/inspectorlib/external_tools.py
  misc/config_tools/board_inspector/legacy/acpi.py
  misc/config_tools/board_inspector/legacy/board_parser.py
  misc/config_tools/board_inspector/legacy/clos.py
  misc/config_tools/board_inspector/legacy/dmar.py
  misc/config_tools/board_inspector/legacy/misc.py
  misc/config_tools/board_inspector/legacy/parser_lib.py
Labels: release_3.0

#8319 ignore debuild intermediate files
  .gitignore
Labels: master

#8316 doc: add tutorial for enabling multiple displays
  doc/develop.rst
  doc/tutorials/enable_multiple_displays.rst
  doc/tutorials/images/virtio-gpu-device-01.png
  doc/tutorials/images/virtio-gpu-device-02.png
  doc/tutorials/images/virtio-gpu-device-03.png
Labels: area: documentation, master

#8326 config-tools: board inspector does not exit if a usb device is unplugged
  misc/config_tools/board_inspector/extractors/95-usb.py
Labels: master

#8322 hv: change the version format
  Makefile
  hypervisor/Makefile
  hypervisor/arch/x86/cpu.c
  hypervisor/debug/shell.c
Labels: master

#8324 ACRN:DM: Fix the vhost register kick fd issue.
  devicemodel/hw/pci/virtio/vhost.c
  devicemodel/hw/pci/virtio/virtio.c
  devicemodel/include/virtio.h
Labels: master

#8321 misc: Update sample launch scripts into generic_board folder.
  debian/acrn-devicemodel.install
  debian/rules
  devicemodel/Makefile
  misc/config_tools/data/generic_board/generic_board.xml
  misc/config_tools/data/generic_board/generic_code/boards/board.c
  misc/config_tools/data/generic_board/generic_code/boards/board_info.h
  misc/config_tools/data/generic_board/generic_code/boards/pci_devices.h
  misc/config_tools/data/generic_board/generic_code/boards/platform_acpi_info.h
  misc/config_tools/data/generic_board/generic_code/hybrid/ACPI_VM0/dsdt.aml
  misc/config_tools/data/generic_board/generic_code/hybrid/generic_board.config
  misc/config_tools/data/generic_board/generic_code/hybrid/ivshmem_cfg.h
  misc/config_tools/data/generic_board/generic_code/hybrid/misc_cfg.h
  misc/config_tools/data/generic_board/generic_code/hybrid/pci_dev.c
  misc/config_tools/data/generic_board/generic_code/hybrid/pt_intx.c
  misc/config_tools/data/generic_board/generic_code/hybrid/vbar_base.h
  misc/config_tools/data/generic_board/generic_code/hybrid/vm_configurations.c
  misc/config_tools/data/generic_board/generic_code/hybrid/vm_configurations.h
  misc/config_tools/data/generic_board/generic_code/partitioned/ACPI_VM0/dsdt.aml
  misc/config_tools/data/generic_board/generic_code/partitioned/ACPI_VM1/dsdt.aml
  misc/config_tools/data/generic_board/generic_code/partitioned/generic_board.config
  misc/config_tools/data/generic_board/generic_code/partitioned/ivshmem_cfg.h
  misc/config_tools/data/generic_board/generic_code/partitioned/misc_cfg.h
  misc/config_tools/data/generic_board/generic_code/partitioned/pci_dev.c
  misc/config_tools/data/generic_board/generic_code/partitioned/pt_intx.c
  misc/config_tools/data/generic_board/generic_code/partitioned/vbar_base.h
  misc/config_tools/data/generic_board/generic_code/partitioned/vm_configurations.c
  misc/config_tools/data/generic_board/generic_code/partitioned/vm_configurations.h
  misc/config_tools/data/generic_board/generic_code/shared/generic_board.config
  misc/config_tools/data/generic_board/generic_code/shared/ivshmem_cfg.h
  misc/config_tools/data/generic_board/generic_code/shared/misc_cfg.h
  misc/config_tools/data/generic_board/generic_code/shared/pci_dev.c
  misc/config_tools/data/generic_board/generic_code/shared/pt_intx.c
  misc/config_tools/data/generic_board/generic_code/shared/vbar_base.h
  misc/config_tools/data/generic_board/generic_code/shared/vm_configurations.c
  misc/config_tools/data/generic_board/generic_code/shared/vm_configurations.h
  misc/config_tools/data/generic_board/hybrid.xml
  misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml
  misc/config_tools/data/generic_board/hybrid_rt.xml
  misc/config_tools/data/generic_board/partitioned.xml
  misc/config_tools/data/generic_board/sample_launch_scripts/launch_user_vm_id1.sh
  misc/config_tools/data/generic_board/sample_launch_scripts/launch_user_vm_id2.sh
  misc/config_tools/data/generic_board/shared.xml
  misc/config_tools/data/generic_board/shared_launch_2user_vm.xml
  misc/config_tools/data/sample_launch_scripts
  misc/config_tools/data/sample_launch_scripts/apl-mrb/launch_uos.sh
  misc/config_tools/data/sample_launch_scripts/apl-up2/launch_uos.sh
  misc/config_tools/data/sample_launch_scripts/launch_ubuntu.sh
  misc/config_tools/data/sample_launch_scripts/nuc/launch_hard_rt_vm.sh
  misc/config_tools/data/sample_launch_scripts/nuc/launch_uos.sh
  misc/config_tools/data/sample_launch_scripts/nuc/launch_vxworks.sh
  misc/config_tools/data/sample_launch_scripts/nuc/launch_win.sh
  misc/config_tools/data/sample_launch_scripts/nuc/launch_xenomai.sh
  misc/config_tools/data/sample_launch_scripts/nuc/launch_zephyr.sh
  misc/config_tools/data/sample_launch_scripts/nuc/runC.json
Labels: master

#8329 dm: change the version format
  devicemodel/Makefile
  devicemodel/core/main.c
Labels: master

#8330 hv: support for pci uart with high mmio
  hypervisor/debug/uart16550.c
Labels: master

#8310 Issue8274 wrong kernel cmdline added in grub menu when install acrn hypervisor
  debian/grub-acrn.README.Debian
  debian/grub/25_linux_acrn
  debian/grub/acrn.cfg
Labels: master

#8332 doc: create 3.0.2 release notes
  doc/release_notes/release_notes_3.0.2.rst
Labels: area: documentation, release_3.0

#8298 doc: update GSG to use debuild to build ACRN packages
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#8336 doc: update GSG with corrections
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#8334 board_inspector: fix the invocation to rdmsr
  misc/config_tools/board_inspector/legacy/acpi.py
Labels: release_3.0

#8333 board_inspector: fix the invocation to rdmsr
  misc/config_tools/board_inspector/legacy/acpi.py
Labels: master

#8335 config_tools/schema: fix division operator in error messages
  misc/config_tools/schema/checks/vm_memory.xsd
Labels: master

#8331 doc: update asa.rst for v3.0.2 release
  doc/asa.rst
Labels: area: documentation, master

#8337 doc: add asa updates for 3.0.2 release
  doc/asa.rst
Labels: area: documentation, release_3.0

#8338 doc: add 3.0.2 release notes to master branch
  doc/release_notes/release_notes_3.0.2.rst
Labels: area: documentation, master

#8340 misc: life_mngr: revise try_receive_message_by_uart
  misc/services/life_mngr/uart.c
Labels: release_3.2

#8342 doc: update GSG to reflect release 3.2 changes
  doc/getting-started/getting-started.rst
Labels: area: documentation, master

#8341 asyncio: refine the setup ioctl
  devicemodel/core/main.c
  devicemodel/core/vmmapi.c
  devicemodel/include/public/hsm_ioctl_defs.h
  devicemodel/include/vmmapi.h
Labels: master

#8346 debian/rules: change default BOARDLIST and SCENARIOLIST to empty
  debian/rules
Labels: master

#8345 debian/rules: search for XML files only
  debian/rules
Labels: master

#8347 debian/rules: search for XML files only, and change default BOARDLIST and SCENARIOLIST to empty
  debian/rules
Labels: release_3.2

#8348 doc: update GSG with v3.2 changes
  doc/getting-started/getting-started.rst
Labels: area: documentation, master
