Repository projectacrn/acrn-hypervisor, pull requests merged in 2022-09, with the labels that each got.

#8104 config_tools: fix a typo in cache info extractor
  misc/config_tools/board_inspector/extractors/20-cache.py
Labels: release_3.1

#8103 config_tools: fix a typo in cache info extractor
  misc/config_tools/board_inspector/extractors/20-cache.py
Labels: master

#8108 config_tools: handle multiple xs:documentation properly
  misc/config_tools/scenario_config/jsonschema/converter.py
Labels: release_3.1

#8110 misc: add assertion to check the CDP Enable
  misc/config_tools/schema/checks/rdt_support.xsd
Labels: master

#8109 misc: add assertion to check the CDP Enable
  misc/config_tools/schema/checks/rdt_support.xsd
Labels: release_3.1

#8112 misc: life_mngr: revise try_receive_message_by_uart
  misc/services/life_mngr/uart.c
Labels: release_3.1

#8107 doc: Update references to scenario options doc
  doc/developer-guides/hld/hld-splitlock.rst
  doc/tutorials/rtvm_performance_tips.rst
  doc/tutorials/using_grub.rst
Labels: area: documentation, master

#8121 misc: refine upgrade script
  misc/config_tools/scenario_config/upgrader.py
Labels: release_3.1

#8122 misc: refine upgrade script
  misc/config_tools/scenario_config/upgrader.py
Labels: master

#8120 [config_tool] Duplicate error for vUART connection
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Labels: master

#8123 config-tools: Fix error reporting for memory addresses below 4G
  misc/config_tools/static_allocators/memory_allocator.py
Labels: master

#8128 [config_tool] v2 UART widget address for pre-launched VM doesn't update
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
Labels: master

#8126 dm: vga: remove all the assertion.
  devicemodel/hw/vga.c
Labels: release_3.1

#8134 [doc]remove some decription about hvlog
  doc/user-guides/kernel-parameters.rst
Labels: area: documentation, master

#8138 config-tools: fix typos of UI and README
  misc/config_tools/configurator/README.md
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue
Labels: master

#8142 misc: add assertion to check the BDF value
  misc/config_tools/schema/checks/vbdf_assignment.xsd
Labels: release_3.1

#8143 misc: add assertion to check the BDF value
  misc/config_tools/schema/checks/vbdf_assignment.xsd
Labels: master

#8144 doc: update vUART tutorials
  doc/tutorials/vuart_configuration.rst
Labels: area: documentation, master

#8140 doc: Remove note about v3.0 Configurator issue
  doc/tutorials/enable_ivshmem.rst
  doc/tutorials/vuart_configuration.rst
Labels: area: documentation, master

#8132 hv: tsc: start HPET counter before calibration
  hypervisor/arch/x86/tsc.c
Labels: master

#8119 doc: Update supported HW
  doc/reference/hardware.rst
Labels: area: documentation, master

#8147 doc: Minor edit to RDT tutorial
  doc/tutorials/rdt_configuration.rst
Labels: area: documentation, master

#8139 doc: Update CPU sharing tutorial to match v3.1 Configurator
  doc/tutorials/cpu_sharing.rst
  doc/tutorials/images/configurator-cpusharing-affinity.png
  doc/tutorials/images/configurator-cpusharing-scheduler.png
  doc/tutorials/images/configurator-cpusharing-vm1.png
Labels: area: documentation, master

#8146 config-tools: diable real_time_vcpu for non real-time VM
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
Labels: master

#8150 doc: Update CPU sharing tutorial
  doc/tutorials/cpu_sharing.rst
Labels: area: documentation, master

#8149 improve the document of acrnd
  misc/services/acrn_manager/README.rst
Labels: master

#8161 dm: virtio-blk: fix parameter err
  devicemodel/hw/pci/virtio/virtio_block.c
Labels: release_3.1

#8169 Add configuration files for ASRock system
  misc/config_tools/data/adl-asrock/adl-asrock.xml
  misc/config_tools/data/adl-asrock/shared.xml
Labels: master

#8166 [doc]GVT-d tutorial update based on ASRock platform constraint
  doc/tutorials/gpu-passthru.rst
Labels: area: documentation, master

#8171 doc: Update acrnctrl readme
  misc/services/acrn_manager/README.rst
Labels: master

#8177 hv: remove CPU frequency control from guests
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vmcs.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/common/hypercall.c
  hypervisor/include/arch/x86/asm/cpuid.h
  hypervisor/include/arch/x86/asm/guest/vcpu.h
  hypervisor/include/arch/x86/asm/msr.h
Labels: master

#8170 Add configuration files for ASRock system
  misc/config_tools/data/adl-asrock/adl-asrock.xml
  misc/config_tools/data/adl-asrock/shared.xml
Labels: release_3.0

#8186 config_tools: handle multiple xs:documentation properly
  misc/config_tools/scenario_config/jsonschema/converter.py
Labels: master

#8188 [config_tool] vCAT widget behavior
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT/HexBlockRangeSelector.vue
Labels: master

#8189 doc: Editorial changes to hypercall hld
  doc/developer-guides/hld/hv-hypercall.rst
Labels: area: documentation, master

#8183 [config_tool] Message when CAT not supported
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
  misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Labels: master

#8192 doc: Update the version infomation of sample app guide
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8194 doc: Upgrade the ubunutu version of sample app guide
  doc/getting-started/sample-app.rst
Labels: area: documentation, release_3.1

#8198 doc: Upgrade the information about Release Notes
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, release_3.1

#8196 doc: Upgrade the information about Release Notes
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, master

#8193 doc: Update S5 tutorial
  doc/tutorials/enable_s5.rst
Labels: area: documentation, master

#8203 doc: Update S5 tutorial
  doc/tutorials/enable_s5.rst
Labels: area: documentation, release_3.1

#8204 doc: Editorial changes to v3.1 release notes
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, master

#8205 doc: Editorial changes to v3.1 release notes
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, release_3.1

#8206 doc: add 3.1 release docs to menu choice
  doc/conf.py
Labels: area: documentation, master

#8211 doc: Update v3.1 release notes
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, master

#8212 doc: Update v3.1 release notes
  doc/release_notes/release_notes_3.1.rst
Labels: area: documentation, release_3.1

#8213 doc: add 3.1 to /latest header note
  doc/_templates/layout.html
Labels: area: documentation, master

#8216 doc: Fix typos in interrupt hld
  doc/developer-guides/hld/hv-interrupt.rst
Labels: area: documentation, master

#8217 doc: Editorial changes to DM params doc
  doc/user-guides/acrn-dm-parameters.rst
Labels: area: documentation, master

#8220 doc: Editorial changes to Configurator doc
  doc/tutorials/acrn_configurator_tool.rst
Labels: area: documentation, master

#8221 doc: Editorial changes to sample app guide
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8223 misc: add documentation element for CACHE_REGION
  misc/config_tools/schema/types.xsd
Labels: master

#8222 config-tools: Missing tqdm python package in board_inspector.deb
  misc/packaging/gen_acrn_deb.py
Labels: master

#8215 config-tools: reserve the secondary PCI bus mmio windows
  misc/config_tools/static_allocators/gpa.py
Labels: master

#8224 revision the GSG document of ubuntu kernel version
  doc/getting-started/getting-started.rst
Labels: area: documentation, master
