Repository projectacrn/acrn-hypervisor, pull requests merged in 2023-08, with the labels that each got.

#8466 hv: fix undefined reference to nested_vmexit_handler() in vmexit.c
  hypervisor/include/arch/x86/asm/guest/nested.h
Labels: master

#8464 hv: disable HFI and ITD for guests
  hypervisor/arch/x86/guest/vcpuid.c
  hypervisor/arch/x86/guest/vmsr.c
  hypervisor/include/arch/x86/asm/cpuid.h
  hypervisor/include/arch/x86/asm/msr.h
Labels: master

#8452 doc: update gsg for ubuntu 22.04.02 iso
  doc/getting-started/getting-started.rst
  doc/getting-started/images/configurator-postvm02.png
  doc/getting-started/images/configurator_postvm01.png
Labels: area: documentation, master

#8450 doc: update network configuration section
  doc/getting-started/getting-started.rst
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8449 doc: replace qemu-kvm with qemu-utils in sample application guide
  doc/getting-started/sample-app.rst
Labels: area: documentation, master

#8468 doc: draft start for v3.2 release notes
  doc/conf.py
  doc/release_notes/release_notes_3.2.rst
Labels: area: documentation, master

#8481 doc: draft organization for multi-arch support
  doc/index.rst
  doc/projects/index.rst
  doc/projects/multi-arch-support.rst
Labels: area: documentation, master

#8482 doc: fix typo in v3.2 release notes
  doc/release_notes/release_notes_3.2.rst
Labels: area: documentation, master

#8483 doc: fix typo in v3.2 release notes
  doc/release_notes/release_notes_3.2.rst
Labels: area: documentation, release_3.2

#8470 hypervisor/ivshmem: Fix some ivshmem bugs/issues
  hypervisor/dm/vpci/ivshmem.c
Labels: master

#8457 Add junjie to hypervisor approver list
  CODEOWNERS
Labels: master

#8484 version:3.3
  VERSION
Labels: master
