Repository projectacrn/acrn-hypervisor, pull requests merged in 2024-08, with the labels that each got.

#8680 doc: add custom commands in acrn.doxyfile
  doc/acrn.doxyfile
Labels: area: documentation, master

#8666 doc: add module design for some defines in hwmgmt_page
  hypervisor/arch/x86/mmu.c
  hypervisor/arch/x86/page.c
  hypervisor/arch/x86/pagetable.c
  hypervisor/include/arch/x86/asm/page.h
  hypervisor/include/arch/x86/asm/pgtable.h
Labels: master

#8689 hv: allow guest with the highest severity to read RST_CNT
  hypervisor/arch/x86/guest/vm_reset.c
Labels: master

#8694 dm: acpi: support CPPC V2 capability in _OSC of DSDT for ACRN guest.
  devicemodel/hw/platform/acpi/acpi.c
  devicemodel/hw/platform/acpi/acpi_pm.c
  devicemodel/include/acpi.h
Labels: master

#8700 hv: multiboot: fix compilation error for module test
  hypervisor/boot/multiboot/multiboot_priv.h
Labels: master

#8696 hv: hypercall: change condition for hcall_get_cpu_pm_state
  hypervisor/common/hypercall.c
Labels: master

#8702 hv: fix testability issues that impact module test
  hypervisor/arch/x86/vtd.c
Labels: master

#8685 doc: add module design for peripheral vrtc device
  hypervisor/dm/vrtc.c
  hypervisor/include/dm/vrtc.h
Labels: master

#8693 doc: add module design for peripheral vpci_bridge device
  hypervisor/dm/vpci/vpci_bridge.c
Labels: master

#8690 doc: add module design for peripheral vuart device
  hypervisor/dm/vuart.c
  hypervisor/include/dm/vuart.h
Labels: master

#8705 hv: ENODEV should be able to be set into RAX as hypercall return value
  hypervisor/arch/x86/guest/vmcall.c
Labels: master

#8699 doc: modify v3.3 release notes
  doc/release_notes/release_notes_3.3.rst
Labels: area: documentation, release_3.3

#8701 doc: modify v3.3 release notes
  doc/release_notes/release_notes_3.3.rst
Labels: area: documentation, master

#8709 local_gva2gpa_common: optimize code
  hypervisor/arch/x86/guest/guest_memory.c
Labels: master
