Repository projectacrn/acrn-hypervisor, pull requests merged in 2024-07, with the labels that each got.

#8641 release: fix the compilation error in release mode
  hypervisor/release/trace.c
Labels: master

#8649 vUART two related configuration support
  hypervisor/arch/x86/init.c
  hypervisor/debug/console.c
  hypervisor/include/dm/vuart.h
  misc/config_tools/configurator/packages/configurator/tests/data/data.json
  misc/config_tools/schema/checks/cpu_assignment.xsd
  misc/config_tools/schema/config.xsd
  misc/config_tools/xforms/config_common.xsl
Labels: master

#8650 dm: pci: update ADL-N and RPL-P iGPU device ids
  devicemodel/include/igd_pciids.h
Labels: master

#8651 vUART: change S5 vUART resource
  devicemodel/hw/pci/lpc.c
  devicemodel/hw/uart_core.c
  devicemodel/include/uart_core.h
  misc/config_tools/static_allocators/intx.py
  misc/config_tools/static_allocators/s5_vuart.py
Labels: master

#8660 doc: update libwebkit2gtk install method & remove unnecessary package
  doc/tutorials/acrn_configurator_tool.rst
Labels: area: documentation, master

#8658 misc: Configurator Main VM Support
  misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
  misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
  misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue
  misc/config_tools/configurator/pyodide/updateSchema.py
Labels: master

#8655 hv: remove Service VM delayed loading
  hypervisor/arch/x86/guest/vm.c
Labels: master

#8670 misc: fix openssl's vulnerability for tauri
  misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.lock
  misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.toml
Labels: release_3.3

#8672 hv: add GUEST_FLAG_STATELESS flag
  hypervisor/arch/x86/guest/vm.c
  hypervisor/include/public/acrn_common.h
  misc/config_tools/schema/config.xsd
  misc/config_tools/static_allocators/guest_flags.py
Labels: master

#8669 misc: fix openssl's vulnerability for tauri
  misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.lock
  misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.toml
Labels: master
